### ISSUE TITLE
services: using only Enable as a string is problematic for non-linux admins

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#10009]
In a usability test with 11 admins that had primarily Windows Server experience, most of the admins had a hard time to finish the task of making a service run on boot.

The task had three steps. First step was to find the service, the second step was to start the service, and the third step was to make the service run on boot.

Step 1 and 2 went fine, but a lot of them got stuck on step 3.
The word "Enable" doesn't communicate to them, so we need to reword that, or add some helper text.

**Comment by martinpitt** [comment]
Technically, "start at boot" is not entirely correct, due to how systemd units work. They could be started in a target which itself does't start at boot, but on-demand as a reaction to hardware changes, or the network getting offline, or even at shutdown (part of shutdown.target). It's of course true for the vast majority of units, so if we want to sacrifice some accuracy for more self-explanation, that might be acceptable.

However, "boot" is by itself a technical term (in this context). Do we happen to know if that's something Windows users can relate to? "Start when you turn on or restart your computer" is too long for many places in the UI where we use this, and sounds a bit too dumbed down to me. It may be ok as a tool tip, though.

For the table headings on the Services page, how about "Enabled (started/stopped automatically)" vs. "Disabled (started/stopped manually)", to teach people what this means? and then the words in parents as tooltips on the buttons on a service's detail page?

I think it's important to somewhere mention the "enabled" vs. "disabled" words, as that's how systemd and its CLI calls them.

**Comment by andreasn** [comment]
Windows Server 2016 calls it _Restart_, but we use reboot on the System page, because that's what the Red Hat documentation guidelines recommend, among other places. The CLI command is also _systemctl reboot_. I think it's less of a terminology issue than Enable.

**Comment by andreasn** [comment]
I like the tooltips idea. Somewhat related terminology here is that Windows Server 2016 calls it _Startup Mode_
![screenshot](https://www.starwindsoftware.com/blog/wp-content/uploads/2017/11/16-starting-and-stopping-Windows-Service-action-in-Honolulu-1.png)

**Comment by martinpitt** [comment]
The "Startup Mode" (Manual/Automatic) sounds very similar to my idea "Enabled (started/stopped automatically)", and technically it's reasonably correct. I would still like to mention Enabled/Disabled somewhere for the teaching/CLI correspondence aspect, though.

**Comment by andreasn** [comment]
How do you feel about this?
![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/e40e4756368d88a68d6620d8818451eaec8973b9/services/services.png)
