### ISSUE TITLE
Cockpit Guide headers overlap the options that are above

### ISSUE THREAD

**Issue by droideck** [cockpit-project/cockpit#10204]
On the https://cockpit-project.org/guide/latest/ page you can't click on the "patternfly.css" element in the list, because "API: docker" overlaps it. 
The same is with other headers in the list.

**Comment by harsha-iiiv** [comment]
can  I work on this issue

**Comment by martinpitt** [comment]
Well spotted, thanks! @harsha-iiiv : Please, if you want to fix this, a pull request is much appreciated. The source is here: https://github.com/cockpit-project/cockpit/tree/master/doc/guide

Otherwise, @garrett, can you please have a look at this?

**Comment by garrett** [comment]
Oh, this is definitely from the CSS.

The generated HTML uses the same tags for standalone pages and also for the overview list. I have a pending fix that limits the CSS to the ones in pages only. (Those are using `div`, whereas the other usages are in `span`s or various definition list elements.)

I'll send a PR ASAP.

**Comment by garrett** [comment]
Thanks for spotting the issue!

It might've been a little tricky to know what was going on with this in particular, as the docs are generated and I have some CSS overrides for the latest guide.

Generally, you don't want to include tag names attached to CSS classes, but I didn't write the HTML, so this was the most obvious and correct fix.

---

### Detailed explanation

(skip, unless interested — but if you're doing web dev, then _you should be interested_ :wink:)

#### What?

Normally, it's better to fix the HTML and rename the classes accordingly, so they are descriptive and uniquely apply to one specific type of use. Right now, the class names have overloaded meanings.

#### Why?

The reasons for trying to keep to CSS as simple as possible (without class names here) is because of simplicity, expected behavior, and specificity. This is already important when you're writing your own CSS & HTML, but _super-important_ when you're using other people's CSS and HTML.

- **Simplicity**: when you're looking through HTML and CSS, it's more obvious something applies when it's the same. You don't need to look across the file (or files) for `div.chapter` versus `.chapter` versus `span.chapter` versus `h1.chapter` and so on.

- **Expected behavior**: If you use "reference" as a class in one place in the HTML and it works as expected, but then you add "reference" elsewhere and it does something completely different, it's not obvious that it's tied to a tag. This also applies for changing tags later on (div to span, or better yet, changing a div or span to a tag with more meaning — aka: a semantic tag).

- **Specificity**: This is a biggie. Specificity rules dictate which CSS rules have more weight than others. 
  - There's a calculation every browser does in this order:
    - inline style (which you should always try to avoid for this reason, and for many others, such as maintainability)
    - ID
    - class/psuedoclass/attribute
    - element (tags)
  - In addition to the above order browsers take complexity of the matching rule into account too (so simple is generally better).
  - `!important` trumps everything by shouting over it, trying to change reality to what it thinks it should be. Don't use `!important`. Ever. (Except as an absolute very last resort. But even then, it's better to bump up specificity instead if you need to.)
  - [Read a nice intro on this topic on css-tricks.com](https://css-tricks.com/specifics-on-css-specificity/).
  - [CSS specificity explained through the Batman universe](http://batificity.com/). :bat: This is silly.
  - [Specificity Calculator](https://specificity.keegan.st/) explains specificity rules on CSS selectors you provide. You can add multiple different selectors to compare and help figure out a solution.

#### How?

In this case, I would've added one class in the HTML for the page structure and changed the CSS to point to that, and I probably would have also renamed the existing classes in one place or another. But it really doesn't make sense to create a patch for the tool that generates the HTML... and what we have isn't _wrong_... it's just not 100% best practices.

So the obvious next-best-thing was to make the CSS only apply to the classes applied to the `div`s, as that's the only place where it's needed, according to a quick [`ag`](https://geoff.greer.fm/ag/) search on the guide's generated HTML.

#### In closing

Yeah, this was pretty detailed answer for just adding `div` to the classes. :grin:
