### ISSUE TITLE
Enable persistent metrics... flow doesn't show the time controls

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#10625]
* I hit _Enable persistent metrics..._
* The system brought up the install dialog. I hit Install.
* Once installed I turned _Store Performance data_ to ON
* But I don't get any time controls. :/
* Only when I log out and log in again I get the time controls.

Either we need to figure out a way to load those, or show a message that you'll need to log out and in again for them to show up in the UI.

**Comment by andreasn** [comment]
![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/90495c41a0a5812120a97e30ce0bbc4e79311485/metrics/metrics-logout.png)

**Comment by andreasn** [comment]
@garrett suggested **Log out and log back in to see stored metrics.**, since it's more direct, so let's go with that instead.

**Comment by marusak** [comment]
This issue is closed due to inactivity.

If this issue is a bug report and you are still able to reproduce it, please
comment here and provide us with an updated reproducer.

If this issue is a request for a new feature, we are sorry, but we won't be able
to address this in any time soon. If you are interested in helping us with
the implementation, please comment here.

**Comment by garrett** [comment]
I'm pretty sure this issue is still relevant and pretty highly visible issue. It can still be triggered the same exact way, afaik. (However, I've been unable to get PCP working on my system for some time, so I don't know for certain.)

We just need someone to implement it.

**Comment by marusak** [comment]
This is exactly how it was implemented when the the metrics page was introduced:
![newlogsafterinstall](https://user-images.githubusercontent.com/12330670/109200387-d5c71980-77a0-11eb-9f61-df6aa1d2db16.png)
