### ISSUE TITLE
machines: no easy way to free up space in a storage pool

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#10654]
If I'm trying to create a new VM, but I can't, since my storage pool is short on space, I have no easy way of cleaning up old and unused qcow-images, ISOs etc. I can see how big they are, but there is nothing I can do about it. The only workaround for now is if I go to the terminal page, and then delete them via the CLI.

**Comment by andreasn** [comment]
![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/962538f1471d16d9a343cc20b075c67547e8bd1f/virtual-machines/storage-pools-delete-volumes.png)

@garrett @KKoukiou how do you feel about this design?

**Comment by KKoukiou** [comment]
@andreasn I like it! We use this tables with the checkboxes anywhere else in cockpit or I have to implement them?

And btw, I see patternfly offers similar tables, do we plan to move to them at some point? [patternfly-tables](https://rawgit.com/patternfly/patternfly-react/gh-pages/patternfly-3/?knob-Show%20Help=true&knob-Field%20Level%20Help%20Content=Please%20specify%20Country%20code%20%3Cbr%3E%20%3Ca%20target%3D%27_blank%27%20href%3D%27https%3A%2F%2Fcountrycode.org%2F%27%3EClick%20here%20for%20a%20list%20of%20Country%20codes%3C%2Fa%3E&knob-Close%20Popover=true&knob-Show%20Modal=true&selectedKind=patternfly-react%2FContent%20Views%2FTable%20View&selectedStory=Server%20Paginated%20Table&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)

**Comment by andreasn** [comment]
In the design I tried to use the [list-view](https://www.patternfly.org/pattern-library/content-views/list-view/) rather than table-view, since it looks clearer and table-view optimized for tables with a lot of columns.

**Comment by andreasn** [comment]
> It's possibly a little weird to have the action appear in the tab row. It's probably fine though.
Yeah, I wasn't quite sure where to put it. Also, if it should be hidden or unselectable when nothing in the list is selected. Probably the latter, right?

> Perhaps the panel height overflow could be limited by a calc using vh, instead of a fixed number?
Yes, that makes sense! You'll end up with a lot of different heights, and making sure the button is hittable without scrolling the browser window up and down is important. `vh` also makes sure it doen't end up being too short.

**Comment by garrett** [comment]
> Yeah, I wasn't quite sure where to put it. 

Yeah, I thought about an alternative but really couldn't come up with one, unless it was on top of the list itself.

At the top, the list would shift down (which would be bad when selecting multiple) or there would always be blank space (which would also be bad, as it's an action that's not too common, so it's just some weird space >85% of the time or so). And there's not really much else. Unless we do a bottom bar? But then it's just for 1 button. And would probably shift page elements too.

Where you have it is probably best considering everything.

> Also, if it should be hidden or unselectable when nothing in the list is selected. Probably the latter, right?

Usually, sure. In this case, I think it would be weird to have a disabled action button there. It's probably better to only show it when needed, as you have it.

Perhaps we should have it subtly animate in somehow to grab attention?

---

For the panel height, I'll just work in overflow logic for the lists by default. I suppose we should have a way to cancel it, but I think that should be the exception instead of the default case. The CSS could include `:not(.ct-noscroll)` (which we could re-use for other scroll overrides) or something? Or just don't support an overflow override and add it in if it is ever needed? (However, it's easy to add with `:not()`.)

**Comment by garrett** [comment]
Whatever's decided here, we should align it and the disks tab in the machines list:

![screenshot_2018-11-27 virtual machines - localhost](https://user-images.githubusercontent.com/10246/49074612-49ca8e00-f235-11e8-99fc-c8da51b257e3.png)

Actions for the actual list item are to the right of the tab area (run, delete).

Actions for the sub-list (embedded list in the panel) are above the sub-list. (There's also some excess white space there — it should probably be removed.)

And if we do implement the overflow, we probably want some action bar that's floaty when overflowing.

**Comment by andreasn** [comment]
I agree, it's a little too easy to delete those disks today.
I would expect the delete action to show up next to the Add Disk button in this case.
It would be weird if we placed both the **Add Disk** and **Delete** Disk in the action area maybe, since the **Delete** for the VM is there

**Comment by andreasn** [comment]
Here is how it would look if we put it in the tab instead, and only use the actions in the tab bar that affects the VM as a whole.
![volumes-mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/485b4b5fe1cc974c965ea6bcecdd409947a35373/virtual-machines/storage-pools-delete-volumes.png)

And corresponding for disks:
![disks-mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/485b4b5fe1cc974c965ea6bcecdd409947a35373/virtual-machines/vm-view-disks.png)

Note that I also snuck the idea of a little counter in there, instead of the overly vague term _selected_.
When you manipulate it, it's clear that the button reacts to the checkboxes.

**Comment by KKoukiou** [comment]
I was checking the patternfly tables vs lists and it looks like when you click on some item the row of a table it is changing backround. This doesn't happen in lists but IMO it looks nice. Shall we consider it?

[patternfly-table-checkbox](https://rawgit.com/patternfly/patternfly-react/gh-pages/patternfly-3/?knob-Show%20Help=true&knob-Field%20Level%20Help%20Content=Please%20specify%20Country%20code%20%3Cbr%3E%20%3Ca%20target%3D%27_blank%27%20href%3D%27https%3A%2F%2Fcountrycode.org%2F%27%3EClick%20here%20for%20a%20list%20of%20Country%20codes%3C%2Fa%3E&knob-Close%20Popover=true&knob-Show%20Modal=true&knob-Bordered=true&knob-Selection%20Type=none&selectedKind=patternfly-react%2FContent%20Views%2FTable%20View&selectedStory=Client%20Paginated%20Table&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs)

Other than that I like it a lot, thanks for putting effort to this!

**Comment by andreasn** [comment]
It doesn't seem like [list view](https://rawgit.com/patternfly/patternfly-react/gh-pages/patternfly-3/?knob-Show%20Help=true&knob-Field%20Level%20Help%20Content=Please%20specify%20Country%20code%20%3Cbr%3E%20%3Ca%20target%3D%27_blank%27%20href%3D%27https%3A%2F%2Fcountrycode.org%2F%27%3EClick%20here%20for%20a%20list%20of%20Country%20codes%3C%2Fa%3E&knob-Close%20Popover=true&knob-Show%20Modal=true&knob-Bordered=true&knob-Selection%20Type=none&selectedKind=patternfly-react%2FContent%20Views%2FList%20View&selectedStory=List%20with%20Compound%20Expansion&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs) has that, but it's a great idea!

**Comment by andreasn** [comment]
Err..correction. [It does, actually](https://www.patternfly.org/pattern-library/content-views/list-view/#example-code-2)

**Comment by andreasn** [comment]
![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/20243410dc5372eefc5754a8c11140f68101cd07/virtual-machines/storage-pools-delete-volumes.png)

![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/20243410dc5372eefc5754a8c11140f68101cd07/virtual-machines/vm-view-disks.png)

**Comment by KKoukiou** [comment]
I am working on this right now, I have the feature exactly as shown in the mockup implemented but I need some extra mockups/advice.
The issue is that when a volume is used by some domain, we should really show that to the user before deleting the volume.

virt-manager shows for each volume if it's used and by which domain, see here:

![virt-manager-volumes](https://user-images.githubusercontent.com/14921356/49585823-bcd3b300-f95f-11e8-97a1-b5211b279a9b.png)


Shall we do the same?
And in addition, if someone attempts to delete a volume which is used, they will get and extra modal dialog with requesting confirmation for force deletion.

**Comment by garrett** [comment]
@KKoukiou It's looking nice! I'll reevaluate the selected color based on PatternFly ones; it feels a little dark, especially after we lightened the hover color to align with PatternFly.

(I think I picked the color originally for the non-checkmark version, so it's probably my fault. :wink:)

**Comment by garrett** [comment]
Oh, right: We should also probably adjust the CSS to remove the extra gap above the button.
