### ISSUE TITLE
docker: Display of long names needs to be truncated

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#1072]
Spinning off from #980 since it affects more than just the hostname and is one of several issues.

There are a number of places where names of things balloon up and are impossibly long.
One of them is issue #980 for hostnames, but I've seen this with storage too.
Lets put a limit of, say 20 characters or so.
css only allows for truncating at the end right now [1]. so this creates issues in the situation where the most crucial piece of information is at the end (such as a number), so maybe jquerydotdot is a solution for now http://dotdotdot.frebsite.nl/
1. http://www.w3.org/wiki/Text-overflow_middle_cropping

**Comment by dperpeet** [comment]
@andreasn is it worth thinking about bringing the ellipsis back? as a fallback we can display the whole text on hover...

**Comment by martinpitt** [comment]
The hostname now gets properly ellipsided on the system page and on the nav menu. There are some breadcrumb lines where we show arbitrary text:
 
 * On the Services page, but it's only two levels, it has plenty of space, and it's unrealistic to have super-long unit names that would overflow the page width
 * On the Applications page, but pretty well the same argument as above

The only place that I found is the docker page. Container names can get very long, and with a narrow layout it does break the layout:

![docker-long-name](https://user-images.githubusercontent.com/200109/51108255-d9ca9400-17f1-11e9-95cf-272a0673f119.png)

So I'll re-purpose this issue to this concrete bug. If we find others, please let's file new issues with screenshots, this issue was way too generic to be really useful.

**Comment by ssbarnea** [comment]
Not sure if this is the same issue but the Containers page looks awful due to the long containers page:
<img width="1479" alt="screenshot 2019-02-08 at 21 09 58" src="https://user-images.githubusercontent.com/102495/52506443-8546e880-2be6-11e9-9736-5b89c929158e.png">


It is true that full containers and command names *may* prove useful but is very unlikely that you want all displayed by default. 

I think use of [CSS truncation with elipses](https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/) could be used to improve the visual look without having to cut the text.

**Comment by marusak** [comment]
As commented in https://github.com/cockpit-project/cockpit/pull/11015 this was addressed when we redesigned to look like PF4.
