### ISSUE TITLE
dashboard: unable to add nother localhost machine 127.0.0.3 with MS Edge browser with same credentials

### ISSUE THREAD

**Issue by jscotka** [cockpit-project/cockpit#10767]
found by new tests for dasboard via selenium in https://github.com/cockpit-project/cockpit/pull/10432
cockpit is unable to add another machine ``127.0.0.3`` via dashboard via **Edge** browser

![image](https://user-images.githubusercontent.com/8735467/49505658-85d8a100-f87c-11e8-9309-27ba637558fd.png)

**Comment by marusak** [comment]
This issue is closed due to inactivity.

If this issue is a bug report and you are still able to reproduce it, please
comment here and provide us with an updated reproducer.

If this issue is a request for a new feature, we are sorry, but we won't be able
to address this in any time soon. If you are interested in helping us with
the implementation, please comment here.

**Comment by marusak** [comment]
This issue is closed due to inactivity.

If this issue is a bug report and you are still able to reproduce it, please
comment here and provide us with an updated reproducer.

If this issue is a request for a new feature, we are sorry, but we won't be able
to address this in any time soon. If you are interested in helping us with
the implementation, please comment here.
