### ISSUE TITLE
cockpit plugins not caching

### ISSUE THREAD

**Issue by yuval1982** [cockpit-project/cockpit#10790]
Hi,
We've developed some plugins (w/ Angular & webpack), and they all rely on our bundles, including a heavy one called 'vendors.bundle.js'.
The plugins (just like the original cockpit tabs/frames) all get a header of 'Cache-Control: no-cache, no-store'. However, their resources all get 'Cache-Control: max-age=31556926, public', and they do not get cached as well.

How can we override it?
Will it affect on the caching of vendors.bundle.js and the rest of the resources?
Or is there another way to cache resources used by our plugins?

Thanks,
Yuval

**Comment by marusak** [comment]
This issue is closed due to inactivity.

If this issue is a bug report and you are still able to reproduce it, please
comment here and provide us with an updated reproducer.

If this issue is a request for a new feature, we are sorry, but we won't be able
to address this in any time soon. If you are interested in helping us with
the implementation, please comment here.
