### ISSUE TITLE
Accessible labels in forms

### ISSUE THREAD

**Issue by jgiardino** [cockpit-project/cockpit#10813]
Looking at some examples from #10793, there are a couple of examples that can be improved for screen reader accessibility.

**Accessible Labels**
In general, the `for` attribute for `<labels>` [only support form elements](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Form_labelable) like `<input>`, `<textarea>`, etc...

Whenever a custom form element is used, like the bootstrap dropdown, the `<label>` `for` attribute should not be used. However, elements not supported can still be labeled using `aria-label` and `aria-labelledby`.

Some helpful tips for using these attributes:

- When both `aria-label` and `aria-labelledby` are defined for an element, the label defined by `aria-labelledby` is the one that gets announced.
- `aria-labelledby` takes the `id` value of the element that provides the label. This element can be hidden if needed. 
- `aria-labelledby` can take multiple `id` values separated by spaces, and the text is announced in the order defined.
- `aria-labelledby` can take the `id` value of it's own element

So given that you have this:
```
<span hidden id="label">Page size</span>
<button id="button" aria-labelledby="label button" aria-expanded="false">5</button>
[...other elements that would be included for a custom select element...]
```
Then the screen reader would announce "Page size 5 button collapsed".

**Fieldsets**
Using `<fieldset>` is a great way to group related inputs, like several checkboxes that are related. Typically `<legend>` provides an accessible label for the group included in the `<fieldset>`, but this might be problematic in certain layouts. If `<legend>` can't be used, then you can define the label using `aria-labelledby`. For example:

```
<span id="label">Page size</span>
<fieldset aria-labelledby="label">...</fieldset>
```

**Comment by garrett** [comment]
Thanks! I'll integrate this into the demos when I get back from vacation and adjust the CSS where needed.

I feel like we might need some example HTML+React somewhere. Perhaps the Cockpit "playground" is enough? (I'm not sure.)

Sadly, `<fieldset>` layouts aren't supported by Chrome ([bug1](https://bugs.chromium.org/p/chromium/issues/detail?id=262679), [bug2](https://bugs.chromium.org/p/chromium/issues/detail?id=375693)). This has been a Chrome bug since at least 2014 (and probably since it was first formed). I haven't found a workaround, except to use `role="group"` on an element (such as a `<div>`). Even WebKit did the right thing here.

**Comment by KKoukiou** [comment]
We use Forms from PF4 now and these are accessible.
