### ISSUE TITLE
show load per cpu as on option

### ISSUE THREAD

**Issue by hiishill** [cockpit-project/cockpit#10885]
on a multiprocessor machine it is necessary to know if any one cpu is maxing out in order to distribute the load

**Comment by PeterFalken** [comment]
I agree, that this might be useful when diagnosing performance issues.
But in the end - you can achieve the same thing by going to the console and calling up 'htop'.

**Comment by marusak** [comment]
This issue is closed due to inactivity.

If this issue is a bug report and you are still able to reproduce it, please
comment here and provide us with an updated reproducer.

If this issue is a request for a new feature, we are sorry, but we won't be able
to address this in any time soon. If you are interested in helping us with
the implementation, please comment here.
