### ISSUE TITLE
NFS storage dialog sometimes eats keystrokes

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#11066]
Cockpit version: 186
OS: all
Page: Storage

One of the most common recent flakes is `test/verify/check-storage-nfs TestStorage.testNfsClient`, for example:

- https://fedorapeople.org/groups/cockpit/logs/pull-11061-20190127-202020-9f8f14a6-verify-ubuntu-stable/log.html#186
- https://fedorapeople.org/groups/cockpit/logs/pull-11060-20190127-172929-5e54cd25-verify-debian-testing/log.html#186
 - https://fedorapeople.org/groups/cockpit/logs/pull-11060-20190127-173232-5e54cd25-verify-fedora-i386/log.html#186

In all these cases it's failing on waiting for the full input line content to be set, but the sent keystrokes just seem to be ignored. For example, it looks like this:

![screenshot](https://fedorapeople.org/groups/cockpit/logs/pull-11060-20190127-172929-5e54cd25-verify-debian-testing/TestStorage-testNfsClient-debian-testing-127.0.0.2-2901-FAIL.png)

I'm fairly sure that our `TestLib.set_input_text()` is correct -- i. e. we should *not* explicitly wait after typing each single character for it to appear in the input line (not sure if that would even help).

Unfortunately the storage dialogs have a lot of wrapping around the actual react components, so it's not that easy for follow where things could go wrong. Possibly the callbacks overlap, or somewhere it's missing a `setState()`, or trying to do an out-of-band setState within setState() or so? In fact, I can't seem to find *any* setState() call with the updated value, but doing so is required with React controlled components. 

I can't reproduce this failure locally; I tried no load, load of 8, single and 4x parallel test runs, and a loop.

@mvollmer , does that ring a bell by any chance?

**Comment by mvollmer** [comment]
> does that ring a bell by any chance?

This is very likely related to the fact that the input text field is part of a ComboBox that gets updated asynchronously in the background. I will look into this.

**Comment by mvollmer** [comment]
One explanation would be that the input field loses focus when the ComboBox changes asynchronusly.

That would be a real bug that would annoy a real user so I vote for somehow keeping the focus instead of making the test code more robust (by sending events directly to the input element, if that is possible, say).

I like the idea of always showing a complete ComboBox even when the list of choices is empty.  Instead of an empty list, it could show a single disabled item that explains why the list is empty, such as "Retrieving exported directories from SERVER", "Could not retrieve exported directories from SERVER" , and "SERVER does not export any directories".

**Comment by mvollmer** [comment]
This can be reproduced reliably by artificially slowing down the typing done by testlib.py by putting a 100ms or 200ms delay between input events.

We get partial input in all text fields, not just the combobox, for example:

https://fedorapeople.org/groups/cockpit/logs/pull-11061-20190127-202020-9f8f14a6-verify-ubuntu-stable/TestStorage-testNfsClient-ubuntu-stable-127.0.0.2-2401-FAIL.png

**Comment by mvollmer** [comment]
Alright, I figured it out, fix in #11079.

What happened was that a asynchronous check_server promise for the first dialog of the test was being resolved when the second dialog was already open.  This caused React to render into a element that wasn't part of the document any more, and for some reason this caused the focus to be removed from the current input element.

The fix is to not render into elements without parent.
