### ISSUE TITLE
Provide ansible role as deployment method

### ISSUE THREAD

**Issue by ssbarnea** [cockpit-project/cockpit#11135]
It would be very useful to provide an Ansible role for deploying cockpit across multiple servers because this role could support all supported platforms and users would only have to define the inventory.

**Comment by andreasn** [comment]
So this would pretty much be a playbook with _dnf install cockpit_ and _systemctl enable --now cockpit.socket_ ?
Is this something we need to ship in the cockpit source tree, or somewhere else?
Is this something you want to work on?
If so, I can assign this issue to you.

**Comment by ssbarnea** [comment]
@andreasn Please label it as need-help and do not assign me yet, I will ping you if I start working on it. I do not want to mislead someone that I am working on a task when I am not yet. Maybe someone else could start doing it. 

Yep, in-repo playbook would be the best and it should be quite easy to implement with not many steps.

**Comment by jscotka** [comment]
I just randomly opened this issue, and seems interesting. Maybe my idea is, not to have so simple deployment method, but allows also automatically add all machines to local machine cockpit dashboard and put there on all of them key authentization for selected user.
I'm not ansible expert, so I do not know if this is possible or completely nonsense. What do you think @andreasn ?

**Comment by martinpitt** [comment]
Note that Ansible has higher-level primitives for [package installation](https://docs.ansible.com/ansible/latest/modules/package_module.html) and [systemd service configuration](https://docs.ansible.com/ansible/latest/modules/systemd_module.html), so these should be used instead of raw command lines.

One can in principle pre-populate the dashboard by [writing /etc/cockpit.machines.d/ JSON files](https://cockpit-project.org/guide/latest/feature-machines.html), which is simple enough in Ansible (e. g. with the [blockinfile module](https://docs.ansible.com/ansible/latest/modules/blockinfile_module.html#blockinfile-module)).

Just keep in mind that the dashboard is limited to 20 machines, and Cockpit should *not* be placed as a tool to mass-administer machines. So I'd be a bit cautious with this, at least the playbook should make this optional.

**Comment by martinpitt** [comment]
Where would we actually provide this role? Certainly not in the distributed RPMs, as that's kind of pointless. If we just put them into our source git, nobody will find them. Is there some kind of "ansible hub" where we could publish that?

**Comment by mvollmer** [comment]
> Is there some kind of "ansible hub" where we could publish that?

https://galaxy.ansible.com/

**Comment by KKoukiou** [comment]
There are already multiple roles in galaxy that deal with cockpit installation, I don't think there is a need to create our own one.
* https://galaxy.ansible.com/oasis_roles/cockpit
* https://galaxy.ansible.com/linux-system-roles/cockpit
etc
