### ISSUE TITLE
Add monitoring support for BSD systems like MacOS, FreeBSD, pfsense, synology

### ISSUE THREAD

**Issue by ssbarnea** [cockpit-project/cockpit#11134]
Being able to monitor machines that are not based on Linux kernel would prove very useful, I am listing here few example from my homelab:
* MacOS (BSD based)
* PfSense (FreeBSD based)
* Synology DSM (FreeBSD based)

**Comment by andreasn** [comment]
Using cockpit-dashboard?
That page is not meant to be a monitoring solution, but more of a bastion host solution that will allow you to jump to Cockpit instances on those machines. I think the first step would be to get cockpit running on those BSD-systems, but that might be a bit hard, due to the heavy systemd dependance in base (used for starting services, changing hostname, rebooting etc.)
For pure monitoring, I would recommend looking into other solutions than Cockpit. I think those would do a much better job.

**Comment by KKoukiou** [comment]
This is not going to be implemented. Cockpit is relying heavily on systemd, dbus and tools that are not available on bsd systems.
