### ISSUE TITLE
Would be great to be able to do a change-media --eject for cdrom images in the machines package

### ISSUE THREAD

**Issue by Zebble** [cockpit-project/cockpit#11185]
Page: 
Machines

Would be great to be able to do a change-media --eject for cdrom images in the machines package.
Have to do this manually through virsh after a VM is created using an ISO image.  Would be handy to have an "eject" button in Cockpit, and possibly some other way to re-attach an ISO.

**Comment by KKoukiou** [comment]
@Zebble thansk for reposting this. Detaching disks or cdrom devices is supported since version 179. Maybe you 're using older version.
However, attaching cdroms is not supported, I 'll leave the issue open for this RFE.

Also, please include the cockpit version next time you open issue, so that we can avoid guesses :)

**Comment by Zebble** [comment]
Ahhh... that makes sense.  I'm running 176, the default version provided with CentOS 7.6.1810.  Is there a repo recommended that provides newer builds for EL7, or is moving to Fedora the preferred path?

**Comment by martinpitt** [comment]
@Zebble : You can install the latest version from our [COPR](https://copr.fedorainfracloud.org/coprs/g/cockpit/cockpit-preview/).
