### ISSUE TITLE
When using ct-form-layout all labels apart from the first have smaller up margin than they should (only in narrow mode)

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit#11229]
This is how the labels look now in narrow mode - apart from the first, all the others have smaller upper margin than the first.
![current-label-misallignment](https://user-images.githubusercontent.com/14921356/53171322-b8c04480-35e2-11e9-9d9c-3bbb50a23515.png)

If I disable the margin overwritting from ct-form-layout class all labels get the same margin now.
Like here:
![expected-label-allignment](https://user-images.githubusercontent.com/14921356/53171395-e3aa9880-35e2-11e9-8573-30f5e7fe4c14.png)

It's this line that sets this margins, https://github.com/cockpit-project/cockpit/blob/master/pkg/lib/form-layout.less#L337

**Comment by KKoukiou** [comment]
@garrett not sure if this intended os not, I just opened an issue because I found it too detailed to explain it over iRC; feel free to close if it's not an actual bug.

**Comment by marusak** [comment]
Well, the style still exists and is still applied, the only difference is that the first item is not select but radio. @KKoukiou @garrett it has been opened for a while, any update/option?

**Comment by garrett** [comment]
Oops. I let this fall through the cracks. :disappointed:

I guess this is related to https://github.com/cockpit-project/cockpit/blob/master/pkg/lib/form-layout.less#L393 (as the file has updated since).

In case things change again, it seems to be this block:

```less
        // Everything but the first label should have space to breathe
        &:not(:first-child) {
          margin: @padding-large-vertical 0 0;
        }
```

The forms layout stuff has gone through a few iterations. It could be that this was necessary at one point and is no longer needed as the technique changed a bit.

## Here are updated screenshots

| Before | After... |
|:--|:--|
| ![Screen Shot 2020-02-13 at 18 11 23](https://user-images.githubusercontent.com/10246/74459962-6f6ca300-4e8c-11ea-8369-cf45c606899f.png) | ![Screen Shot 2020-02-13 at 18 11 46](https://user-images.githubusercontent.com/10246/74459960-6e3b7600-4e8c-11ea-91ea-5a0b73e0f383.png) |

---

So I agree and we can remove it. I looked in a few other places and it seems fine to _not_ have it.

**Comment by garrett** [comment]
Please test the PR all around Cockpit before merging. There was probably a reason why I added that snippet of code, but I couldn't find it on a quick glance through this and didn't test it thoroughly. :wink:

(Again, it could just be leftover code that just isn't needed anymore.)
