### ISSUE TITLE
Firewall: No way to make services accessible only to certain hosts (zones)

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#11240]
Page: Network > Firewall

**Problem**
As a sysadmin, I need to allow traffic to a service from certain hosts, but block it for others.

**User story**
Jeff is a new Linux admin. He's done a lot of system administration in the past, but on other OSes.
He runs a public web server that hosts his company's website, He wants http traffic to be available for everyone on the Internet, but he doesn't want them to have any way of accessing the system via ssh. However, he does want people who's connected to the internal network to be able to connect over ssh, so that they can do maintenance on the system when needed.

He logs in to the server. He starts the httpd service. Then he goes to the firewall section and edits the existing sshd firewall service to only allow traffic from `192.168.1.*.` Then he adds the httpd firewall service and sets it to access all traffic.

---

_**Edit**: Latest mockup is @ https://github.com/cockpit-project/cockpit/issues/11240#issuecomment-484138862_

**Comment by andreasn** [comment]
BTW, trying this format for new enhancements rather than the wiki

**Comment by garrett** [comment]
My WIP mockup of the firewall page is growing into a monster, as I'm figuring out how all the pieces we talked about (in that firewall design meeting and email thread) fit together:

![firewall-zones](https://user-images.githubusercontent.com/10246/55332613-065b8700-5496-11e9-864a-b5eaae93ce43.png)

The logging, disable/enable, menu, and labels can be mostly ignored for now. I think it would be nice to change the default zone in the zones implementation though. I suppose that can be considered a label and we'd probably need a menu for that action.

Also, I think we probably want to make adding existing system zones the focus of the first pass and then have custom zones (with editing) be a second pass. (Creating a new zone would add it, of course.) If @Gundersanne feels they should both be in the first PR, then I'm happy with that too.

**Comment by garrett** [comment]
BTW: I'm a bit torn between edit as an inline button or on the menu. I'm leaning toward the button though, as it's and indicator that it's a custom zone or service. It's not a huge issue though.

**Comment by andreasn** [comment]
It might be a little bit of a hidden indicator it's a custom zone. A pattern you will learn after a while, but that will be a bit of an odd pattern.
I would lean towards the edit button if it's a super common action that would be carried out a lot. But I also don't have a super-strong opinion about it, so we can just run with it for now and see what comes up in testing.

**Comment by garrett** [comment]
> a hidden indicator it's a custom zone

We could use a "Custom" badge too, as we're _probably_ going to have badges anyway.

> run with it for now and see what comes up in testing

Yeah, totally. :+1:

**Comment by garrett** [comment]
Ah right, the Firewall overview also changes when we add zones. Here's a mockup from 2017:
![firewall-zones-networking-summary](https://user-images.githubusercontent.com/10246/55399460-724bf700-554b-11e9-8ae7-f20c990cdc62.png)

Of course, it's subject to change. (This also shows suggestions, which also should be implemented at some point. That part should be dropped, of course, until we need it.)

**Comment by garrett** [comment]
I iterated through a bunch of designs with lists, scrollable lists, metadata in the lists —  and even a slider.

So far, I've settled on this one as a starter:

![firewall-dialog-add-zone](https://user-images.githubusercontent.com/10246/55488323-232bc200-5630-11e9-874e-c4ac7c6bb5f9.png)

I did have a horizontal connected radio button group too, but that falls apart with longer languages and on mobile, so I went with this vertical one. The line should communicate that they're all somewhat connected. I chose the default group of services minus "Home" as it is exactly the same as "Internal" ­and Cockpit is for servers, not laptops.

Also, I went with this _huge_ list of radio buttons instead of a select dropdown because the group (with the line) communicates the relationship between the different zones (the level of trust). If it's in a select dropdown, then the associations are hidden away.

Description, included services, and address are all `<output>` fields, depending on the `<input>`s selected for trust level and interface (for address). Range is a progressive disclosure, but perhaps the text needs to be called something else.

Included services and ports would appear based on the zone definiton. (Internal doesn't have ports or masquerade or anything special aside from services.)

We'd need to add a way to have multiple interfaces and allowed address ranges too.

**Comment by garrett** [comment]
Here is a bunch of explorations of how to show the various default zones:

![firewall-dialog-add-zone-all](https://user-images.githubusercontent.com/10246/55489571-79016980-5632-11e9-962b-eb82619475b1.png)

(I moved the mockup in the previous comment to the top-left)

**Comment by garrett** [comment]
Other zone-related things:

- Zone support in the add services dialog
  - We (@Gundersanne, @andreasn, and I) decided on IRC that it should be a horizontal list of checkboxes, listing only the active zones
- Services that are included in zones
  - Not editable, not deletable
  - Automatically tied to a zone
  - There should be some visual distinction to make it obvious that they are included from a zone (TBD)

Of course, we need to add multiple interfaces and enhance the allowed addresses area to support more addresses, ranges, etc. (Or is a text-based CSV list enough for this, similar to adding custom ports?)

**Comment by garrett** [comment]
Experiment for connected radios: https://codepen.io/garrett/pen/bJExev

The technique used for the horizontal list is better and can (and should) be used for a vertical list too. It connects lines between the radio buttons instead drawing one line behind them all (and offsetting for an approximate height & width).

As it's a rough proof of concept, the CSS is throw-away code and not to be used for production. The HTML, however, is really basic and something like it should probably be used in Cockpit. The same HTML is reused for both the vertical and horizontal lists too.

**Comment by andreasn** [comment]
So what's the workflow for _allowing traffic to a service from certain hosts, but block it for others_ with these mockups?
Do I add a service and set the zone in there? Or do I add a new zone that happen to have the service in it? I think there is some part of this that makes it hard to wrap my head around it.

**Comment by garrett** [comment]
@andreasn: Everything's blocked by default. You allow a service and bind it to a zone (it has to be added to at least one zone, and the default zone is pre-selected). That's it.

**Comment by andreasn** [comment]
Ah, so there is a zone selector in the Add Service dialog?

**Comment by Gundersanne** [comment]
@andreasn I think that would make sense, like similar to the proposed add zones dialog but then with checkboxes instead of radio buttons.

**Comment by garrett** [comment]
Here's a slimmed-down zones mockup:

![firewall-zones](https://user-images.githubusercontent.com/10246/56215348-cf719d80-605f-11e9-86fd-e22c5cbf1f3c.png)

I added some example text in an info popup... but the actual text still needs work. I also show a menu for setting a default.

Here's the same, without the popup or menu (for showing off, mainly for Terry):

![firewall-zones-nopopup](https://user-images.githubusercontent.com/10246/56215534-22e3eb80-6060-11e9-929f-a5dbe9a7bd1c.png)

**Comment by garrett** [comment]
I'm exploring how the horizontal layout might work with both the (pruned down) list of default zones and what happens when there are more (and longer-named) zones and how they should be displayed.

For a first pass, we could also just choose to ignore the custom non-Firewalld too. But it's probably not really much more effort to support them code-wise, I think?

![firewall-dialog-add-zone-horizontal](https://user-images.githubusercontent.com/10246/56219114-7b1dec00-6066-11e9-8469-e6a1d625d791.png)

"Libvirt" is RHEL, the ones with "Fedora" are Fedora. :wink:

The top row is what would happen with additional not-shipped-by-Firewalld-itself zone(s) when there's space to the side. The bottom row is what it would look like if it was forced to wrap. 

I'd do some CSS layout (flex, specifically) to make the groups wrap when needed. I could always make them wrap lower too, but it does look nice if there's one on the same line otherwise.

On the left is an experiment with labels above radios and then to the right, I have radios above labels. Go further right, and you see what it would look like if labels are to the right of the radios — but just for custom services. The rightmost mockup on the top line is what it would look like if custom options would _always_ wrap.

**Comment by garrett** [comment]
I've thought about how the zones should be added to services.

There are 3 options:
1. Above
2. Below
3. Integrated (and duplicated, basically)

![firewall-dialog-add-service-with-zones](https://user-images.githubusercontent.com/10246/56221577-c6d29480-606a-11e9-877b-45a22aad31ae.png)

Even though there's duplication, the integrated option feels best to me. What do you think?

I suppose yet another alternate approach would be to make the radio buttons a progressive disclosure switcher at the top and change the dialog below it... but that would indent everything over a bunch and add a few more elements.

**Comment by garrett** [comment]
Here's a rework of the vertical zone selector without drop/block/trusted and with "Libvirt" and the Fedora zones, just to compare again against the horizontal one.

![firewall-dialog-add-zone-vertical](https://user-images.githubusercontent.com/10246/56223908-f2f01480-606e-11e9-85c4-0fc4f45d9a1f.png)

**Comment by andreasn** [comment]
> Even though there's duplication, the integrated option feels best to me.

If we go with integrated, will checking it in one pane affect it in the other?

**Comment by garrett** [comment]
@andreasn: Ideally, yes. The two zone widgets should really act as one. In typical usage, it would be a bit of a corner case to check a zone with services selected and then select ports and re-select zones... but if someone does that, it should persist.

**Comment by garrett** [comment]
@Gundersanne: As far as implementations go, all the alternates for the zone radios are basically CSS / layout changes. The simplest to implement would be the vertical version of the radios. You don't need to worry about the layout or the line behind the radio buttons. Just put the first set of zones in a `<fieldset></fieldset>` (with a class) and the second set in another `<fieldset>`.

And for the zones in the services dialog, it should only display when there's > 1 zone. Otherwise, it should act like it currently does and add the service to the default zone.

**Comment by garrett** [comment]
I've made an overview that tries to capture everything above as well as IRC and BlueJeans conversations.

## Zone Radios

The Add Zone sets of radios have been flattened out to be two sets of `<fieldset>`s (grouped inside a `role="group"`, probably) — the two groups are the filtered list of defaults and additional zones added by other packages.

I've dropped "custom", as @Gundersanne and I both think that there are enough zones already. (We can add it later, if need be. But it shouldn't be a focus for now.) 

I've gone with the vertical design and removed the layout, so @Gundersanne can focus on implementing it instead of worrying about implementing one of the layouts above. I can add some style and layout later via CSS.

## Read-only Services

The biggest change is the addition of read-only services. These are brought in via zones and mentioned when the service is expanded. To remove these services, one needs to remove the zone.

_Also_, I have Cockpit set as a read-only service by default too, as we wouldn't want to break Cockpit from within Cockpit itself. :scream:

Right now, read-only services removes all actions. (When we _eventually_ have logging, we'd probably have the ︙ menu... but still no :wastebasket: button or "Disable" action.) Read-only is also indicated with a grey background. It should also have a message when expanded. Additionally, read only services should probably be sorted to the top of the list, similar to security updates in the Software Updates page.

## The New Mockup

![firewall-zones-overview](https://user-images.githubusercontent.com/10246/56299369-2fd20f00-6134-11e9-8f0f-a16c842129d6.png)

**Comment by marusak** [comment]
Already implemented
