### ISSUE TITLE
use cockpit more than one user

### ISSUE THREAD

**Issue by vampywiz17** [cockpit-project/cockpit#11308]
i install cocpit about 7 machine and manage all off them one system (named "master cockpit")

My problem is that i login to my cred. and add the machines my cred. if  someone else is login to the "master cocpit" the system is try to login the attached server to my cred... and of course  ask my password.

It not possible to set that the cockpit try to logging in to the other servers to logged user? (all user that able to access it, able to access all machine)

Little tricky, but this user is AD users (realm ) so not possible to sync the users between the servers.

**Comment by johnnygtech** [comment]
I came here to post this exact problem.  A shared cockpit master server, without shared credentials.

The fix I THINK makes sense might be to allow 'adding machines' with a "passthrough authentication" option instead of storing a username in the machine.d/file, have a flag that, if true, simply uses the credentials of the logged in user.  

Assumes that the user has matching usernames/passwords on target machines.

**Comment by martinpitt** [comment]
You can directly log into a remote server without first logging into the "master cockpit" server. This is called "bastion host" mode. You can do this by opening "Other options" on the login page and set a host name, then cockpit will use ssh to log in from the "master cockpit" server to the remote one.
