### ISSUE TITLE
manifest: It's unclear what the difference between menu and tool is

### ISSUE THREAD

**Issue by larskarlitski** [cockpit-project/cockpit#11310]
We [document](https://cockpit-project.org/guide/latest/packages.html#package-manifest) both `"menu"` and `"tool"` keys for a package manifest. I think this goes back to the old shell layout. Now, that distinction is a bit of vertical whitespace in the sidebar.

Does it make sense to have these two sections? Which packages should go in which section? It seems arbitrary to me right now.

**Comment by garrett** [comment]
Oh, right! 

The discussion was captured at: https://github.com/cockpit-project/cockpit/pull/5980 — I remember discussing this with @stefwalter and others prior to that. Stef wrote it down in that PR.

---

I think now that we have more "tools", there needs to be a more prominent separation between the two items — or even more groups.

Here's a screenshot with a tiny bit more space, to make it more obvious:

![screenshot_2019-03-05 virtual machines - sunny 2](https://user-images.githubusercontent.com/10246/53808049-8226ea00-3f51-11e9-8291-43d99b29cdb9.png)

Also, I think at one point we wanted to move tools to the bottom to separate them from the rest of the host items. At the time, I didn't understand grid and flex layouts quite as much as I do now, but a simple bit of CSS to achieve the effect would be the following:

```css
.host-apps {
  display: flex;
  flex-direction: column;
  justify-content: space-between;
}
```

It would look like this:

![screenshot_2019-03-05 virtual machines - sunny 1](https://user-images.githubusercontent.com/10246/53808033-789d8200-3f51-11e9-9cc9-15e18be241ba.png)

Considering we now have so many "tools" (and items in general), we probably want to rethink this one way or another. Perhaps a new reclassification, or additional ones are needed.

---

I do remember working with @andreasn and @mvollmer with regard to Applications and how they had their own entry in the sidebar (mockup @ https://github.com/cockpit-project/cockpit/wiki/Feature:-Task-Switcher#application-support & https://github.com/cockpit-project/cockpit/wiki/Server-Applications). You can see the tools menu in that mockup is only "Accounts", "Diagnostic Reports", and "Terminal". It was only intended to be around that size originally. Since then, Cockpit has grown a lot.

For a frame of reference: Support for Applications in Cockpit was design and landed around the same time the new navigation did.

**Comment by larskarlitski** [comment]
Thanks a lot for the context, Garrett!

I really like the [order you linked to](https://github.com/cockpit-project/cockpit/pull/5980). I think we should add it to the manifest documentation and reorder the new pages to fit this model.

**Comment by garrett** [comment]
## Recommendations

- Re-order current items again based on [the documented order](https://github.com/cockpit-project/cockpit/pull/5980#issue-108280897)
- Merge the various diagnostic pages into 1 page (with sub-pages)
- Move SELinux to logs, as it's a specialized log tool basically (or perhaps diagnostics?)
- Move all of our developer-centric items into one group, perhaps move them to the bottom, so we can see a pristine menu without our clutter
- Make Applications and its installed applications a group
- Graduate the Software Updates page away from the "tools" group

## Considerations

- Add additional group(s)?
- Icons for the main elements?
  - Perhaps not. [There are good reasons why we don't have icons](https://uxmyths.com/post/715009009/myth-icons-enhance-usability). But we might want to consider it for the top-most important pages only, if so. And only then, symbolic and SVGs.
- Group with headings?

**Comment by garrett** [comment]
We have something like "simple nav" for the host menu now:
https://www.patternfly.org/v4/documentation/react/components/nav/#examples

But I think we should take the above recommendations & considerations and combine it with our discussion at the recent hackfest about integrating everything into one side menu. As it would mean we'd have even more stuff in the menu, I'd suggest switching to the grouped menu:
https://www.patternfly.org/v4/documentation/react/components/nav/#grouped-nav

I have a lot in mind about the navigaiton and would like to capture it into a design when I get back from vacation. :wink:

**Comment by marusak** [comment]
There is #12784 which designs new menu and also shows "tools" text in mockups, so it makes it apparent what is what :)
