### ISSUE TITLE
storage: Many custom NFS mount options can only be changed when unmounted

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#11436]
Cockpit version: 188.x
Page: Storage

We let people change the mount options of mounted NFS filesystems, and rely on "mount -o remount,..." to apply them.  This works for the standard "auto" and "rw" options, but not for most other options, such as "soft", ""acl", "nfsvers", ...  The error message is less than helpful:
```
mount: /mnt: mount point not mounted or bad option.
```

**Comment by marusak** [comment]
This issue is closed due to inactivity.

If this issue is a bug report and you are still able to reproduce it, please
comment here and provide us with an updated reproducer.

If this issue is a request for a new feature, we are sorry, but we won't be able
to address this in any time soon. If you are interested in helping us with
the implementation, please comment here.

**Comment by marusak** [comment]
This issue is closed due to inactivity.

If this issue is a bug report and you are still able to reproduce it, please
comment here and provide us with an updated reproducer.

If this issue is a request for a new feature, we are sorry, but we won't be able
to address this in any time soon. If you are interested in helping us with
the implementation, please comment here.
