### ISSUE TITLE
cannot install latest version of cockpit on debian

### ISSUE THREAD

**Issue by connected201** [cockpit-project/cockpit#11584]
current installed version: 188. 
OS: Debian 9
i installed with tutorial on official page (https://cockpit-project.org/running.html)
current version is 188, but on github is 191, how i can upgrade to v.191 ?

**Comment by martinpitt** [comment]
Sorry, newer cockpit versions are [only available in experimental](https://tracker.debian.org/pkg/cockpit) right now, as  Debian unstable is frozen for the Debian 10 (buster) release. So I can't currently do newer official backports. But you are of course welcome to take the source package from experimental and [build it yourself](https://wiki.debian.org/SimpleBackportCreation). We test the newer versions including their packaging on Debian 9, so that's pretty much guaranteed to work.

**Comment by connected201** [comment]
thanks, best regards!
