### ISSUE TITLE
bug: dockerfile create dirs and chown www-data:www-data

### ISSUE THREAD

**Issue by ilovett** [cockpit-project/cockpit#11685]
Can't mount storage/config for persistence because docker mounts as `root:root` and upon going to `/install` the ui tells me those dirs are not writable.

![image](https://user-images.githubusercontent.com/1776100/56851897-38131280-68c9-11e9-8f22-0493e62c357a.png)

**Comment by marusak** [comment]
I am sorry, but I don't follow.
Can you me more specific, mainly what actions you do in Cockpit and in what place it does not work as expected or what feature you are missing.

**Comment by marusak** [comment]
ping @ilovett

**Comment by KKoukiou** [comment]
@ilovett I don't understand how to reproduce your issues either - or how it's related to cockpit whatsoever. It's seems that this issue has being long inactive, so I will close it so that our list does not get filled with inactive issues - feel free to reopen if you want to discuss it and let us know how to reproduce.
