### ISSUE TITLE
machines: disk Storage and Pool makes the list very tall

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#11754]
Cockpit version: 192
OS: Fedora
Page: Machines

I added a new disk to a VM. The entry is very tall. I think it's because Pool and Volume goes on top of each other, rather than inline next to each other.

![Screenshot from 2019-05-06 15-12-09](https://user-images.githubusercontent.com/209895/57227352-79b26480-7011-11e9-81bd-d2df02e952e1.png)

**Comment by garrett** [comment]
I think this is the expected behavior?

Each source is on its own line. That entry has a source of "Pool" and "Volume". I think we had this discussion before somewhere?

The alternative would be to flow them across, but then that would have to be done correctly (so label + value would always be on the same line, in case they needed to wrap)... and there can be several sources, according to @KKoukiou.

Closing, as I don't think there's a better way of properly handling this. At least they're all top-aligned.
