### ISSUE TITLE
Show an error message when websocket fails (especially for Safari on iOS)

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#11844]
While Cockpit shows an error message when websocket isn't supported at the login screen, there are times when websocket doesn't work as expected after signing in.

The one "common" case I know about would be Safari on iOS with a self-signed certificate.

Right now, Cockpit just shows a blank white screen. We should at least show an error message. It would be even better if we suggested a solution.

**Comment by garrett** [comment]
Related: https://github.com/cockpit-project/cockpit/issues/10146

**Comment by SunilMohanAdapa** [comment]
This is a big improvement in debugging cases were `Origins` is not configured properly, but the error message could itself be improved.

In case of FreedomBox, `Origins` directive in the Cockpit is automatically configured to be a list of all domains the system is responsible for handling. We, however, don't add IP addresses of the machine to the list due to fear of CSRF with WebSocket when the IP address of the machine changes due to DHCP. All of this is hidden from the user and the FreedomBox manual explicitly mentions that Cockpit is not available when tried using IP addresses. However, some users are always bound to use Cockpit over IP addresses due to habit with other applications.

This is where a more specific message would be helpful. Since Cockpit knows list of domains in the `Origins` directive has and the current domain sending requests, it should be possible to conclude if the current domain is a valid domain for sending WebSocket requests. A message such as 'Cockpit is not configured to be available using this domain.' would provide the user better direction than 'There was an unexpected error while connecting to the machine.'.
