### ISSUE TITLE
Machines: No volumes in iscsi and iscsi-direct pool

### ISSUE THREAD

**Issue by qiankehan** [cockpit-project/cockpit#11850]
Cockpit version: cockpit-193-1
OS: RHEL8

Steps to reproduce
1. Add a iscsi storage pool in cockpit machines
2. Click the pool and click the **StorageVolumes** tab, no storage volumes.   
While they can be listed by virsh:
```
# virsh vol-list iscsi                         
 Name         Path
----------------------------------------------------------------------
 unit:0:0:0   /dev/disk/by-id/wwn-0x6001405383e88a7319647ca90cfd80cd
 unit:0:0:1   /dev/disk/by-id/wwn-0x60014056cdcf2cbf4c549da892be00ce
```

![Screenshot_20190517_161341](https://user-images.githubusercontent.com/6197582/57913355-05a07800-78bf-11e9-98f1-d179ede23e49.png)

**Comment by KKoukiou** [comment]
I can't reproduce on fedora-30, this is RHEL specific issue, I guess we 'll need a bugzilla for it if I will manage to reproduce it.

**Comment by KKoukiou** [comment]
@qiankehan I am afraid I can't reproduce in RHEL8.0 either. I can see the volume list from my iscsi pool.
I am using the ramdisk type in backstore for testing.

Do you see any errors in console? What happends if you force refresh the UI with ctrl-shift-R?

If not errors exists in console and you issue remains, I would need an precise reproducer. Also since this bug is for RHEL probably it would make sense to track it in BZ.

**Comment by KKoukiou** [comment]
@qiankehan Any update on this issue?

**Comment by KKoukiou** [comment]
I will close this because it's not relevant for upstream and also it has been inactive for almost a month. In case this is still reproduceable on RHEL please create a bugzilla on cockpit-appstream component.
