### ISSUE TITLE
build failing for cockpit-kube-auth on Centos

### ISSUE THREAD

**Issue by chipmap** [cockpit-project/cockpit#11894]
Cockpit version: 190
OS: Centos 7
Page: N/A

Build fails with following error:
[root@mcentos cockpit]# make
make  all-am
make[1]: Entering directory `/home/mali/Ethinza/cockpit'
  GO       cockpit-kube-auth
go tool asm: exit status 2
flag provided but not defined: -V
usage: asm [options] file.s ...
Flags:
  -D value
    	predefined symbol with optional simple value -D=identifier=value; can be set multiple times
  -I value
    	include directory; can be set multiple times
  -S	print assembly and machine code
  -debug
    	dump instructions as they are parsed
  -dynlink
    	support references to Go symbols defined in other shared libraries
  -e	no limit on number of errors reported
  -o string
    	output file; default foo.o for /a/b/c/foo.s as first argument
  -shared
    	generate code that can be linked into a shared library
  -trimpath string
    	remove prefix from recorded source file paths
make[1]: * [cockpit-kube-auth] Error 1
make[1]: Leaving directory `/home/mali/Ethinza/cockpit'
make: * [all] Error 2

**Comment by martinpitt** [comment]
Hm, the build rule just calls the Go compiler (`go build -ldflags ...`), there is no `-V` there. Can you please  re-try with `make V=1` to see the full command line? If your Go installation is broken/incompatible, then it's perhaps best to either uninstall it (so that the kubernetes part will simply not be built), or build cockpit in a [mock](https://github.com/rpm-software-management/mock/wiki) environment.

**Comment by marusak** [comment]
@chipmap ping

**Comment by marusak** [comment]
No update
