### ISSUE TITLE
Cockpit launch with Edge20 and Google Chrome 51 browser failed. 

### ISSUE THREAD

**Issue by weiwang-linda** [cockpit-project/cockpit#11994]
Cockpit version: cockpit-193-1.el7.x86_64
OS: rhvh-4.3.0.8-0.20190529.0
Page: 

Cockpit launch with Edge20 and Google Chrome 51 browser failed. 

Steps to reproduce

1. Clean install rhvh-4.3.0.8-0.20190529.0
2. Launch cockpit with browser like "http://<localhost>:9090"

**Comment by KKoukiou** [comment]
What errors do you see in the browser console? Does it work with with some browser?

**Comment by weiwang-linda** [comment]
The error is : The web browser configuration prevents Cockpit from running (inaccessible display: grid)
A modern browser is required for security, reliability, and performance.

Yes, it works with Firefox 62.

**Comment by martinpitt** [comment]
Chrome 51 is known to not be supported. https://cockpit-project.org/running.html at least requires 57. Edge 20 was expected to work, but if it doesn't support grid, we should bump the dependency. @garrett, is there a place to check this?

**Comment by garrett** [comment]
## Summary

The browsers you're talking about are from 2015 (Edge) and 2017 (Chrome). We're already half-way through 2019.

**Upgrade your browsers**. Every single browser and version you mentioned _extremely insecure_ and also don't support modern features Cockpit relies upon.

## Possible problems with old browsers

Your old browsers and (implied) Windows versions all have severe security issues that could compromise your system just by browsing to various nefarious websites. 

Once the computer running the old OS and browser combo is compromised, then connecting to any other machine through any means possible (including SSH, VNC, RDP, Cockpit, or anything else) could mean an attacker could also possibly access those systems too. They could even sniff out passwords you use on your desktop using a keylogger.

This is one of the big reasons why it's important to keep software up-to-date.

## Details

Cockpit doesn't check browsers or browser versions. It checks the _capability_ of browsers. The browser versions do not matter to Cockpit; we numbers we post on the website are the earliest browser versions that support all the features Cockpit requires to operate properly.

You will definitely want to run newer versions of browsers than the minimum, however.

Edge 20 doesn't exist. Edge is typically versioned by EdgeHTML, its engine. The _current_ version of EdgeHTML is 18. The next version of Edge is 76 (based on Blink, with version aligned to Chrome's version). Any version of Edge between 18 and 76 doesn't exist.

If you're talking about _builds_ 20.10158 through 25.10586 of Edge, those were _[preview releases of Edge from 2015](https://en.wikipedia.org/wiki/Microsoft_Edge#EdgeHTML_(2014%E2%80%932019))_.

It's possible to cross-reference versions and release dates with specific features:
- websockets: https://caniuse.com/#feat=websockets
- CSS Grid: https://caniuse.com/#feat=css-grid
  - Chrome has supported grid since March 2017
  - Edge has supported grid since October 2017
  - Firefox has supported grid since March 2017
- `@supports`: https://caniuse.com/#feat=css-featurequeries

There have been literally several hundreds of CVEs found and fixed in Edge and Chrome since 2017 (and even more if you go back all the way to 2015):
- Edge: https://www.cvedetails.com/product/32367/Microsoft-Edge.html?vendor_id=26
- Chrome: https://www.cvedetails.com/product/15031/Google-Chrome.html?vendor_id=1224

Some of these are extremely bad security issues _that have been fixed_. Browser vendors are generally really good at fixing these ASAP, but you have to be running updated versions of the browsers.

Even Firefox 62 has critical security issues at this point. The current stable Firefox is 68. The current Firefox extended release is 60 ESR, which has security backports. You shouldn't even be running Firefox unless it's one of these releases (68 or 60 ESR). There are [critical security advisories including _sandbox escape vulnerabilities_ for anything less than these versions](https://www.mozilla.org/en-US/security/known-vulnerabilities/firefox/).

(The same is true for Chrome and Edge too... they fix big bugs every release.)

Please use a modern browser. Anything that doesn't support grid is beyond insecure at this point.

Also, @weiwang-linda, you **need** to _update your version of Windows_. Whatever version you're running is _extremely_ insecure. You cannot run an even remotely secure version of Windows and run such an old version of Edge, as Edge (currently) comes bundled with Windows updates. (This will change when they officially switch to using a fork of Chromium.)

## Extended versions

If you don't want to have to upgrade major browser versions that much, then use Firefox ESR (currently at 60.8). It still needs updates, but the browser UI won't change much — it'll only get security updates in-between major releases. (I am pretty sure this slower-moving version of Firefox is available in Red Hat Enterprise Linux too.)

If you don't want to update Windows that frequently, then switch to an Enterprise Linux distro, like Red Hat Enterprise Linux for your desktops (or one of the others, but I see you're talking about using RHRV, so RHEL would make a lot of sense for you). You'd still need to install updates when they arrive, but things will be stable and the updates your computer would get will be focused on security and bug fixes.
