### ISSUE TITLE
Containers: showing wrong memory consumption

### ISSUE THREAD

**Issue by esolma** [cockpit-project/cockpit#12045]
Cockpit version: cockpit-195-1.fc30.x86_64
OS: Linux alice 5.1.7-300.fc30.x86_64 / Fedora 30 Server
Page: 

Hello everybody,

I have an issue with docker memory usage on cockpit : 

For example : if I go to Containers panel on cockpit, I can see CPU/Memory consumption of all my dockers containers.
When my containers are idle, memory consumtion are I think real. But If I download something I can see my memory usage growing and growing to the max (4 or 8GB) for deluge or nzbget. Maybe the other containers too but it's not significative.

If i do a "docker stats nzbget deluge" at the same time I see a lot of memory usage in cockpit, I got only 100Mb or 200Mb.

On the screenshot you can see that I use more than 5GB on cockpit but only 120Mb with command line.

![cockpit](https://user-images.githubusercontent.com/51715093/59290174-3e423000-8c78-11e9-8e21-52eca9bab0c5.jpg)

![terminal](https://user-images.githubusercontent.com/51715093/59290168-3aaea900-8c78-11e9-91b1-3b7265f712f4.jpg)

Then I check memory with "free" or netdata, its' exactly the same as "docker stats".

I think something is wrong with Container panel on cockpit

**Comment by marusak** [comment]
Docker is being obsoleted and being replaced with [cockpit-podman](https://github.com/cockpit-project/cockpit-podman/) and since this issue seems very specific for a two specific images I don't see this as being fixed unless someone from community is willing to do that.
My gut feeling is that we show some other metric that `docker stat` shows. More about these metrics can be found [here](https://docs.docker.com/config/containers/runmetrics/)
