### ISSUE TITLE
Embed external applications

### ISSUE THREAD

**Issue by 7roxel** [cockpit-project/cockpit#12269]
It would be useful if adding applications were as simple as configuring settings for a reverse proxies to hit a different port on 127.0.0.1 within an iframe, or even just iframes directed to ports that have been exposed like cockpit. This would give us a unified interface to for server administration of 3rd party applications such as syncthing,monit,netdata, etc.

Sorry if this is impractical or not in line with cockpit's goals. I was unable to find any reference to this suggestion so I figured I would put it out there.

**Comment by martinpitt** [comment]
You can do it the other way around at least, and [embed cockpit pages as iframes](https://cockpit-project.org/guide/latest/embedding.html).

Embedding other web sites into cockpit feels a bit strange. They would be completely detached from each other, as these pages can't run any cockpit API to actually *do* stuff on the machine; and likewise, cockpit can't receive notifications from them, tell them which language to use, etc.

That said, it should be possible in principle to extend the [manifest](https://cockpit-project.org/guide/latest/packages.html#package-manifest) to have an "url" instead of a "path" and then just load that. It's not something which our team would work on themselves, but I'm happy to help a contributor with that.

**Comment by marusak** [comment]
Closing according to the last comment

**Comment by Zinka010** [comment]
Hi there,

Was this implemented? I can't find anything in the [manifest](https://cockpit-project.org/guide/latest/packages.html#package-manifest) documentation and iframe tags that work independently aren't working with cockpit.
