### ISSUE TITLE
Should a bridge be used instead of trying to determine the path for a spawn call?

### ISSUE THREAD

**Issue by mckenziec** [cockpit-project/cockpit#12358]
Cockpit version: 194
OS: CentOS7 (Atomic as well)

Hi. Great work on cockpit. I'm really enjoying working with it (after the npm/react learning curve that is ;-)

I developed a custom plugin that leverages cockpit.js spawn to call a python script I included with the plugin itself. e.g. /usr/share/cockpit/myplugin/bin/test.py

I've tarballed my plugins so they can be copied to any Cockpit supported default plugin location (https://cockpit-project.org/guide/latest/packages.html#package-layout) such as:

~/.local/share/cockpit/
/usr/local/share/cockpit/
/usr/share/cockpit/

However there's no clear way to determine where my plugin is located (during runtime spawn() call). I could write a series of spawn failure handlers to re-call it until the right path is found, but I don't think that's the right way to do it.

The custom "bridge" support for a plugin might be another way, but there's no docs I can see on how to call a bridge command from cockpit.js. Maybe I'm misunderstanding how custom bridges are used though.

**Comment by martinpitt** [comment]
I seriously recommend to not try and find "your" plugin on the file system. Besides these three paths, someone may also compile cockpit with a different `--prefix` or set a non-default `$XDG_DATA_DIRS`.

What we do in cockpit is to include the contents of our *.py helpers right into the webpack as a string with [raw-loader](https://www.npmjs.com/package/raw-loader). E. g. the [Machine page's getOsList.py](https://github.com/cockpit-project/cockpit/blob/master/pkg/machines/getOSList.py) is imported [here](https://github.com/cockpit-project/cockpit/blob/master/pkg/machines/libvirt-common.js#L8) and then used [here](https://github.com/cockpit-project/cockpit/blob/master/pkg/machines/libvirt-common.js#L1248).

[python.spawn()](https://github.com/cockpit-project/cockpit/blob/master/pkg/lib/python.js) is a little helper around `cockpit.spawn()` that checks whether the system has python3 or python2, so that stuff works equally well on modern distros and RHEL 7. If you care about this, feel free to copy python.js into your project (or just the function), otherwise use `cockpit.spawn()` directly.

Does that help you?

**Comment by martinpitt** [comment]
Bridges are explained in the [guide](https://cockpit-project.org/guide/latest/packages.html#package-bridges), but first they wouldn't really help you here, and second they would be total overkill for such a task.

**Comment by mckenziec** [comment]
Thanks for the quick reply Martin. I was thinking to go with a custom JS (using cockpit.js) exec caller that'll check the XDG paths on the host system, and attempt to execute the first one I find in order of the XDG paths that cockpit would use anyways. I could also cache the location my spawn call was able to successfully execute from so I don't have to good looking for it every time. The reason for doing it this way would be so I could use pyinstaller to package up any python script dependencies into a single executable.

I try playing with your suggested python.spawn approach and see if I can get it going.
