### ISSUE TITLE
machines: Inadaquate messaging when "create VM" is not possible

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#12383]
When it's not possible to create a new VM, a tooltip shows up. Unfortunately, it's at the top of the screen and the message is cut off.

![Screenshot from 2019-07-22 12-03-25](https://user-images.githubusercontent.com/10246/61624538-1384c780-ac79-11e9-9ed5-810816afe8c3.png)

This is running on Silverblue, and I don't have pools or virtual networks available either (which I guess would bump this down).

**Comment by KKoukiou** [comment]
@garrett it's on top of the screen because you didn't have libvirt-dbus installed (because you installed from sources ignoring the deps)

With libvirt-dbus, you get the two tabs for Virtual Storages and Networks, which makes this tool-tip be visible, since it's not hitting the top shell.

In addition, we are soon dropping support from distros which don't have libvirt-dbus available, so no user will get to this view, unless they build from sources and forget to install the required deps.

I think it's safe to close this as won't do for the above mentioned reasons, but I leave it up to you.

**Comment by KKoukiou** [comment]
I will close this as I don't think it's worth do get it fixed. This only happens when libvirt-dbus is not installed and also virt-install is not install.
libvirt-dbus is a required dependency of cockpit-machines for all the distros that have that package.
ubuntu-stable is the only image we support now that does not have this.
I don't think it makes sense to bother to fix it honestly.
