### ISSUE TITLE
Stop and DO NOT disable service

### ISSUE THREAD

**Issue by andreymal** [cockpit-project/cockpit#12451]
The new design does not allow to stop a service without disabling it.

I don't want to disable it, I just want to stop it until reboot!

Please restore the old behavior in some way.

---

Old design ("Stop" and "Disable" are sepatate buttons, it's good):

![](https://i.imgur.com/VOL3eo7.png)

---

New design ("Stop and Disable" is not what I want):

![](https://i.imgur.com/svDWuEL.png)

**Comment by garrett** [comment]
@andreymal: Thanks for your feedback! I talked with @marusak and others on IRC and have come up with an idea on how to adjust this design.

(The redesign was made because the old design performed quite poorly in usability studies. The only people who understood what to do were very experienced UNIX admins — and even then, not all of them. So, we're not going back to the old design... but we can improve the new one to fit your needs.)

---

@marusak: Let's rework the menus a bit.

Move "Reload" above "Restart". Add "Start" or "Stop" in some cases. The actions would be ordered from lightweight to heavyweight, with a divider before masking (as it's not common and should generally be avoided).

In the case of a service running, we'll drop "Restart" and "Reload" and replace them with "Start".

In addition, I think it would be nice to have a start button displayed when the service was intentionally stopped, similarly to when the service is failed, so it's easy to start back up.

Revised menus would look like this:

#### Enabled & running
> Reload
> Restart
> Stop
> ___
> Disallow running (mask)

#### Enabled & stopped
> Start
> ___
> Disallow running (mask)

#### Enabled & failed
> Start
> ___
> Disallow running (mask)

#### Disabled & stopped
> Start
> ___
> Disallow running (mask)

#### Disabled & running
> Stop
> Restart
> ___
> Disallow running (mask)
