### ISSUE TITLE
Support for host networking in Docker

### ISSUE THREAD

**Issue by rcarmo** [cockpit-project/cockpit#12485]
Page: Docker 

It would be nice to be able to specify that a container should be run with host networking instead of having to map ports. This is necessary for things like Plex, Minecraft, etc., which need to do UDP broadcasts for network discoverability as well as opening extra ports on demand.

**Comment by KKoukiou** [comment]
@rcarmo cockpit-docker is not being actively developed any more from our side. cockpit-podman has our focus as a container UI mainly. We can look into porting this feature over to cockpit-podman if you are interested, or, if you want to implement it that we 'll gladly review that and add it.
Closing this RFE issue, since docker is not being developed any more. Feel free to open a PR or an issue in https://github.com/cockpit-project/cockpit-podman/
