### ISSUE TITLE
"Create VM" button unclickable (keeps adding spacing, "jumping" down the page)

### ISSUE THREAD

**Issue by fonix232** [cockpit-project/cockpit#12511]
Cockpit version: 199-1
OS: Ubuntu 19.04 (cockpit installed from Backports)
Page: Virtual Machines

On a freshly installed server, the "Create VM" button, while enabled, is unclickable - the moment the mouse pointer hovers over the button, it "jumps down", adding some empty space to the page. 

Steps to reproduce

1. Install Cockpit 199-1 from disco-backports, with `cockpit-machines`
2. Go to "Virtual Machines" page of cockpit
3. Try to click "Create VM"

Screenshots:

<img width="1680" alt="Screenshot 2019-08-07 at 11 05 26" src="https://user-images.githubusercontent.com/371847/62614491-66aa7b80-b903-11e9-9e8b-a89ed3a2ab54.png">
<img width="1680" alt="Screenshot 2019-08-07 at 11 05 35" src="https://user-images.githubusercontent.com/371847/62614492-66aa7b80-b903-11e9-9234-c9172eb8500f.png">
<img width="1680" alt="Screenshot 2019-08-07 at 11 05 37" src="https://user-images.githubusercontent.com/371847/62614493-66aa7b80-b903-11e9-8979-c7ced63b3a17.png">
<img width="1680" alt="Screenshot 2019-08-07 at 11 05 39" src="https://user-images.githubusercontent.com/371847/62614494-66aa7b80-b903-11e9-8a3a-d7b8b06b08b7.png">
<img width="1680" alt="Screenshot 2019-08-07 at 11 05 41" src="https://user-images.githubusercontent.com/371847/62614495-67431200-b903-11e9-9b7a-0da2a4e90194.png">

**Comment by fonix232** [comment]
Looks like a similar thing is happening to the "Get new image" button on the "Docker Containers" page as well - not on hover, but on clicking it, it will slide down. Difference is, the Docker button is clickable.

**Comment by garrett** [comment]
This looks like the issue snuck in recently. I see it here locally in WebKit-based browsers, including GNOME Web (Epiphany) and Safari.

As I'm on the last day of a work trip, I might not get to it today (I'll try), but I'll try to get this addressed ASAP. I'd love to get this fixed in our next release.

**Comment by garrett** [comment]
I've been working more on this issue today.

For testing purposes, I:
- removed the positioning of the button (removing position absolute)
- removed all `animation` and `transition` CSS from our "listing" component.

...and there are _still_ issues in WebKit browsers (Safari and Epiphany). They're not blinking or moving things around _as much_, but they still do.

It looks like we're hitting https://bugs.webkit.org/show_bug.cgi?id=187903.

There's a _possible_ workaround to add a `will-change` property (in CSS) to the `caption` element. I'll investigate this.

Meanwhile, I think we should drop `<caption>` from listings. It should be replaced with a block element that can take `display: flex` (caption cannot) above the table, with a heading (`h3` most likely — I'd have to double check, but we should have `h1` for the app "title", `h2` for the page's title (even if not visible), and `h3` for the headings on the page... heading levels even work across `iframes`, so consider the `iframe` a part of the parent document in this usage). Then, there should probably be an `aria-labelledby` attribute on the table that points to the ID of the `h3` for the title of the list (basically replicating the functionality of a `<caption>`).

As we currently abuse table `caption`s by shoving extra stuff inside (like buttons floated to the right), this approach would fix accessibility issues, making alignment better (using flex instead of float or absolute positioning), and also fix WebKit-based browsers.

We'd probably want to reformat it to something like this:

```html
<section class="ct-listing">

  <heading>

    <h3 id="machines-listing-title">Title here</h3>

    <div class="ct-listing-actions">
      Buttons and other stuff
    </div>

  </heading>

  <table aria-labelledby="machines-listing-title">[table goes here]</table>
</section>
```

The API would change, which means every place where elements shoved into what would become `<caption>` currently would need to be fixed to specify the non-title part as "actions" or something. If the title is just plaintext, then it would work as-is.

---

Why wasn't this noticed earlier? There's more positioning and and animations (using positioning) in the PatternFly 4-ish style, triggering the WebKit caption bug quite a bit more.

**Comment by garrett** [comment]
Apparently, there's an issue when trying to workaround caption elements by using ARIA in WebKit where adding ARIA to a table element would cause WebKit to treat the table as a layout table instead of an actual table:

- https://www.scottohara.me/blog/2019/04/19/tabled-tables.html
- https://bugs.webkit.org/show_bug.cgi?id=197082

Perhaps we'd need `<table role="table">` or to drop the aria attributes and rely on contextual headings. There's a similar technique I previously looked at for deconstructing tables for responsive views that use redundant roles on elements to force browsers to treat elements properly @
- http://adrianroselli.com/2018/02/tables-css-display-properties-and-aria.html.
- https://developer.paciellogroup.com/blog/2018/03/short-note-on-what-css-display-properties-do-to-table-semantics/

I'll update my example snippet above.
