### ISSUE TITLE
Bot triggers all tests when branch not in testmap

### ISSUE THREAD

**Issue by atodorov** [cockpit-project/cockpit#12633]
With the bots code as of today I've force pushed a pull request and noticed that there were multiple test jobs scheduled which are all wrong, see:
https://github.com/weldr/lorax/pull/837

Branch `rhel8-branch` is not listed in `testmap.py` and this PR triggers all `rhel-7-7*` jobs, all `fedora-30*` jobs and all `rhel-8-1*` jobs while I expect it to trigger none of them. For this branch we're supposed to use only the `rhel-8-1` jobs by triggering them by hand until the rest of the CI enablement code lands in place.

This is messing up with pull request for downstream branches so please take a look at it ASAP.

**Comment by marusak** [comment]
Thank you for the report.
It is true that we don't open PRs against unknown branches. Why don't you just add that branch into `testmap` and have things triggered for it automatically?
Or if you just don't want any tests for this branch you can either:
1. Add `no-tests` label or `no-tests` string into PR title
2. Specify this branch in testsmap with empty array

Although it is not intentional to trigger everything when the branch is unknown, it does not seem that wrong to me (bots don't know what to test, so they try everything). However it is a lot of noise.
We should however probably trigger no tests - it just needs a bit more logic, which is getting to complex with all possibilities of what to trigger when and what still is acceptable.

**Comment by atodorov** [comment]
> Why don't you just add that branch into testmap and have things triggered for it automatically?

Because the CI integration for this branch isn't ready yet. It is still not merged.

> We should however probably trigger no tests 

I think this was the default before, maybe unintentionally I don't know. My expectation is that if a branch isn't in testmap then bots will not try to start test jobs. But a person should be able to kick off the jobs manually via the command line, no ?
