### ISSUE TITLE
New Navigation

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#12784]
## Desktop

- Includes search
- Merges top-level nav into "normal" nav
- Organizes nav into separate groups
- Prioritizes applications at the top
- Merges dashboard into host selector (not pictured)

![Screenshot_2019-09-12 Cockpit HTML mockups(2)](https://user-images.githubusercontent.com/10246/64786707-55dace80-d56f-11e9-87c5-2885b772320c.png)

## Mobile

- Bottom action areas (like we have now), for easy finger reaching on phones
- Consistent placement
- Apps icon when there are apps (would need to have the apps group in the normal menu — perhaps do the same for desktop?)
- Split host selector into separate top-level
- Change dashboard concept
   - Make the host selector "the dashboard"
   - Make dashboard page a bit more detailed with status
   - Remove graphs from dashboard page (as they break scaling, cause extra load on remote machines, and are not so usable as they require interpretation and show different scales for all the machines)
   - This page would be editable by default with add/remote buttons (not yet pictured)
- Searching for host menu and host switcher ("dashboard") are at the bottom for finger reach

Due to the amount of optimizations, I think we'd need to have 2 similar, yet different, top-level menus to accommodate both desktop and mobile views. :neutral_face: (Perhaps I can iterate and come up with a better solution?)

![nav-unified-mobile](https://user-images.githubusercontent.com/10246/64786773-8458a980-d56f-11e9-8e6c-0104e5b07885.png)

**Comment by marusak** [comment]
Just worth mentioning that https://github.com/cockpit-project/cockpit/issues/11310 exists and this issue (hopefully) obsoletes it :)

**Comment by martinpitt** [comment]
I really like the single-level nav and getting rid of the dashboard! Some questions/comments:

  * What is "View all apps"? Is that our current "Applications" page where you can find/install new ones? I. e. if you uninstall cockpit-packagekit that would disappear.

 * I like renaming the  "System" page to "Overview". We could then move the graphs and PCP to a new "Performance" page.

 * I'm not that fond of the "Debug" section. Pretty well everything we do is being used for debugging problems. It's hard enough to draw a well-defined line between "menu" and "tool" (although there's still a good intuition about it); e. g. selinux should be "menu" (particular aspect of functionality), and kdump and sosreport should be in "tools" (not specific to a particular subsystem, general troubleshooting or maintenance). Also, with the recent merging of playground pages, there's just one extra "Developer" entry now, which should be fine to go into the menu or tools.

 * Could we save some vertical space by indenting the Apps/System/Tools entries and skip the empty lines? Or conversely, format the headings so that they stand out better?

 * Mobile: I don't have a strong opinion between keeping a second top-level button for the apps vs. merging it into the menu (as desktop mode does). But if we have two buttons, it feels like apps should be the leftmost, as it also influences the menu then.

Thanks!

**Comment by garrett** [comment]
> What is "View all apps"? Is that our current "Applications" page

Yep!

I was also thinking about perhaps dropping this menu item, adding an "edit" link next to apps and keeping Applications under System. (And "edit" would simply be a duplicate link to Applications, but in-context instead of separated out.)

The reasoning for the change: The Apps group wouldn't appear unless there's actually an application. You would add an application from the Applications page like now. The edit link would let you change it without having to re-find the Applications entry.

> I like renaming the "System" page to "Overview". We could then move the graphs and PCP to a new "Performance" page.

:+1:

> I'm not that fond of the "Debug" section. 

Yeah, agreed. 

> Could we save some vertical space by indenting the Apps/System/Tools entries and skip the empty lines? Or conversely, format the headings so that they stand out better?

1. Space is not bad. It helps to break up the items.
2. This is how PatternFly 4 is.

> Mobile

Mobile is still WIP. I wanted to shared what I had with an idea of splitting out applications. That might change, however.

I did have apps on the left first, but then the UI is then inconsistent whether or not an app is installed. (And if it's always there, then we're showing a useless menu icon.)

**Comment by garrett** [comment]
## Updated desktop version

1. Interactive demo: https://garrett.github.io/cockpit-mockweb/navigation2/

2. Static mockup

   ![nav-merged-desktop](https://user-images.githubusercontent.com/10246/76869912-495e6800-6869-11ea-8092-f26e307d34ff.png)

## Updated mobile

1. Static mockup

   ![nav-merged-mobile](https://user-images.githubusercontent.com/10246/76869956-58451a80-6869-11ea-89a7-7cef2bc26c64.png)

Reordering of the menu so search is at the bottom and apps are righ tabove it would probably be done with duplication of the elements and hiding the non-applicable version, so we could react to the mobile/desktop CSS and keep document order in both layouts. (The alternative, simpler approach would be to shift things around with CSS... but that would break a11y. Therefore, the duplication method I mentioned would probably be better.)

Interestingly, the new Firefox Preview does exactly this same thing. They have a menu attached to their navigation bar. The navigation bar can be moved to the top or bottom. They reorder the items on the menu (which are in groups) based on prominence and pointer location. (On mobile devices, the "pointer" is actually the pointer finger, of course.)
