### ISSUE TITLE
Firewalld: add custom ports, leads to unpredictable names and persistent data, inconsistecy with firewallcmd

### ISSUE THREAD

**Issue by jscotka** [cockpit-project/cockpit#12849]
I creted custom port to network firewall via cockpit: 
with name: ``random_name``
tcp port: 22
udp port: 55

it is properly created and displayed in cockpit.

But:
1. **firewallcmd inconsitency** command ``# firewall-cmd --list-services`` shows
```
amqp cockpit custom--ssh-isi-gl dhcpv6-client ssh
```
where ``custom--ssh-isi-gl`` is name of ``random_name`` service

the name is used not the proper one bug name of generated file: 
```
# cat /etc/firewalld/services/custom--ssh-isi-gl.xml 
<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>random_name</short>
  <port port="22" protocol="tcp"/>
  <port port="55" protocol="udp"/>
</service>
```
what leads to incompatibilty of names via cmd line tool and cockpit
probably solution is to generate also name of file, or set some attribute there, to not use file name, but some name defined in XML

2. I'm **able to use same name** for creting new ports with another number (eg tcp 33, udp 55), it leads that I have same name, what is confusing

3. I'm **not able to create new port filter with another name**: because file name will be same:
leads to erros, because this short name is not unique identificator: 
```
Failed to add service

Error message: org.fedoraproject.FirewallD1.Exception: NAME_CONFLICT: new_service(): 'custom--ssh-isi-gl' 
```

4. last one is more less RFE: when I' create custom ports, this is permanently stored, unable to anyhow to **remove** it, I can add it via add service dialog and search for this newly created. So that unable to revert when I've create something by mistake and previous errors causes to misuse of same firewall service name

**Comment by marusak** [comment]
We talked about this on IRC and we came up with idea that the best solution would be to introduce another optional field `id` where users who are interested in having a specific id could set it up.

**Comment by Gundersanne** [comment]
And no. 4: firewalld's dbus api has the "builtin" property for services. We could use this to see if the service is "custom" or not. And then (optionally?) delete the definition of that service as well.

**Comment by Gundersanne** [comment]
So we switched to using IDs for zones now, as `firewall-cmd` and `firewall-config` never really show `<short_name />`. We should probably do the same for services, as the `<short_name />` is only retrievable by `--permanent --service="$service" --get-short` with `firewall-cmd`. So it's not really used for services either.

I'll make a PR for permanently deleting custom services as well. I think this should only happen if the service isn't part of any other zone (active or inactive).

**Comment by Gundersanne** [comment]
So #13756 removes the `Name` field in the form and switches to `Id`. It'll offer to generate a service Id for the custom services, or you can specify a custom id to use. So naming conflicts shouldn't be too much of a problem anymore.

Also after discussing on irc, allowing to permanently delete the custom services would open up another can of worms. There's no way to figure out if a custom service has been created by cockpit and the only way we can find out if a service is custom or not is by the path (custom services are stored in `/etc/firewalld/service`). Furthermore we'd need to be sure that the custom service isn't in use for any zone, but since zones can also be added/defined at runtime it's difficult to ensure it.
