### ISSUE TITLE
Version in centos 8 

### ISSUE THREAD

**Issue by santxus** [cockpit-project/cockpit#12968]
Hi

We are starting to use Centos 8 but the last version that we can update using yum or dnf is 185.

Do we have any other repo or option to update cockpit to the last version?

Thank you

**Comment by martinpitt** [comment]
https://copr.fedorainfracloud.org/coprs/g/cockpit/cockpit-preview/ always has the latest build. Beyond that we (as in the Cockpit upstream project) don't have any influence on what goes into CentOS 8.

**Comment by PeterFalken** [comment]
I think that maybe the repo for CentOS 8 is being updated from beta to release, because I checked today and the COPR site only lists the Fedora 30 repository, I'm guessing that a cleanup is happening in the background now that Fedora 31 has been released as well.

![Screen Shot 2019-11-04 at 3 10 54 PM](https://user-images.githubusercontent.com/2557898/68158614-96bee600-ff15-11e9-8eb5-ec9e95cd5945.png)

**Comment by marusak** [comment]
Thanks for pointing this out @PeterFalken . We updated it and now there is epel 8 (next release should build for it as well).

**Comment by martinpitt** [comment]
Today's 207 release now has a current COPR build for epel-8: https://copr.fedorainfracloud.org/coprs/g/cockpit/cockpit-preview/build/1093927/

**Comment by PeterFalken** [comment]
Thank very much - The update to this version was smooth and without any issues. It also removes the subscription manager dependencies on CentOS 8.
