### ISSUE TITLE
Cockpit should not permit empty password

### ISSUE THREAD

**Issue by cowreth** [cockpit-project/cockpit#12996]
Cockpit version: cockpit.x86_64, 185.1-1.el8_0
OS: Linux centos8 4.18.0-80.11.2.el8_0.x86_64
Page: LOGIN

**Issue description** : Cockpit accepts login when user has no password

**Issue facility** : Security, Login
**issue criticity** : default to low, but might be critical if any standard installation leaves an unlocked account with empty password, cockpit will disclose a lot of information.
**issue follow-ups**: might fall as "need_discussion" or "wontfix"

**Steps to reproduce**
1. adduser test_user
2. passwd -d test_user
3. login in cockpit with _any_ password

**Source, Considerations**
It's because of _PAM_ having `nullok` by default and cockpit relying on _PAM_.
Even if one should not leave an account with an empty password, cockpit should prevent login for such users (IMHO).
SSHd prevented this behaviour by default; vsftpd did not.

**Possible fix**
Don't rely on `pam.d/system-*`, create a new profile (e.g. : as ssh does)

Kind regards,
Seb

**Comment by martinpitt** [comment]
Sorry, we won't do a parallel PAM hierarchy. This would destroy too many things the admin sets up for other logins, such as 2FA, pam_faillog, pam_deny rules, etc. Also, PAM configs vary wildly between distributions and releases, so both conceptually and practially we want to use the same stack as ssh, login, gdm, etc.

**Comment by cinderblock** [comment]
But SSHd has configuration that specifically disables empty passwords, doesn't it? It also has the ability to disable password authentication (to enforce key usage for instance). So, unless I'm confused, it's common that programs using PAM allow some subset of extra configuration for authentication mechanisms. Is this option so out of place?

**Comment by martinpitt** [comment]
Yes, just preventing empty passwords in the UI is a really bad security architecture. It's the equivalence of a "don't step on the grass" sign, instead of building a proper wall around your vault. It even hides the problem, instead of making it  apparent so that the account can be fixed properly.

Note that you can disable password authentication in cockpit.conf as well if you want to:

```
[Basic]
action = none
```
For that you need to use another mechanism, like ssh or kerberos or certificates.

**Comment by martinpitt** [comment]
In other words, the proper fix is to remove "nullok" from the common PAM config. That's not part of /etc/pam.d/cockpit though, that just includes the common PAM stack. Is there a PAM module that says "reject auth if user has an empty password"? If so, that's something which could in principle be put into cockpit.conf, but I'm still not entirely convinced that this is a good idea.

**Comment by cinderblock** [comment]
I don't think your "don't step on the grass" analogy is quite accurate.

I think it's more like a security guard that is told to not let anyone in without a badge; even if the guard knows the person coming in has a badge but just isn't wearing it right now. Maybe this is because it's a checkpoint inside a secured area (private LAN) so you might not expect to need your badge... but intruders *could* get in... so better to be safe than sorry.

When I was younger, and glanced over man pages too quickly, I thought `passwd -d $USER` removed the password, making it so that no password could be used to log in. When I realized I was typing in the wrong password and still getting in... that was quite the wakeup call. So, while I can understand why you say it hides the problem, I contest that the problem makes itself "apparent".

Sidebar: I was wondering if it was possible to authenticate to Cockpit with SSH keys over http[s]... Sounds like it might be. Time to go read up 😀

Removing `nullok` from common PAM config does seem like a pretty good way to lock this down in a more complete secure way.
