### ISSUE TITLE
Machines: Inconsistent enforcement of memory limits

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#13072]
Our selenium-machines-basic.py (MachinesBasicTestSuite.testCreateVMWithISO) test often [fails on Edge](https://209.132.184.41:8493/logs/pull-13068-20191030-215656-a20d3bdd-cockpit-project-cockpit--fedora-30-selenium-edge/log.html#36) due to something which is a real bug:

![screenshot](https://209.132.184.41:8493/logs/pull-13068-20191030-215656-a20d3bdd-cockpit-project-cockpit--fedora-30-selenium-edge/screenshot-testCreateVMWithISO-835825.png)

The test sets "Memory: 128 MiB", but creating the VM fails with "The selected OS has minimum requirement of 1024 MiB" and "up to 851 MiB available on the host".

If the intention is that the creation always fails if "configured mem" < "minimum mem", then this failure is legit -- but then it should also fail on firefox and chrome, and it should always fail as these two values are fixed in the test.

Since it's a flake, and only seems to happen with Edge, my gut feeling is that it's comparing recommended against available. This is wrong though -- it should enforce available > configured (and not allow creation otherwise), and strictly or mildly (warning?) enforce configured ≥ recommended.

**Comment by yunmingyang** [comment]
Hi, @martinpitt , I think this issue is because of a situation which is 'Operating System' can not get correct input from the case.In this case, actually, I input 'CirrOS' and two keys that are ARROW_DOWN and ENTER, but only 'ARROW_DOWN' and 'ENTER' is inputted, 'CirrOS' is dropped, so you can see 'Fedora Silverblue 29' in [this picture](https://209.132.184.41:8493/logs/pull-13068-20191030-215656-a20d3bdd-cockpit-project-cockpit--fedora-30-selenium-edge/screenshot-testCreateVMWithISO-835825.png).It is only happening in edge and there is no such issue on Firefox/Chrome.I used to try to resolve this issue in my last PR, and the issue disappear on my laptop after adding some resources for the machines and using another way to input. I think it is not the issue about the cockpit-machines and selenium case.So maybe we can just skip this case in edge test, and I will run it manually.

**Comment by martinpitt** [comment]
We have not seen this in a while, closing.
