### ISSUE TITLE
selenium-machines-storage-pool.py: Fix actual/expected number  of storage pools

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#13073]
This test has a common [flake on Edge](https://209.132.184.41:8493/logs/pull-13068-20191030-152323-a20d3bdd-cockpit-project-cockpit--fedora-30-selenium-edge/log.html#53) (maybe also on Firefox/Chrome, I didn't check that) where it would fail with
```
Traceback (most recent call last):
  File "/tmp/avocado_tests/selenium-machines-storage-pool.py", line 29, in testCheckStoragePool
    self.click(self.wait_text('Storage Pools', cond=clickable))
[...]
testlib_avocado.exceptions.SeleniumElementFailure: Unable to locate name: //*[contains(text(), "Storage") and contains(text(), "Pools")]
```

The [screenshot](https://209.132.184.41:8493/logs/pull-13068-20191030-152323-a20d3bdd-cockpit-project-cockpit--fedora-30-selenium-edge/screenshot-testCheckStoragePool-339946.png)  shows that cockpit displays "1 Storage Pool", but the test expects "Pools".

 Looking at just the test, it seems to be written rather dynamically:
```
        cmd_active = int(self.machine.execute('virsh pool-list | awk \'NR>=3{if($0!="")print}\' | wc -l')) + int(
            self.machine.execute('sudo virsh pool-list | awk \'NR>=3{if($0!="")print}\' | wc -l'))
        self.wait_css('#card-pf-storage-pools > div > p > span:nth-child(1)', cond=text_in, text_=str(cmd_active))
```

This doesn't always happen, though -- e. g. in [this run](https://209.132.184.41:8493/logs/pull-13068-20191030-215656-a20d3bdd-cockpit-project-cockpit--fedora-30-selenium-edge/log.html) the test succeeded. The final screenshot shows "3 pools".

*if* having one storage pool is an expected case, then waiting for "Storage Pool" instead of "Pools" would be correct. However, this seems fine on Firefox/Chrome, and I can't imagine that the number of pools differs between the browser tests? It seems to me that the intention of the test is to have > 1 pool, and sometimes they fail to get created.

FTR, I'm happy to walk you through how to interactively debug this. Ironically, this is quite easy with Edge (much easier than with firefox/chrome)

**Comment by martinpitt** [comment]
This affects all storage pool tests, not just testCheckStoragePool: https://209.132.184.41:8493/logs/pull-13068-20191031-072525-81bea96f-cockpit-project-cockpit--fedora-30-selenium-edge/log.html

**Comment by yunmingyang** [comment]
Hi @martinpitt ,these failed cases are because the locator use text which is 'Storage Pools' to locate the 'Storage Pool' button to click when switching storage pool pages. I think I can change the other locator to resolve this issue in next PR.


And for the code:
```
cmd_active = int(self.machine.execute('virsh pool-list | awk \'NR>=3{if($0!="")print}\' | wc -l')) + int(
self.machine.execute('sudo virsh pool-list | awk \'NR>=3{if($0!="")print}\' | wc -l'))
self.wait_css('#card-pf-storage-pools > div > p > span:nth-child(1)', cond=text_in, text_=str(cmd_active))
```
The wait_css here is because sometime the number of active storage pool will be less than the actual number in a short time when open page, so I use a wait_css here to make sure the process that page gets the information from back-end has finished.Then I can do some calculation.


For the intention of the case:
The case is going to get the number of storage pools from the page and command lines, then compare them, make sure they are the same. So the intention of the case is comparison, whatever the number of storage pool is.The error is raising when clicking the 'Storage Pool' button, so the comparison should be passed.


For the different number of storage pools in results of two test run:
I think maybe I can get more information from other test-run after this case fixed, then compare the results of firefox, chrome and edge to make sure why this issue appear.
