### ISSUE TITLE
storage: No longer read and write on drives

### ISSUE THREAD

**Issue by theycallme-west** [cockpit-project/cockpit#13114]
Hi. 
I couldn't find any issue mentioning this. I am using cockpit on Debian 10. 
I recently upgraded cockpit from 188 to 202 from buster-backports and to my surprise, I can no longer see read and writes to the individual disks. 
In 188 it looks like this:
![2019-11-08-09:48:39_229x346_selection](https://user-images.githubusercontent.com/42537058/68463308-a50b4b80-020e-11ea-9d43-7efaa4abb8bc.png)

On 202 there are no R: or W: at all. Is this an intended regression or a bug? I am using LVM cache, so I find it useful to see that data is going to the fast SSD before it gets written to HDD or if there is some issues with the cache. For the time being I have rolled back to 188.

On a side note; have the interface changed in newer build. When I upgraded, the sidebar changed to white and the text and elements are noticeably bigger. It is not really an "issue", but I would like to know if this is an upstream change or if Debian did something. The front page of cockpit-project.org still features the "old" interface with the gray sidebar and that is much more to my liking.
I am a bit disappointed that cockpit on Debian is very limited compared to Fedora/RHEL. It would have been nice to have things like NFS and FreeIPA applications that for some reason is not packaged for Debian.

**Comment by marusak** [comment]
> I can no longer see read and writes to the individual disks.

Indeed, this was dropped in https://github.com/cockpit-project/cockpit/commit/fa951998d4474f0adc692c352d873be8f061dcab#diff-95c26d6dda7f6f7c43952cb935d49d4b . @mvollmer was the one who did this change and I also think it is correct change since all I remember was just bunch of some semi-random numbers jumping around. Your usecase makes sense, I just wonder if it justifies to show it there.

> When I upgraded, the sidebar changed to white and the text and elements are noticeably bigger.

We did some redesign - since we want to adopt Patterfly v4 (we were at Patterfly v3). You can read about on our blog: https://cockpit-project.org/blog/cockpit-198.html

> The front page of cockpit-project.org still features the "old" interface with the gray sidebar and that is much more to my liking.

Well, you may want to update to 205, since we now have black sidebar :) https://cockpit-project.org/blog/cockpit-205.html .And yes, we should update those images. There is issue for it https://github.com/cockpit-project/cockpit-project.github.io/issues/255

**Comment by marusak** [comment]
@theycallme-west how strongly you feel about showing IO on drives?
@mvollmer you think it would be justifiable or not worth it?

**Comment by theycallme-west** [comment]
I feel pretty strongly about showing IO on drives for the above mentioned reasons. Of course I could use another tool for that, but it would nice to have everything in cockpit.

**Comment by mvollmer** [comment]
> I feel pretty strongly about showing IO on drives for the above mentioned reasons. Of course I could use another tool for that, but it would nice to have everything in cockpit.

We still have the graphs at the top.  If you hover over them, you can see which drive is responsible for which traffic. I would agree that this is significantly more awkward than just looking at numbers in the drives panel.

Would it work for you to have the I/O on the details page for a drive?

We have removed the I/O traffic numbers in the Drives panel because they have a non-trivial cost of retrieving from the system, and they take space. But that of course assumes that they are not very useful, which seems to be a wrong assumption.

As to the cost: they were only expensive because I was too lazy to dig out the numbers that we already get for the graphs. So cost is not really an argument either.

(Whatever we do, we would continue to _not_ show the I/O stats when there are more than, say, 50 drives.)

**Comment by theycallme-west** [comment]
Having the I/O traffic numbers under details is an improvement at least, but it has the disadvantage of only showing for that particular drive, so it could be a lot of clicking back and forth to get a full overview of different drives.

**Comment by trgill** [comment]
Maybe have a switch to turn on/off performance monitoring on block devices?  I also think it is useful to have at a per device level - but some people might not want to constant polling I suspect.

FYI - the output of :

iostat -dx -o JSON /dev/sdXXX 

might be easy to parse. 

If you want to go big with IO statistics - you could look at dmstats.  I recently proposed a patch that would add JSON output:

https://www.mail-archive.com/linux-lvm@redhat.com/msg02031.html

If you think you'd use that - I'll ping the LVM folks about merging the patches.

**Comment by marusak** [comment]
This was idle for some time. It seems we won't put this back in any time soon.
If we would decide to do this, we need to have better design that would not pollute UI, would be easier to interpret (as bunch of jumping numbers) and it would need to be less resources hungry.
