### ISSUE TITLE
machines: The size of the storage volume should not exceed the size of the storage pool 

### ISSUE THREAD

**Issue by cxhlunar** [cockpit-project/cockpit#13120]
Cockpit version: cockpit-machines-205.1-1.fc30.noarch
OS: Fedora30
Page: Virtual Machines/Storage Pools
Browser: Google Chrome Version 74.0.3729.169 (Official Build) (64-bit)

The size of the storage volume should not exceed the size of the storage pool 

Steps to reproduce

1.Prepare a Dir storage pool
2. Click "Storage Pools", unfold the new created storage pool and enter the "Storage Volumes" tab, then click "Create Volume"  
3.Enter a size which exceed the size of the storage pool , click create

Actual Result:
The disk can be created successfully.
Expected Result:
The total size of all the disks should not exceed the size of the storage pool, there should be a error to avoid user arrange size exceed the total size, it's better to show the user the left size in the storage pool on "Create storage volume" dialog.
![screenshot-10 66 92 212_9090-2019 11 11-13_13_27](https://user-images.githubusercontent.com/12710195/68562530-12c0ad00-0485-11ea-8687-74988742f4fe.png)

**Comment by mvollmer** [comment]
> The total size of all the disks should not exceed the size of the storage pool, there should be a error to avoid user arrange size exceed the total size,

What's the point of thin provisioning if the size of the volumes can't exceed the pool size?  lvcreate allows this, and Cockpit should, too, in my opinion.

I have noticed that lvcreate started issuing a warning in this scenario, so maybe Cockpit should do the same?

Can you say more about why you expect Cockpit to prevent a volume size that exceeds the pool size? What goes wrong when people do that? Why does lvcreate issue that warning?

**Comment by mvollmer** [comment]
> What's the point of thin provisioning if the size of the volumes can't exceed the pool size?

Oh, sorry, this isn't about LVM2 at all.  @KKoukiou, your turn. :-)

**Comment by KKoukiou** [comment]
Hey @cxhlunar - thanks for reporting this.
You issue report is valid - we need to fix this. I suggest that we really ignore the allocation and look in the total capacity of volume inside a pool - since when creating volumes through Cockpit we never do thinly allocation.

**Comment by skobyda** [comment]
@cxhlunar 

> The total size of all the disks should not exceed the size of the storage pool

I agree with @mvollmer that with this we would basically disable the whole functionality of thin provisioning. It's perfectly fine that **combined capacity of all volumes** exceeds capacity of storage pool as long as they are actually not using it all (which is a point of thin provisioning).

But on the other hand if a **single volume has bigger capacity than the capacity of storage pool**, then something is fishy. I heard there might be use cases for that (e.g. user wants to test filesystem on a disk of several terabytes, but they do not have as much storage physically available, so they create a volume. Or some similar use case), but these are niche use chases.
So we could show warning in a sense of "Capacity of this volume would exceed capacity of it's storage pool", or something like that, but we should not disable the creation of such volume nevertheless.

**Comment by KKoukiou** [comment]
> @cxhlunar
> 
> > The total size of all the disks should not exceed the size of the storage pool
> 
> I agree with @mvollmer that with this we would basically disable the whole functionality of thin provisioning.
In cockpit though we never create thin provisioned volumes :) See the code of https://github.com/cockpit-project/cockpit/blob/master/pkg/machines/xmlCreator.js#L129
So it's same to assume that if a user creates a volume through cockpit all the requested capacity will be directly allocated and it shouldn't be allowed to exceed the total pool size.

> It's perfectly fine that **combined capacity of all volumes** exceeds capacity of storage pool as long as they are actually not using it all (which is a point of thin provisioning).

That's true - but we can finely check the total allocated storage space (see volume allocation vs capacity xml elements) and not the total capacity. And this should never exceed the total pool capacity.
> 
> But on the other hand if a **SINGLE VOLUME has bigger capacity than the capacity of storage pool**, then something is fishy.
This is fine as long as the allocation value respects the limits. The pool capacity can be extended in the future - same for the volume capacity.

> I heard there might be use cases for that (e.g. user wants to test filesystem on a disk of several terabytes, but they do not have as much storage physically available, so they create a volume. Or some similar use case), but these are niche use chases.
> So we could show warning in a sense of "Capacity of this volume would exceed capacity of it's storage pool", or something like that, but I think we should not disable the creation of such volume nevertheless.

I would really show an error when requested capacity > pool capacity now since we don't do thin allocation when creating volumes from cockpit UI.

**Comment by skobyda** [comment]
> I would really show an error when requested capacity > pool capacity now since we don't do thin allocation when creating volumes from cockpit UI.

I believe we do thin provisioning. Apart from few storage types (like LVM), thin provisioning is the default option unless we specifically pass --prealloc option, which we don't.

**Comment by KKoukiou** [comment]
> > I would really show an error when requested capacity > pool capacity now since we don't do thin allocation when creating volumes from cockpit UI.
> 
> I believe we do thin provisioning. Apart from few storage types (like LVM), thin provisioning is the default option unless we specifically pass --prealloc option, which we don't.

When we create the volumes in 'Create Storage Volume' dialog, we do that by using the VolumDefineXML API, and we pass the XML, which is not including the allocation element. And when that is missing the volume is fully allocated at the creation, https://libvirt.org/formatstorage.html#StorageVol
So the dialog for which this issue is reported for is always creating non-thinly allocated volumes.
Of course when we create new VMs, virt-install does other stuff (but this issue refers to the dialog that we expicitely create volumes)

**Comment by skobyda** [comment]
Oh I see.
Officialy we do not support thin provisioning. But thanks to buggy nature of fully allocating volumes (e.g. https://bugzilla.redhat.com/show_bug.cgi?id=1759454), most of the time volume won't be fully allocated anyway. That's after you create a new volume thru cockpit UI and look into it's XML, in many it's not fully allocated anyway. So in the end user will practically use thin provisioning thru cockpit thanks to these bugs. Jeez what a mess.
In https://bugzilla.redhat.com/show_bug.cgi?id=1759454 they suggest to use defautly thin-provisioning, maybe we should also follow that?

But anyway, I do not understand what would limiting capacity fix. Allocation of volume can exceed it's capacity. And it's the allocation value which can lead to user problems. Capacity on the other hand is quite meaningless value actually. And limiting allocation to pool allocation is quite impossible, because that's a dynamic value, which fluctuates during runtime. It can very easily shrink or grow, making the previous limitation out-dated in matter of moment, no?
