### ISSUE TITLE
machines: VM Graphics Console (VNC) always disconnected

### ISSUE THREAD

**Issue by Panakotta00** [cockpit-project/cockpit#13158]
Cockpit version: 188
OS: Debian 10 (buster)
Page: Virtual Machine

When I try to open the "Graphics Console (VNC)" cockpit just tells me "Disconnected".

I can directly connect with a VNC Client to the provided "Manual Connection" data of the "Graphics Console in Desktop Viewer" Console Type.

I tried it with Debian Buster, Windows Server 2016 and Windows Server 2019 but I get the same result.

I tried it from a remote point (no direct access to the host and port, just to the cockpit root which is a different server) and from the LAN (again, website by root but I have direct access to host and port)

Steps to reproduce

1. Create a new VM in cockpit
2. Run it
3. Go to the "Consoles" section
4. Select "Graphics Console (VNC)" as Console Type

**Comment by KKoukiou** [comment]
@Panakotta00 please paste any errors you see in the browser console.

**Comment by BennyE** [comment]
Hi @Panakotta00 and cockpit-project team,

I just encountered a similar, if not the same, issue on my Debian Buster server. A good friend of mine recently introduced me to "cockpit" and I installed the package(s) available in Debian Buster. The version currently available from those packages is 188, as shown below. 

![version](https://user-images.githubusercontent.com/5174414/70372370-389f6d00-18de-11ea-850c-e46223d6a1fe.png) 

If the following looks familiar to you, you might have the same issue I had
![connecting](https://user-images.githubusercontent.com/5174414/70372306-9ed7c000-18dd-11ea-9efa-03f8aae457c6.png)

In my case, the issue was related to the "passwd" set in the vnc configuration that you can open / edit via "virsh" (I put an alias like this for "virsh -c qemu:///system", assuming your user is part of libvirt group)

![config-vnc](https://user-images.githubusercontent.com/5174414/70372643-f9731b00-18e1-11ea-95c4-11baead14fe4.png)

If you remove that passwd='' save the configuration and **shutdown & start** (**_NOT_** reboot/reset) your VM, it started to work just fine for me.

![working](https://user-images.githubusercontent.com/5174414/70372664-5a9aee80-18e2-11ea-9160-5974bf9d9c33.png)

While you're on it, you may want to change your configuration to a more secure one that will just automatically make things work in cockpit:

![good-config](https://user-images.githubusercontent.com/5174414/70372676-87e79c80-18e2-11ea-8fb5-d190ebb4fd55.png)

Again as text, so that you don't have to type things out ...
You may want to remove "keymap='de'" in your case, depending on your keymap needs.
```
    <graphics type='vnc' port='-1' autoport='yes' listen='127.0.0.1' keymap='de'>
      <listen type='address' address='127.0.0.1'/>
    </graphics>
```
I hope this write-up helps others that encounter the same issue.

Have a good weekend! :)

Thanks,
Regards,
Benny

**Comment by Panakotta00** [comment]
So I tried now your solution. And it still doesn't work.

When I try to connect the JS console returns:
```
machines.js:59 Failed when connecting: Connection closed (code: 1001, reason: not-found)
_fail @ machines.js:59
(anonymous) @ machines.js:59
(anonymous) @ machines.js:59
machines.js:59 Connection lost:  CustomEvent {isTrusted: false, detail: {…}, type: "disconnect", target: null, currentTarget: null, …}
```

And my screen simply shows:
![image](https://user-images.githubusercontent.com/16022267/70376517-f8ee7a80-1909-11ea-93f5-d08a3901a381.png)

**Comment by Panakotta00** [comment]
I also should have told you that I run cockpit behind an apache2 proxy...

sry for that

**Comment by BennyE** [comment]
In my setup I'm not running through Apache (Reverse Proxy), but my friend has such a setup. He told me that the following might help you, as you need to handle the websockets.

You'll need to add this to your apache site, that handles the cockpit-project in your case:
(this should give you also some additional insight for your personal research on this topic)
```
    ProxyPass           /               http://127.0.0.1:9090/
    ProxyPassReverse    /               http://127.0.0.1:9090/

# allow for upgrading to websockets
    RewriteEngine On
    RewriteCond %{HTTP:Upgrade} =websocket [NC]
    RewriteRule /(.*)           ws://127.0.0.1:9090/$1 [P,L]
    RewriteCond %{HTTP:Upgrade} !=websocket [NC]
    RewriteRule /(.*)           http://127.0.0.1:9090/$1 [P,L]
    ProxyRequests Off
```

**Comment by Panakotta00** [comment]
Yeah... I did that already cuz without it, nothing would work ^^

**Comment by KKoukiou** [comment]
@Panakotta00 and is it cockpit only issue or you have the same behavior with vnc viewer?
In other words can you get access to VNC console with `vncviewer $(virsh vncdisplay YOURVM)` ?

**Comment by Panakotta00** [comment]
@KKoukiou Ok so... I need to run that virsh command as sudo to get the port number.
But when I do that the vncviewer command exits with:
`CConn: unable connect to socket: Connection refused (111)`
🤔

**Comment by Panakotta00** [comment]
OK update I got that command to work...
fix was to remove some stuff from my first attempts to fix it (force a specific port)
I set the listen argument in the qemu VM settings to localhost.
Now I can connect with that command but still not from cockpit.
Three questions, does the frontend user need to have direct access to the given port?
Or does the cockpit master need it? (cause the VM and cockpit vm module are on a slave)
Does it matter that the frontend only has access to the cockpit masters http port through the proxy.

**Comment by Az3RuS** [comment]
I have the same problem, I use a VM where cockpit-dashboard is installed in order to centralize the access to my KVMs where cockpit, cockpit-machines, cockpit-storaged... are installed.

192.168.105.150:9090 => KVM 1
192.168.105.152:9090 => KVM 2
192.168.105.160:9090 => Dashboard

From the local cockpit management page no problem to access the VNC of my VMs. But from my VM cockpit-dashboard VNC remains disconnected (I have access to the cockpit management of my KVMs from this machine though).

My VNC conf for Dashboard VM

```
    <graphics type='vnc' port='-1' autoport='yes' listen='127.0.0.1' keymap='fr'>
      <listen type='address' address='127.0.0.1'/>
    </graphics>
```

Is there a solution to this problem?

**Comment by KKoukiou** [comment]
> I have the same problem, I use a VM where cockpit-dashboard is installed in order to centralize the access to my KVMs where cockpit, cockpit-machines, cockpit-storaged... are installed.
> 
> 192.168.105.150:9090 => KVM 1
> 192.168.105.152:9090 => KVM 2
> 192.168.105.160:9090 => Dashboard
> 
> From the local cockpit management page no problem to access the VNC of my VMs. But from my VM cockpit-dashboard VNC remains disconnected (I have access to the cockpit management of my KVMs from this machine though).
> 
> My VNC conf for Dashboard VM
> 
> ```
>     <graphics type='vnc' port='-1' autoport='yes' listen='127.0.0.1' keymap='fr'>
>       <listen type='address' address='127.0.0.1'/>
>     </graphics>
> ```
> 
> Is there a solution to this problem?

Not yet, this is a bug that has being torturing us quite long time. There is an open issue about that, https://github.com/cockpit-project/cockpit/issues/11227, it's referring to the spice console, but conceptually it's the same.

**Comment by Az3RuS** [comment]
Okay thanks, so the case is open, no worries. I'll keep an eye on the patchnotes. Will a version higher than 195 ever be available on CentOS7 or higher than 196 on CentOS8?

**Comment by Az3RuS** [comment]
Here are the errors my browser is displaying.

```
Failed when connecting: Connection closed (code: 1001, reason: not-found) machines.js:59:585056
    _fail https://192.168.105.160:9090/cockpit/$c60c64f52929ed06e582cdfc48d11ade97a94201f21f6a8fe735ab234f3dfb69/machines/machines.js:59
    vd https://192.168.105.160:9090/cockpit/$c60c64f52929ed06e582cdfc48d11ade97a94201f21f6a8fe735ab234f3dfb69/machines/machines.js:59
    onclose https://192.168.105.160:9090/cockpit/$c60c64f52929ed06e582cdfc48d11ade97a94201f21f6a8fe735ab234f3dfb69/machines/machines.js:59

```
```
Connection lost:  
disconnect
​
bubbles: false
​
cancelBubble: false
​
cancelable: false
​
composed: false
​
currentTarget: null
​
defaultPrevented: false
​
detail: Object { clean: false }
​
eventPhase: 0
​
explicitOriginalTarget: null
​
isTrusted: false
​
originalTarget: null
​
returnValue: true
​
srcElement: null
​
target: null
​
timeStamp: 14631
​
type: "disconnect"
​
<get isTrusted()>: function isTrusted()
​
<prototype>: CustomEventPrototype { initCustomEvent: initCustomEvent(), detail: Getter, … }
machines.js:59:611346
```
Via my Windows VNC client it works fine, the problem occurs when I connect via another machine hosting the dashboard.

**Comment by Panakotta00** [comment]
Okay.
Yes, I have it similar.
I have now installed the dashboard on the target directly and as it turns out, there VNC works.

**Comment by Az3RuS** [comment]
Hello, you just installed the cockpit-dashboard on your KVMs and on the VM acting as a Dashboard and this time it can correctly display the consoles?

I've installed cockpit-dashboard on all my KVMs, but the problem is that the VM acting as Dashboard can't display the consoles. On the other hand the console works very well when I open it from the KVM hosting them. (Directly from the IP of the KVM port 9090)

**Comment by Panakotta00** [comment]
Well... I mean... I have Server A (Dashboard i normally use) wich is bridged to Server B (normally no dashboard). Server B hosts the VM. When i now go onto the dashboard of Server A select Server B and show the VNC console, it tells me "disconnected". But now i have installed the dashboard directly onto Server B and opened the console page there. There the console works.

**Comment by Az3RuS** [comment]
Indeed we are in the same scenario! The dashboard only allows you to use VNC "locally" on the VMs it hosts. If possible, I'd like to have a dedicated VM centralizing all my other KVMs; in order to centralize and facilitate administration. But from what I've seen it's not possible... something is blocking ! If you try to add your KVM B to the dashboard of your machine A; you will then be able to access the cockpit of B but the VNC in "Virtual machines" will not work normally.

**Comment by tjjh89017** [comment]
Maybe this PR will help.
It will disable exclusive access, and let other could access the VNC.
https://github.com/cockpit-project/cockpit/pull/14182

**Comment by tjjh89017** [comment]
> > I have the same problem, I use a VM where cockpit-dashboard is installed in order to centralize the access to my KVMs where cockpit, cockpit-machines, cockpit-storaged... are installed.
> > 192.168.105.150:9090 => KVM 1
> > 192.168.105.152:9090 => KVM 2
> > 192.168.105.160:9090 => Dashboard
> > From the local cockpit management page no problem to access the VNC of my VMs. But from my VM cockpit-dashboard VNC remains disconnected (I have access to the cockpit management of my KVMs from this machine though).
> > My VNC conf for Dashboard VM
> > ```
> >     <graphics type='vnc' port='-1' autoport='yes' listen='127.0.0.1' keymap='fr'>
> >       <listen type='address' address='127.0.0.1'/>
> >     </graphics>
> > ```
> > 
> > 
> > Is there a solution to this problem?
> 
> Not yet, this is a bug that has being torturing us quite long time. There is an open issue about that, #11227, it's referring to the spice console, but conceptually it's the same.

@KKoukiou I think it is different between #11227 and @Az3RuS 's problem.

It should not use 127.0.0.1 for VNC on the KVM node. It should be KVM IP on KVM server (e.g. 192.168.105.150 for KVM1)
```
<graphics type='vnc' port='-1' autoport='yes' listen='192.168.105.150' keymap='fr'>
    <listen type='address' address='192.168.105.150'/>
</graphics>
```
Because `vnc.jsx` will always connect to dashboard IP and port, and using cockpit-channel as proxy to access VNC port. (`window.location.hostname` is always dashboard's IP, `window.location.port` is always dashboard's web port, `path` will contain info to setup proxy arguements)
https://github.com/cockpit-project/cockpit/blob/6e052b7a6e7aeb381785031f2b55280c12925b6a/pkg/machines/components/vnc.jsx#L158-L169

And address and port in cockpit-channel path will always get from Libvirt config.
If we setup VM's VNC address on 127.0.0.1,  `consoleDetail.address` will 127.0.0.1.
That also means cockpit-channel will setup a proxy path to connect 127.0.0.1:<vnc_port>
That is the reason that dashboard will only work "locally".
https://github.com/cockpit-project/cockpit/blob/6e052b7a6e7aeb381785031f2b55280c12925b6a/pkg/machines/components/vnc.jsx#L74-L86

When I used `virsh edit` or patched `machine.min.js.gz` with KVM's IP, I can connect VNC from dashboard to other KVM node.

--- 

Another solution will be:
When setting the `VncConsole`, use KVM's IP and port to be the `host` and `port`.
Let KVM node be proxy for `127.0.0.1`.
It will be correct way to connect 127.0.0.1 (actually connect to KVM's IP and VNC port)
But I cannot find any way to figure out the non-local host's info to setup `VncConsole` parameter

---

Because of `cockpit-channel` and default config of `VncConsoles`, it will hold the connection to the VNC port and request exclusive access.
Hence, when you used KVM's VNC page to access graphic, you will not be able to use dashboard to access VNC because cockpit-channel didn't release the exclusive connection. (vice versa, connect from dashboard first, and use KVM's VNC later﻿)

I will suggest to patch this to let react-console setup `shared` VNC connection.
https://github.com/cockpit-project/cockpit/pull/14182

Thanks

**Comment by luhuaei** [comment]
try to `protocols`  instead of `protocol`

```
const query = JSON.stringify({ 
         payload: "stream", 
         protocols: ["binary"], 
         binary: "raw", 
         address: consoleDetail.address, 
         port: parseInt(consoleDetail.tlsPort || consoleDetail.port, 10), 
     }); 
```
