### ISSUE TITLE
Memory (RAM) information

### ISSUE THREAD

**Issue by iFrozenPhoenix** [cockpit-project/cockpit#13182]
Currently the memory consumption is just showed as a chart.
It would be an advantage to also see the information as numbers.

OS: Ubuntu 18.04.3
Cockpit: 207

**Comment by KKoukiou** [comment]
This will be solved when https://github.com/cockpit-project/cockpit/issues/13121 will get solved.
Closing so that we don't track this in two places.
The new page will look like this https://github.com/cockpit-project/cockpit/issues/13121 and you can see there the memory consumption in the usage card.
