### ISSUE TITLE
Migrate to the new Fedora translation platform

### ISSUE THREAD

**Issue by Jibec** [cockpit-project/cockpit#13319]
Hello, the Fedora project migrates its translation platform to Weblate [1].

This tool directly interact with your git repository, and requires us to know:
* [mandatory] which branch is your development branch?
* [mandatory] have you merged latest translation from Zanata and locked the project?
* [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]
* [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)
* [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)
* [optional] do you need us to activate any specific checks? (this is a setting per component [3])
* [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

Please note:
* For github hosted projects, Weblate open pull request. For other project, you'll have to add a key to allow commits.
* In Weblate's vocable, one project is a group of component. Each component is a translation file. You can have many projects or many components or both.
* You can change your mind over time, just reach trans@lists.fedoraproject.org

[1] https://communityblog.fedoraproject.org/fedora-localization-platform-migrates-to-weblate/ 
[2] https://docs.weblate.org/en/latest/admin/continuous.html#avoiding-merge-conflicts
[3] https://docs.weblate.org/en/latest/user/checks.html#translation-checks

**Comment by marusak** [comment]
Hi,
Thanks for the issue. We have been waiting until we can replace zanata with something new and modern. I checked docs and looked around and founds some things, which could cause problems for us if we would just switched to weblate from zanata right now. I'll describe our workflow of pushing and pulling translations and then write down how I understood we should use weblate. Then compare those to see what is missing and how big deal it is. (note that we would first migrate cockpit-podman and then cockpit itself, but commenting here as here we have the most complex workflow)

Our workflow: (once a week our bots come around and do this)
1. Generate .pot file and push it into zanata. We do not keep .pot file in upstream.
2. Pull translations that have more than 50% of strings translated.
3. Check if there is some new language which was not 50% translated before but is now. If there is such language, create separate commit for it and edit `po/LINGUAS` and generate new record into `pkg/shell/manifest.json.in`. [Example](https://github.com/cockpit-project/cockpit/commit/96b294439d764b5cf2bca76ccddf9c5f9a0dac44#diff-f01df94a2cefcdbfba92071a55353be4)
4. Check if some language which had over 50% strings translated now dropped under this threshold. Then do opposite of previous item. [Example](https://github.com/cockpit-project/cockpit/pull/11582/commits/954dc41d8f6a169fbd0d0d1b8f7182d5d25678fa)
5. Check any other `.po` files that changed. If there is no real change (meaning translated string, There are always changes in comments describing occurrence of the given string) ignore it. Add files with real changes into another commit. [Example](https://github.com/cockpit-project/cockpit/pull/11582/commits/4198db0527d0dd627334fdfbc793e42888fc1531)
6. Create commit. It also adds `Closes #<PR number>` into commit message.

Weblate workflow: (to my understanding, please correct me if I am wrong)
1. Project has `.pot` file in upstream. Project updates this file regularly.
2. Weblate has hooks which notice that `.pot` file changed and upload it for translations.
3. When translator does some translations and hits `save` button (or whatever means `when translators are finished`) a new commit is generated with these changes and a new PR is opened. If there is still opened PR from previous changes, this new commit is pushed into the same PR.
4. Upstream merges this PR when they feel like doing so. Possible squashing not to have way too many commits.

What is difference and what is missing:
1. We need to keep `.pot` file in upstream. No problem with that. Our bots would only update this file once a week. Great, less work for our bots :) However, if there is pending PR, updating `.pot` file will cause conflicts with this PR. So we would need to run tests on the PR with .po files, squash it, land and then merge the PR with `.pot` file from our bots. (hoping that in that timeframe we won't get another PR). Also what happens if we close PR? Do we get all changes in another PR straight away?
2. Weblate does not support setting some threshold for how many strings needs to be translated. So we would have all languages' `.po` files in master and get updates on all of them. And that of course implies no `Add language` and `Drop language` as well. (With automatic generating of list of supported languages in their native form).

Conclusion:
It seems that the % thingy is missing feature on which we depend. That means both that we would have all `.po` files in master and get updates to all of them as well as that we won't know which files actually have this limit which we were required to introduce.
Also it seems it would require more manual work (ironically) from developers. Checking new/old languages and editing manifest if something changes (it is rare occasion, so I guess we could live with it) (and I think that they edit `po/LINGUAS` so easy to spot when it happens). Squashing and adding closes line is our workflow, so we need to live with that. A bit annoying is that github sends notification on every push into PR - which would mean we could get much more notifications just when someone will be doing some translations. Also we need to do a bit of "synchronization" work once a week, where when we get PR with updated `.pot` file from our bots, we firstly need to run tests on PR from weblate, then squash it with editing message (if language would be added or dropped we need to edit files and create commits manually) and only than land PR which updates `.pot` file.

Questions:
1. Would it be possible to have translations in weblate but not getting PR with updates? And we could use command line interface as before. It would solve all of our problems. Well except that it also does not support % thingy. (I am looking into `wlc` command and don't see it there)
2. We use branches in Zanata. We have master for every project and then some projects also have stable branches. Is this supported?
3. On an unrelated note, just curious - based on what languages were selected? For example Slovak is missing.

**Comment by martinpitt** [comment]
Thanks @marusak for the investigations! My take on this:

 * The main dealbreaker here is the push  vs. pull approach. From an upstream perspective, regularly pulling translations in batches that are aligned with releases, with the option of post-processing them  is *much* preferable to a constant waterhose of pull requests for each translation update. This would be so much human and machine effort, and cause so much noise and conflict to other PRs, that as with my team lead hat onI say outright "no" to that. Without a pull oriented workflow we won't switch to weblate, sorry.

 * Maintaining a .pot upstream is inconvenient and brittle, as with every PR that changes strings and lands, it becomes inconsistent. It has been best practice for literally decades to *not* store the .pot in git, and often not even in release tarballs, but build it on demand. But I could live with that, and we can force rebuilding the .pot on a release (i. e. when regenerating JS translations from the po files).

 * The % limitation seems like the smallest barrier. This can be achieved reasonably easily on the client side, and we can just change our build process to ignore existing .po files that are less than 50% translated. I. e. this is ok for me.

Thanks!

**Comment by martinpitt** [comment]
> Without a pull oriented workflow we won't switch to weblate, sorry.

To clarify: If these weblate PRs can be configured to happen, say, once a week, that'd be totally fine. But if they happen every day, or even for every change, that's just too much. https://docs.weblate.org/en/latest/admin/projects.html does not describe this -- how often do these happen?

**Comment by Jibec** [comment]
Weblate has an internal git repository. Each time a contributor translate, a new commit is created. Commits can be squashed by author (see docs for more options).

Every three days or when a translation reach 100%, weblate will open a pull request if none is opened. If one is open, commits will be added to the existing one.

Automation is possible at different level. You can disable automatic pushes and manually interact with weblate.

Please have a look at what libvirt did (you'll find the upstream ticket in fedora wiki). But I feel like either you have a git synchronization and merge, either you have to manually push/pull string without letting know weblate about your repository at all. What you want to prevent: conflict on translation files.

**Comment by marusak** [comment]
Thank you for the reply @Jibec 
We will go with manual push/pull. I'll follow up in cockpit-project/cokpit-podman so we can have project and try how it works.

**Comment by Jibec** [comment]
hi, when do we migrate this last repository?

**Comment by marusak** [comment]
> hi, when do we migrate this last repository?

Today I finally completely finished cockpit-podman and cockpit-composer (it is not yet merged, but I think it is done). It took us a bit longer since we had a hiccup with our bots not being able to push `.pot` file at first.
I plan to do cockpit tommorow. In the morning I'll lock Zanata, then prepare the new repository, sync all branches and then write here what components we need and which points to which branch...

**Comment by marusak** [comment]
We are ready :)
Can we please get `cockpit` project (it already exists but with wrong component) with **master** component, that points to master branch of https://github.com/cockpit-project/cockpit-weblate . For now we don't need any other components, but in about two weeks time we will create a new component.
And please also, can you set it up with ssh and not https git access? Thanks!

> [mandatory] which branch is your development branch?

master

> [mandatory] have you merged latest translation from Zanata and locked the project?

Yes.

>   [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)

LGPL-2.1-or-later

    [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)

No.

    [optional] do you need us to activate any specific checks? (this is a setting per component [3])

The usual set + javascript. Also we use $n where n is number as format string, not sure which rule would match this.

    [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

No.
