### ISSUE TITLE
How to completely remove cockpit - DNS issues

### ISSUE THREAD

**Issue by bonovski** [cockpit-project/cockpit#13383]
ubuntu 18.04.03 LTS server

I was foolish enough to install cockpit without backup and now my system can't resolve DNS.

How does one completely uninstall the network mess this does to the system?

**Comment by pitsi** [comment]
You can remove any package and its configurations with the --purge parameter of apt, e.g.
`sudo apt-get autoremove cockpit --purge`

However, I think that the issue you are facing is because of network manager that was probably brought in with cockpit-networkmanager package. Try removing and purging that one first.

**Comment by bonovski** [comment]
Yeah, the problem was with the netplan configuration, that got borked, as well as my docker network.
I managed to get it back working with symlinking the proper resolv.conf as decscribed here (installation on ubuntu): https://github.com/pi-hole/docker-pi-hole
