### ISSUE TITLE
Fedora CoreOS

### ISSUE THREAD

**Issue by keithy** [cockpit-project/cockpit#13414]
Fedora CoreOS is now stable (last minute tweaks not withstanding), opened to discuss issues/ideas arising as a result. 

* SSH Keys supplied by ignition are dropped in to ~/.ssh/authorized_keys.d/ignition (cockpit doesnt see them there)
* Zincati status report aka: https://github.com/coreos/zincati/blob/master/docs/usage/metrics.md
* coreos-installer list-stream
* Builds status page https://builds.coreos.fedoraproject.org/browser

p.s. Ignition snippets to run cockpit are available via https://github.com/keithy/ign-tool/wiki/plug:cockpit-overlay

**Comment by martinpitt** [comment]
Hello @keithy. We regularly build FCOS images and test them in CI. It has been an officially supported install platform for target for a while, see https://cockpit-project.org/running.html . Is there something particularly missing?

**Comment by keithy** [comment]
See above. FCOS has some particular features like update streams also there is no sign of links to documentation...(upcoming release?) Installation as chrooted systemd portable service.

**Comment by martinpitt** [comment]
@keithy: I'm afraid I don't understand -- "links to documentation" -- https://cockpit-project.org/running.html#coreos documents how to install Cockpit on FCOS.

Please file an issue against [cockpit-podman](https://github.com/cockpit-project/cockpit-podman/issues) for the "useful units" bits. "checking for package updates" got fixed in PR #13401, fix will be in 211. Usage graphs are issue #13380.

**Comment by keithy** [comment]
I thought this had been merged https://github.com/systemd/systemd/pull/10270

**Comment by marusak** [comment]
Closing as per Martin's last reply. If there are specific issues, please open the separately. Thanks
