### ISSUE TITLE
Standalone Backendless Interface for managing remote systems

### ISSUE THREAD

**Issue by cinderblock** [cockpit-project/cockpit#13440]
I was looking at the map of how cockpit works and wondering how much work it would be to make cockpit work without `cockpit-bridge` running locally.

[![Cockpit Map](https://user-images.githubusercontent.com/419955/73019550-a7764e00-3dd8-11ea-8bdc-3eca1d030d6c.png)](https://raw.githubusercontent.com/cockpit-project/cockpit/master/doc/cockpit-transport.png)

My particular interest is running `cockpit-ws` on my local machine and using my local credentials to connect to all the remote servers that I want.

I realize this is essentially possible right now, just log into cockpit with my user at http://localhost:9090, which then allows me to use my local stored credentials to monitor and control as many remote systems as I might like.

This however is sub par for a number of reasons:
1. I have zero interest in controlling my local system with cockpit-ws
2. Should not need authentication (already logged into my desktop environment)
3. Does not work on non-systemd systems

So, what would it take to allow cockpit-ws to run "standalone"?

Would it be possible to make this run on Windows and using my PuTTY keys to authenticate to remote servers?

Maybe the right solution would be something like an electron based wrapper for cockpit-ws.

Any thoughts?

PS, if I'm reading the map correctly, I only need to install `cockpit-bridge` on remote systems and can entirely skip `cockpit-ws`. Would be nice if this was more clear in the docs.

**Comment by aadrian** [comment]
Standalone Windows + Putty support would be very helpful (but also working over a bastion/jump server). It would bring many new users to the tool :)

**Comment by martinpitt** [comment]
@cinderblock : What you describe is what we call "bastion host". This would only have the web server (cockpit) and cockpit-ssh to control remote hosts, but never log into the local one. You can already do that with a standard installation and expand "Other options" on the login page to directly log into a remote host. You only need the cockpit-ws package for that (naturally), plus cockpit-bridge as that ships the "cockpit-ssh" command.

We also have an example of a [bastion host container](https://github.com/cockpit-project/cockpit/tree/master/containers/bastion). This has never been fully worked out unfortunately into a real product (mostly due to lack of time, as in general it's a very interesting way of using cockpit), but the container by and large works, and we test it in CI. You'd only need that container which bundle cockpit-ws and cockpit-ssh, and it's physically unable to directly log into its host due to the container isolation.

> Should not need authentication (already logged into my desktop environment)

That is a rather different scenario. See `man cockpit-desktop` for one solution that we support, and it might just be what you need, especially with the recently added "ssh host" feature.

**Comment by martinpitt** [comment]
> I only need to install cockpit-bridge on remote systems and can entirely skip cockpit-ws

You additionally need at least cockpit-system, plus any extra modules that you want to use on that remote server, e. g. cockpit-machines. But yes, you don't need cockpit-ws.

I [gave a talk about that](https://www.youtube.com/watch?v=m92Vl-FZdA8) if you don't mind a 20 min introduction about all this.

**Comment by martinpitt** [comment]
I'm closing this now. This isn't actionable, was more of a question, and I (hopefully) explained enough above. If there's still something missing, please follow up here. Thanks!
