### ISSUE TITLE
Option to add/remove CD-ROM device and load/eject ISO

### ISSUE THREAD

**Issue by Az3RuS** [cockpit-project/cockpit#13454]
Hello !

Have you thought about adding an option to add CD-ROM devices but also to eject and load ISOs into them?

Like qemu-guest-agent command :

Insert : `virsh change-media $VMName --path sda --source $ISO --insert --live`
```
<disk type='file' device='cdrom'>
      <driver name='qemu' type='raw'/>
      <source file='/datastore/ISOs/CentOS-7-x86_64-Minimal-1908.iso'/>
      <backingStore/>
      <target dev='sda' bus='sata'/>
      <readonly/>
      <alias name='sata0-0-0'/>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>
```
![image](https://user-images.githubusercontent.com/8822287/73226697-46040580-4171-11ea-98f4-588f0e2428d7.png)

Eject : `virsh change-media $VMName --path sda --eject --live`
```
    <disk type='file' device='cdrom'>
      <driver name='qemu' type='raw'/>
      <target dev='sda' bus='sata' tray='open'/>
      <readonly/>
      <alias name='sata0-0-0'/>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>
```
![image](https://user-images.githubusercontent.com/8822287/73226657-2cfb5480-4171-11ea-9824-7b3d8908cf9a.png)
_PS : When you use its controls you can already see on the cockpit the disc being added or ejected._

**Comment by KKoukiou** [comment]
@Az3RuS thanks for opening this feature request, it's definitely a valid feature, once I find some time I will implement it.

**Comment by deajan** [comment]
I'd totally love to see that feature too ;)

**Comment by LucienShui** [comment]
sorry for bothering, is there any implementation now?

**Comment by KKoukiou** [comment]
> sorry for bothering, is there any implementation now?

Not yet unfortunately.

**Comment by KKoukiou** [comment]
This feature will be part of 238 release.
![Screen Shot 2021-02-12 at 22 52 51](https://user-images.githubusercontent.com/14921356/107826375-15dfd280-6d85-11eb-9ec1-772f597746a3.png)

**Comment by lzap** [comment]
Just a small nitpick - when I was trying this feature on F33, both cache and bus was set to "default" but when I hit Add, it fails with error that "bus is undefined". Once I set ti to "sata" or "scsi" it works fine.

**Comment by shodanshok** [comment]
While attaching a cdrom drive is now possible, one can not eject/change the virtual cdrom. Please add this capability.

**Comment by garrett** [comment]
> While attaching a cdrom drive is now possible, one can not eject/change the virtual cdrom. Please add this capability.

You can actually remove a CD from a VM. It was implemented quite some time ago.

It's in the "Disks" section of an individual VM's details page. It looks like this:

![image](https://user-images.githubusercontent.com/10246/192237171-551bc517-3e33-4250-a56c-02ddbbdbb2ef.png)

Click on the "Remove" button that corresponds to the ISO.

I tried today and was successful when doing so. However, I did have to shut down the VM before removing the ISO. (I think you can also just make sure it's unmounted inside of the VM, but this was on a VM in the installation phase, so the ISO was actively in use.)

When the disk was in use, I did get this confusing error message, however:

![Screenshot 2022-09-26 at 10-57-14 Virtual machines - garrett@Bolt](https://user-images.githubusercontent.com/10246/192236175-5fa4fd42-0cac-4f94-8e06-0ab8c091cbaf.png)

I think this error message is directly from libvirt, which is why it's so strange. We should rephrase the error to make it more straightforward. It could say something like the disc cannot be ejected as it is in use.

**Comment by shodanshok** [comment]
@garrett removing the virtual drive is not the same thing as ejecting the virtual cdrom.

Removing the virtual drive means detaching the ide/sata virtual device, a thing `libvirt` will not accept when the domain is running (ie: it is the equivalent of `virsh detach-disk`)

Ejecting the virtual cdrom means removing (or changing) the virtual ISO "inserted" in the virtual drive, a thing which *can* be done on a running domain (the equivalent of `virsh change-media`)

`virt-manager` provides the capability to eject/change the virtual drive from the beginning. With Red Hat deprecating it, it become important to have it in `cockpit-machines`.
