### ISSUE TITLE
Storage page layout broken: overlapping table/card, bad layout of warnings

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#13485]
I was going through all our pages for a [react-core npm update](https://github.com/cockpit-project/cockpit/pull/13476), and noticed that the storage volume/block device detail page of our Storage page looks rather bad:

![storage](https://user-images.githubusercontent.com/200109/73737240-8a2f7100-4742-11ea-9fec-5c9f3f76ed5e.png)

When you expand a particular volume, the table grows wider and grows into the "Physical Volumes" card, and the file system warning is really badly laid out.

That warning can be reproduced with a block device that fstab assigns to one mount point, but it's mounted someplace else:
```
sudo modprobe scsi_debug
sudo mkfs.ext4 /dev/sdb
echo "/dev/sdb /mnt/blah ext4 defaults 0 0" | sudo tee -a /etc/fstab
mkdir /tmp/x
sudo mount /dev/sdb /tmp/x
```

**Comment by martinpitt** [comment]
Note that it works with very wide screens, but my laptop only has 1366 pixels.

**Comment by KKoukiou** [comment]
The problem here comes from the PF4 alert component.
There is a rule on pf-c-alert 
--pf-c-alert--grid-template-columns: max-content 1fr max-content;
So basically this gives the ability to the actions (3rd column in the grid) to take as much space as they need.
@garrett I guess we need a grid where the first column spans to all rows so something like grid-row: -1/1 and the for the rest of the two columns to take as much space as they need and expand to next row if needed. I am not sure how to write that though :(

**Comment by garrett** [comment]
So this: `1fr repeat(2, max-content)` ?

(Take up the largest size possible for the last two items, then use the remainder of the space for the first. Alternatively, use `auto` instead of `max-content`, but that means something slightly different. There's also `fit-content`, which is similar to `auto`, but with a clamp.)

Or do you mean something like 2 rows with the other being another?

### Meanwhile...

I just scrolled up and looked at the screenshot. This should actually probably be best as `flex` instead of `grid`, so it would auto-wrap based on content sizing. (This probably could be done with grid too, with an auto-fit and such, but then the content would probably all be the same widths, unless you then use `grid-template` based layout or whatnot. Either way, to do this with grid becomes more complex than just a `grid-template-columns`. So it would require overriding the with CSS _probably_.)

I can look more at this tomorrow, if you wish. :wink: (Remind me if I forget.)

**Comment by garrett** [comment]
BTW: If this is a PF4 notification, we might need to do an override and suggest an upstream fix.

**Comment by KKoukiou** [comment]
> BTW: If this is a PF4 notification, we might need to do an override and suggest an upstream fix.

it's PF4 Alert.

**Comment by garrett** [comment]
I've been playing around with this and added the following CSS:

```css
.pf-c-alert__action {
  padding-bottom: var(--pf-c-alert__action--PaddingTop);
}
.pf-c-alert {
  grid-template-areas: "icon title title" "icon content content" "icon action action";
}
```

to get this:

![Screenshot_2020-02-05 Storage - Rain](https://user-images.githubusercontent.com/10246/73845031-0e0c5a80-4822-11ea-8793-95ade87f7409.png)

But I don't think it's right. We'd have to have an arbitrary breakpoint. We can't change things like this; it would be fragile and isn't a generically fixable approach.

---

Stepping back, I think the UI is wrong. At a bare minimum, the alert is incorrect. The title should be simple, the actions should also be simplified. There should be alert body content too.

Right now, it's this:

> ### The filesystem is currently mounted on /tmp/x but will be mounted on /mnt/blah on the next boot.
>
> [Mount automatically on /tmp/x on boot] [Mount on /mnt/blah now]

Perhaps it should be something like:

> ### Inconsistent filesystem mount
> The filesystem currently at `/tmp/x` will be at `/mnt/blah` next boot.
>
> [Re-mount filesystem at /mnt/blah] [Change configuration to /tmp/x]

...and maybe we would have the buttons in the body text instead?
