### ISSUE TITLE
Ssh key for secondary server authentication unloads itsef

### ISSUE THREAD

**Issue by sprietNathanael** [cockpit-project/cockpit#13544]
Cockpit version: 212
OS: Ubuntu 19.01
Page: Authentication

I have 4 servers, each hosting Cockpit 212. I connect to my main server with login/password.
Then, I want to connect to the other three with a different login, and an ssh key.
I "load" (I tick the blue switch button next to the key)  the ssh key in Authentication page, and everything work fine.
But as soon as my user is disconnected from cockpit, the key is not loaded anymore and have to type its password to activate it again. Then I have to go to each hosts tab for them to reconnect.

I am new to cockpit, and maybe there something I missed during the configuration, or maybe it comes from my system ssh-agent configuration.

Do you have any idea on what is happening?

**Comment by SudonymTM** [comment]
I have the same Problem.
I want to keep them loaded, otherwise the Connection drops to the Servers and as @sprietNathanael said, even if you load the Key again manually you have to go trough each Server (click onto them) just so they get loaded again.

That's a bit frustrating doing so for like 50 Servers...

**Comment by mvollmer** [comment]
@sprietNathanael, @SudonymTM, is this a regression for you?  I.e., did Cockpit behave as you want in the past but now something has changed, and you have to explicitly load the key every time?

When logging in to the primary session, Cockpit just runs `ssh-add` and answers any prompt of that process with the login password.  Thus, it will only loads those private keys that either have no passphrase at all, or that have a passphrase that is identical to the login password of the primary session.

Does this match what you are seeing?  I.e., does you SSH key have a passphrase, and is that passphrase different from your login password?

If so, then everything works as expected.  If you want more convenience, you need to sacrifice a little security by changing the passphrase of the SSH key to match the login password of the primary session.


Newer versions of Cockpit should help you figure this out, actually.  When connecting to a secondary server with a SSH key that is protected by a passphrase, Cockpit offers to change that passphrase so that it matches the login password:

![image](https://user-images.githubusercontent.com/3228183/108040137-9c2a3c00-7045-11eb-9da8-44167e8695e5.png)

**Comment by marusak** [comment]
No reply and what Marius said makes sense. It seems Cockpit behaves as desired
