### ISSUE TITLE
Error 16 while removing NFS Share with the same path as an active one

### ISSUE THREAD

**Issue by leomoty** [cockpit-project/cockpit#13566]
Cockpit version: 212
OS: Fedora Server 31
Page: Storage

So I've had issue with one of my networked resources and I decided to mount another one using the same path `/mnt/data`.

![image](https://user-images.githubusercontent.com/1463740/74693163-48360e80-51c9-11ea-863c-b1467c04b964.png)

That works well, however now I am trying to remove the other entry and it greets me with:

![image](https://user-images.githubusercontent.com/1463740/74693196-6b60be00-51c9-11ea-9fed-54ba572bcc94.png)

Notice how that is the non-mounted mapping, I am not sure if this is cockpit specific or not.

**Comment by leomoty** [comment]
Renaming the mount path yields the same error, anyways:

![image](https://user-images.githubusercontent.com/1463740/74693442-a6172600-51ca-11ea-84c8-4ab63be9660e.png)

**Comment by mvollmer** [comment]
I can reproduce this, and it looks like a bug in Cockpit.

**Comment by mvollmer** [comment]
Removing the entry failed because removing the mount point directory failed with EBUSY.

Cockpit tries to clean up unused mount point directories, and it tolerates some errors, such as ENOTEMPTY and ENOTDIR.  If those happen, it will happily leave the mount point directory behind. In your case, we got EBUSY and this was not yet in the list of tolerated errors.

In fact, I can't really think of any OS error that we should not tolerate, so let's fix this by tolerating them all: #13569

**Comment by mvollmer** [comment]
A workaround is of course to temporarily unmount `/mnt/HD/HD_a2`, remove the entry for `192.168.2.20:/mnt/data` and then re-mount `/mnt/HD/HD_a2`.
