### ISSUE TITLE
is it possible to have restrict access for regular users?

### ISSUE THREAD

**Issue by alejojo** [cockpit-project/cockpit#13633]
Page: All

Ideally, I would like to setup the host and hand it over to my coworkers/devs. They should be able to:
- create vm
- use their vm
- destroy their own vm
- (share with other member their vm?)

but they should not have access to:
- destroy other member vms
- create/modify/destroy volumes
- create/modify/destroy network
- etc etc

is this possible?

I am thinking, perhaps is possible to only give access to login and https://host:9090/machines ?
thanks!

**Comment by KKoukiou** [comment]
@alejojo It's clear that you need the concept of 'owning' VMs. This can only be achieved by using the 'Session' Connection when the users create their VMs. 'System' connection VMs are shared between users and this we can't limit operations on them since any user with admin privileges or proper polkit configuration can manipulate them.

So - what you ask if possible - your users should use "Session" Connection when creating VMs.
