### ISSUE TITLE
Don't disable UI elements that can be used through specific polkit privileges

### ISSUE THREAD

**Issue by jeffoatess** [cockpit-project/cockpit#13655]
Cockpit version: 195.1
OS: Centos 7 Atomic Host
Page: users

I do not want my admin users to be able to change the root password, or really configure anything about the root account.  Is there a way to disable the ability to configure the root account?

I was hoping to take the approach of specifically allowing actions in policykit, but it seems like in order to do many things in cockpit (docker, system updates, create new accounts) you need to allow root escalation for the action id "org.cockpit-project.cockpit.root-bridge", which ultimately gives them the keys to the whole castle.  Am I misinterpreting that?

Any guidance would be much appreciated.

**Comment by martinpitt** [comment]
No, you are not misinterpreting this. Indeed almost all pages (except for Storage, Firewall, and Machines where the backends directly support PolicyKit) talk to backends which need actual root. So the only approach is to log in as a user who can't do sudo or generic pkexec, i. e. a user which is not in the wheel group, and then just use what remains working through polkit. However, our unfortunately our pages have too strict permission check in this case, and disable UI elements which you could actually do through specific polkit permissions.

So there is, and never will be, an "option to disable root account management" in cockpit, as that just uses the permissions that your user has. The issue is that cockpit disables UI elements that you could use through specific polkit privileges.

**Comment by martinpitt** [comment]
@mvollmer: FYI, as you are redesigning the permissions bits.

**Comment by jeffoatess** [comment]
So, is the idea to migrate more (eventually all) of the pages to support PolicyKit to allow specific permissions for each action in cockpit?  This would mitigate any need to have an "option to disable root account management".

Are there any other workarounds you can think of in the mean time for me to achieve my goal of maintaining most admin abilities in cockpit but not changing the root password?  

At this point I'm considering just giving them `sudo` for cockpit-bridge and then patching the users page locally so that it cannot configure the root user.

**Comment by mvollmer** [comment]
There is always the terminal in Cockpit, so trying to prevent from doing certain things by removing them from the UI just makes doing that certain thing more annoying, instead of making it impossible.

But that might actually be enough in your case, no?  There are a million things that people shouldn't be doing, and we can't catch them all with strict permissions. So we trust that people want to do the right thing and make it hard for them to do the wrong thing by accident.

How would you solve this problem for people that use the command line? Do you restrict what they can run via /etc/sudoers, for example? Or just tell them they shouldn't be changing the root password (or ~root/.ssh/, /etc/sudoers, etc) and having a backup ready?

I have to admit that while working on #13482 I have bigly misunderstood how Cockpit uses PolKit... and right now I am not sure what my plan is... :-) Your feedback here is certainly very timely.  Hmm.

**Comment by martinpitt** [comment]
This issue has just sat around for a year, and it's too big and underspecified to be actionable. If you see a particular page that talks to a D-Bus service which supports polkit (and thus  giving partial privileges to a user), but you can't control that service in Cockpit, please mention it in a more specific issue.

For what you describe about "most of cockpit", then allowing `sudo cockpit-bridge` indeed seems ok. (But of course that *is* "handing over the keys to the castle")
