### ISSUE TITLE
Join Domain does not map Domain Admins (or other group) to privileges on Cockpit server

### ISSUE THREAD

**Issue by mckenziec** [cockpit-project/cockpit#13688]
Cockpit version: 194
OS: Centos7 Atomic

When you login to Cockpit with a Domain Account you *can* select "login as privileged" but you're *not* privileged. You'll have the privileged label next to your username, but all privileged features will be locked because you *can't* sudo (you're not part of a group that can, and you're not a sudoer). As a local privileged user you can't select and add "System Administrator" to a Domain Account. e.g. Domain login accounts aren't visible from the Accounts page.

Is there not a way to configure a Centos server, or through Cockpit, to map or auto map a Domain Group to a privileged account?

I can successfully join multiple Cockpit servers to an Active Directory domain. I can also login into Cockpit and the command line (via su -) to the domain user (e.g. administrator@test.net). When I view the user's groups they are domain groups:
```
$ groups
domain users@test.net domain admins@test.net schema admins@test.net enterprise admins@test.net group policy creator owners@test.net denied rodc password replication group@test.net
```
Obviously this user account won't be able to sudo, so no hope of a privileged login into cockpit.

How can I auto map or add a general configuration that'll include joined domain users/groups to wheel or the sudoers?

I've dug into this a bit:
1) If I manually add the full domain group to a /etc/sudoers.d/domain file it works but messing around with group wildcards doesn't:
```
%domain\ admins ALL=(ALL) ALL <-- no luck
%domain\ admins@* ALL=(ALL) ALL <-- no luck
%domain\ admins@bert-qa.net ALL=(ALL) ALL <-- works but I have to drop into every single server and add this, and its domain specific.
```
2) I could try turning realmd automatic ID mapping off:
```
[domain.example.com]
automatic-id-mapping = no
# automatic-id-mapping = yes
```
This should result in the domain part of the AD user/group not being auto populated. Yes there would be the possibility of conflicts with the AD server, but really the server is meant to be primarily logged into by domain users.

Also I believe this setting is domain specific, so I'm again stuck editing domain specific settings on every server. No hope of a general setting, and it has to be done on the command line.

Any suggestions? The join domain feature is *very welcome* but it seems a bit incomplete without Domain Admins not being able to login as privileged.

Am I missing something? Thanks!

**Comment by martinpitt** [comment]
The general topic of handling privilege in cockpit is indeed a major gap, and @mvollmer is currenty working on fixing this for good. See e. g. PR #13482 or https://www.youtube.com/watch?v=alyerHAMaRM .

The user privilege mapping itself is a completely unrelated problem. In general, if a user is supposed to be a (local) admin, and they can run `sudo cockpit-bridge`, then they  can become admin in Cockpit as  well. I'm afraid I don't know much about AD, but with FreeIPA you can [tell the domain controller to turn IPA admins into local admins as well](https://cockpit-project.org/guide/latest/sso.html) (e. g. `ipa-advise enable-admins-sudo`), then PAM+sssd will work. FreeIPA can also export groups without a `@domain` suffix, so that they effortlessly work with sudo and other groups. We also cover this in our integration tests.

realmd can enable/disable fully qualified names in /etc/realmd.conf:
```
[bert-qa.net]
fully-qualified-names = no
```
(and in fact in recent versions this is finally the default). This works for FreeIPA, and in principle realmd  also supports AD. Again I don't know if that works, but it may be worth a shot.

**Comment by martinpitt** [comment]
The general privilege rework has landed some months ago, and is now in all major distros including CentOS 8. As for setting up AD to provide local sudo privileges, that's outside of Cockpit's domain, see the previous comment for some general directions.

**Comment by alok8bb** [comment]
```
[WebService]
AllowUnencrypted = true
Origins = https://admin.my.com 
ProtocolHeader = X-Forwarded-Proto
```
