### ISSUE TITLE
Deactivating a VPN results in a D-BUS error

### ISSUE THREAD

**Issue by PedroJG** [cockpit-project/cockpit#13776]
Cockpit version: 211
OS: Ubuntu 18.04
Page: Network

When a VPN connection is active in the system, deactivating it in any way results in D-Bus trying to access the previously existing object which no longer exists.

This is what it looks like in the browser:
![image](https://user-images.githubusercontent.com/50325076/77333789-3a256180-6d24-11ea-91aa-fb84d456c9cd.png)

Steps to reproduce

1. Have an active VPN connection in the system
2. Go to the "Network" page
3. Open console
4. Deactivate the connection. Be it with nmcli conn [vpn] down or via cockpit in the tun network interface.
5. You get a DBusError

**Comment by marusak** [comment]
Right, but this is handled error.
If it was unhandled the page would show Oops and then it might stop working. Here the page continues to work and that is because we catch this and then just log it into console. It just looks a bit bad, but it is the same as if we would print "Could not refresh device". Since console is for developers and hackers (normal user does not read console logs) I would say this is fine as it might help to resolve potential issues in the future.
