### ISSUE TITLE
cockpit using jquery . nead help

### ISSUE THREAD

**Issue by asklinux** [cockpit-project/cockpit#13868]
helo 

i have write code using jquery . but not working for run cockpit api this my example code

$(function() {

check_httpd();

});

function check_httpd() {

        var semak = cockpit.spawn("systemctl status httpd");
        semak.done(papar);

}
function papar(data){

        $("#display").text(data);

}

this code example for run systemctl command and get apache status . but no output  
thanks

**Comment by marusak** [comment]
From [documentation](https://cockpit-project.org/guide/latest/cockpit-spawn.html)

> The args should be an array starting with the executable and containing all the arguments to pass on the command line. If args is a string then it is interpreted as an executable name.

So your example:
```
cockpit.spawn("systemctl status httpd")
```
is actually trying to call executable `systemctl status httpd` and not executable `systemctl` with two arguments.

It is always a good practice to also attach `.catch()` callback to see if the command fails.

What you need is to create an array:
```
cockpit.spawn(['systemctl', 'status', 'httpd']);
```

Also just side note, but you can use `.then()` instead of `.done` as with standard promise.
