### ISSUE TITLE
VM:s not visible after v216

### ISSUE THREAD

**Issue by polhaghverdian** [cockpit-project/cockpit#13863]
Cockpit version: 216
OS: Ubuntu 18.04

I cannot see manually created VM:s in Cockpit after version 216. I use virt-install to create them, but are not visible after version 216 in tab "Virtual machine".  Is this maybe because drop of support for virsh? as stated in the release log of version 216 "_Machines: Drop virsh backend support_"

**Comment by KKoukiou** [comment]
@polhaghverdian since 216 we stopped building cockpit-machines for ubuntu-1804 backports for this exact reason. We rely now on libvirt-dbus package for communicating with libvirt so you need that to use newer versions of cockpit.

I guess you built the package by yourself to get 216?

FYI: In ubuntu-1910 the package libvirt-dbus is available so you will be able to use cockpit-machines and in fact with much more features than what you used to have with the virsh backend in ubuntu-1804.

**Comment by polhaghverdian** [comment]
@KKoukiou Thats right i built the package, so i just need to install libvirt-dbus, in order to get it to work with 18.04 right?

**Comment by KKoukiou** [comment]
@polhaghverdian exactly, but libvirt-dbus is not available in ubuntu-1804. You need to build that as well from sources.

**Comment by polhaghverdian** [comment]
@KKoukiou thanks you!
