### ISSUE TITLE
Don't show successful last login in alert but in system information

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#13882]
I don't think it should be a dismissable notification. You're not being notified of anything. It is a piece of static information about the state of the system (in this case, limited to a specific user).

Right now, as a notification, it competes with MOTD, which is also a dismissable notification:

![Screenshot_2020-04-09 Overview - Rain-2](https://user-images.githubusercontent.com/10246/78902573-41fe3900-7a7a-11ea-80ae-5d9023a282ff.png)

And, it's also quite weird paired with the sudo branch too:

![Screenshot_2020-04-08 Overview - localhost localdomain](https://user-images.githubusercontent.com/10246/78902706-6d812380-7a7a-11ea-80c5-9ca1f1e76a61.png)

(Although this has been changed in the sudo branch.)

It may make sense to move it to system information and show the session and session type as well.

Perhaps something like this:

**Previous log in**: garrett 19 Apr 12:34 PM on web console

- Drop year, if the same as current.
- Drop seconds.
- Use locale.
- Say "previous" instead of "last", as this isn't necessarily the last log in to the system, it's the previous time the same user was logged in... right?
- The previous log in can be linked with a popup or page that shows the last log in times (multiple), similar to running "last" (or a similar command) in a terminal.

**Comment by garrett** [comment]
This all said, if there were _failed_ logins, those should be shown with a notification. That's a possibly important thing to show as a notification, but not a normal login.

**Comment by KKoukiou** [comment]
@garrett @marusak so to understand this properly:

* we always show the last login in the system card
* we show when there are failed login attempts above in an alert card

Since these two information are quite connected, shouldn't we keep them together? I guess in the system card, but I feel we should not split them. Of course having a alert icon or something for failed login attemts is important. 

In matters of "Previous' vs "Last" wording, I think both are problematic, but previous is even more problematic.

Previous is contradictory with the fact that the user can be still logged in. In this case, of a currently connected user, the 'previous' is a misleading term.
We can use 'Latest' which is the term that lastlog is using as well, but that's the same as "Last" actually. So basically we are refering to the latest login for this specific user, not for the whole system. And for this reason 'Last" is not really wrong.

**Comment by marusak** [comment]
> Target here is:

Yes. The thinking is that last successful login is not really important enough to be in alert box. Therefore we can just drop it into system card. But failed attempts are something that you should be notified, thus it should be shown in alert box.

Whether just icon would do, I'll keep that for Garrett.

**Comment by garrett** [comment]
Another approach: We could also always have it in the system card and make it look like a warning on a failed attempt. Basically: use the color and icon.

If you wanted to use an inline alert, then it could be possible to drop the background, border, and padding, and it'd look like:

![Screenshot_2021-04-27 PatternFly 4 • Alert](https://user-images.githubusercontent.com/10246/116222514-f3880f00-a74e-11eb-9f57-e7636ad85d62.png)

```
.pf-c-alert.pf-m-inline {
    --pf-c-alert--BoxShadow: var(--pf-c-alert--m-inline--BoxShadow);
    --pf-c-alert--BackgroundColor: var(--pf-c-alert--m-inline--BackgroundColor);     padding: 0;
    background: transparent;
    border: none;
}
```

But I think we'd still want the last successful login? And a link to filter the logs with the login warnings/errors for more details, rather than just the last one? This is why I was thinking the login info should go in the card whereas the warnings should be alerts. (As they're different. Logging in successfully is metadata done by an authorized user whereas an unsuccessful login attempt could possibly be a higher-priority real issue done by someone else.)

**Comment by jelly** [comment]
The seconds in the last login time where already dropped in the conversion from moment to timeformat, the datetime should also be locale aware.
