### ISSUE TITLE
[RFE] Cluster several cockpit instances

### ISSUE THREAD

**Issue by verslyap** [cockpit-project/cockpit#13939]
Would it be difficult to sync the configuration between several cockpit instances across several hosts?  This could let the cockpit setup be highly available, and the different instances could even be placed on the same virtual ip in case one of them goes down.

**Comment by marusak** [comment]
What configuration you have in mind?

**Comment by verslyap** [comment]
Something like a cluster, where several instances could be combined to have some high availability features.  So if one node went down, an identically configured cockpit would still be reachable.  I know that can be done by adding machines to each node manually, but didn't know if there was a smoother process to do it at scale.

**Comment by martinpitt** [comment]
There is not much to sync, really. You may have a customized /etc/cockpit/cockpit.conf, which can be synchronized to multiple hosts via Ansible, puppet, chef, or similar standard config management tools. Beyond that, there is no cockpit specific configuration.

There is no particular support for load balancing, as that's not something that the web server itself can control - you need to set one up on top of whichever web service (cockpit or otherwise) you want to multiplex. But I'm afraid I don't have experience with load balancers, other than Kubernetes services.

**Comment by verslyap** [comment]
Can cockpit tell when a computer that's just been added is also running cockpit?

**Comment by martinpitt** [comment]
@verslyap : You mean added to the dashboard? It can heuristically detect that, but not reliably. Firewalls, reverse proxies, NAT etc. are all factors which get applied from outside and can't be detected from inside. But maybe I misunderstood your question.

**Comment by verslyap** [comment]
Sorry.  I'm probably not using the best terminology here.  I guess what I have in mind is something like:
1) the end users opens up cockpit on server1 and adds server2 to it
2) cockpit on server1 sees that cockpit is also running on server2
3) server1, somehow, adds itself to server2

Ansible for the machines.d folder probably works just as well.

**Comment by marusak** [comment]
That sounds super magic and unexpected - I add server to the dashboard and suddenly my localhost appears in config on some remote server.
I think this is not something Cockpit wants to support.
If you want to have this kind of sync between bunch of server I suggest creating and sharing `/etc/cockpit/machines.d/` in some fashion between these servers (like ansible for example).
