### ISSUE TITLE
Optional Feature: --disable-polkit

### ISSUE THREAD

**Issue by hoinmic** [cockpit-project/cockpit#13947]
For embedded devices it would be useful if Polkit could be disabled. Since Polkit is dependent on mozjs. mozjs is about 25MB on the target device.
Would this be a good or bad feature? Or does it have a chance to be included in the master branch?

**Comment by martinpitt** [comment]
We are de-emphasizing polkit anyway in favor of sudo as a primary means to get administrative power in the UI. We still want/need it for use cases where a non-admin user has specific polkit privileges -- so if you drop it, some pages will not work well for non-admin users. But that is a sensible compromise, especially for embedded devices.

(BTW, Debian/Ubuntu never moved to the mozjs version of polkit -- mostly because it's a hilariously bad design, but as a side effect it also avoids this large dependency.)

So, I'd  be happy to include that in the master branch, and provide some guidance if you want to try and work on a patch. I'm just afraid we don't currently have a lot of time (or honestly, interest) to do that ourselves. It shouldn't be too bad though, like conditionalizing the build of cockpitpolkitagent.c and `#if`fing its instantiation in the bridge.

**Comment by hoinmic** [comment]
@martinpitt Thanks for your answer. With your support I will try to implement it (A not clean code hack is already running :-) )

**Comment by hoinmic** [comment]
Implemented and merged
