### ISSUE TITLE
logs: add new presets

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#13992]
Page: Logs

From PR #13905

```
Presets would include the most useful searches, with possible things like:

    Current boot
    Previous boot
    Crashes
    sudo (priority: debug, identifier: sudo)
    SELinux (priority: debug, identifiers: setroubleshoot, setroubleshootd)
    etc.

```

**Comment by marusak** [comment]
Agree. I think we could make the `Time` select really about time and enable users to specify `since` and `until` time. From `man journalctl`:
> -S, --since=, -U, --until=
 Start showing entries on or newer than the specified date, or on or older than the specified date, respectively. Date specifications should be of the format "2012-10-30 18:17:16". If the time part is omitted, "00:00:00" is assumed. If only the seconds component is omitted, ":00" is assumed. If the date component is omitted, the current day is assumed. Alternatively the strings "yesterday", "today", "tomorrow" are understood, which refer  to 00:00:00 of the day before the current day, the current day, or the day after the current day, respectively.  "now" refers to the current time. Finally, relative times may be specified, prefixed with "-" or "+", referring to times before or after the current time, respectively. For complete time and date specification, see systemd.time(7). Note that --output=short-full prints timestamps that follow precisely this format.

With that we could give users power to actually find logs that happened during specific time. And then we would have presets of the usual ones like `previous boot`, `last 24 hours` etc.

@andreasn WDYT? Would this be usable and useful? I think month, day and hours would be enough.  We could also possibly go with with `-7 days`, `-3 hours` etc. but that is a bit more complicated to get to specific time.
Possibly we could have this just as option in search box and having it documented (both in rhel doc and in inline help) that it accepts whatever journal accepts. So something like `until:"2012-10-30 18:17"`.
And if we would go with just these quantifiers in the search box, then we could also introduce `boot:` quantifier and translate presets to these basic options. That would go nicely with teaching people how journalctl works and give them option to tweak the search created by presets (Someone would pick `Last 7 days` option, that would translate into `since:"-7 days"`, and then user would realize it was actually in last 4 days and not 7 days and could tweak it.

**Comment by andreasn** [comment]
Yes, I think that would make a lot of sense. Ability to set more detailed time controls would be of massive help for pinning issues down.

So should we make a new issue about more detailed time controls then maybe, and keep this one about the presets idea from garrett?

**Comment by martinpitt** [comment]
Stale, and we have a much more generic/flexible search now.
