### ISSUE TITLE
cockpit module to monitor laptop battery health

### ISSUE THREAD

**Issue by biji** [cockpit-project/cockpit#14059]
Page: 

Battery

It would be great if cockpit can collect data from upower, to collect historical EnergyFull, cycle count, temp, and warning if EnergyFulk is decreased

Thanks

**Comment by marusak** [comment]
That would surely be nice :) 
But I also think it will not be maintained by cockpit-project itself. Firstly because the maintainers are rather busy already but also since cockpit is mostly for servers and not laptops (I am not saying it is not good for laptopts, just that the core team focuses on server-usecases).
However we provide [starter-kit](https://github.com/cockpit-project/starter-kit) with which it is very simple to create own plugin. So if you decide to implement one, let us know! :)
