### ISSUE TITLE
Some tests fail to unrestrict core dumps

### ISSUE THREAD

**Issue by kurahaupo** [cockpit-project/cockpit#14129]
I was looking into #12949 and noticed this while searching for code relating to `ulimit`.

Commit d1b71540268f3ea23c362dbabb68351e7407d89c seems to have introduced a bug while refactoring to create the `crash` method.

It replaced
```
    m.execute("ulimit -c unlimited; timeout --signal=SEGV 0.1s sleep 5s || true")
```
with
```
    m.execute("ulimit -c unlimited")
    sleep = m.spawn("sleep 1m", "sleep.log")
    m.execute("kill -SEGV %d" % (sleep))
```
Unless I am misunderstanding the `execute` method, this means that `ulimit -c unlimited` is run in a separate process, to no effect. (The current limit on core dumps will continue to apply to the `sleep` process.)

It may be appropriate to audit the codebase to see if there are similar misunderstandings elsewhere.

**Comment by marusak** [comment]
> this means that `ulimit -c unlimited` is run in a separate process, to no effect. 

Right, so that command is not needed there.  But tests are happy, so I would not worry about it too much. But if it bothers you, feel free to fix it up and send us PR.

> It may be appropriate to audit the codebase to see if there are similar misunderstandings elsewhere.

It is always a good idea to audit the codebase, but it is just rather impossible to go through so many lines of code and read through them. Especially in tests. If you have something specific in mind, please let us know, otherwise I see this as non-actionable.
