### ISSUE TITLE
Virtual machine - disable 'delete' or any editing options

### ISSUE THREAD

**Issue by paulhargreaves** [cockpit-project/cockpit#14125]
Page: Virtual Machines

The virtual machines tab is useful, but the only features I want to use from it are Run/Shutdown and to view the status. What I don't want to do, ever, is 'Delete' or change autostart etc.

Currently it seems to be an all or nothing. There doesn't seem to be a way to configure what operations are possible, and that would be really handy.

**Comment by KKoukiou** [comment]
You will need to write some polkit configuration for libvirt for your user and enable polkit as you access driver.
cockpit will allow you to do exactly what your connected user would be able to do if you connect with ssh and try to perform the same operation with `virsh`.

See more information about that on https://libvirt.org/acl.html#drivers

If you need help setting your polkit policies or this solutions does not work for you let me know, otherwise please close the issue.

**Comment by paulhargreaves** [comment]
Does setting the polkit automatically remove all the delete buttons etc from the UI?

**Comment by KKoukiou** [comment]
> Does setting the polkit automatically remove all the delete buttons etc from the UI?

No, you will see the button but the operation will fail if you did not allow it through polkit rules.

**Comment by paulhargreaves** [comment]
That's not ideal, nor as simple as a quick 'disable all' toggle or setting, but it's a usable workaround. Thanks
