### ISSUE TITLE
Document how to define alternative transports besides SSH

### ISSUE THREAD

**Issue by strugee** [cockpit-project/cockpit#14148]
Page: N/A, documentation(?)

I run a few LXD containers locally, and I would like Cockpit to be able to connect to them and manage them as independent hosts. I don't really want to run sshd on them because there's no reason to - since I have root I can easily arrange for a `cockpit-bridge` process to be started in the container, with its stdin and stdout intact, like so: `sudo lxc exec $containername cockpit-bridge`

Unfortunately I can't figure out how to teach Cockpit to do this, by spawning `lxc ...` instead of `cockpit-ssh`. I read the documentation on bridges and tried making an `lxd` package to hook this up, but I can't seem to make it work. AFAICT this should just be something that only needs documentation, but I'm obviously not an expert so feel free to retitle this issue if it would need code too.

**Comment by martinpitt** [comment]
A good first step may be to play around with [cockpit-desktop](https://cockpit-project.org/guide/latest/cockpit-desktop.1.html). In commit 3e84af2815866d3126b93be310239ce82438b87a I added ssh support, the core of which is just [one code line change](https://github.com/cockpit-project/cockpit/commit/3e84af2815866d3126b93be310239ce82438b87a#diff-c25541e7d6fc01933ca6164ae8228030R164) (the rest is documentation and tests).

Instead of that ssh you can add the relevant `lxc exec` command. This is of course mostly a first proof of concept, not a production solution, but it should give you some idea how to piece that together. [This presentation](https://www.youtube.com/watch?v=m92Vl-FZdA8) may also be helpful to understand the parts.

I agree that this could use some more written documentation.

**Comment by martinpitt** [comment]
Note: The general way to do this would be to implement some "cockpit-lxc" bridge similar to cockpit-ssh, and defining a [manifest like cockpit-ssh](https://github.com/cockpit-project/cockpit/blob/main/pkg/ssh/manifest.json), which does pattern matching on particularly formatted `host` fields. However, this is *very* advanced material, which involves a lot of bridge redesigning. This is not just a simple matter of documentation -- so far I am not aware of a single third-party bridge for cockpit, as implementing the protocol handling alone is a major task.

I am going to close this -- there isn't anything actionable here short of the above work, and we don't have the capacity nor business priorities to do that, sorry.

**Comment by martinpitt** [comment]
In other words -- installing  `openssh-server` into your LXC containers or running cockpit-ws inside of them is the practical solution that works today.
