### ISSUE TITLE
help icons are cut off

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#14160]
Cockpit version: 218
OS: Fedora
Page: Logs, but also Shell

So not sure if these are the same issue or different ones. Happy to split up if needed, so we can take care of each one in their time.

Seems the help icons are cut off. The shell one on the top, and the logs one on the left side.

![Screenshot from 2020-05-27 14-49-27](https://user-images.githubusercontent.com/209895/83021052-b0e32180-a029-11ea-9d89-2415a01d3557.png)

**Comment by garrett** [comment]
The icons are actually _not_ cut off; they're provided by a font and font rendering is not optimal for these glyphs. It's being "hinted" and shouldn't be.

There's https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth — but it's non-standard, doesn't work as expected cross-browser, and differs across platforms. (In other words, it's basically useless.)

We'd have to swap them out for SVG to get them to render in a more pleasing way.

**Comment by garrett** [comment]
GitHub [used to use an icon font many years ago](https://github.blog/2012-05-09-the-making-of-octicons/) (2012). [They switched to using SVGs a few years back](https://github.blog/2016-02-22-delivering-octicons-with-svg/) (2016), for the reason this issue is open, among others.

Basically, all the other big websites (including Twitter, Facebook, etc.) switched to SVG years ago. GitHub's is just the most well known who blogged about it with nice examples.

**Comment by garrett** [comment]
(This all said, icon fonts render _okayish_ for many non-simple icons. Basic geometric shapes are always going to be problematic in an icon font — especially circles.)

**Comment by andreasn** [comment]
Yeah, probably OK enough. I don't think it's worth switching to SVGs. Closing.

**Comment by garrett** [comment]
Oh, the actual SVG to download from the PF4 website is misaligned and goes outside of bounds. So the source icon itself is cut off. I wonder if that followed into the font.

Anyway, it wouldn't fix it for Cockpit even if the font was recompiled with the glyph bumped a bit, due to hinting. (It's cropped on the bottom and has space at the top, which is the opposite of the rendering we're seeing. And we're also seeing issues with the left vs. right sides too.)

**Comment by garrett** [comment]
"Swtiching to SVGs" would mean an override for the class with a `content:` line that has an SVG embedded. That should be it, _probably_. Otherwise, we could embed the SVG in the HTML. (PF4 does this a bunch with React.)
