### ISSUE TITLE
Use cockpit-package in my web application without login 

### ISSUE THREAD

**Issue by madiseh** [cockpit-project/cockpit#14252]
Hello Guys
i want to use cockpit in my web application for networkmanager 
`<...............blob blob blob................>
<iframe src="http://172.30.30.36:9090/cockpit+app/@localhost/network/index.html"
    width="600" height="400"></iframe>
`

in my web application, user Login into my website 
and i dont want to login again in cockpit 
is it possible to handle this ?
other way if there is anyway to see this page without login 
http://s12.picofile.com/file/8400435776/2020_06_19_0_57_32.jpg

beacause in my web application i have login Page and handle session 
if possible please Help
thanks

**Comment by martinpitt** [comment]
Logging into your website is a completely different thing than starting a Linux user session (what Cockpit is). The user, password, and the mechanics are completely independent from each other. Of course, the user/password may *happen* to be the same; then you could try to send the user/password to http://172.30.30.36:9090/cockpit+app/login as Basic Authentication, and if it succeeds, just keep the cookie. And if it fails because the user/password is different, getting the login page is what you want, I suppose.

**Comment by madiseh** [comment]
hello again
 when i send login param with postman 
http://172.30.30.36:9090/cockpit+app/login
i get error 
http://s13.picofile.com/file/8400496650/2020_06_19_20_06_24.jpg
401 Not Authorized 
if possible please Help
thanks
