### ISSUE TITLE
navigation: permission switcher has low discoverability rate

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#14305]
Cockpit version: 220
OS: RHEL
Page: Navigation

During the usability testing in June with 5 participants, 2 participants failed the task, and 2 needed assistance to complete the task of putting the system in limited access mode.

![Screenshot from 2020-06-30 18-02-27](https://user-images.githubusercontent.com/209895/86354115-bf47dd00-bc68-11ea-969a-e6cb785c19b1.png)

**Comment by garrett** [comment]
I wanted to have the icon there, but was talked out of it. It currently reacts to hovering (with an underline and background change), but, as we saw, that isn't enough.

I wonder if simply adding a locked/unlocked icon would be enough? (Or should we consider another icon instead. If then, what?)

**Comment by martinpitt** [comment]
What about making it a labelled On/Off switch, like we have on the React Patterns page?

**Comment by garrett** [comment]
1. On switch
2. Off switch
3. Off switch with disabled switch background color

![header-auth](https://user-images.githubusercontent.com/10246/86609789-bcbcee80-bfac-11ea-9b62-bd5c71402282.png)

As the switch is on a dark background, I think a standard off looks disabled and the disabled background makes it look active. (Basically: inverting the shades, as there's a dark background.)

As the widget is right-aligned, the toggle shifts position due to the text being of varying lengths. However, there's a dialog that immediately shows up when switching, so it's probably not too strange?

What do you think?

**Comment by martinpitt** [comment]
@garrett: My gut feeling is that we shouldn't disable the on/off switch. If the page knows that the user isn't a sudoer (but you need to try to find out at least for the first time), then it should just be a label. That's consistent with what we now do on most other pages (hide instead of disable elements that require privileges), and avoids the ambiguity.

The alignment is certainly unhappy -- one part of me just wants the on/off button to go after the label, to be consistent with right alignment; but we don't do that anywhere else, and it would also "collide" with the help icon. So my 2 cents are to just accept it.

**Comment by garrett** [comment]
> My gut feeling is that we shouldn't disable the on/off switch.

I never suggest disabling it.

I was pointing out that the stock switch, when turned off, looks disabled. My workaround was to change the gutter color to match the disabled one (but not the round switch itself), to make it look like it's active. This is due to a dark background, and the switch is made for the light one.

In other words, the top two are stock, the bottom one is a modification. The bottom one looks active on the black background, right? (The middle one looks disabled, not off.)

**Comment by garrett** [comment]
Note: There's no `pf-m-dark` mode available for the switch, hence recoloring it to look active on a dark background.

**Comment by martinpitt** [comment]
@garrett: Sorry, I misunderstood you then. I can honestly not decide which one looks "more" or "less" disabled to me.

**Comment by marusak** [comment]
> In other words, the top two are stock, the bottom one is a modification. The bottom one looks active on the black background, right? 

Still looks kind of disabled. Can we just go with some other colour then grey? (I don't really know, red? (would seem like something is wrong), green? (would suggest it is as it should be, don't touch it), other shade of blue? (as it is just "other type of" privileges anyway)?)

I think we should implement this if we can come up with some reasonable design. I am happy to do it of course.

**Comment by garrett** [comment]
I'm not sure if a switch makes sense to always be in-your-face really.

The admin case is not a big deal. Most people will never downgrade capability, right?

The big problem is when you're _not_ and admin and want extra privileges. So we should probably make it look more clickable in this one state. And people, once they click, might understand that's where you click to de-escalate too. And if they don't, then there shouldn't really be much harm done, as — again — people almost always need to increase permissions, not decrease.

The one issue is if they actually cannot increase privileges. So it shouldn't be in-your-face and it should not look like a warning.

**Comment by marusak** [comment]
> The admin case is not a big deal. Most people will never downgrade capability, right?

Right, I think this is safe to assume. And if someone has actually usecase to drop privileges, they will most likely look around how to do it as opposed users who login, don't have privileges but are not aware that they can escalate it and wonder why they cannot do some actions. For the latter group we should be more verbose.

> The one issue is if they actually cannot increase privileges. So it shouldn't be in-your-face and it should not look like a warning.

Correct. I am not sure right now if we can recognize this in advance though.

**Comment by martinpitt** [comment]
> I am not sure right now if we can recognize this in advance though.

We do. The Overview page already gives you an extra banner+button if and only if you can eleveate privileges.

**Comment by garrett** [comment]
There's been further discussion @ https://github.com/cockpit-project/cockpit/discussions/16133.

I should re-prioritize this issue. I lost it in the backlog (whoops), as there's always something to do; but this is important.

**Comment by garrett** [comment]
Here's a mockup with several different ideas. We could adopt some of them; we don't have to adopt everything (or we could even adopt more).

![cockpit-shell-not-admin](https://user-images.githubusercontent.com/10246/127020723-a20a4e1c-1b12-401d-9096-eb4dceb8f5a4.png)

1. Make the banner color more attention-getting. 
2. Change the icon to a derivative of `pf-icon-private` (split into two colors, to emphasize the lock, however). We could use `fa-lock` instead, without the circle around it.
3. Left-align the action button to better connect it with the text.  
4. Move the top border of the banner alert to the bottom, as it gets lost next to the black.
5. Use an icon (`fa-lock`) paired with the "limited access" text in the top bar.
6. Add color to the "limited access" icon.
7. Add a background to the "limited access" area, to make it look like a button (although with a dark grey).

Items 1 - 4 cover the overview page exclusively. Items 5 - 7 applies to the shell, so it's seen in all pages.

When someone has administration access, it should look like Cockpit currently does. (No icon, no color, no button, no banner.)

Additionally: We currently have successful log in attempts as an alert for some odd reason (there's a longstanding bug open on this @ https://github.com/cockpit-project/cockpit/issues/13882); having something that's an alert that shouldn't be alerted distracts from things that are actually more important (such as things that should be alerts and this banner). Moving it to its proper place will help attention go to the things that actually need attention.
