### ISSUE TITLE
question: why waring, couldn't add host no more than 20 ?

### ISSUE THREAD

**Issue by tscswcn** [cockpit-project/cockpit#14414]
Page: 

we  think cockpit  dashboard is good tools to mange kvm vm. 
we got warningmessages when add hosts   couldn't add host no more than 20 ?
 we  want to detail  information about this warnign messagess, is there any limits, thanks, please tell us the detail

**Comment by martinpitt** [comment]
This is by design. The Dashboard page is quite expensive, it needs to keep a persistent connection to every host, collect metrics from them, etc. This is really more of a demo. Cockpit is a tool to administer a single machine (or really only a few), not a large fleet. For the latter, please use Foreman/Satellite, Ansible, or another large-scale tool. E. g. foreman/Satellite even have Cockpit integration, so that you get a cockpit window for a particular host with one click.

We will not change this general design.
