### ISSUE TITLE
machines: Width calculation for columns in VM table is all over the place

### ISSUE THREAD

**Issue by skobyda** [cockpit-project/cockpit#14443]
Page: machines

Every time i switch between VM tabs, the width of each column in VM header which contains things like "Name", "Connection", "State", etc. recalculates. The problem probably is that we use `--pf-c-table--cell--Width` which has automatic value.

Screenshots how switching between tabs changes column width. This also results in usage diagrams being too far apart:
![Screenshot from 2020-08-03 12-44-22](https://user-images.githubusercontent.com/42733240/89174993-1a7e2f80-d587-11ea-8906-f428a09d9be9.png)
![Screenshot from 2020-08-03 12-44-28](https://user-images.githubusercontent.com/42733240/89174997-1ce08980-d587-11ea-9a1a-8b9c9a45a013.png)
![Screenshot from 2020-08-03 12-42-26](https://user-images.githubusercontent.com/42733240/89174842-cd9a5900-d586-11ea-89dc-61799f6cb2c9.png)

**Comment by garrett** [comment]
This will be less of a problem when we finally land https://github.com/cockpit-project/cockpit/pull/14346. The issue is a result of having nested PF tables. This is more of an issue in Chrome than in Firefox, as Chrome does some funky recalculations.

Also, at some point, the actions also stopped being right-aligned due to a regression. And then the inner list buttons also had some regression where they're no longer side by side in desktop mode.

**Comment by garrett** [comment]
Note: This _did_ work at some point, even recently. There's something odd going on.
