### ISSUE TITLE
Cockpit is not working on Microsoft EGDE 

### ISSUE THREAD

**Issue by elhananjair** [cockpit-project/cockpit#14448]
Cockpit version: xxx
OS: Windows 10 version: 10.0.18363 Build: 18363
 
 
I tried to use cockpit to access fedora 32 server but I am getting this error:

                                 **Connection failed**

- There was an unexpected error while connecting to the machine.
- Messages related to the failure might be found in the journal:
- journalctl -u cockpit
It worked fine on other browsers

**Comment by martinpitt** [comment]
We test Cockpit on Edge, although a fairly old version. "connection failed" is not specific enough. Can you please send a complete screenshot? What *exactly* are you trying to do and what happens exactly?

**Comment by elhananjair** [comment]
The version of edge is:
**Version 84.0.522.52 (Official build) (64-bit)**
am trying to login into fedora server 32 that I had installed on VM, and I entered my credential as I hit enter, the above error shown on screen.
![temp](https://user-images.githubusercontent.com/69236638/89386988-89d05c80-d70a-11ea-9595-7c90bc9af0c2.PNG)

**Comment by martinpitt** [comment]
Ah, so you do see the initial cockpit login screen? This means that there's something wrong with the websocket connection. What does the journal show around the time when you log in? Easiest to do this with starting

    sudo journalctl -u cockpit -f

and then try to log in. Press Control-C to stop the logging.

**Comment by elhananjair** [comment]
Nothing is happening...
![temp2](https://user-images.githubusercontent.com/69236638/89388590-e765a880-d70c-11ea-97a4-7e0ba802b526.PNG)

**Comment by marusak** [comment]
You misspelled `cockpit` as `cockit`

**Comment by elhananjair** [comment]
oww yeah sorry, 
![temp2](https://user-images.githubusercontent.com/69236638/89389666-5d1e4400-d70e-11ea-8227-95a261d284ab.PNG)

**Comment by martinpitt** [comment]
Thanks; that also basically just says "wah wah, don't like TLS". This smells a bit similar to the issues we get on Safari.

**Comment by elhananjair** [comment]
hahaha oww ok,

**Comment by garrett** [comment]
I see the version of Edge you're using is one based on Chromium. 

We specifically test on Chrome and EdgeHTML-based Edge. We don't test on Chromium-based Edge right now. But theoretically, Chrome and Edge based on Chromium _should_ be the same — at least rendering-wise. Some parts of the browser are implemented differently from Chrome. It's possible that certificate-related parts of Edge are different from Chrome. (I do not know if this is the case.)

That said, I installed the new Edge based on Chromium on a Windows 10 VM here and was able to access Cockpit just fine. (But this is a simple set-up with Cockpit's default generated self-signed certificate and no proxy or anything in the middle.)

>  It worked fine on other browsers

Which other browsers did you try accessing Cockpit with?

**Comment by elhananjair** [comment]
Currently it worked for me on firefox 79.0 (64-bit)

**Comment by garrett** [comment]
@elhananjair: Have you manually created the certificate? Are you using a proxy?

Here's a screenshot where I'm using the same exact version of Edge (based on Chromium) to access Cockpit running on my machine, without a proxy in the way, and with using Cockpit's self-generated self-signed certificate:
![Screenshot from 2020-08-10 13-30-07](https://user-images.githubusercontent.com/10246/89778386-b373f400-db0d-11ea-81dc-b0d4ec1867ea.png)

**Comment by elhananjair** [comment]
hey bro it worked now, I really don't know what is the exact issue, one thing I suspect is, my antivirus ESET I once turned of web protection like https filtering and it worked even when I back the setting to "ON". The other thing I suspect is I use VPN extension on my edge browser maybe that could cause a problem too, but I don't if it does. 
I also create self-signed certificate using openssl. Now everything is working good.
Thanks for your support :)

**Comment by elhananjair** [comment]
Maybe someone can suggest something and I can close after that :)

**Comment by garrett** [comment]
@elhananjair: It'd be great to know what the problem is of those two issues.

From what you've described, it sounds like ESET is effectively running a MitM exploit to sniff traffic over HTTPS. (That is, it's hooked into your system's certificate store, added its own root certificates, and is intercepting traffic between endoints — your computer and the server it is connecting to.) It's similar to what a lot of other anti-virus software on Windows also do, explained at: https://security.stackexchange.com/questions/73476/why-is-avast-web-mail-shield-root-listed-as-ca-for-google-com/73481 (this is talking about Avast, but it also applies to ESET).

It's usually not a good idea to let software sniff all your traffic. This means it's intercepting information in-between your browser and your bank, any site where you enter credit card information, any site you write anything on forums, direct messages, email, download extensions, and so on. You're putting a _huge_ amount of trust that ESET is doing nothing wrong. It _could_ do things like: reporting back some of this information somewhere, allowing your computer to download different things than what is intended (especially if signatures aren't checked — but even it could also switch around signatures), and so on. But that's also a similar amount of trust we're putting in browsers and operating systems too.

A VPN extension should not mess with certficiates. If it was the culprit, then you probably couldn't get to Cockpit at all. However, [some VPNs (like "Betternet", "PrivateVPN", "Hotspot Shield", "Hide.me", "CyberChost", and "TorGuard" according to the article) do actually seem to MitM too](https://www.tomsguide.com/news/vpn-mitm-attack), so depending on which VPN you use, it might also be causing this problem, in a very similar way. (I still think it's more likely caused by ESET, as interception is an advertised feature.)

---

So: Why is this happening? My guess at the most likely scenario is this:

By default, Firefox does not use the native OS certificate store. In Firefox 75 (and higher), there's a preference to opt-in to the OS certificate store (mainly intended for corporate usage): https://blog.mozilla.org/security/2020/04/14/expanding-client-certificates-in-firefox-75/

So I suspect it's likely ESET installed a root certificate in your Windows 10 certificate store so it could intercept all traffic. When it swapped out certificates (with a mangled one) for Cockpit (which it also does for all other sites), the self-signed Cockpit certificate happened to be changed in such a way so that Edge did not like the certificate.

Meanwhile: Firefox, using only its own certificate store, kept showing you Cockpit just fine.

---

Now, to try to figure out if this is the case or not:

- Is Cockpit working now in both browsers with both ESET and the VPN enabled?
- What happens in both browsers when you only have ESET enabled and the VPN off?
- What happens with just the VPN on?

**Comment by elhananjair** [comment]
Yes its working in both cases, ESET and VPN extension on browser are both on.

**Comment by garrett** [comment]
@elhananjair: So I guess it's working 100% of the time for you now?

Still, thank you tons for reporting this and working with us as to what the possible issue might've been. Knowing about how a lot of Windows AV software works by essentially doing MitM attacks — just like malware — to snoop on connections is really useful as to help diagnose what's going on.

I feel that we should update the error page with this sort of scenario as well. (I don't think there's anything else we can do about it to actually prevent if from happening though. But knowing what's possibly going on is a huge step toward figuring out ways to fix or work around a problem.)

**Comment by elhananjair** [comment]
Thank you so much for your support, :) and I like a lot using cockpit, its so easy and neat!

**Comment by garrett** [comment]
Closing this issue as Cockpit does work on Edge under normal circumstances.

I have opened another issue to improve messaging on certificate issues, making note of proxy problems (with a specific mention to Windows AV software) @ https://github.com/cockpit-project/cockpit/issues/14485
