### ISSUE TITLE
VM:s not visible v225

### ISSUE THREAD

**Issue by polhaghverdian** [cockpit-project/cockpit#14453]
Hi,

After installing **v225** from **v221** i can no longer see my vms. Has it been any changes that might cause this? 

The vms has been created with **virt-install** as usual and have been visable until installing v225. I am using **Ubuntu 20.04**.

**Comment by polhaghverdian** [comment]
Find the problem and related to this issue: 

https://github.com/cockpit-project/cockpit/issues/13343

**Comment by ICarryTheDustOfAJourney** [comment]
This happened to all my Ubuntu 20.04 installations running under v215 recently.
I' pretty sure more (all Ubuntu 20.04?) users will find this issue here, so I'm 
describing the solution more detailed:

As mentioned above and described in [#13343]( https://github.com/cockpit-project/cockpit/issues/13343)
```
sudo usermod -a -G libvirt libvirtdbus
sudo usermod -a -G libvirt libvirt-qemu
```
and a reboot made the VMs reappear, but I'm not sure what sideeffects this has.

So far everything seems to work fine. May be someone with deeper insights then me 
can validate this remedy?
