### ISSUE TITLE
RFE: Sort Machines by state

### ISSUE THREAD

**Issue by sghosh151** [cockpit-project/cockpit#14462]
Page: Machines

enable sorting of the machine list by name (alpha, reverse-alpha) or by state ( running, shut-off, etc)

**Comment by KKoukiou** [comment]
Hi @sghosh151, this is a nice feature to have indeed. I decided to implement filters by name and state above the table, instead of sorting alphabetically. The alphabetical sort makes sense for name sorting, but not for state IMO, since there are many possible states.
I hope you are satisfied with the decision, I will send a PR shortly.

**Comment by sghosh151** [comment]
Filtering is great, but sorting is helpful in other scenarios as well when you need to see systems grouped by current state
I'll take filtering for now

**Comment by martinpitt** [comment]
@sghosh151 : @KKoukiou sent PR #14505 to implement this
