### ISSUE TITLE
SSH_AUTH_AGAIN returned from ssh_userauth_password

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#1460]
SSH_AUTH_AGAIN is sometimes returned from ssh_userauth_password(). Seen it in the wild. This seems to mean that we can try again with another password. We should treat it just like an authentication failure, rather than "internal-error"

https://github.com/cockpit-project/cockpit/blob/master/src/ws/cockpitsshtransport.c#L334

**Comment by petervo** [comment]
I could be way off but my understanding of SSH_AUTH_AGAIN is that it is an invitation to resubmit your credentials when using non blocking mode, usually because there were communication problems. Most libraries seem to just retry with the same credentials in a do while loop. Are you sure we don't want to just automatically retry for them?

**Comment by stefwalter** [comment]
But our connect loop doesn't run in blocking mode. It runs synchronously in a thread. Hence the confusion, having seen this in the wild.
