### ISSUE TITLE
Non-responsive after creating encrypted disk

### ISSUE THREAD

**Issue by RoyKas** [cockpit-project/cockpit#14651]
Cockpit version: 227
OS: Debian 10 (Buster)
Page: Storage

When I create a new encrypted disk, Cockpit becomes non-responsive for at least 15 minutes:

![Prepare encrypted EXT4](https://user-images.githubusercontent.com/26328039/93913141-f0cec280-fd04-11ea-8a8c-54c15377d08e.png)

If I ssh into the server the encrypted disk is created and added to /etc/fstab, but not mounted.

If I open a second Cockpit I see the newly created file system:

![Listed filesystem](https://user-images.githubusercontent.com/26328039/93913422-5ae76780-fd05-11ea-84d5-af5af95f6f90.png)

And I can mount this manually.

Logs show little:

![Logs](https://user-images.githubusercontent.com/26328039/93913489-72beeb80-fd05-11ea-963e-39f61cdda2ca.png)

**Comment by KKoukiou** [comment]
Closing this as its using a very old cockpit version, and we (cockpit team) did not manage to reply in time.

@RoyKas I apoligize for not reaching back to you here, if you can still reproduce it with the latest available cockpit-storaged version availabe in debian, please comment so that we can reopen and address this.
