### ISSUE TITLE
Can't Connect to VM / Direct Network Connection with Interface Not Functioning Properly

### ISSUE THREAD

**Issue by xer0-1ne** [cockpit-project/cockpit#14676]
I modified the original post:
System: Arch Linux (banshee) 5.8.12-arch1-1 #1 SMP PREEMPT Sat, 26 Sep 2020 21:42:58 +0000 x86_64 GNU/Linux
Cockpit Version: **228**
Libvirt version: **6.5.0-2**
qemu version: **5.1.0-1**

The issue is that I cannot connect to a VM that is configured to get an IP address from the host network.  The ports are open on the host machine, but the VM itself is not accessible from anywhere on the network.

### Host Setup:
Default Gateway: **192.168.1.1**
Subnet Mask: **255.255.255.0**
Host IP interface 1 (eno2): **192.168.1.90**
Host IP interface 2 (enp5s0): **192.168.1.91**

I created a VM using the Virtual Machines page and configured the network for a direct attachment with interface 2 (enp5s0).
<hr>
<img width="1032" alt="Screen Shot 2020-10-01 at 9 28 15 AM" src="https://user-images.githubusercontent.com/7335096/94827897-f13b1d80-03d6-11eb-8ba7-2a61d00b84b0.png">

<img width="718" alt="Screen Shot 2020-10-01 at 9 29 28 AM" src="https://user-images.githubusercontent.com/7335096/94828952-05cbe580-03d8-11eb-8f83-efc740183371.png">
<hr>
The device holds 2 IP addresses:
192.168.1.91 (static) and 192.168.1.229 (assuming dhcp)
<hr>
<img width="1008" alt="Screen Shot 2020-10-01 at 9 29 55 AM" src="https://user-images.githubusercontent.com/7335096/94828967-0c5a5d00-03d8-11eb-8d40-f80675116b86.png">
<hr>
and the VM is getting an IP address from the main router / gateway. (The ip address is dhcp assigned as 192.168.1.233)
<hr>
<img width="790" alt="Screen Shot 2020-10-01 at 11 24 38 AM" src="https://user-images.githubusercontent.com/7335096/94829714-cce04080-03d8-11eb-9ea4-08482ac46e23.png">
<hr>
The VM can ping the gateway, but nothing else.  
<hr>
<img width="787" alt="Screen Shot 2020-10-01 at 11 22 01 AM" src="https://user-images.githubusercontent.com/7335096/94829292-5e02e780-03d8-11eb-861e-e8e55c7393b5.png">
<hr>
On the physical network, nothing can ping the VM, but the bridge and macvtap device can be pinged.
<hr>
<img width="659" alt="Screen Shot 2020-10-01 at 11 31 56 AM" src="https://user-images.githubusercontent.com/7335096/94830607-c0a8b300-03d9-11eb-92e3-3679e49f9180.png">
<hr>
So, the fun part is that when the VM is running,  the macvtap device is created and, on the host, ports 5900 and 5901 are open.  This doesn't matter though because the VM is still unreachable from any other device (aside from the host machine).

iptables are disabled and ebtables are wide open.
<hr>
<img width="490" alt="Screen Shot 2020-10-01 at 1 17 09 PM" src="https://user-images.githubusercontent.com/7335096/94841720-711db380-03e8-11eb-9731-2d1068d90629.png">
<hr>
Any idea as to why a VM couldn't be accessed from the network?

**Comment by zippy2** [comment]
This is typical macvtap problem. Using macvtap in VEPA mode means that guest <-> host communication is not possible unless a fancy switch with hair pin is used. The reason is that when a guest sends a frame down the wire (through macvtap), switch sees it and must send the frame back through the same wire it just came from. In networking this is considered a misconfiguration and/or a loop. Hence the switch drops the frame to break the loop. It's the same story if hosts sends a frame that has the guest as the destination.

But since you have two interfaces attached to the host, what might work is using the other NIC that doesn't have the macvtap attached to communicate with the guest, e.g. `ping -I eno2` or `ping -I enp5s0` but it boils down to another problem that the kernel is unable to handle if a reply to a ICMP/TCP/UDP packet comes to a different NIC than the one that has sent the request.

In general, if you need host <-> guest communication then just put another NIC to your guest that uses a bridged network (e.g. libvirt NATed network).

**Comment by xer0-1ne** [comment]
With a direct attachment, the issue is resolved.  Furthermore, the firewall in windows will block all unnecessary traffic.  Disabling Windows Defender on Windows 10 VMs helped.
