### ISSUE TITLE
accounts: Provide a temporary, non-wheel approach to making someone an administrator for a limited time 

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#14731]
From the top tasks UX tests: "I was unable to find where to change the account so it had to change its password every day. I also think it's not a good practice to use the wheel group to give admin rights. most places I work have that commented out in sudoers."

In other words:

We should have some sort of way to temporarily give someone administration rights.

(FWIW: This apparently pairs well with https://github.com/Scribery/cockpit-session-recording, so someone could temporarily give a person admin rights and then later see what they did, to make sure they didn't do anything nefarious.)

**Comment by martinpitt** [comment]
It is impossible to give someone "temporary" admin rights declaratively in Linux. As an admin, you need to explicitly remove the admin rights from the user, *and* do a full audit of the system that they did not leave behind any changed configs (sudo, polkit), processes, or backdoors (such as suid root files).

But this is also not exactly what the original text said. The accounts page has had "password expiry" for a long time, so that can be set already.

As to not using groups, but a custom sudoers config, that's the prerogative of the admin, and they are free to do that. But the [official Red Hat documentation recommends the wheel group](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/granting-sudo-access-to-a-user_configuring-basic-system-settings), and I wholeheartedly agree. in Cockpit we will *not* have an UI for editing sudoers -- this is an incredibly complex format, and it's really easy to completely wreck your system with it.

**Comment by garrett** [comment]
@andreasn: Do you know more about this issue? I opened it based on your UX findings. Perhaps the interpretation is incorrect?

**Comment by andreasn** [comment]
Sorry, I don't quite recall the details. I'll see if I can hunt down the full script. Not impossible that this is something someone wished Linux did, rather than something Linux actually does :)
