### ISSUE TITLE
software: Automatic updates → Scheduled updates?

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#14834]
The updates are applied automatically, but it's more about scheduling a time to automatically apply them, right? Would this text be clearer if we renamed it?

Related: #14723 #14749

(I even subconsciously referred to it as scheduled updates in #14723.)

**Comment by KKoukiou** [comment]
I am not big fun of this rename, automatic updates is also correct term here, since the updates are not performed manually any more. Of course there is a journal timer in the background scheduling the updates, but I think the initial term is well describing the process.
In addition, everywhere in the documentation the dnf/yum autoupdate are referring to 'Automatic updates' and I always tend to want to follow the upstream documentation because it makes it easier for users to google their problems with known terms.
See https://fedoraproject.org/wiki/AutoUpdates#How_are_automatic_updates_done.3F

**Comment by garrett** [comment]
@KKoukiou: Great points. Thanks!
