### ISSUE TITLE
Some Selects are not espaping outside of PF4 modals causing scrolling to appear

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit#14857]
example:
![Screen Shot 2020-11-03 at 12 57 26](https://user-images.githubusercontent.com/14921356/97982531-38e90680-1dd4-11eb-8801-ee3c6a55123d.png)

Solution possibly similar to:

**Comment by garrett** [comment]
We have the same issue elsewhere in Cockpit too. Here's one of the issues: https://github.com/cockpit-project/cockpit/issues/10424 (I included a list of several workarounds.)

This is one of the reasons why I suggest using "form select" instead of "select" whenever possible, so it won't have this issue in overflowed areas (not just dialogs). We've worked around it in other ways by turning off overflow. But that's also not very good.

Obviously, for the autocomplete widget, we cannot use a form select. On the call yesterday, @KKoukiou and I talked about some solutions. PatternFly seems to have one for some widget(s) where it probably reparents the popup outside of the scrolled area?
