### ISSUE TITLE
Can't install Windows VMs

### ISSUE THREAD

**Issue by cheapproxies** [cockpit-project/cockpit#14904]
I'm trying cockpit and works great with linux machines, but there is no option for running Windows.

I can't choose Windows Operating Systems, only linux systems are listed in the dropdown menu.

Can someone help ?

Thanks

**Comment by garrett** [comment]
The OS dropdown should have Windows. However, I'm also not seeing it here.

My initial guess: We do filtering of the OS list based on supportability status; perhaps it's wrong for Windows, either in the list or our filtering?

**Comment by KKoukiou** [comment]
We do support windows installations, but you need to provide the installation media by yourself.

In other words, choosing in the UI `Download an OS` option for the installation source, which will automatically install the selected operating system as selected in the `Operating system` dropdown, is not available for Windows. And that's because it's not supported by the tools we use, in this case libosinfo.  

However, if you supply your installation media, by choosing, `Local installation media` you can then select the currently supported windows OS in the dropdown, which is `Microsoft Windows Server 2019 (10.0)`.

See:
![Screen Shot 2020-11-16 at 14 46 25](https://user-images.githubusercontent.com/14921356/99259971-14048280-281b-11eb-8b0d-d0bb4fa42123.png)

So @cheapproxies I guess you wanted that you don't supply the installation source manually but you just selected the desired operating system like you do with most linux distros?

**Comment by KKoukiou** [comment]
And for your information, the reason that windows is not listed under this automatic downloadable Oses, is because it's not tree installable. I just fetched this info from osinfo DB.

 {
    "id": "http://microsoft.com/win/2k19",
    "shortId": "win2k19",
    "name": "Microsoft Windows Server 2019",
    "version": "10.0",
    "family": "winnt",
    "vendor": "Microsoft Corporation",
    "releaseDate": "2018-10-02",
    "eolDate": "",
    "codename": "",
    "recommendedResources": {
      "ram": 2147483648,
      "storage": 42949672960
    },
    "minimumResources": {
      "ram": 536870912,
      "storage": 34359738368
    },
    "profiles": [],
    "unattendedInstallable": false,
    "medias": {},
    "treeInstallable": false                      <<<<<<<<<<<< This is the problem here
  },

**Comment by KKoukiou** [comment]
@fidencio any plan to support windows for virt-install os option?

**Comment by KKoukiou** [comment]
@cheapproxies can  you confirm if the missing Windows entry is only when choosing 'Download an OS' option? In that case I will close this ticket, and you (or I can do it for you) need to open a feature request for libosinfo.

**Comment by fidencio** [comment]
@KKoukiou, long time no see, :-)

> @fidencio any plan to support windows for virt-install os option?

We can't do "tree" based insallations with Windows.  However, you can and should advertise Windows installation works with medias, by calling `virt-install --cdrom /path/to/windows/iso --unattended`.  The user can pass the product-key as a sub option of --unattended.  Everything is described in the virt-install manpages.

Does this answer your question? Feel free to reach me out with questions about this, so we can ensure it also works with cockpit machines.

> @cheapproxies can you confirm if the missing Windows entry is only when choosing 'Download an OS' option? In that case I will close this ticket, and you (or I can do it for you) need to open a feature request for libosinfo.

Windows 2019 should be present.  One known issue we have and we sincerely don't have a way to solve is differentiating between some Windows versions, as Microsoft uses exactly the same volume-id for those.  Still, it shouldn't block the user to select the distro, provide the minimum needed, and perform an unattended installation.

**Comment by fidencio** [comment]
> @KKoukiou, long time no see, :-)
> 
> > @fidencio any plan to support windows for virt-install os option?
> 
> We can't do "tree" based insallations with Windows. However, you can and should advertise Windows installation works with medias, by calling `virt-install --cdrom /path/to/windows/iso --unattended`. The user can pass the product-key as a sub option of --unattended. Everything is described in the virt-install manpages.
> 
> Does this answer your question? Feel free to reach me out with questions about this, so we can ensure it also works with cockpit machines.
> 

On a conversation on #cockpit channel, @KKoukiou made clear this is not about unattended installations, but rather about downloading the ISO for the user.  This is something we **cannot** do, as osinfo-db would require a direct link to the ISO (so cockpit machines would be able to download it), which is something still not provided by Microsoft.

**Comment by cheapproxies** [comment]
The option to choose WIndows (XP,7,10, Server etc) is empty. No Windows OS present.

Have a look : 

![image](https://user-images.githubusercontent.com/59569096/99378143-600d0100-28c7-11eb-83fb-839e77c5e9e8.png)

It doesn't matter whether I want to install from a URL or from a local ISO image.

**Comment by KKoukiou** [comment]
Ah that's different issue. On which os are you @cheapproxies are what version of osinfo-db are you using?
If on rpm distros: $ rpm -qi osinfo-db

And can you also paste the output of the command $ osinfo-query --fields=release-date,eol-date,name os vendor="Microsoft Corporation"

I think that your osinfo-db is quite old, and does not contain Windows Server 2019. All the rest we hide, because their EOL date is more than two years old. 

Here is this command's output on my system:
```
$ osinfo-query --fields=release-date,eol-date,name os vendor="Microsoft Corporation"
 Name                                               | Release date | End of life 
----------------------------------------------------+--------------+-------------
 Microsoft Windows 1.0                              | 1985-11-20   | 2001-12-31  
 Microsoft Windows 10                               | 2015-07-29   |             
 Microsoft Windows 2.0                              | 1987-12-09   | 2001-12-31  
 Microsoft Windows 2.1                              | 1988-05-27   | 2001-12-31  
 Microsoft Windows 2000                             | 2000-02-17   | 2010-07-13  
 Microsoft Windows Server 2012                      | 2012-09-04   |             
 Microsoft Windows Server 2012 R2                   | 2013-10-18   |             
 Microsoft Windows Server 2016                      | 2017-10-17   |             
 Microsoft Windows Server 2019                      | 2018-10-02   |             
 Microsoft Windows Server 2003                      | 2003-04-24   | 2015-07-14  
 Microsoft Windows Server 2003 R2                   | 2005-12-06   | 2015-07-14  
 Microsoft Windows Server 2008                      | 2008-02-27   | 2013-07-09  
 Microsoft Windows Server 2008 R2                   | 2009-10-22   | 2013-07-09  
 Microsoft Windows 3.1                              | 1992-04-06   | 2001-12-31  
 Microsoft Windows 7                                | 2009-10-22   | 2015-01-13  
 Microsoft Windows 8                                | 2012-09-01   | 2018-01-09  
 Microsoft Windows 8.1                              | 2013-10-17   | 2018-01-09  
 Microsoft Windows 95                               | 1995-08-24   | 2001-12-13  
 Microsoft Windows 98                               | 1998-06-25   | 2006-07-11  
 Microsoft Windows Millennium Edition               | 2000-09-14   | 2006-07-11  
 Microsoft Windows NT Server 3.1                    | 1993-07-27   | 2000-12-31  
 Microsoft Windows NT Server 3.5                    | 1994-09-21   | 2001-12-31  
 Microsoft Windows NT Server 3.51                   | 1995-05-30   | 2001-12-31  
 Microsoft Windows NT Server 4.0                    | 1996-08-24   | 2004-12-31  
 Microsoft Windows Vista                            | 2006-11-30   | 2012-04-10  
 Microsoft Windows XP                               | 2001-10-25   | 2009-04-19  

```

**Comment by cheapproxies** [comment]
Hello, I use Openmediavault 5 with Debian 10. I updated the osinfo-db manually and now I get Windows Server 2019 (10.0). But I still don't have any other Windows versions to choose from. 

The output of the command osinfo-query is :

# osinfo-query --fields=release-date,eol-date,name os vendor="Microsoft Corporation"
 Name                                               | Release date | End of life
----------------------------------------------------+--------------+-------------
 Microsoft Windows 1.0                              | 1985-11-20   | 2001-12-31
 Microsoft Windows 10                               | 2015-07-29   |
 Microsoft Windows 2.0                              | 1987-12-09   | 2001-12-31
 Microsoft Windows 2.1                              | 1988-05-27   | 2001-12-31
 Microsoft Windows 2000                             | 2000-02-17   | 2010-07-13
 Microsoft Windows Server 2012                      | 2012-09-04   |
 Microsoft Windows Server 2012 R2                   | 2013-10-18   |
 Microsoft Windows Server 2016                      | 2017-10-17   |
 Microsoft Windows Server 2019                      | 2018-10-02   |
 Microsoft Windows Server 2003                      | 2003-04-24   | 2015-07-14
 Microsoft Windows Server 2003 R2                   | 2005-12-06   | 2015-07-14
 Microsoft Windows Server 2008                      | 2008-02-27   | 2013-07-09
 Microsoft Windows Server 2008 R2                   | 2009-10-22   | 2013-07-09
 Microsoft Windows 3.1                              | 1992-04-06   | 2001-12-31
 Microsoft Windows 7                                | 2009-10-22   | 2015-01-13
 Microsoft Windows 8                                | 2012-09-01   | 2018-01-09
 Microsoft Windows 8.1                              | 2013-10-17   | 2018-01-09
 Microsoft Windows 95                               | 1995-08-24   | 2001-12-13
 Microsoft Windows 98                               | 1998-06-25   | 2006-07-11
 Microsoft Windows Millennium Edition               | 2000-09-14   | 2006-07-11
 Microsoft Windows NT Server 3.1                    | 1993-07-27   | 2000-12-31
 Microsoft Windows NT Server 3.5                    | 1994-09-21   | 2001-12-31
 Microsoft Windows NT Server 3.51                   | 1995-05-30   | 2001-12-31
 Microsoft Windows NT Server 4.0                    | 1996-08-24   | 2004-12-31
 Microsoft Windows Vista                            | 2006-11-30   | 2012-04-10
 Microsoft Windows XP                               | 2001-10-25   | 2009-04-19

**Comment by cheapproxies** [comment]
@KKoukiou 

> We hide all OSes whose EOL date is older than two years ago and their RELEASE DATE is older than 3 years ago. 

Why ? What if I want to install Windows XP or Windows 7/8 as a VM, for example? Wouldn't it be better to show all systems?

**Comment by KKoukiou** [comment]
The OSes with EOL more than two years ago we decided to not show, and XP had EOL 2014. https://docs.microsoft.com/en-us/lifecycle/products/?terms=windows%20xp&products=windows
I think it makes sense, why someone would like to install an OS which is already two years not supported?

However, `osinfo-db` is missing a lot of EOL dates for windows, and needs an update, in order to show windows 10, 8 and some others. I plan to send a patch to the osinfo-db to fix your issue today.

**Comment by garrett** [comment]
> osinfo-db is missing a lot of EOL dates for windows

Are the missing EOL dates for some Windows versions due to Microsoft still supporting those versions and not having an announced EOL date so far?

I took the output of `osinfo-query --fields=release-date,eol-date,name os vendor="Microsoft Corporation"` on Fedora 33, copied the list into LibreOffice, sorted by EOL date, then Launch date, swapped the date columns and added a few computed fields:




Windows version | EOL date | Launch date | Years supported | Years since EOL | Years since Launch
-- | :-- | :-- | --: | --: | --:
NT Server 3.1 | 2000-12-31 | 1993-07-27 | 7.44 | 19.90 | 27.33
95 | 2001-12-13 | 1995-08-24 | 6.31 | 18.95 | 25.25
1 | 2001-12-31 | 1985-11-20 | 16.12 | 18.90 | 35.02
2 | 2001-12-31 | 1987-12-09 | 14.07 | 18.90 | 32.97
2.1 | 2001-12-31 | 1988-05-27 | 13.61 | 18.90 | 32.50
3.1 | 2001-12-31 | 1992-04-06 | 9.74 | 18.90 | 28.64
NT Server 3.5 | 2001-12-31 | 1994-09-21 | 7.28 | 18.90 | 26.18
NT Server 3.51 | 2001-12-31 | 1995-05-30 | 6.59 | 18.90 | 25.49
NT Server 4.0 | 2004-12-31 | 1996-08-24 | 8.36 | 15.89 | 24.25
98 | 2006-07-11 | 1998-06-25 | 8.05 | 14.37 | 22.42
Millennium Edition | 2006-07-11 | 2000-09-14 | 5.82 | 14.37 | 20.19
XP | 2009-04-19 | 2001-10-25 | 7.49 | 11.59 | 19.08
2000 | 2010-07-13 | 2000-02-17 | 10.41 | 10.36 | 20.77
Vista | 2012-04-10 | 2006-11-30 | 5.36 | 8.61 | 13.98
Server 2008 | 2013-07-09 | 2008-02-27 | 5.37 | 7.37 | 12.73
Server 2008 R2 | 2013-07-09 | 2009-10-22 | 3.72 | 7.37 | 11.08
7 | 2015-01-13 | 2009-10-22 | 5.23 | 5.85 | 11.08
Server 2003 | 2015-07-14 | 2003-04-24 | 12.23 | 5.35 | 17.58
Server 2003 R2 | 2015-07-14 | 2005-12-06 | 9.61 | 5.35 | 14.96
8 | 2018-01-09 | 2012-09-01 | 5.36 | 2.86 | 8.22
8.1 | 2018-01-09 | 2013-10-17 | 4.23 | 2.86 | 7.09
Server 2012 |   | 2012-09-04 |   |   | 8.21
Server 2012 R2 |   | 2013-10-18 |   |   | 7.09
10 |   | 2015-07-29 |   |   | 5.31
Server 2016 |   | 2017-10-17 |   |   | 3.09
Server 2019 |   | 2018-10-02 |   |   | 2.13

Support lifespan stats, in years:
- Average: 8.21
- Median: 7.44
- Maximum: 16.12
- Minimum: 3.72

But this is a little misleading, as server R2s are counted alongside the R1s. But you can see trends. And Microsoft has changed over time too. If we consider the most recent EOL'd server, Server 2003, that would probably give us a hint as to how the current server products are going to be supported. Server 2003 (including R2) was supported for over 12 years. That's probably going to be the case for 2012 (+R2) as well, and it's probably why they don't have EOL dates yet, as Server 2012 has been around for "just" 8.21 years.

So, at least in the current DB, I'm pretty sure the ones without EOL are on purpose, as Microsoft hasn't decided when to end support for them quite yet.

**Comment by KKoukiou** [comment]
osinfo-db is just a bit outdated/incomplete and does not contain all the EOL that the mcrosoft website is listing - https://docs.microsoft.com/en-us/lifecycle/products/?terms=windows%208&products=windows

For all the versions that are missing EOL in the osinfo-db I can find the dates in the microsoft website. It's just a matter of updating the osinfo-db, which is what I plan to do.

**Comment by garrett** [comment]
Ah, right; some of the support EOL dates aren't quite right.

For example, Windows 8 isn't supported any longer, but 8.1 (an update for 8) is, with an extended end date:

Listing | Start Date | Mainstream End Date | Extended End Date
-- | -- | -- | --
Windows 8.1 | 11/13/2013 | 01/09/2018 | 01/10/2023

The DB seems to have the mainstream end date only... 😐

**Comment by fidencio** [comment]
@garrett, osinfo-db maintainer here.

From our side we don't have the distinction of a mainstream and extended EOL date.  I do believe using the Extended End Date is the most correct approach, indeed.

I'm looking forward to reviewing @KKoukiou patches improving the Windows situation!

**Comment by KKoukiou** [comment]
@fidencio @cheapproxies I send the PR, https://gitlab.com/libosinfo/osinfo-db/-/merge_requests/250

So now it's just about that one getting merged and released and reaching the distros.
Cockpit-machines has nothing to do with this process, so @cheapproxies if you don't mind I will close the issue, and you can follow the updates on osinfo-db package.

**Comment by cheapproxies** [comment]
Thank you. The osinfo-db update brings Windows 10, 8.1 etc back to the list 👍

**Comment by 1-1-2** [comment]
> I use Openmediavault 5 with Debian 10. I updated the osinfo-db manually...

Running the same OS on my system. May I ask how to upgrade to the latest osinfo-db on debian 10? I use `apt -y upgrade osinfo-db` and I was told that the latest version was 20181120.

```
>> apt -y upgrade osinfo-db
Reading package lists... Done
Building dependency tree
Reading state information... Done
osinfo-db is already the newest version (0.20181120-1+deb10u1).
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  libpapi5.7 libpcp-gui2 libpcp-import1 libpcp-mmv1 libpcp-pmda-perl libpcp-pmda3 libpcp-trace2 libpcp-web1 libpcp3
  libpfm4 linux-image-5.7.0-0.bpo.2-amd64 pcp pcp-conf python3-pcp
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by fidencio** [comment]
@1-1-2, you can manually update osinfo-db by doing:
```
$ curl -O https://releases.pagure.org/libosinfo/osinfo-db-20210312.tar.xz
$ sudo osinfo-db-import --local  osinfo-db-20210312.tar.xz
```

This will install the newest database in `/etc/osinfo`, which has precedence when the db is loaded by the apps.

When doing this, please, also file a bug on debian so the distro can also step up and update osinfo-db as part of their patch releases.

**Comment by 1-1-2** [comment]
@fidencio It works. Thanks a lot!

**Comment by sonofwatt** [comment]
Running OMV5 (Debian) and executed "apt-get install -y libosinfo-bin"
When I run 
> osinfo-query --fields=release-date,eol-date,name os vendor="Microsoft Corporation"

It correctly shows Win 10 in the list. But in Cockpit it's not listed in the Create VM > Operating System, list.
I also ran 
> $ curl -O https://releases.pagure.org/libosinfo/osinfo-db-20210312.tar.xz
> $ sudo osinfo-db-import --local  osinfo-db-20210312.tar.xz

The .tar download works, but got the following error when running the 2nd command. "-bash: osinfo-db-import: command not found".

How do I get that list to update in Cockpit?

**Comment by fidencio** [comment]
@sonofwatt, you need `osinfo-db-tools` installed as well.

**Comment by sonofwatt** [comment]
@fidencio thank you!

**Comment by ffrediani** [comment]
I can confirm I have the same problem reported in the image above which doesn't show any Windows type OSes.
Fresh new installation of Ubuntu 20.04 LTS with Cockpit-machines 215-1 and it only show Linux and FreeBSD related types under Operating System.

Have also updated the osinfo-db and confirmed with the osinfo-query commando it has the Windows. It is just the cockpit-machines that doesn't show them.

Have updated the osinfo with the command on  #14904 but it still doesn't show the Windows OS types.

Is there any manual way to fix this ?

**Comment by KKoukiou** [comment]
@ffrediani your version of cockpit-machines is also very old, https://github.com/cockpit-project/cockpit/releases/tag/215 (one y ago :)). There have been many fixes till then, try installing a newer one from backports.


Check the ubuntu section here https://cockpit-project.org/running

**Comment by ffrediani** [comment]
@KKoukiou but does the problem described has any relation with the this specific older version ?

Have upgraded to 250-1 using backports but still it doesn't show any Windows OS type VMs when creating a new one. Do you think is there still something to be fixed in the cockpit-machine modules or in any other OS package which is depends on ?

**Comment by KKoukiou** [comment]
With the updated cockpit-machines (250 is fine) and osinfo-db > 20210312 you should have the WIndows OSes appearing in the Os fields in all options for the installation source, apart from the 'Download an OS'. If this is not true, please paste here the version of:
cockpit-machines
osinfo-db
Screenshot of the Create dialog  with the fields you try to input apart from the OS.

**Comment by olegstepura** [comment]
> I think it makes sense, why someone would like to install an OS which is already two years not supported?

Hi, @KKoukiou! Imagine someone would like to test how their software runs on an outdated version of OS. This is still a vlid use-case. There might be a setting somewhere to hide/show list of outdated OS version. But deciding for all users without providing them a way to reenable looks too much opinionated.

**Comment by ffrediani** [comment]
Exactly @olegstepura 
The important thing is that the virtualization technology supports and run it fine.
It should not be much of a concern of the orchestration layer the reasons the user is bringing up an old operating system and its associated security concerns, but his own.
There cases of legacy systems that are still in use and need to be kept running in that host until upgrade to newer versions for example.

**Comment by garrett** [comment]
The EOL OS discussion is continued in https://github.com/cockpit-project/cockpit-machines/issues/509 specifically about EOL operating systems (more than just Windows). Please visit that issue and click the subscribe button (on the sidebar on the right) if you'd like to follow along or leave a comment if you have something to add. Thanks!

Quick summary of that issue: @KKoukiou mentioned that we could have an expander to including EOL in the list when browsing and I suggested that searching should additionally show them. And I also said that we need to note that when the vendor has stopped supporting the OS, and it would be a good idea to include when too.

It's a very bad idea to use an expired OS that no longer gets security fixes, as every EOL OS will definitely have security issues in the wild. So, if you must use an expired OS, you prevent it from having network access, I guess? But we could still show them in the list and searches, as long as we're clear they're no longer updated... and you should proceed with caution.

(I can only think of a few specific additional reasons why someone wants to run an old OS: 1. Seeing what someone else sees when they're on an old OS, like for browsers that are no longer supported, such as IE and old EdgeHTML-based Edge. 2. Supporting offline OSes that are embedded in devices, such as medical devices that ship with ancient version of Windows... that really hopefully aren't on any network. But those are valid uses of wanting to run a old OS in a VM, and I guess we should allow it, hence the ongoing discussion.)

Thanks for everyone's input on the issue here!

**Comment by kyouji-kuroya** [comment]
![image](https://user-images.githubusercontent.com/5319377/157633010-ff16dd59-4a73-4ce9-bb85-3f592bfcb302.png)
I can't create a Windows VM with cockpit-machines either.
I am using the following version of osinfo and have already imported osinfo-db-20210312.tar.xz.
![image](https://user-images.githubusercontent.com/5319377/157632814-1bf339d1-cafc-4df8-8a55-14270e6c86b5.png)
After importing osinfo-db, Fedora Silverblue is newly displayed, so it should be able to read osinfo, but only Windows is not displayed.
![image](https://user-images.githubusercontent.com/5319377/157634032-ad726c05-13da-4a7a-a9c4-0f1f07dcac71.png)

(This text was translated from Japanese to English using DeepL.)

**Comment by aldoexpert** [comment]
**Cockpit-Project is supported windows lists**
This to install in fresh Ubuntu 20.04
```
# apt install cockpit -y
# apt install cockpit-machines -y
# apt install libosinfo-bin -y
# apt upgrade osinfo-db -y
# apt install osinfo-db-tools -y
# curl -O https://releases.pagure.org/libosinfo/osinfo-db-20210312.tar.xz
# osinfo-db-import --local  osinfo-db-20210312.tar.xz
# systemctl restart cockpit
# systemctl status cockpit
```
Open browser url to
https://hostname_or_ip:9090

![Screen Shot 2022-03-23 at 07 08 05](https://user-images.githubusercontent.com/6316711/159597070-72b7bca8-26ac-410b-a926-eb1e5fa9781c.png)

**Comment by garrett** [comment]
>  This to install in fresh Ubuntu 20.04

By the way: That's a very old version of Cockpit. You should be aware there is a much newer version of Cockpit available for you, even on Ubuntu LTS (and Debian Stable too), if you want it, by way of backports, which let you use some newer software on older releases:

https://cockpit-project.org/running.html#ubuntu

If you want to keep using an old version of Cockpit for now, then you could skip the backports and wait for 22.04, which should show up in a month (likely 2022-04-21) and then you could upgrade everything when you'd like.

Note: There _isn't_ a newer version of osinfo-db in backports, however, so [the instructions above](https://github.com/cockpit-project/cockpit/issues/14904#issuecomment-1075772630) are still useful for osinfo-db regardless of your version of Cockpit. 

Note 2: The backports version has a bunch of new features and bugfixes, but we did deprecate and remove the dashboard page a long while ago, so that will go away when you upgrade (either with backports or with the new LTS when it comes out). The replacement, if you use the dashboard, is to [set up Grafana using PCP, which Cockpit helps you set up](https://cockpit-project.org/blog/pcp-grafana.html).

**Comment by ZacTyAdams** [comment]
When trying to install any version of Windows 10 to cockpit machines running on the latest Ubuntu Jammy backport I'm getting BSOD errors. Any idea on what I'm doing wrong or if standard desktop Windows 10 versions aren't supported?
![image](https://user-images.githubusercontent.com/6806769/200668075-77f87e8a-9192-4682-962b-3d13a216c3c3.png)

the error is SYSTEM_THREAD_EXCEPTION_NOT_HANDLED

**Comment by garrett** [comment]
BTW, just in case anyone comes across this post and has the same issue as the previous comment: @ZacTyAdams filed this as an issue (thanks!) @ https://github.com/cockpit-project/cockpit-machines/issues/851 and then closed, as the problem was that a system update flipped support for VMs off in the BIOS:

> Sorry, my virtualization turned off during a recent bios update. If anyone comes across this double check your virtualization was turned on using sudo kvm-ok

(https://m.xkcd.com/979/ prevention)

**Comment by ZacTyAdams** [comment]
@garrett Yeah sorry about the double post here, I found the specific cockpit-machines repo after posting here. 


Although I guess Linux machines were installing and still starting correctly without virtualization enabled you absolutely need virtualization enabled when trying to install and run Windows 10. You can use `sudo kvm-ok` to make sure you've enabled the right setting in your bios and try using raw for your disk instead of qcow2. Also if you're on a backport installation make sure the cockpit-machines package is actually up-to-date,[ you have to manually update packages unless you enabled automatic updates from backport.](https://help.ubuntu.com/community/UbuntuBackports)
