### ISSUE TITLE
Credentials not saved

### ISSUE THREAD

**Issue by hyprem** [cockpit-project/cockpit#14914]
Hi

I started using Cockpit today and found it very helpful. I just have one big issue. All my Linux Server has different passwords but the same users. When I add the Servers and save the credentials it works until the next logout. When I log in i will uncheck use my crdentials for admin tasks. What is the the normal behavior on this? Do I need to set the same username on all Systems to access it?

**Comment by mvollmer** [comment]
> All my Linux Server has different passwords but the same users. When I add the Servers and save the credentials it works until the next logout. 

This is the expected behavior.  Cockpit does not store credentials permanently and for each new session, you thus need to log into each remote server again.

If you don't want to type your passwords every time, it is recommended to set up SSH keys.  Newer versions of Cockpit can help you with this, see [the release notes for version 228](https://cockpit-project.org/blog/cockpit-228.html).

What version of Cockpit are you using?

**Comment by hyprem** [comment]
Thanks for your reply. I first have to see how to get the latest Version of Cockpit since in my fresh Install of Ubuntu 20 it installs version 215 and we are running on 232. I will need to find out why I get an outdated version first then try this on the new version and check out the section of the ssh keys you mentioned. Thanks. Maybe any tips on getting the latest cockpit version on ubuntu 20? I have seen something about different mirrors but these are for Ubuntu 18.04

Cheers

**Comment by mvollmer** [comment]
> Now i am seeing the ssh key options you mentioned. Thanks

Great!

**Comment by martinpitt** [comment]
Correct -- also see https://help.ubuntu.com/community/UbuntuBackports#Enabling_Backports
