### ISSUE TITLE
Cockpit doesn't open in Firefox 83

### ISSUE THREAD

**Issue by maruns** [cockpit-project/cockpit#14936]
Cockpit version: 
cockpit.x86_64 211.3-1.el8 @BaseOS
OS: Centos 8
Page: All pages

When I open my cockpit installation in Firefox 83.0 it fails to load main page (not even menu shows up) or loads a page but content is blank or reports "Server has closed the connection." or something in between like partially loaded page (some data are loaded and some not).

In developer tools you will see thousands of messages like

```
Too many calls to Location or History APIs within a short timeframe.
```
along with
```
Uncaught DOMException: The operation is insecure.
```
```
 can't get NTPSynchronized property {
  "problem": "disconnected",
  "name": null,
  "message": "Server has closed the connection."
}
```

Chrome shows quite a few 

```
index.js:72 Uncaught DOMException: Blocked a frame with origin "https://10.0.0.2:9090" from accessing a cross-origin frame
```

Steps to reproduce

1. Open Cockpit in Firefox 83

I suspect the source of an issue is a change in Firefox 83. 
- [Firefox CVE-2020-26963 release note](https://www.mozilla.org/en-US/security/advisories/mfsa2020-50/#CVE-2020-26963)
- [Firefox bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1314912)

![Zrzut ekranu z 2020-11-20 23-48-01](https://user-images.githubusercontent.com/1474085/99857329-44398180-2b8b-11eb-9764-10edb518bda3.png)
![Zrzut ekranu z 2020-11-20 23-48-44](https://user-images.githubusercontent.com/1474085/99857331-44d21800-2b8b-11eb-9fce-7f321fee0d3d.png)
![Zrzut ekranu z 2020-11-20 23-49-35](https://user-images.githubusercontent.com/1474085/99857333-456aae80-2b8b-11eb-9d93-5abed1d235b7.png)

**Comment by marusak** [comment]
I am also using firefox 83.0 and works fine, so there must be something more to this than just a new version of Firefox.

> Too many calls to Location or History APIs within a short timeframe.

This is far from great. Our CI sees this, but I never saw this in real life. To confirm/rule out this one, can you please set `dom.navigation.locationChangeRateLimit.count` to `9999` in `about:config` page? 

> Uncaught DOMException: The operation is insecure.

This one though smells like the reason for Oops. Is there traceback for this?

Is chrome working fine for you? If so, then it is worth looking if you have some plugins in your firefox and disabling them and see if it fixes the issue.

**Comment by maruns** [comment]
> I am also using firefox 83.0 and works fine, so there must be something more to this than just a new version of Firefox.
>
>> Too many calls to Location or History APIs within a short timeframe.
>
> This is far from great. Our CI sees this, but I never saw this in real life. To confirm/rule out this one, can you please set dom.navigation.locationChangeRateLimit.count to 9999 in about:config page?

After updating it to a 9999 cockpit loaded fine and worked.  When I reverted it back to default (200) it started crashing. For my computer around 500-540 is a place where it becomes a grey zone. Where it sometimes works and sometimes not. 



>>    Uncaught DOMException: The operation is insecure.
>
> This one though smells like the reason for Oops. Is there traceback for this?

```
Uncaught DOMException: The operation is insecure. index.js:72
    jump https://10.0.0.2:9090/cockpit/$23e273445615a6833622f41e71ea1d72df5a629b915f2a7ee80ea82300a5aa6a/shell/index.js:72
    v https://10.0.0.2:9090/cockpit/$23e273445615a6833622f41e71ea1d72df5a629b915f2a7ee80ea82300a5aa6a/shell/index.js:72
    ho https://10.0.0.2:9090/cockpit/$23e273445615a6833622f41e71ea1d72df5a629b915f2a7ee80ea82300a5aa6a/shell/index.js:72
    jQuery 4
    p https://10.0.0.2:9090/cockpit/$23e273445615a6833622f41e71ea1d72df5a629b915f2a7ee80ea82300a5aa6a/shell/index.js:72
    overlay https://10.0.0.2:9090/cockpit/$23e273445615a6833622f41e71ea1d72df5a629b915f2a7ee80ea82300a5aa6a/shell/index.js:72
    g https://10.0.0.2:9090/cockpit/$23e273445615a6833622f41e71ea1d72df5a629b915f2a7ee80ea82300a5aa6a/shell/index.js:72
    r https://10.0.0.2:9090/cockpit/$23e273445615a6833622f41e71ea1d72df5a629b915f2a7ee80ea82300a5aa6a/base1/cockpit.js:2487
    n https://10.0.0.2:9090/cockpit/$23e273445615a6833622f41e71ea1d72df5a629b915f2a7ee80ea82300a5aa6a/base1/cockpit.js:897
```

It's best I have for now. If it's not enought I might try to run cockpit from sources during next weekend. 

> Is chrome working fine for you? If so, then it is worth looking if you have some plugins in your firefox and disabling them and see if it fixes the issue.

Chrome is working. To check if plugins are affecting my firefox I've rerun the tests in new profile and issue is still there.

**Comment by winsmith** [comment]
For me, this error occurred as I was adding a 7th machine to my dashboard. I use the multi-server dashboard, and with 6 or less machines, the error never occurred. Adding a 5th and 6th machine to my cluster triggered the error occasionally, and now with 7 machines the error is constant so that I can't even use the dashboard any more.

**Comment by marusak** [comment]
@winsmith dashboard is not supported anymore. By any chance can you update and use integrated host switcher and see if it still has the same issue?

**Comment by marusak** [comment]
Ant update @winsmith or @maruns

**Comment by garrett** [comment]
Latest versions of the software mentioned in this issue, at the time of writing:

- Firefox: 96.0.2
- Cockpit: 261
- CentOS: Stream 8 & Stream 9 (CentOS Linux 8 has been EOL since December)

To upgrade from CentOS Linux 8 to CentOS Stream 8 it's as easy as these three commands:

```sh
dnf swap centos-linux-repos centos-stream-repos
dnf distro-sync   
```

After that, reboot and you'll be on CentOS Stream 8 instead.

There's not much of a difference between using CentOS Linux 8 and CentOS Stream 8. The big difference between CentOS Linux and CentOS Stream is basically that CentOS now feeds into RHEL instead of RHEL feeding into CentOS, so you'd get updates a little _before_ they land in RHEL instead of after. That's really mainly it. The placement allows people outside Red Hat more directly affect RHEL by making changes in CentOS, which is a great benefit to the change. Details are listed @ https://centos.org/cl-vs-cs/

As for the dashboard, there's a single machine replacement built in on the metrics page, there's a host switcher built into the navigation of Cockpit (at the top-left), and for aggregated metrics, we have implemented some features to help you use Cockpit with Grafana instead: https://cockpit-project.org/blog/pcp-grafana.html (Grafana is a much better solution than our old dashboard for all sorts of reasons. It scales better, is more customizable, and displays metrics better than our old dashboard did.)

**Comment by marusak** [comment]
No reply for a while so closing
