### ISSUE TITLE
Cockpit can't create Networks

### ISSUE THREAD

**Issue by cheapproxies** [cockpit-project/cockpit#14942]
Hello,

i have the problem that i cannot create a network with Cockpit. No matter what I try, a LAN bridge or NAT is not working with the error message : internal error: Network is already in use by interface eno1.

My system is freshly installed with Openmediavault 5.

I only installed Docker with a macvlan and a Docker Container with Portainer and Adguard Home. This works so far. The Adguard Home is accessible as DNS in the network.

I have tried every tutorial found on google, but I can't get the network running in Cockpit.

Does anyone have a solution for this problem and can help me ?

Thanks a lot.

**Comment by marusak** [comment]
> `Network is already in use by interface eno1.`

That sounds like you try to create network, that already exists.
Can you post screenshot of network page and of the dialog, when you see the error? Thanks.

**Comment by KKoukiou** [comment]
I think @cheapproxies means Virtual Networks (in machines page).

**Comment by skobyda** [comment]
Hello @cheapproxies , if you are talking about virtual networks in machines page, then this error message usually happens when there is already a virtual network with same address and has nothing to do with forward mode. For example if you are trying to create a virtual network with an address 192.168.100.xxx/24, that error message can mean that there already is a network with same address. Can you check if this is the case and try other address?

**Comment by KKoukiou** [comment]
@cheapproxies you can also paste the XMLs of all your libvirt networks here, and @skobyda can help you figure out where the colision is happening.

**Comment by marusak** [comment]
No reply, closing. Please feel free to reopen and provide required data. Thanks.
