### ISSUE TITLE
Unit tests are not triggered on PRs opened by workflows

### ISSUE THREAD

**Issue by marusak** [cockpit-project/cockpit#14941]
For example npm updates on po-refreshes don't get unit tests triggered. But these are required, thus block merging.

See https://github.com/peter-evans/create-pull-request/issues/48

So this is "by design" (a bit shitty design as it prevents from using github actions for full blown integration) but there are workarounds mentioned in the aforementioned issue. We need to adopt one of those.

**Comment by marusak** [comment]
https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#workarounds-to-trigger-further-workflow-runs

list of possible workarounds

**Comment by marusak** [comment]
@martinpitt do you have you favorite workaround?

**Comment by martinpitt** [comment]
@marusak: My preferred solution would be to use `secrets.COCKPITUOUS_TOKEN` instead of `secrets.GITHUB_TOKEN`. po-refresh already uses our token anyway to be able to push to weblate. That's simple, and what we had before. It indeed goes back from "zero secrets management" to "manage one PAT", but as this is by design we just have to live with that.
