### ISSUE TITLE
TestMetrics.testBasic flaky depending on time of day

### ISSUE THREAD

**Issue by allisonkarlitskaya** [cockpit-project/cockpit#14950]
I noticed a bunch of `TestMetrics.testBasic` fails lately.  They're caused by the time when you run the tests.

Here are some examples:

 * running the tests on a VM that booted in a different day will result in bad behaviour when selecting "yesterday" to ensure that there is nothing there.  For example, if a VM boots at 23:55 and the test runs at 00:05.  We can see this assumption in a comment in the tests:  `# VM just started, we don't have 12 hours of data`.  nondestructive tests with long-running VMs make this more likely to be untrue.

This results in us getting the wrong "No data available" message, and failing an assert.  We expect:
```
        b.wait_text(".pf-c-empty-state", "No data available")
```
but we actually get the one with `.metrics .pf-c-alert` with the "No data available between ..." (plus timestamps).  This is visible in many screenshots from failing tests, eg https://logs.cockpit-project.org/logs/pull-14856-20201123-235121-0e05ba38-debian-stable/TestMetrics-testBasic-debian-stable-127.0.0.2-2601-FAIL.png

That's from the pretty complicated logic:
```
        if (!this.state.loading && this.state.hours.length > 0 && this.oldest_timestamp < this.state.hours[this.state.hours.length - 1]) {
[snip]
            nodata_alert = <Alert className="nodata" variant="info" isInline title={ cockpit.format(_("No data available between $0 and $1"), t1, t2) } />;
        }
        if (!this.state.loading && this.state.hours.length === 0)
            nodata_alert = <EmptyStatePanel icon={ExclamationCircleIcon} title={_("No data available")} />;
```

 * running the tests at an hour boundary can cause issues, for example, adding a `sit()` here:

```
        # clean slate, to avoid seeing the data from preparing the VM
        m.execute("systemctl stop pmlogger; rm -rf /var/log/pcp/pmlogger/*; systemctl start pmlogger")

        sit() # <========

        login(self)
        # eventually finishes data loading and shows heading
        b.wait_in_text(".metrics-history-heading", "CPU")
        b.wait_present(".metrics-hour .metrics-data-cpu")

        # only shows current hour
        b.wait_js_func("ph_count_check", ".metrics-hour", 1)
```

and setting your clock to [something]:59 before running the tests and waiting at the `sit()` until the "new hour" will result in a reliable fail.

**Comment by marusak** [comment]
Nice, thank you for the analysis @allisonkarlitskaya !

Mind you, this test is destructive, so the VM is booted just for this test. There is no " nondestructive tests with long-running VMs make this more likely to be untrue."

> running the tests on a VM that booted in a different day will result in bad behaviour when selecting "yesterday" to ensure that there is nothing there.

This is indeed a valid failure. I think we can just select day before yesterday and that should do it.

> running the tests at an hour boundary can cause issues, for example, adding a sit() here:

I think I see the problem here as well. Your reproducer is misleading, because by making it sit, you make the test run for longer then it in any case would. But it indeed might happen, somewhat more reliable reproducer would be:
```
--- test/verify/check-metrics
+++ test/verify/check-metrics
@@ -92,12 +92,18 @@ class TestMetrics(MachineCase):
         b = self.browser
         m = self.machine
 
+        m.execute("timedatectl set-ntp off")
+        m.execute("while systemctl is-active systemd-timesyncd; do sleep 1; done")
+        m.execute("timedatectl set-time '2020-11-24 00:59:52'")
+
         # clean slate, to avoid seeing the data from preparing the VM
         m.execute("systemctl stop pmlogger; rm -rf /var/log/pcp/pmlogger/*; systemctl start pmlogger")
+        time.sleep(4)
 
         login(self)
         # eventually finishes data loading and shows heading
         b.wait_in_text(".metrics-history-heading", "CPU")
+        time.sleep(4)
```
as some of those waits may wait up to 5s and then it fails reliably as well.
Making this test flake-free we would need a bunch of hack like "show one or two hours" or "show between 2 to 4 minutes" of data... Maybe better fix for both would be just to set up system time to something like "09:24:00" in which case we are safe for minutes, hours or days changes. And since the test is destructive, setting up time if harmless.
