### ISSUE TITLE
machines: 'Delete' button of snapshot will go off the screen when inputting long strings to 'Description' of snapshot creation dialog 

### ISSUE THREAD

**Issue by yunmingyang** [cockpit-project/cockpit#14966]
Cockpit version: 232
OS: fedora 33
Page: Machines

Description
'Delete' button of snapshot will go off the screen when inputting long strings to 'Description' of snapshot creation dialog 

Steps to reproduce
1. Prepare a VM and go to the VM detail page
2. Open the snapshot dialog of the VM, then input name and a long string(a length  297 String) for 'Description', then create. 
![image](https://user-images.githubusercontent.com/25657472/100339621-0d44ef00-3015-11eb-806d-42cdb5e5d7ff.png)

**Comment by KKoukiou** [comment]
This only happens when the description has a single word *without* spaces. If it's a normal sentence with spaces it wraps normally.
![Screen Shot 2020-12-07 at 16 40 19](https://user-images.githubusercontent.com/14921356/101371421-033fad80-38ab-11eb-835d-7e313416a6b8.png)

I think this is a corner case that we should not really care about. PF deals with the wrapping of table columns, and I don't think this worths to be reported to them or fixed in our code with an override.

**Comment by garrett** [comment]
@KKoukiou and I talked about this in IRC and I pointed out https://www.patternfly.org/v4/components/table/react/#controlling-text — where cellTransforms: [breakWord] /  transforms: [wrappable] / and other such things are possible by changing settings in the table header and data.

If one of the options provided can fix this bug without regressions, I'd say go for it.  Or we could have it overflow with ellipsis in the too-long-string case, if that's another option. (I know it's an option for some parts of PF, but not sure if it is for table cells.)
