### ISSUE TITLE
cockpit-docker: Missing jquery.js?

### ISSUE THREAD

**Issue by 82ghost82** [cockpit-project/cockpit#14979]
Cockpit version: 233.1-1
OS: Manjaro Architect 20.2

If I click on Docker Containers on the left menu the browser shows a red "Ooops" in the top right corner.
All other pages are working correctly for me, this apply only to Docker page.
By analyzing the browser console it seems jquery.js is missing.
I copied jquery.js from the official external source into /usr/share/cockpit/base1/ and the issue is now solved.

**Comment by 82ghost82** [comment]
Probably the same as:
https://github.com/cockpit-project/cockpit/issues/14974

**Comment by martinpitt** [comment]
@82ghost82 : As you managed to install an older version of cockpit-docker, please install an older version (< 233) of cockpit-system to avoid that.

For upstream, let's add another conflicts like in commit 23fadbd9b2 to avoid broken partial upgrades.

**Comment by mvollmer** [comment]
> I copied jquery.js from the official external source into /usr/share/cockpit/base1/ and the issue is now solved.

That sounds like a good workaround for now.  The jquery.js file was removed in Cockpit 233 and current Cockpit packages have been updated accordingly.

But since the cockpit-docker package is no longer maintained by us, it didn't get fixed.  (Cockpit-docker was dropped with the Cockpit 215 release in March 2020.)

You really shouldn't be using the unmaintained cockpit-docker anymore... If you can, switch to cockpit-podman.

**Comment by martinpitt** [comment]
Sent PR #14987 to fix that.

**Comment by marusak** [comment]
And also, if possible, please use [cockpit-podman](https://github.com/cockpit-project/cockpit-podman/) if possible as `cockpit-docker` was obsoleted some time ago and is not supported anymore.

**Comment by 82ghost82** [comment]
Thank you all, I just did as you suggested about cockpit-docker/cockpit-podman.
I just reinstalled the OS and installed cockpit from manjaro stable repository and I have no more any problem.
