### ISSUE TITLE
The side panel actions in storage page need some CSS help

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit#14973]
Page: storage
![Screen Shot 2020-11-24 at 19 20 40](https://user-images.githubusercontent.com/14921356/100371001-70c82000-3007-11eb-86cf-9309be2af82b.png)

At least on my laptop screen size it looks like this.

**Comment by garrett** [comment]
Meanwhile, my page looks like this:

![Screenshot_2020-12-09 Storage - garrett Rain](https://user-images.githubusercontent.com/10246/101646295-a291ab80-3a37-11eb-872e-5ec80ec46db1.png)

I don't even know how to recreate that.

**Comment by garrett** [comment]
OK, on IRC, @KKoukiou and @marusak helped me figure out how to run the tests to get a "fake" iSCSI device visible in a VM:

Edit the test to add a `sit()` (in Python) in the respective test. In this case, it's line 93 in `test/verify/check-storage-iscsi`.

Then, run this:

```sh
TEST_SHOW_BROWSER=1 test/verify/check-storage-iscsi
```

(More docs on testing are @ https://cockpit-project.org/external/source/test/README)

And a Chromium window should pop up and show the right page. (The same URL can be accessed by other browsers while the test is running.)

**Comment by garrett** [comment]
I haven't figured this out yet. Today was mainly a communication day, with meetings, design-related work, release notes editing, and so on. I hoped to get around to this.

Anyway, I have spent _some_ time today on this, but it's a mess.

1. The storage page is using a Bootstrap-style 12-column grid and the values don't play well with the sidebar.
   - The main list is too wide, not providing enough width to the right side. It should be wider. Bumping the main down by 1 and the side up by 1 helps.
2. There seems to be a negative margin applied _somewhere_ to the button. Or its container. Or something?
3. The button is PF3. Or at least the icon is?
4. The list is a table and it probably shouldn't be? Or is this a PF4 list widget rendering to a table?
5. There's an overflow hidden there for some reason?
6. There's some absolute positioning?! I think it's on a pseudo-element, but... still?
7. I had something that kind of fixed it in-browser but I lost it on accident.

Anyway, this is enough for this week. I'll look more into it next week. And I'll look at the generation code too. I mainly have been poking at it in-browser to try to understand what's going on. Perhaps I'm doing this backwards for this bug. (It _usually_ works, but this is a bit complex.)

I think this is a side effect of directly porting BS (Bootstrap) code from PF3 to PF4 w/o re-thinking the widgets used, mixed with some legacy CSS that just shouldn't be there anymore.

(TL;DR: The problem is harder than it looks.)

Hopefully I can look more into this next week and come up with a good solution.
