### ISSUE TITLE
machines: allow user to choose location for guest image storage

### ISSUE THREAD

**Issue by flmaxey** [cockpit-project/cockpit#15079]
When installing a guest, default storage for the guest OS in on the boot drive under /var/lib/libvirt/images

Since I'm booting an Openmediavault server with a 16GB thumbdrive, it would be helpful to be able to relocate guest image storage to a data drive.

Thanks

**Comment by KKoukiou** [comment]
@flmaxey what you ask makes sense, there is already a way to do that however. 

Note: The original libvirt documentation gives an overview of how to do that from the CLI, see https://wiki.libvirt.org/page/Tips#Adding_an_alternative_storage_pool, here I will give you the steps of how to do that from the UI.

1. Go to Storage Pools subpage and find the 'default' storage pool on system connection, click the toggle button to expand the row.
![Screen Shot 2021-01-04 at 11 25 16](https://user-images.githubusercontent.com/14921356/103525595-c0f49680-4e7f-11eb-89bc-0bb02ea67083.png)

2. On the expanded row of the window, click on the 'Deactivate' button, which will stop the default storage pool. Once the pool is stopped, click on the 'Delete' button, which will delete the pool. Note that this action will NOT remove the VM images inside the pool.

3. Now click 'Create storage pool' button to add a new storage pool.
![Screen Shot 2021-01-04 at 11 30 06](https://user-images.githubusercontent.com/14921356/103525883-437d5600-4e80-11eb-8b7b-2a24e66e21ab.png)

Type in the name of a new storage pool (e.g., default), and choose the type of the pool. In this case, choose a “Filesystem directory” type since you are just changing a storage pool directory and point to the directory of the mounted thumbdrive.

At this point, the new storage pool should be started, and automatically used when you create a new VM.
