### ISSUE TITLE
Selecting a service in the logs ui gets slower as the amount of logs grow

### ISSUE THREAD

**Issue by xhalo32** [cockpit-project/cockpit#15085]
Cockpit version: 215
OS: `Linux beta 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

Going to the logs ui and selecting the service causes high CPU usage and a significantly long loading period when a large amount of system logs (1.2GB in my case) are present. The selected time span does not make a difference to the time it takes to fetch all the logs. The command which is using all of the cpu when clicking the service dropdown menu is:
```shell
journalctl -q --no-tail --output=verbose --reverse -- PRIORITY=0 PRIORITY=1 PRIORITY=2 PRIORITY=3 PRIORITY=4 PRIORITY=5 PRIORITY=6 PRIORITY=7
```

Steps to reproduce

1. Set up a cockpit server and wait for the server's logs to grow to a few GBs.
2. Go to the logs part of the cockpit ui (`/system/logs`)
3. Click on the service drop down menu and observe that it takes a while to finish loading

Screeshot of the dropdown menu when it's loading:
![image](https://user-images.githubusercontent.com/15152190/103467826-c35dd000-4d5b-11eb-8429-c0eca97441b3.png)

**Comment by martinpitt** [comment]
I'm afraid that we have no control over how long `journalctl` itself takes to find logs. The journal has "traditionally" been quite slow, as it just takes time to sift through gigabytes of logs, particularly on rotating disks. However, it really should get better if you select "current boot" or "last  24 hours" in the top left "time" selector. Can you confirm that?

@marusak, @mvollmer: IMHO our default to show so much available logs is a bit misfortunate. It also takes a while here, makes the page slow and bulky. Today I get logs up to December 17, so it roughly looks like we are showing 14 days by default? My on-disk journal goes back to Oct 27, so we at least don't show *all* logs by default. But maybe defaulting to 24 hours is enough, and we have the "Load earlier entries"/time selector as well?

**Comment by martinpitt** [comment]
@xhalo32 : Note that also cockpit 215 is quite old, and the Services page was much improved since then.

**Comment by marusak** [comment]
Ok, let me explain.
We show only 5000 logs by default. Then you can click `Load earlier entries` to load 1000 more. If your log files are > 1GB, you most likely have there hundred thousands or millions of entries.
The service dropdown on logs page however reads through all the logs to find all possible services. Therefore it takes so much longer. It of course accepts all filters user uses like boot, since, priority... but only those time restrictions help here - which by default none is used. That is a bit misfortune I guess.

> maybe defaulting to 24 hours is enough

With the default `err` priority I would get ~20 logs per day. So I would say we can probably show even more. And possibly do `--since -72h --limit 5000` to be on a safe side. That would speed up also this services loading on the default page.

A good argument is, that it is very unlikely you would go to the page and just scroll through 4500 lines. You would use search option, so the default is mostly about "show if something interesting happened in last few lines".

**Comment by marusak** [comment]
I suggest introducing new preset called `Last 3 days` and make it default option. Marking as `good first issue`.
