### ISSUE TITLE
Provide the ca.key to be able to self-sign certificates in order to be validated by the correspondent ca.cert provided, please

### ISSUE THREAD

**Issue by q2dg** [cockpit-project/cockpit#15270]
Hello.

I'm using Fedora 33 and, by default, inside "/etc/cockpit/ws-certs.d" folder there's is a file called "0-self-signed-ca.pem", which I infer it's the ca's root-certificate I should import inside browser's ca's root-certificate list in order to accept the self-signed "0-self-signed.cert" Cockpit's certificate without warnings. 

But when I do this and then I want to log in into Cockpit, I get an error SSL_ERROR_BAD_CERT_DOMAIN from browser because, as it is explained in error message, self-signed certificate is only valid for "localhost.localdomain", "localhost" and "127.0.0.1" and not for the facing IP/name my Cockpit server really has. So I infer I should rebuild another self-certificate to get right. But to be able to do this, I need the ca's private key corresponding to the ca's root-certificate provided in order to sign this new self-certificate, and I can't get this file from anywhere. 

Maybe am I missing something?

Thanks!!

**Comment by martinpitt** [comment]
The secret key doesn't actually exist -- sscg destroys it right after creating the self-signed cert.

The self-signed cert is really mostly a crutch to at least not completely break TLS. If you want to use cockpit remotely through TLS (instead of SSH), I really recommend to ditch the self-signed cert, and [use a real one](https://cockpit-project.org/guide/latest/https.html#https-certificates): LetsEncrypt or another provider, use certmonger, or join the machine to a FreeIPA domain (then cockpit requests a cert from the IPA server), or put cockpit behind a [reverse proxy](https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-NGINX) and let that do the TLS termination.
