### ISSUE TITLE
ActiveDirectory / LDAP how to turn off automatic login to cockpit

### ISSUE THREAD

**Issue by mariuszkopowski** [cockpit-project/cockpit#15309]
Hi 
I have fallowing issue. I'm have multiple server running CENTOS 7 and Oracle Linux 8. Each of them is added to Active Directory to allow for user authentication for the same users etc.

The problem is that as a standard Admin access is done on separate users (not the one that we use every day). What is happening that after joining server to domain and opening cockpit in a browser as a standard it log in a user that is running a browser. And by default this should not be allowed and each time we should be asked for password and user, so I could be log in as admin user.

Is there any option in cockpit or this have to be done on the level of sssd if so how ?
Can you help ?

**Comment by martinpitt** [comment]
This is called [single sign-on](https://cockpit-project.org/guide/latest/sso.html) and happens because your session (where you run the browser) has a kerberos ticket from Active Directory. This allows you to log into Cockpit without a password again.

If you don't want that, you should be able to disable that with adding this to /etc/cockpit/cockpit.conf:
```
[negotiate]
action = none
```
This is also explained in the [cockpit authentication documentation](https://github.com/cockpit-project/cockpit/blob/master/doc/authentication.md#actions).

After changing cockpit.conf, you need to do `sudo systemctl try-restart cockpit` for the change to become effective.

Does that work for you?

**Comment by martinpitt** [comment]
No response in half a year, and I gave the solution above.
