### ISSUE TITLE
filter box for the journal

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#1535]
Splitting this off issue #1378 since after discussing it a bit with @stefwalter we realized it's a whole heap of logic in itself and it would be bad to block on the layout fixes.

https://bugzilla.redhat.com/show_bug.cgi?id=1657756

**Comment by andreasn** [comment]
based strictly on syntax used by journalctl we would have 
priority: err, warning, notice, debug
since: 2012-10-30, today, yesterday
unit: nameofservice.service

**Comment by andreasn** [comment]
should "err" be "error"?
should "debug" be "all"?
should "unit" be "service"?

**Comment by dperpeet** [comment]
I think "error" is better - doesn't take much more space than "err" and is easier to read.

"debug" vs "all" depends on the description. If we talk about the lowest level, then "debug" would be more consistent. Also, "debug" would deviate less from the underlying terminology.

"service" is better than unit, because once we talk about multi-machine environments, "units" may be ambiguous.

**Comment by andreasn** [comment]
Note that this is pretty much a braindump at this point. Still a lot of open questions

![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/0f6ba849489cee84144b15c3c82c8123f9a96b03/journal/journal-search.png)

**Comment by andreasn** [comment]
With freeform text as well.
Feedback welcome!

![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/journal/journal-search.png)

**Comment by andreasn** [comment]
Somewhat related https://brianreavis.github.io/selectize.js/

**Comment by andreasn** [comment]
https://www.patternfly.org/wikis/patterns/search/

**Comment by andreasn** [comment]
Searching and filtering is the same, and that is covered in #1281, so closing.
