### ISSUE TITLE
Virtual machine disk used is incorrect.

### ISSUE THREAD

**Issue by rsprinkle** [cockpit-project/cockpit#15389]
Cockpit version: 237
OS: Debian 10
Page: Machines

Drilling into a specific virtual machine, in the 'Disks' area, the value showed in the 'Used' column appears to actually be the free space.

Steps to reproduce

1. Select specific machine on machine page.
2. Compare value shown in disks/used against value returned by the df command in the web console.

Results from df:
Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/vda1      123329088 10601840 106419460  10% /

![Capture](https://user-images.githubusercontent.com/12002236/108628218-b12d1380-7427-11eb-945c-1cbc5289db10.PNG)

**Comment by KKoukiou** [comment]
Hey @rsprinkle, 

The values that you see in the Cockpit UI for `Used`, represent how the host sees the disk allocation, not the guest.
However you seem to run the `df` command inside the VM. The /dev/vda1 used value from inside the guest is expected to be smaller than the value of 'Used' from the perspective of the host, since the root partition is not the only one part that takes space from the image.

Here is an example from a VM's disk on my system:

![Screen Shot 2021-02-22 at 08 46 22](https://user-images.githubusercontent.com/14921356/108677791-7809a780-74ea-11eb-9a1e-59f874e4a204.png)

We basically display the values from the following commands:
```
[kkoukiou@sequioa cockpit]$ sudo virsh domblklist fedora-33-unattended-download-an-OS 
 Target   Source
-----------------------------------------------------
 vdc      fedora-33-unattended-download-an-OS.qcow2

[kkoukiou@sequioa cockpit]$ sudo virsh domblkinfo fedora-33-unattended-download-an-OS  vdc
Capacity:       10737418240
Allocation:     2592411648              <---------------- This value converted to GiB is what you see above in the UI as used.
Physical:       10803085312

```
And here is my df from inside the guest:
![Screen Shot 2021-02-22 at 08 51 29](https://user-images.githubusercontent.com/14921356/108678491-712f6480-74eb-11eb-9f2e-66cfa71da46b.png)

**Comment by KKoukiou** [comment]
@rsprinkle I will close this because the steps you used for the bug report are not valid, as I explained in the comments. If you still have questions or disagree, feel free to comment or reopen this issue.
