### ISSUE TITLE
Cockpit VM set up help - Network issue

### ISSUE THREAD

**Issue by STUKguy** [cockpit-project/cockpit#15405]
Hi,

I did the following step by step so please tell me if something is wrong.

1. OMV > OMV-Extras > Cockpit > Install
2. Once installed clicked on "Open web"
3. Entered log in details
4. Virtual Machines > Network > default > active
5. Virtual Machines > Create new VM > filled in details as requierd > create
6. Using the "Console" window installed OS (Ubuntu)

This is were i get stuck i get the IP as 192.168.122.247/24 which is no good to me as my network is set up for IP address such as 192.168.68.xxx

I have asked this in the OMV forums but no one has an answer.

Can someone please explain how i access the VM? using VNC or Remote desktop or something else?

**Comment by KKoukiou** [comment]
Hi @STUKguy, step 6 shows you have a functional VM console. Can't you just keep using the VM console from there?

**Comment by STUKguy** [comment]
Hi @KKoukiou , Yes it is, but i wanted to set it up as a remote machine which i can access from another device which out having to log into Cockpit thats why i need the IP range to be somewhere in 192.168.68.xxx

**Comment by KKoukiou** [comment]
irt-viewer needs the IP address of the host the is serving your VM, not the IP of the VM itself.
Then you can access your machines with virt-viewer like `remote-viewer spice://yourhost:spiceport`

The spice port for a specific VM you can get from that VM details page. 

![Screen Shot 2021-02-24 at 09 14 56](https://user-images.githubusercontent.com/14921356/108968394-0152e280-7681-11eb-94ee-bc27925e0283.png)

Theoretically the 'Download vv file' should do that automatically for you, but it's broken for remote hosts. Let me know if this worked for you.


If you actually do want to set up the IP of the VM in that IP range you can do that as well, it's just not related to the spice/vnc consoles. 

So in order to get the IPs you mentioned, just change your default network which is the the one that VMs are using by default. 

You need something like this:

```
$ sudo virsh net-dumpxml default 
<network connections='1'>
  <name>default</name>
  <uuid>bb912984-3dc8-4f86-b322-a04ac05462cd</uuid>
  <forward mode='nat'>
    <nat>
      <port start='1024' end='65535'/>
    </nat>
  </forward>
  <bridge name='virbr0' stp='on' delay='0'/>
  <mac address='52:54:00:6f:91:0c'/>
  <ip address='192.168.68.1' netmask='255.255.255.0'>
    <dhcp>
      <range start='192.168.68.2' end='192.168.68.254'/>
    </dhcp>
  </ip>
</network>
```

You can edit it with `sudo virsh net-edit default` and make sure to add the range you want. If you want for a specific VM to have an static IP you can add a mac address entry in the dhcp configuration. https://wiki.libvirt.org/page/Networking#Applying_modifications_to_the_network

**Comment by STUKguy** [comment]
Hey @KKoukiou ,
Sorry its taken me so long to reply,

So if i do the first part i get this 
![image](https://user-images.githubusercontent.com/66088795/109390860-f495ef00-790b-11eb-8606-66347e23f457.png)
Which IP address would i need to type spice://192.168.122.62/5901 or spice://192.168.68.62/5901 (.62 is the actual address for my Cockpit server)

I also tried the 2nd thing you suggested and edited Virsh but i got this when i tried to activate the network.
![image](https://user-images.githubusercontent.com/66088795/109390923-62dab180-790c-11eb-841f-984d007d8c96.png)
 
not sure what to do? basically what i wanted to test was to install Android TV on a VM (not going to plan either) and then use an old Android box i have (these cannot be updated just too old) to connect to this VM of Android TV.

**Comment by KKoukiou** [comment]
@skobyda maybe you can help more here.

**Comment by STUKguy** [comment]
@KKoukiou , i have managed to resolve the network issue turns out i had to create a bridge between the virtual network and the physical network. my new issue is i cannot seem to get audio to work through the VM. Any ideas?
