### ISSUE TITLE
Docker image size is misleading and probably useless

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#1541]
Listing the size of a Docker Image is pretty misleading as various images share lots of space. I think we could leave out that column in our Containers page.

**Comment by dperpeet** [comment]
The size might not be useless - it might be nice to know when starting a container.

Docker uses the term "Virtual Size". While not perfect, it implies that it's not referring to the size on disk. Currently we access VirtualSize, but the docker API also exposes other values (such as Size).
For derived images I got expected values, but not for the base images (they had size 0). I could look into this further.
![image](https://cloud.githubusercontent.com/assets/8711649/5643480/4bcd0372-9659-11e4-9be4-fef7c2785a32.png)


For a cleaner UI I could imaging moving this info to hover-text or removing it completely. Where it definitely should appear is in the details (click on an image).

Currently size information (virtual or otherwise) is not listed there:
![image](https://cloud.githubusercontent.com/assets/8711649/5643444/eee58058-9658-11e4-85df-c3f5cc3c6e21.png)

**Comment by stefwalter** [comment]
Agreed.

In addition we need to represent how much of the entire available space for docker is in use, free. Running out of the free Docker space (eg: /var/lib/docker) is pretty disastrous.

**Comment by andreasn** [comment]
@stefwalter that would be good. Should we solve that in this issue, or should I file a separate one for that?

**Comment by stefwalter** [comment]
Yup.

**Comment by martinpitt** [comment]
Our docker UI is on maintenance mode, and improvements should go to cockpit-podman.
