### ISSUE TITLE
Move PF3 overrides from page.scss to patternfly-overrides.scss

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#15425]
When working on the CSS variable reduction @ #15183, I noticed that there are apparently still quite a few PatternFly 3 overrides in page.scss.

Anything that can be moved to the override file for PF3 should be.

It doesn't make sense to pull in PF3 overrides for all pages — especially for PF4-only pages.

**Comment by KKoukiou** [comment]
This is actually important to do, because page.scss is used by PF4 only pages as well. So these 'new' pages are importing also PF3 overrides. Quite a mess here.

Let's prioritize it, I might do it as well.

**Comment by martinpitt** [comment]
What would be an example of such an override? Most of the [current version](https://github.com/cockpit-project/cockpit/blob/16c3c16d37a6edc00916f30f72caacb13064ea3f/pkg/lib/page.scss) look like genuinely cockpit specific (and not PF3 specific) additions to me, and there were some updates like commit b39f08ce8b43c62 which removed PF overrides. There are certainly some questionable things there, such as the various [disabled overrides for `pointer-events: auto`](https://github.com/cockpit-project/cockpit/blob/16c3c16d37a6edc00916f30f72caacb13064ea3f/pkg/lib/page.scss#L38) 

One thing that I found is [blank-slate-pf](https://github.com/cockpit-project/cockpit/blob/16c3c16d37a6edc00916f30f72caacb13064ea3f/pkg/lib/page.scss#L128) -- that is a PF3 only thing. It would be harmless on a PF4-only page, but in order to keep page.scss clean that one should certainly move.

Likewise, lines 238 to 249 look like PF4 fixes/workarounds -- these should certainly move to patternfly-4-overrides.scss then?

**Comment by martinpitt** [comment]
I sent PR #16215 as a first draft.
