### ISSUE TITLE
SSO problems - 10-ipa.cert not being created

### ISSUE THREAD

**Issue by mattblack** [cockpit-project/cockpit#15440]
I have a machine running Fedora 33 server. It runs cockpit-238-1.fc33.src.rpm out of the box. I have installed FreeIPA server on this machine.

What happens: The Cockpit browser app doesn't use a FreeIPA certificate. Firefox warns about it being untrusted.

What should happen: The Cockpit browser app should automatically obtain a FreeIPA certificate and present it to the browser. Firefox already trusts the FreeIPA server CA so doesn't issue a warning.

Some investigating:

The docs say that Cockpit will create the service `HTTP/sso.example.com@EXAMPLE.COM` when it joins a domain. However this service already exists - it relates to the FreeIPA web admin panel.

Signing into the Cockpit web app with my SSO username and password works fine.

No `/etc/cockpit/krb5.keytab` was created automatically. Creating it with `sudo ipa-getkeytab -p HTTP/server.example.com@EXAMPLE.COM -k /etc/cockpit/krb5.keytab` doesn't help.

No `10-ipa.cert` is created in `/etc/cockpit/ws-certs.d`

**Comment by martinpitt** [comment]
cockpit-certificate-helper should get along with an existing HTTP/ principal:
```
    ipa service-show "${SERVICE}" || \
        ipa service-add --ok-as-delegate=true --ok-to-auth-as-delegate=true --force "${SERVICE}"
```
this would only bail out if it does not exist *and* fails to be created. But if that happens, it would also skip the ipa-getkeytab and -getcert steps. If this still happens for you, can you please check `sudo journalctl --since '5 minutes ago'` (or however long ago it was) and put the output here? That should have some error message.

**Comment by martinpitt** [comment]
No response in almost a year. If you still have this problem, please respond with the information asked for in the previous comment, then we will reopen. Thanks
