### ISSUE TITLE
Move Shutdown/Restart to main server page

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#1544]
The server page should have the shutdown/restart dialog ... it doesn't fit on the 'Tools' menu, it's not a tool, it's a basic aspect of the Server.

**Comment by andreasn** [comment]
So this goes outside the scope of this bug a bit and breaks up the reboot and shutdown actions into separate dialogs. This would decrease the risk of shutting down by accident when you want to reboot (and if it's a remote system, that's a mistake that could cost you quite some time).
It would also make the label for the button nicer.

![Mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/shutdown-reboot/shutdown-reboot.png)

**Comment by stefwalter** [comment]
Very good. Although the implementations of those dialogs could be the same, and just change itself a bit to fit the two contexts.

**Comment by andreasn** [comment]
Sure

**Comment by andreasn** [comment]
The "Power Options" label really bugs me. So I was thinking, if we have the "Status: Running since 3 days" maybe this shutdown/reboot label would work really well just below it. It's also close to "Last updated", so in the cases like Atomic where it needs a reboot in to be able to apply the OS updates, the button could suddently grow a 3rd option, that is "Reboot and update"

**Comment by andreasn** [comment]
https://github.com/cockpit-project/cockpit/wiki/Atomic:-OSTree-Update

**Comment by stefwalter** [comment]
This is done in #1768
