### ISSUE TITLE
VM console does not fit onto screen 

### ISSUE THREAD

**Issue by lzap** [cockpit-project/cockpit#15472]
Cockpit version: cockpit-238.1-1.fc32.s390x
OS: Fedrao 32
Page: Virtual machines

Hello, when I launch a new VM, overview pane changes a bit and displays "CPU Type" field which is longer than usual and t his pushes the Console pane to the right so it's not visible on a reasonably-sized browser window. I tested on 1440x900.

I have Czech locale and chances are the translation is simply too wide, I wanted to test this with English but I am unable to switch to English - when I select the language and confirm and logout/login, I still see Czech for some reason. Maybe a bug?

Anyway, this is S390x where processor type is also long string: "z14ZR1-base", in total it does not fit. Small issue.

![Cockpit S390x](https://user-images.githubusercontent.com/49752/109980837-9fd5e800-7d00-11eb-8476-2977a0ef333c.png)

**Comment by KKoukiou** [comment]
I can reproduce you issue when I use the serial console also with english locale. It really depends on the screensize.
![Screen Shot 2021-03-04 at 18 09 11](https://user-images.githubusercontent.com/14921356/110001598-ce5dbe00-7d14-11eb-83e7-46d24906f70c.png)

**Comment by KKoukiou** [comment]
From the dev tools I see that the overflow element is: <div class="xterm-screen" style="width: 792px; height: 418px;">

@garrett can probably figure this out easily.

**Comment by garrett** [comment]
I'm seeing similar things in English as well.

While the VNC console scales, the text one does not. 

|VNC|Text|
|---|---|
|![Screenshot_2021-03-15 Virtual Machines - garrett Rain](https://user-images.githubusercontent.com/10246/111195680-caefef80-85bc-11eb-90c7-8651794592c6.png)|![Screenshot_2021-03-15 Virtual Machines - garrett Rain(1)](https://user-images.githubusercontent.com/10246/111195676-ca575900-85bc-11eb-9024-b766665bf54b.png)|

**Comment by garrett** [comment]
The problem is not as indicated; the cards to the side have nothing to do with the terminal, nor does language.
The problem is due to the text-based terminal setting the terminal as fixed width.

I can override the width, but then that cuts off the side of the terminal.

I think this would need fixing in the xterm component itself, as I don't think there's anything I can do outside of it, with layout or anything. The best option while this bug exists is to click on expand... but of course, getting shoved to the side truncates it from even showing up. :shrug: 

The problem comes down the rigidness / inflexibility of the xterm widget.

**Comment by marusak** [comment]
I think the solution is the same as we do it on terminal page itself - that is always fits the whole screen - while we use the same component. So nothing difficult.

**Comment by lzap** [comment]
In both English and Czech it's just few characters from fitting okay. I am wondering if we could just do newline between "custom" and "(cpu type)". This field looks like the widest from all. Instead:

    custom (Intel Skylake blah blah) edit

it would be

```
custom
(Intel Skylake blah blah) edit
```

**Comment by garrett** [comment]
I think it's more a problem with the terminal using hardcoded sizes and not adjusting. It should, ideally, wrap the lines and go from 80 characters wide to arbitrary amounts that it should be able to do, like 70 or 65 or whatever.

If we make the labels shorter, there will always be other long labels. Besides, I'm hitting it even with shorter labels. I'm pretty sure it only _looks_ like the label is the problem.

Here's a VM page for CentOS Stream 8 Server with a text-mode console and _no_ CPU label.

![Screenshot_2021-03-18 Virtual Machines - garrett Rain](https://user-images.githubusercontent.com/10246/111641624-a040a980-87fd-11eb-99c0-9b3161024160.png)

Things still run off the screen.

Same if I remove the autostart too:

![Screenshot_2021-03-18 Virtual Machines - garrett Rain(2)](https://user-images.githubusercontent.com/10246/111641999-f7df1500-87fd-11eb-9b88-0bc5bfb170e6.png)


VNC based console displays fine (although small of course, but that's why there's "expand"):

![Screenshot_2021-03-18 Virtual Machines - garrett Rain(1)](https://user-images.githubusercontent.com/10246/111641775-c1a19580-87fd-11eb-962c-146715f10924.png)

**Comment by garrett** [comment]
I suppose one solution could be to use a sort of [CSS clamping](https://caniuse.com/css-math-functions) (with `clamp()` or `max()`) on the font to make it scale down to something like 2/3 of the screen divided by 80 and then rely on expand for people for want to actually use the console. Of course, at a certain width, the text would still be 100% the size it currently is.

If we could have it wrap text, that would be better... but I think @marusak would have to handle that solution.

**Comment by garrett** [comment]
I've been debugging this further and might have found a fix. I don't see a normal console in any of my VMs though, so I don't know how well this works. All I see is what's pictured above.

Anyway, it seems forcing xterm-screen to 100% width keeps it within bounds.

```css
.xterm-screen { width: 100% !important; }
```

I'll send a PR. If we can fix this a different way, that would be great. Otherwise, this seems to work.
