### ISSUE TITLE
own cockpit plugin for custom monitoring

### ISSUE THREAD

**Issue by mvala** [cockpit-project/cockpit#15500]
Page: own cockpit plugin for monitoring

I would like to implement module for monitoring of some external parameters. I already have pcp working and it can publish my values. Now i would like to make graph or use `cockpit.metrics()` I am looking at doc https://cockpit-project.org/guide/latest/cockpit-metrics.html and some how i cannot make it work to see some values in browser console at least. Would you be so kind to help me with example?

Currently i have something like this
```
const CURRENT_METRICS = [
            { name: "cpu.basic.user", derive: "rate" },
            { name: "cpu.basic.system", derive: "rate" },
            { name: "cpu.basic.nice", derive: "rate" },
            { name: "memory.used" },
            { name: "memory.swap-used" },
            { name: "disk.all.read", units: "bytes", derive: "rate" },
            { name: "disk.all.written", units: "bytes", derive: "rate" },
            { name: "network.interface.rx", units: "bytes", derive: "rate" },
            { name: "network.interface.tx", units: "bytes", derive: "rate" },
            { name: "cgroup.cpu.usage", derive: "rate" },
            { name: "cgroup.memory.usage" },
            { name: "cpu.core.user", derive: "rate" },
            { name: "cpu.core.system", derive: "rate" },
            { name: "cpu.core.nice", derive: "rate" },
        ];

        const options = {
            source: "internal",
            metrics: CURRENT_METRICS
        };

        // const options = { metrics: ['ctp.time'], source: "pcmd" };
        console.log(options);
        const metrics = cockpit.metrics(1000, options);
        const grid = cockpit.grid(1000);
        const row = grid.add(metrics.series, "kernel.all.cpu.user");
        metrics.follow();
        grid.walk();
        grid.sync();
        console.log(grid);
        console.log(row);
        metrics.onchanged = function () {
            grid.walk();
            console.log((new Date()).toLocaleTimeString());
            console.log(grid);
            grid.walk();
            grid.sync();
            console.log(row);
        };
```
Thanks for any help in advance

**Comment by KKoukiou** [comment]
I did not try your code snippet here yet, will do it tomorrow.

For your interest we plan to provide an integration of cockpit with Grafana, so that you can use the latter for monitoring PCP exposed parameters that you can't see in the metrics page.

Is this a way that you would prefer maybe to go with? If you would rather have your own cockpit plugin for this I am happy to help you with implementing it.

**Comment by mvala** [comment]
And i am also interested how to work with metrics+series+grid. It would be very nice to have such nice example.

**Comment by mvollmer** [comment]
The main gotcha is probably how to get a grid to walk with real time data. This is one of the very few places in computer science where a negaitve zero is different from a positive zero. :-)

Here is a working example:

```
const CURRENT_METRICS = [
    { name: "cpu.basic.user", derive: "rate" },
    { name: "cpu.basic.system", derive: "rate" }
];

const options = {
    source: "internal",
    metrics: CURRENT_METRICS
};

const grid = cockpit.grid(1000, -10, -0);
grid.walk();

const metrics = cockpit.metrics(1000, options);
const row_all_metrics = grid.add(metrics);
const row_first_metric = grid.add(metrics, [ 0 ]);
grid.sync();

grid.addEventListener('notify', function () {
    console.log("A", row_all_metrics)
    console.log("0", row_first_metric);
});
```

This will show ten samples of the immediate past with an interval of one second.  The grid arguments are:

1000: interval between samples in milliseconds. This must match the interval of the the metrics series.
-10: start at ten samples before now. Negative numbers are relative to now.
-0: and end at exactly now. A positive zero would mean something else, I am not sure exactly what. Maybe zero sample interals since the unix epoch.

The metrics series can have any number of metrics in it, and their values show up in the same order in the grid row.  Example output from `console.log("A", row_all_metrics)` may be:

```
A 
0: Array [ 0.019940179539844394, 59.95998033834621 ]
1: Array [ 9.990049830405042, 50.0698501104489 ]
​2: Array [ 19.950139630935155, 39.93027901323512 ]
​3: Array [ 10.039770877105184, 30.059671494178474 ]
​4: Array [ 10.000079383025877, 39.98015902470797 ]
​5: Array [ 10.00999016861897, 40.039920398034155 ]
​6: Array [ 9.980069780838676, 49.89036881364882 ]
​7: Array [ 19.98996028874535, 119.90985140390694 ]
​8: Array [ 19.999979960615747, 50.139540621079504 ]
​9: Array [ 10.029969990020618, 30.070208873134106 ]
​length: 10
```

For example, at index 9, the 10.029969990020618 value is for cpu.basic.user, and the 30.070208873134106 value is for cpu.basic.system.

You can specify a path with `grid.add`, and for cockpit.metrics this is just the index into the `metrics` array in the options.

This basic usage  of metrics+grid is not well documented. I'll try to improve that.

**Comment by mvollmer** [comment]
@mvala, I hope this helps. Please reopen if there are still questions.

**Comment by mvalarh** [comment]
@mvollmer Thanks. I will try it.
