### ISSUE TITLE
when checking out a fork, missing tags break autogen/configure

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#15540]
1. `git clean -dxf && test/make_dist.py`
2. `./autogen.sh --prefix=/usr --enable-debug && nice make -j4`
3. see the error due to the lack of tags

```
...
fatal: No tags can describe '61c59488f564a59bd09eaa8d0e6ba82f33ddb0e4'.
Try --always, or create some tags.
...
checking that PACKAGE_VERSION is properly set... no
configure: error: Please build from a .git checkout or .tar.xz tarball
```

**Comment by martinpitt** [comment]
I suppose you directly cloned a fork (which usually have no tags), instead of doing a `git fetch <repo> <branch>; git checkout FETCH_HEAD`. I usually do the latter, which still retains the tags from origin.

For directly cloning a fork we'll need some heuristic to fetch the tags from origin. I'm not sure where exactly that would live, in make_dist or in autogen.sh. It's a rather nasty special-case hack. First we need to check how crucial the version still actually is -- we still have a few versioned Requires/Conflicts which require having a fairly recent version. If we *can*  live with a static version like "0", then let's create a local fake tag with that; otherwise, let's fetch them from cockpit-project/cockpit.

**Comment by marusak** [comment]
How often would one hit this? Is this once when you set up your environment or every single time?

I would not be a huge fan of having some nasty hack when the fix is as simple as `git fetch` or `git pull --tags`. Also the error message is rather obvious `...No tags...`. But if this can happen more than on initial environment, then lets do some workaround.

**Comment by martinpitt** [comment]
Its not about "often", it's about workflow. If you do the checkout like so:

    git clone -b new-timer https://github.com/KKoukiou/cockpit

then you *only* clone  a fork, and don't get tags. If you keep working in your cockpit-project/cockpit checkout and then test a PR like this:

    git fetch https://github.com/KKoukiou/cockpit new-timer
    git checkout  FETCH_HEAD
    
then you retain the tags from the "real" origin.

FTR, this is nothing new, the former would never have worked properly.

**Comment by garrett** [comment]
> I suppose you directly cloned a fork (which usually have no tags)

Nope. It was my normal checkout, with tags and all.

I just did the `test/make_dist.py` and then attempted to build on top of that checkout.

**Comment by martinpitt** [comment]
@garrett: Then I'm afraid I don't know what's going on. Can you please provide a reproducer from scratch? I.e. how did you clone cockpit, which fork/branch did you check out and how.

**Comment by garrett** [comment]
I was using this branch when the error happened: https://github.com/cockpit-project/cockpit/pull/15515 and was on git commit 61c59488f564a59bd09eaa8d0e6ba82f33ddb0e4 (as mentioned in the error), which was the furthest commit in the branch at the time.

The checkout was my normal checkout, with tags and all.

**Comment by garrett** [comment]
...I cannot reproduce it now.

Weird.

**Comment by martinpitt** [comment]
Right, neither can I. `fatal: No tags can describe` definitively means that your local checkout has no tags. However, @KKoukiou 's fork does have [tags](https://github.com/KKoukiou/cockpit/tags), so I suppose it was someone else's fork, or you somehow managed to delete all tags from the checkout.

**Comment by garrett** [comment]
Perhaps it was VS Code? I usually use GitHub's cli for checking out branches these days, but I tried using VS Code's GitHub integration lately. It might've misbehaved in a way that cause this to freak out.

That's the only think I can think of that might've cause this issue.

**Comment by garrett** [comment]
Anyway, I think we might want to close this issue as "NOTABUG"... and reopen if it happens again (either if it routinely happens or we have more info).

Closing now. Please reopen if you disagree. :wink:
