### ISSUE TITLE
No method to hide sidebar

### ISSUE THREAD

**Issue by rixon** [cockpit-project/cockpit#15587]
Cockpit version: 224
OS: CentOS 8.3
Page: Main

Sidebar menu is too big, and there should be a way to hide it.

The sidebar was revamped with Cockpit release 220.  Prior to the change, the sidebar was a few icons that expanded when you hovered over them.  With the updated sidebar, the icons are now gone, and the options for the sub menus are now all included in the sidebar.  Since the sidebar is now static, there should be a way to hide the sidebar.  The PatternFly specification says that when there is a sidebar, the hamburger icon should always be present to allow the sidebar to be hidden.  The hamburger icon is not present, so there is no way to hide it and free up display space.

Before release 220:
<img width="161" alt="Screen Shot 2021-03-24 at 5 37 26 PM" src="https://user-images.githubusercontent.com/743064/112392637-c4056300-8cc7-11eb-924a-2d95ce479d0d.png">

After release 220:
<img width="256" alt="Screen Shot 2021-03-24 at 5 37 57 PM" src="https://user-images.githubusercontent.com/743064/112392684-cf588e80-8cc7-11eb-91cd-2da45a081101.png">

**Comment by marusak** [comment]
> Prior to the change, the sidebar was a few icons that expanded when you hovered over them.

Not really. There were two menus side by side only on Dashboard the main menu was hidden. Now we have only one menu.

> The PatternFly specification says that when there is a sidebar, the hamburger icon should always be present to allow the sidebar to be hidden.

Can you please provide link to this specification. I quickly looked at [PF navigation component](https://www.patternfly.org/v4/components/navigation) and it does not have option for having hamburger icon.

**Comment by rixon** [comment]
The part I saw about the hamburger was linked under the [Masthead section](https://www.patternfly.org/v3/pattern-library/application-framework/masthead/):

> The tall design is recommended when using Vertical Navigation. The hamburger menu should always be visible in the top left corner in this case.

I see now that I was looking at v3, and you were referencing v4.  I don't know how different they are, but under the [Masthead section in the v4 pages](https://www.patternfly.org/v4/components/masthead#) they show the hamburger.

**Comment by marusak** [comment]
Right. V3 is the old version, v4 is redesigned version.
It is not as simple as putting the hamburger menu up there as we have there different widget.
Lets see what @garrett thinks from design point of view.

**Comment by KKoukiou** [comment]
@marusak seems they do support nav that can be hidden, check https://www.patternfly.org/v4/components/page#vertical-nav

**Comment by KKoukiou** [comment]
So I just realized that our outer shell is not PF4 at all, (nav is), so indeed the ping to @garrett is valid.

Can we make the shell utilize what PF4 offers us instead of our custom code? If we are not happy with what they offer for mobile, which I think was the initial reason we introduced our implementation, can we open an feature/enhancement  request to the PF4 repo core?

**Comment by KKoukiou** [comment]
So I gave it some thought and I really think what PF4 offers for the shell is as good what we have for mobile and better than what we have for desktop.
When we redesigned/rewrote the shell maybe there was not there Patternfly component at least to the state that is know, but I think it's time to agree to use what they offer instead of our custom things.

* Desktop mode - we really need to provide a way to hide the sidebar - as this issue requests. It does not make sense to keep it constantly expanded, it takes reasonable amount of the page without being needed all the time.
* Mobile mode can be just fine by having the sidebar toggle on the top and optionally showing the navigation. Right now we have a completely custom implementation which moves the sidebar on the bottom of the page. It's really nice and all but tons of custom code without any further benefit compared to what PF offers.

Note: Of course the content of the NAV itself should keep all the custom CSS because it's much more complicated compared to the PF examples. I am really talking only about the Shell elements positioning here.

**Comment by KKoukiou** [comment]
For the record I gave it a try, and using only PF4 components the shell can be something like this:
(of course if far from optimal, it's just a scratch try)
![Screen Shot 2021-03-26 at 13 15 15](https://user-images.githubusercontent.com/14921356/112631550-537d5400-8e37-11eb-8eb4-a536fc9787b4.png)
![Screen Shot 2021-03-26 at 13 26 19](https://user-images.githubusercontent.com/14921356/112631607-64c66080-8e37-11eb-80d3-2dada982ba06.png)

**Comment by garrett** [comment]
### It's intentional, backed by UX studies

How Cockpit is designed is intentional.

Why would you want to hide the navigation? If you have space constraints, Cockpit has been designed and implemented to scale to the amount of space you can give it.

The sidebar navigation has been designed so you can see where you are and quickly get to other parts of Cockpit. When there's something that needs attention in another page, such as systemd services having issues or software that needs updating, there's even a little alert icon that appears to catch your attention.

Hiding sidebars is an anti-pattern. PatternFly does _allow_ for it (and it's probably overused by various PF apps — especially on desktops — but only because it's _possible_ and demonstrated as such)... but it's really **not a good idea**, especially on a desktop.

### Hypotheticals

If we did have a toggleable sidebar, that would mean you always have to click to show it, find your bearings, click to navigate, and then click to hide. And you'd have to do this each and every time you want to change pages.

If we did have the collapsing sidebar: If the sidebar is out, what happens? 

1. Do we need to reflow the content each toggle? That can be a bit much, especially for some pages like the journal. And on others, that would completely change the UI of the content. It'd switch between a desktop and mobile experience, completely altering everything. 
2. Alternately, the content could be shoved off the page, but then it's truncated and you cannot see everything.
3. A third option would be to keep the content where it is, but pop-up the navigation above the content. But then you're missing parts of the content again, and arguably the most important parts.

When in mobile, we do something kind of like # 3, but it's treated like a menu instead of another layer. Menus go away on activation, unlike a secondary toggable layer.

---

### Research & design articles

I'm including a bunch of design-focused articles here that touch on the topic. Most of them have done research which backs up their claims as well. (Cockpit has also done some research in this area a while back, which has found similar results, and is the reason for why Cockpit is the way it is.)

#### How Poorly Hamburger Menus and Hidden Navigation Work
https://www.noupe.com/design/hamburger-menus-hidden-navigation-98460.html

> Conclusion
>
> In the result, one can say that the hidden navigation was used much less, took longer, and a much lower amount of content was actually found using it. On the desktop, only 54 percent of the content that the users were supposed to call up was actually found, and on mobile, it was only 64 percent.

#### The Obvious UI is Often the Best UI
https://medium.com/google-design/the-obvious-ui-is-often-the-best-ui-7a25597d79fd

This one's especially interesting, as it's a direct comparison between a hamburger menu on the top left (which is what's proposed in this issue) versus navigation at the bottom (which is what Cockpit has been designed to do, with UX testing backing it up).

> ![comparison](https://user-images.githubusercontent.com/10246/112817011-4607da00-9082-11eb-863b-7cb67f1e79ae.png)
> Before: The Redbooth (Teambox) app previously used a hamburger menu. After: The app switched to a bottom navigation menu and saw a 65 percent increase in daily active users and a 70 percent increase in session time.

#### Hamburger Menus and Hidden Navigation Hurt UX Metrics
https://www.nngroup.com/articles/hamburger-menus/

> Our quantitative usability testing of hidden menus (such as hamburger icons) and visible menus (such as links across the top of pages) reveals that:
>
> - **Hidden navigation is less discoverable** than visible or partially visible navigation.
>     
>     - When navigation is hidden, users are less likely to use navigation.
>     - If people use hidden navigation, they do so later in the task than if it were visible.
> - **Hidden navigation** **provides a worse user experience than visible** or partially visible navigation does, in both mobile phones and desktop user interfaces. This finding holds true across multiple UX metrics including users’ assessment of task difficulty, time spent on task, and task success.
>     
> - On desktops, hiding navigation degrades the experience and the navigation discoverability more than it does on the phones.
>     
> - Hiding the navigation mostly affects content that is not directly accessible through an in-page link.

...And it ends with this conclusion:

> - What are the takeaways of this research for your next design project?
>     
>     **Desktop**: There is plenty of screen real estate for displaying navigation options, and we recommend:
>     
>     - Do not use hidden navigation (such as hamburger icons) in desktop user interfaces.
>     - Instead display the top-level navigation options, usually across the top of the page or down the left side.
>     
>     **Mobile**: For phones, there is no hard-and-fast rule. But our general recommendations are:
>     
>     - If your site has 4 or fewer top-level navigation links, display them as visible links.
>     - If your site has more than 4 top-level navigation links, the only reasonable solution is to hide some of these. We did find that the usability penalty imposed by hidden navigation is very present on mobile, but it is smaller than on the desktop. Thus, we recommend making this design tradeoff because the usability of an expandable navigation menu is far better than that of alternative designs.
>     - Provide in-page links to important information on your site, or use other methods of [supporting the hamburger](https://www.nngroup.com/articles/support-mobile-navigation/) (or some other hidden) menu.
>     
>     Remember: [*mobile-first* is not the same as *mobile-only*](https://www.nngroup.com/articles/mobile-first-not-mobile-only/). Plus, of course, follow the other long-established [UX guidelines for menu design](https://www.nngroup.com/articles/menu-design/).

**Comment by garrett** [comment]
@KKoukiou: I appreciate the effort at this first pass of porting the shell to be closer to PatternFly 4. We could go in this direction.

However, I strongly believe having the navigation toggle is a bad idea, and there's lots of research (including our own) on this topic. But we could adopt a lot of the rest of the implementation shown in your initial prototype (with more work, of course).

**Comment by marusak** [comment]
@garrett Thank you for such exhaustive reply!
I was not fan of having hamburger menu but seeing it is not just my feeling but it is backed up by research is great.
So let's not do that. Closing this issue then.


@KKoukiou moving from custom widgets and css to PF4 is always a good step forward. So definitely worth doing it, just we won't add burger menu at the end.
