### ISSUE TITLE
software: Update icon in sidebar should not be a warning

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#15592]
When a system has software updates, there's an icon in the sidebar. That's good. However, it's a warning icon, and this isn't a warning; it should be another type of alert.

![software-sidebar-icon](https://user-images.githubusercontent.com/10246/112467759-be5f5a00-8d67-11eb-8bda-5ea7197518d3.png)

Possibly, as a generic icon:
pf-icon-attention-bell | pf-icon | AttentionBellIcon

![Screenshot_2021-03-25 PatternFly 4 • Icons](https://user-images.githubusercontent.com/10246/112468287-58bf9d80-8d68-11eb-8388-75de9472344d.png)

But an **even better icon**: Use the same icon as the overview health card and the software overview uses. That is: The highest update type. (Security, bugfix, enhancement, etc.)

In this case, it would have been the shield update icon:

![Screenshot_2021-03-25 Overview - admin debian(2)](https://user-images.githubusercontent.com/10246/112468752-f4510e00-8d68-11eb-8231-12ecbd8acd0c.png)

I marked this as a software updates page related thing, even though this is actually within the shell... but I think the updates page provides the information?

**Comment by KKoukiou** [comment]
I don't think we should we use the same icons that we use currently in the Health card in the shell.

I think warning/error/info alert make more sense to use, even for the health card, instead of that bug/enhancement/security buttons. 

So I suggest to change the icons in the Health card, to reflect the alert severity (info, warning, danger).

**Comment by martinpitt** [comment]
> I think the updates page provides the information?

Correct, the shell just displays it.

**Comment by KKoukiou** [comment]
I feel like the shell icons should be either warning, error or info. (how they are now)
icons like shields should not appear on the shell, there is just too little context there and it will confuse the users.


In the health card however, these more specific icons (bug, shield) are fine, since there is the text as inline button which helps with the context. 

That said, I am not sure, there is actually that I would like to change regarding the icons. @garrett what do you think about this?

**Comment by garrett** [comment]
If there are updates and they're just feature updates, it's not really a warning. Nor is it really informational.

If there are security updates, they're not really an error. (It's a warning right now though.) And it's not a warning either, really, as a warning is when something has, is about to, or could possibly go wrong.

It feels inconsistent to me as-is.

Having any icon in the shell just serves as an attention-grabber. The icon and color indicate how important something is to grab attention. Right now, it's mainly warnings and sometimes errors. That works with services, certainly, as there's a 1:1 mapping there.

**Comment by KKoukiou** [comment]
> If there are updates and they're just feature updates, it's not really a warning. Nor is it really informational.
> 

We actually display info icon for normal updates. And I feel it's food git, it just means action can be taken, but nothing to worry about.

> If there are security updates, they're not really an error. (It's a warning right now though.) And it's not a warning either, really, as a warning is when something has, is about to, or could possibly go wrong.
> 

When security updates are pending, the system is more vulnerable, therefore I think the warning makes sense here. But then we want to differentiate between security updates and other bug fixes, therefore we introduced these two levels. I don't find it wrong. 

> It feels inconsistent to me as-is.
> 
> Having any icon in the shell just serves as an attention-grabber. The icon and color indicate how important something is to grab attention. Right now, it's mainly warnings and sometimes errors. That works with services, certainly, as there's a 1:1 mapping there.

That shield, bug etc icons are really just a beatification thing, with not so much context, especially when does not use  them with an explanatory tooltip.
Honestly, I noticed very recently that the shield has something to do with security.
So since tooltips will definitely not go on the shell items icons, I believe that the only icons that belong in the shell, are warning, error, info, these are the ones that a user is always familiar with.

Of course I am open to more discussion, but let's just put a clear suggestion on the table, because I feel like this issue will just stay open without a final decision on what's needed to address it.

@garrett so my opinion is:
* only the default icons (error, warning, info) should appear on the shell as page status. And I am actually happy with the current usage, also for updates.
* you suggest that  the current icons are not reflecting what severity for the special case of packagekit. And instead we need that shield, bug and enhancement icons respectively displayed in the shell.

**Comment by marusak** [comment]
> I believe that the only icons that belong in the shell, are warning, error, info, these are the ones that a user is always familiar with.

agree with this. Lets not make the shell menu a christmas tree with random icons, lets keep it simple with info (you may take a look), warning (you should take a look) and error (something is broken, please take a look).

There is also tooltip next to it, so you know about severity:
![Screenshot from 2021-05-20 13-54-34](https://user-images.githubusercontent.com/12330670/118974363-09b27500-b973-11eb-8a7e-da602802f9d8.png)

**Comment by marusak** [comment]
And whether for the middle level of notification (for all pages) we should use triangle with exclamation mark or bell with exclamation mark :man_shrugging: 

Bell seem less of a attention catcher, but also less known icon.

**Comment by garrett** [comment]
Considering the conversation above, I guess we should probably just close this then. :shrug:
