### ISSUE TITLE
Icons and colors for devices are not saved for the local machine after restarting or logging in and out?

### ISSUE THREAD

**Issue by nmcain** [cockpit-project/cockpit#15660]
Cockpit version: 215
OS: Ubuntu Server 20.04.2 arm64
Page: Dashboard

The icon for my local machine is not saved after logging in and out, it resets to a yellow color and the default icon, but the other devices that I have added stay the same. Is there a way to either hard code that icon or save the configuration?

On version 215, change the icon and color of a machine, then logout and login again, it will be reset

Steps to reproduce

1. Change the icon/color of the local machine
2.Log out
3.Log in again to see it reset to the default icon and the color yellow

![image](https://user-images.githubusercontent.com/18690588/113801326-751aed00-970d-11eb-945f-e96a21674981.png)
After logging out and logging in:
![image](https://user-images.githubusercontent.com/18690588/113801375-9380e880-970d-11eb-8e86-e7ee2f50153d.png)

**Comment by marusak** [comment]
This is indeed the case. It is due to how we store info about machines and the fact, that we don't store localhost. We had discussion about it in the team, how we should properly store these info.

This is dashboard, which has been obsoleted and dropped. But we still have this color on top of the page. Right now it uses picked color for any remote machine and well defined color for local machine (based on branding)

**Comment by nmcain** [comment]
Is it possible for me to manually edit that in the code? Where would I look?

**Comment by marusak** [comment]
I don't have dashboard anymore to test this out, but I am almost certain that it can be hacked in `/etc/cockpit/machines.d/99-webui.json`.

This is hack, not a good practice, just so you know :)
In that file add entry for `localhost` (or what you use when you access cockpit) and define color and icon. Then when you log out and back in, it should use that.
