### ISSUE TITLE
Activating snapshots with filesystems is problematic.

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#157]
Since the UUID of the filesystem is the same as for the origin but many things assume that the UUID is unique.  We have to take this into account.  Maybe we just need to help the user avoid this situation.

(But even switching between snapshot and origin, making sure that only one of them is active at any given time, causes confusion.)

**Comment by mvollmer** [comment]
This is still open.

**Comment by marusak** [comment]
This issue is closed due to inactivity.

If this issue is a bug report and you are still able to reproduce it, please
comment here and provide us with an updated reproducer.

If this issue is a request for a new feature, we are sorry, but we won't be able
to address this in any time soon. If you are interested in helping us with
the implementation, please comment here.
