### ISSUE TITLE
LUKS key slot removal confirmation removes the wrong key slot

### ISSUE THREAD

**Issue by gasinvein** [cockpit-project/cockpit#15773]
Cockpit version: 242
OS: Fedora 33
Page: Storage

When deleting a LUKS key slot with passphrase, Cockpit asks to enter a passphrase to confirm. If I enter a passphrase from another slot in this form, instead of deleting the selected passphrase slot, the one with passphrase I've entered is deleted.

Steps to reproduce

0. Create a new encrypted volume
1. Set key slot 0 passphrase to `passphrase0`
2. Add key slot 1 with `passphrase1`
3. Remove key slot 1, upon confirmation enter `passphrase0`
4. Observe key slot 0 removed

**Comment by marusak** [comment]
Indeed, I can reproduce this. This is a odd one for sure :) I'll quickly look into code what is actually happening.

**Comment by marusak** [comment]
Aha, ok, so the thing is, when you use the first option we call `cryptsetup luksRemoveKey <dev>` and then submit the passphrase that you type in. If you use the other option then we would call `cryptsetup luksKillSlot -q <dev> <slot>`.

Notice that `luksRemoveKey` does not take any slot number, from `--help`:
```
        luksRemoveKey <device> [<key file>] - removes supplied key or key file from LUKS device
        luksKillSlot <device> <key slot> - wipes key with number <key slot> from LUKS device
```

So I am afraid this works as expected. @mvollmer WDYT?

**Comment by gasinvein** [comment]
>this works as expected

Well, if so, the UI is misleading, isn't it? It unequivocally state that the key N is going to be deleted, what appears to be not true if a passphrase from a key lot other than N is entered.

**Comment by marusak** [comment]
> Well, if so, the UI is misleading, isn't it?

It surely is. We need to think about it but it may be that backend just does not support deleting specific slot in this manner and we need to change the UI. Or maybe we can validate that the passprhase is for given slot before we try to remove it.

**Comment by marusak** [comment]
Reading man pages, all of `luksConvertKey`, `luksAddKey`, `luksChangeKey` have `--key-slot` option but not `luksRemoveKey`.
I'll ask Luks guys if there is a good reason for this.

**Comment by gasinvein** [comment]
I'm not a UI expert, but maybe make the "confirmated remove" button non slot specific and put it to the right of the plus button (the one for adding slots), so it won't refer to any particular key slot?

**Comment by marusak** [comment]
> maybe make the "confirmated remove" button non slot specific and put it to the right of the plus button (the one for adding slots), so it won't refer to any particular key slot?

That is one option that I ma thinking of. The other one being using `luksKillSlot` without `-q` and confirming with remaining passphrase (not the one you are removing).

Not sure what is the best way forward. @garrett WDYT?

**Comment by garrett** [comment]
Can we get a listing of the keys to remove? Or have some association between the key and the slot? Or is it all tied to a password?

**Comment by garrett** [comment]
Is this because we're using `luksRemoveKey` but should be using `luksKillSlot`? Would that match with the UI?

**Comment by marusak** [comment]
> Can we get a listing of the keys to remove? Or have some association between the key and the slot? Or is it all tied to a password?

The situation is: You can have multiple passphrases - each is presented as one slot. So when you create your encrypted partition you have one slot with one passphrase. Then you can add another passphrase that is presented as another slot.

When it comes to deleting. Lets say we have `Slot 1` with passphrase `foo`, `Slot 2` with `bar` and `Slot 3` with `foobar`. You can either say "Remove passphrase foo" and it would remove `Slot 1` or you can say "Remove Slot 1" (which we currently have as well but without passphrase confirmation, we can add it and it would require any other passphrase).

> Is this because we're using luksRemoveKey but should be using luksKillSlot? Would that match with the UI?

We have both. One is with and the other without passphrase. Here are screenshots (the UI is broken, needs some attention :) )

This is when I click on the `-` icon next to `Slot 1`
![removepassphrase](https://user-images.githubusercontent.com/12330670/116874641-ecaf3f80-ac19-11eb-8fe3-8ec511bd5b86.png)

This is the other radio button:
![dangerous](https://user-images.githubusercontent.com/12330670/116874688-018bd300-ac1a-11eb-8dd8-49873d2536e1.png)

We can actually request in the other option passphrase for different slot. We don't enable deleting the last slot anyway. But maybe user would still like to remove the passphrase without confirmation? Should we then just have the other option (which uses `luksKillSlot`) and have checkbox like `Don't require confirmation` or something?

**Comment by marusak** [comment]
Actually! Now that I read the UI properly we say `Confirm removal with passphrase` not `Remove passphrase` so I think we really just want to use `luksKillSlot` and confirm it with any other passphrase.

So this is misunderstanding of what `luksRemoveKey` does.

**Comment by garrett** [comment]
> Actually! Now that I read the UI properly we say Confirm removal with passphrase not Remove passphrase so I think we really just want to use luksKillSlot and confirm it with any other passphrase.
>
> So this is misunderstanding of what luksRemoveKey does.

Yep! That's what I thought, when reading the conversation here and in the man page. OK, so the solution should be easier, right?

> Here are screenshots (the UI is broken, needs some attention :) )

:scream: 

I'm glad you recognize this! :wink: Please let me know if you'd like help fixing the UI, if you wonder what anything would look like. Otherwise, I would still definitely like to see the fixes and approve them. These are... not correct. I'm not sure what happened. Perhaps they were made in the PF3 days and were ported oddly?

(Or is this just a first pass at fixing it where you're only interested in the functionality?)

The "Remove passphrase in *key slot 1*" should be the modal title, like specified @ https://www.patternfly.org/v4/components/modal/design-guidelines/#confirm-a-destructive-action:

That is, like this:

![Screenshot_2021-05-03 PatternFly 4 • Modal](https://user-images.githubusercontent.com/10246/116878748-123f4780-ac20-11eb-8109-f324a92b72ea.png)

**Comment by marusak** [comment]
> OK, so the solution should be easier, right?

It is, I have fix already working.

> That is, like this quick mod of a PF4 example:

Good call! I was just wondering how to fit all the text in. I am now wondering how we want to do the "Enter passphrase" or "Force remove without passphrase". Do you have idea for the best practice?

**Comment by garrett** [comment]
> It is, I have fix already working.

:+1: 

Since this is a binary state (password or not, we could make it a checkbox in this case, with a default on with a password expected. And since it can be dangerous to remove it without a password, we could keep the warning at the bottom when the password is unselected.

![luks-remove-passphrase](https://user-images.githubusercontent.com/10246/116882727-0f932100-ac25-11eb-9246-616d0e285103.png)

Having a second icon is probably redundant. The whole thing can (intentionally) cause "data loss" (password metadata in this case), so the singular icon at the top is fine enough. And the text being dangerous red at the bottom makes sense.

![luks-remove-force](https://user-images.githubusercontent.com/10246/116882861-39e4de80-ac25-11eb-9736-554bc4434db0.png)

Note: I messed up and used "Delete" in the earlier quick mockup. "Remove" is correct, as it already is, and I've fixed it in these sketchy mockups.

**Comment by garrett** [comment]
An alternative approach would be to always ask for the confirmation and have a force removal... But I don't like this. It changes stuff above it, which is odd. And it becomes extra verbose.

![luks-remove-alternative](https://user-images.githubusercontent.com/10246/116884219-c6dc6780-ac26-11eb-8b19-208434739af2.png)

And here's another take, with the force remove a secondary action... but it doesn't have a warning. (Popping up a second dialog would be odd.)

![luks-remove-alternative-2](https://user-images.githubusercontent.com/10246/116884293-dfe51880-ac26-11eb-8cd2-c443350f940e.png)

Anyway, I think that's why we should go with my previous comment's designs instead.

**Comment by marusak** [comment]
Problem of this dialog (and there are more of them) is that they use rather restricted set of components and very restricted layout.
Right now it requires that we use only `Label   Field` kind of structure - therefore there is this huge gap on left as it expects to have some label. Of course text does not have any label.
I think that worst case scenario I could use custom dialog and diverge from what we are doing in storage in general.

**Comment by garrett** [comment]
Oh, are you talking about the storage dialog generator abstraction? Yeah, I guess it was useful back in the pre-PatternFly-3 days, but making a dialog in React with PF4 isn't as difficult now as it was back then.

Please implement it how you see fit instead of feeling forced to use the abstraction.

**Comment by mvollmer** [comment]
> therefore there is this huge gap on left as it expects to have some label.

They used to look okay at some point. We must have missed this layout regression when porting to PF4.

**Comment by garrett** [comment]
> They used to look okay at some point. We must have missed this layout regression when porting to PF4.

Yep, totally.

**Comment by mvollmer** [comment]
>  Yeah, I guess it was useful back in the pre-PatternFly-3 days, but making a dialog in React with PF4 isn't as difficult now as it was back then.

I think it still saves a lot of boilerplate related to state management and input validation.
