### ISSUE TITLE
tests: services: remove dependency from sockets.target

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit#15838]
In rhel-8-5.0 tests for services page seem to fails on sockets.target not running. There is not need to check this specific target, let's create a robust dummy one.

```
Traceback (most recent call last):
  File "test/verify/check-system-services", line 187, in testBasic
    self.wait_service_state("sockets.target", "active")
  File "test/verify/check-system-services", line 82, in wait_service_state
    self.browser.wait_in_text(self.svc_sel(service), state_new)
```

**Comment by martinpitt** [comment]
sockets.target seemed like an appropriate choice to me -- it has been a standard early-boot systemd target for many years (see  man systemd.special), and if it fails, cockpit.socket would not run either as that is installed into sockets.target. So that RHEL 8.5 gating VM seems rather broken. But indeed, we can create a synthetic target or use sysinit.target.

**Comment by martinpitt** [comment]
I analyzed this in the downstream PR a bit. TL/DR: Let's move to basic.target.
