### ISSUE TITLE
exposing ports for images that does not have expose syntax in their dockerfile

### ISSUE THREAD

**Issue by hrezaee** [cockpit-project/cockpit#1587]
When the EXPOSE directive in the docker image is not used, no ports are exposed.

But there's an alternative way to expose ports using the -p or --publish option while running a container from the command line.

Perhaps cockpit should detect that the expose syntax is not used, and offer to expose additional ports while running the container?

Or give a notification that let's the user know that no ports will be exposed.

**Comment by dperpeet** [comment]
I suggest doing both. If no ports are exposed by default, instead of the "bind to" fields we can display a warning "No ports exposed by default."

Additionally we add fields to populate the -p option:
host port, container port, protocol (tcp/udp)
Do we want to specify an interface as well?
We have to be a bit careful, because the interface may have a default value from Docker server settings

**Comment by andreasn** [comment]
Trying to leverage this with EXPOSE ports and establishing a common pattern with issue #1297

![Mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/containers/docker-ports.png)

**Comment by andreasn** [comment]
I can't quite make up my mind about if it should warn when no ports from EXPORT are mapped, because ideally it should be possible to just hit "Run" without changing any parameters and have a container up and running. On the other hand some containers are fairly unusable without any ports exposed.
I have odiobill/transmission running here at home with only 9091 exposed, even though it ideally also want 51413 and 51413/udp running. So I guess it should be possible to at least run it without specifying all EXPOSE ports.

**Comment by andreasn** [comment]
Note that there is no solution for the -P/--expose-all command above, partly because docker gives out those randomly generated numbers only once you hit the Run button. Otherwise we could have given it a random number by default instead of "none" in the host port input boxes.

**Comment by dperpeet** [comment]
If a container defines ports to be exposed, I think a user shouldn't be able to delete those rows. Also, their internal port should be non-editable. Otherwise you could delete a row by accident and to restore the default state you would have to close and reopen the dialog.

**Comment by andreasn** [comment]
All right, I think that could work.

**Comment by andreasn** [comment]
https://github.com/andreasn/cockpit/tree/expose-extra-ports

**Comment by stefwalter** [comment]
Submitted related patternfly styling issue here: https://github.com/patternfly/patternfly/issues/45

**Comment by stefwalter** [comment]
Using: fedora/apache:latest image. When i try to map predefined port 80 ->33333 and add an additonal port 8080 -> 80028, i get this error:

![screenshot from 2015-01-22 11 45 33](https://cloud.githubusercontent.com/assets/795070/5854273/43aa1746-a22c-11e4-9f65-18660d956355.png)
