### ISSUE TITLE
Navigation menu bug

### ISSUE THREAD

**Issue by tijanicm** [cockpit-project/cockpit#15975]
Hi,

I noticed that sometimes when I click on the navigation buttons they do nothing so I inspected the code and saw that the padding is on the element around the link.

Maybe you could set the padding on the link instead so there is no more confusion. :)

My Cockpit version is 243.

![cockpit-navigation](https://user-images.githubusercontent.com/11855714/122730282-580ca980-d27a-11eb-86ce-ceff867672a0.png)

**Comment by KKoukiou** [comment]
Thanks for reporting this @tijanicm. @garrett let's fix it by doing what PF does in the navigation, https://www.patternfly.org/v4/demos/primary-detail/react-demos/primary-detail-full-page/ 

They don't have this issue upstream.

**Comment by garrett** [comment]
I know for a fact that this used to work properly. We used to have the padding on `a`. I guess it changed at some point. The problem is that we have a link class on the span now for some reason.

**Comment by garrett** [comment]
I'm looking at this and I see what happened. It looks like this was changed to a span wrapper when we added status icons...

(BTW: @tijanicm: Thanks for pointing this out!)

**Comment by tijanicm** [comment]
Glad I could help a bit.

Keep up the good work!

**Comment by garrett** [comment]
@KKoukiou: We're actually using grouped nav:

https://www.patternfly.org/v4/components/navigation#grouped
https://www.patternfly.org/v4/components/navigation/react/grouped/
https://www.patternfly.org/v4/components/navigation/html/grouped-nav/

It has different sizes / padding / separators (none) than default simple nav. But they don't have this issue because status notifiers were sandwiched inside of a span and the CSS wasn't adapted.

I have a PR that I've been working on today that fixes a bunch of related things, including the `<a>` coverage, and more closely aligns our nav to PF4 (using the CSS from PF4 instead of overriding it to make it look like the current PF4 style, which was needed in the past, when PF4 navigation looked different)... and it make the entire element clickable again.

Sending in a few minutes.
