### ISSUE TITLE
browser terminated TLS websocket connection

### ISSUE THREAD

**Issue by xCallMeNoah** [cockpit-project/cockpit#15980]
Cockpit version: Newest
OS: Ubuntu 20.04 LTS
Page: https://muxxlenetzwerk.at:9090/

![image](https://user-images.githubusercontent.com/67311138/122951477-99d24880-d37d-11eb-961d-5874f64c781b.png)
![image](https://user-images.githubusercontent.com/67311138/122951599-afe00900-d37d-11eb-90ca-b30546e902e6.png)

**Comment by martinpitt** [comment]
This error message mostly just says "The browser terminated the connection", in most cases because it doesn't like the server's TLS certificate. In this case, it seems the static page contents actually *do* load (did you get and approve the self-signed cert warning?), but the websocket connection fails.

Is this a MacOS/iOS Safari browser by any chance? If not, please try this in a fresh browser profile without extensions. There seem to be several popular extensions around which break websockets.

**Comment by martinpitt** [comment]
Closing this, as there was no update, and this is not actionable. There are several similar reports about this, e.g. #16143. There seem to be some popular browser extensions or the like around which break the websocket TLS..
