### ISSUE TITLE
Javascript enable issue

### ISSUE THREAD

**Issue by dpk89** [cockpit-project/cockpit#16013]
Cockpit version: xxx
OS:Linux/Ubuntu

While doing this - mount -  mount -o bind dist/static/ /usr/share/cockpit/static/
Error : http://i.imgur.com/6LBaeyV.png
Getting javascript enable issue issue on login page

I want to add menus in sidebase and want to add a iframe on page.

Steps to reproduce

1.Clone cockpit
2. mount -o bind dist/static/ /usr/share/cockpit/static/
3.Login page refresh

**Comment by garrett** [comment]
It looks like you're trying to build Cockpit and see changes locally _on the login page_.

1. Is your goal to edit the login page specifically? Or some other part of Cockpit? (If the login page, continue below. Otherwise, you don't need to do a bindmount of the static page, but would need to do some setup according to the "[HACKING](https://cockpit-project.org/external/source/HACKING)" document.)
2. Did you build Cockpit in-between cloning it and doing the bind mount? (see https://cockpit-project.org/external/source/HACKING#building)
   - `./autogen.sh --prefix=/usr --enable-debug`
   - `make -j4`
3. Did you restart the Cockpit session between the bind mount and reloading the page? (see https://cockpit-project.org/external/source/HACKING#working-on-your-local-machine-web-server)
   - `systemctl stop cockpit.service`
4. Which browser are you using?

If you aren't working on the login page specifically, please read:
- https://cockpit-project.org/external/source/HACKING
- And other guides at https://cockpit-project.org/external/wiki/Contributing.html — especially those under "further reading" at the bottom of the page, such as the "starter kit".

**Comment by garrett** [comment]
Oh, and please let us know here if my previous comment answers the issue you were facing.

**Comment by dpk89** [comment]
Hi ,
I want to add new modules into cockpit .

I am doing the following steps, but menus not reflecting at front-end

adding new module into pkg folder and linking to usr/share/cockpit

Then getting the above issue and also tried login module changes

**Comment by martinpitt** [comment]
@dpk89 : If you want to add a new module (we call that "page"), i.e. an entry in the cockpit session's left menu, then you don't need the bind mounting of dist/static. Instead, [set up the symlink](https://github.com/cockpit-project/cockpit/blob/main/HACKING.md#working-on-your-local-machine-cockpits-session-pages) so that the pages are served from your build tree.

Moreover, as you want to add a *new* module, I strongly suggest to not start from cockpit.git, as that is unnecessarily complex, and hard to maintain from your side. Instead, [have a look at starter-kit](https://cockpit-project.org/blog/cockpit-starter-kit.html), that blog post shows you all the steps from scratch to "I see my new page in the browser", and it is *much* easier to  work with.

**Comment by dpk89** [comment]
I have done from - ln -s $(pwd)/dist /usr/share/cockpit
Is it fine?

**Comment by dpk89** [comment]
I have added the package in pkg folder and want to build it.

But its not reflecting in sidebar

**Comment by dpk89** [comment]
Hi,

My build folder is showing changes done in login page but its not showing at front end?

What can be the issue?

**Comment by dpk89** [comment]
Now changes reflected but login showing - http://i.imgur.com/W8tyCqA.png
and unable to login

**Comment by martinpitt** [comment]
@dpk89 : Again, please don't do the dist/static bind mounting, you do *not need* that. Check https://cockpit-project.org/blog/cockpit-starter-kit.html how to create and use a new Cockpit page.
