### ISSUE TITLE
CentOS 8 Stream - missing 'Export to Network' option under 'Metrics settings'

### ISSUE THREAD

**Issue by PeterFalken** [cockpit-project/cockpit#16054]
Cockpit version: 247 - using Cockpit Preview
OS: CentOS Stream 8
Page: Overview > (Usage) Performance Metrics

The option 'Export to Network' under 'Metrics settings' is missing.

Steps to reproduce

1. Clean install of CentOS Stream 8
2. sudo dnf -y install epel-release
3. sudo dnf copr enable @cockpit/cockpit-preview
4. sudo dnf -y install cockpit cockpit-packagekit cockpit-pcp cockpit-storaged

Expected results:
![metrics-settings-2](https://user-images.githubusercontent.com/2557898/124678037-face4600-de7e-11eb-8b10-e4645bfd2baf.png)

The results I got:
![CentOS8_Metrics](https://user-images.githubusercontent.com/2557898/124678055-06217180-de7f-11eb-97a7-6a9f13a7048f.png)

**Comment by KKoukiou** [comment]
@PeterFalken there is a check in the code in the version you are using which makes the switch is hidden when pmproxy or redis are not installed.

In next release (248) which will happen today, these package are installed on demand if they are missing, and the switch is always visible. 

Fixed by: https://github.com/cockpit-project/cockpit/commit/1694295128b2b569a47f8b2b13a4aa0e2f76c253

**Comment by martinpitt** [comment]
Indeed, thanks @KKoukiou . Closing. Please let us know if you still get this with 248.

**Comment by PeterFalken** [comment]
Thanks @KKoukiou and @martinpitt - I'll check the new 248 release. On my system the pmproxy service was installed but not redis. So not sure if both must exist at the same time or just one.

**Comment by martinpitt** [comment]
@PeterFalken : You need both for metrics export. 248 will install that as needed (with a confirmation dialog)
