### ISSUE TITLE
Apache proxying to cockpit in HTTPS mode - Authentication failed page, no log information

### ISSUE THREAD

**Issue by morphet81** [cockpit-project/cockpit#16113]
Cockpit version: 215-1
OS: Ubuntu 20.04

Hi everyone!

I've freshly installed a new version of cockpit on my server and created a proxy through Apache. My firewall disallow port 9090. I disabled SSL by setting `AllowUnencrypted` option to `false`. My Apache server handles the SSL connection.

I can access the login page from the domain I assigned to my server but when I try to login I've got a connection failed message. The page is correclty loaded in HTTPS mode. No useful information comes in the logs, below:

```
Jul 17 04:49:02 scw-laughing-heyrovsky systemd[1]: Starting Cockpit Web Service...
Jul 17 04:49:02 scw-laughing-heyrovsky systemd[1]: Started Cockpit Web Service.
Jul 17 04:50:36 scw-laughing-heyrovsky systemd[1]: cockpit.service: Succeeded.
Jul 17 06:56:40 scw-laughing-heyrovsky systemd[1]: Starting Cockpit Web Service...
Jul 17 06:56:40 scw-laughing-heyrovsky systemd[1]: Started Cockpit Web Service.
Jul 17 06:58:47 scw-laughing-heyrovsky systemd[1]: cockpit.service: Succeeded.
Jul 17 06:59:45 scw-laughing-heyrovsky systemd[1]: Starting Cockpit Web Service...
Jul 17 06:59:45 scw-laughing-heyrovsky systemd[1]: Started Cockpit Web Service.
Jul 17 07:01:42 scw-laughing-heyrovsky systemd[1]: cockpit.service: Succeeded.
Jul 17 07:03:33 scw-laughing-heyrovsky systemd[1]: Starting Cockpit Web Service...
Jul 17 07:03:33 scw-laughing-heyrovsky systemd[1]: Started Cockpit Web Service.
Jul 17 07:06:33 scw-laughing-heyrovsky systemd[1]: cockpit.service: Succeeded.
```

Here is my Apache configuration file:

```
<IfModule mod_ssl.c>
<VirtualHost *:443> 
  ServerName cockpit.obellianne.fr

  RewriteEngine On
  RewriteCond %{HTTP:Upgrade} =websocket [NC]
  RewriteRule /(.*)           wss://127.0.0.1:9090/$1 [P,L]
  RewriteCond %{HTTP:Upgrade} !=websocket [NC]
  RewriteRule /(.*)           http://127.0.0.1:9090/$1 [P,L]

  ProxyRequests off
  ProxyPreserveHost on
  AllowEncodedSlashes NoDecode

  ProxyPass / http://localhost:8080/ nocanon
  ProxyPassReverse / http://localhost:8080/

  RequestHeader set X-Forwarded-Proto https
  RequestHeader set X-Forwarded-Port 443

  SSLCertificateFile /etc/letsencrypt/live/cockpit.obellianne.fr/fullchain.pem
  SSLCertificateKeyFile /etc/letsencrypt/live/cockpit.obellianne.fr/privkey.pem
  Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
```

I tried to enable SSH authentication by password because it was disabled, it did not fix the issue.

Do you know what is the issue?

**Comment by eagerestwolf** [comment]
Quick question, do you have those Let's Encrypt certs linked to your `/etc/cockpit/ws-certs.d/` directory? If so, that's the problem. `cockpit-ws` doesn't run with root privileges (for security reasons), and only root can even *see* those Let's Encrypt files, much less ***read*** them (again, for security reasons). If you are using Apache to proxy the requests to Cockpit, they aren't needed anyway because Apache (as well as Nginx and HAProxy) don't care if a proxy connection is actually secure, they handle all the SSL themselves, so the built-in self signed certificate is fine.

**Comment by eagerestwolf** [comment]
Actually the problem is way more simple. The Apache config is wrong, unless you changed Cockpit's port to 8080. Sorry I didn't notice that with my first comment, I'm not the best with Apache, I prefer Nginx. I assume below is what you wanted. You want to upgrade `ws://` requests to `wss://`, upgrade `http://` requests to `https://`, and redirect everything to Cockpit.

```apacheconf
<IfModule mod_ssl.c>
	<VirtualHost *:443>
		ServerName cockpit.obellianne.fr
		
		RewriteEngine On
		RewriteCond %{HTTP:Upgrade} =websocket [NC]
		RewriteRule /(.*)           wss://127.0.0.1:9090/$1 [P,L]
		RewriteCond %{HTTP:Upgrade} !=websocket [NC]
		RewriteRule /(.*)           https://127.0.0.1:9090/$1 [P,L]

		ProxyRequests off
		ProxyPreserveHost on
		AllowEncodedSlashes NoDecode

		ProxyPass / https://localhost:9090/ nocanon
		ProxyPassReverse / https://localhost:9090/

		RequestHeader set X-Forwarded-Proto https
		RequestHeader set X-Forwarded-Port 443

		SSLCertificateFile /etc/letsencrypt/live/cockpit.obellianne.fr/fullchain.pem
		SSLCertificateKeyFile /etc/letsencrypt/live/cockpit.obellianne.fr/privkey.pem
		Include /etc/letsencrypt/options-ssl-apache.conf
	</VirtualHost>
</IfModule>
```
`ProxyPass` passes an incoming connection `/` to a server or application (i.e. Cockpit). Also you aren't actually going to upgrade any connections because you're only listening on port 443.

**Side note**: unless you changed Cockpit's configuration, you still have to do `https://` because by default Cockpit doesn't allow non `https` connections, even locally.

**Comment by martinpitt** [comment]
Thanks @eagerestwolf for your help with Apache config! Just to clarify:

> you still have to do https:// because by default Cockpit doesn't allow non https connections, even locally.

That's not true -- on localhost/127.0.0.1, cockpit-ws *does* allow http. Try http://localhost:9090 in a private browser window. It may look that way because browsers remember a redirection to https:// if you ever used https locally. But cockpit-ws does not set HSTS.

**Comment by martinpitt** [comment]
In fact, I think it's a lot easier to leave TLS entirely to the reverse proxy, and use cockpit-ws in plain http *only*. No fiddling with certificate permissions, and no pointless re-encryption along the way. Usually on cockpit you want to have the same certificate as the other pages on Apache, not a cockpit-specific cert.

**Comment by martinpitt** [comment]
@morphet81 : So indeed it looks like you simply got the ports wrong:

>  ProxyPass / http://localhost:8080/ nocanon
>  ProxyPassReverse / http://localhost:8080/

This must be 9090, as you already specified in your RewriteRules.

Also see https://github.com/cockpit-project/cockpit/wiki/Proxying-Cockpit-over-Apache-with-LetsEncrypt which documents this case.
