### ISSUE TITLE
GPT Partition Support

### ISSUE THREAD

**Issue by FireDrunk** [cockpit-project/cockpit#1621]
I've just installed Cockpit on a Minimal Fedora 21 VM. First impression: Awesome!
Works like a charm!

But i found one "bug". It looks like Cockpit doesn't support GPT Partition Labels.
Partitions are still shown by their "old" /dev/sd[a-b][0*] identification.

Would it be possible to make Cockpit check for partition labels in /dev/disk/by-partlabel/ ?

**Comment by stefwalter** [comment]
@mvollmer Do you have comments here? Is this a limitation of udisks?

**Comment by cmurf** [comment]
Seems to be missing from udisksctl -b /dev/sda1 output for me. The IdLabel field is blank, and Symlinks lacks /dev/disk/by-partlabel. It does have /dev/disk/by-id and /dev/disk/by-partuuid though.

Open question if it's more useful to show partition labels or volume labels; typically we care more about locating the fs volume (which may be on more than one partition or not on a partition at all) and hence deference to volume label and volume uuid. Certainly for disk failures /dev/disk/by-id is useful.

**Comment by FireDrunk** [comment]
If you use the Fedora 21 Installer to set the Labels ( it creates a MBR partition by default ), the labels do show up in Cockpit. I don't know about this udisksctl -b command, but i do have udisksctl.

The man page doesn't show anything regarding the command you posted, but it shows some different command options like [info, mount, unmount, unlock, lock, monitor and a few others].

Mayby the syntax has changed?

**Comment by cmurf** [comment]
User error. 
$ udisksctl info -b /dev/sda1

**Comment by FireDrunk** [comment]
Ah, that works fine indeed. If i use that command on a GPT label it doesn't recognize the label directly, but it is found in the Symlinks section.

```bash
[root@fed21 ~]# udisksctl info -b /dev/sdb1
/org/freedesktop/UDisks2/block_devices/sdb1:
  org.freedesktop.UDisks2.Block:
    Configuration:              []
    CryptoBackingDevice:        '/'
    Device:                     /dev/sdb1
    DeviceNumber:               2065
    Drive:                      '/org/freedesktop/UDisks2/drives/VMware_Virtual_disk_1'
    HintAuto:                   false
    HintIconName:
    HintIgnore:                 false
    HintName:
    HintPartitionable:          true
    HintSymbolicIconName:
    HintSystem:                 true
    Id:
    IdLabel:
    IdType:
    IdUUID:
    IdUsage:
    IdVersion:
    MDRaid:                     '/'
    MDRaidMember:               '/'
    PreferredDevice:            /dev/sdb1
    ReadOnly:                   false
    Size:                       1072676352
    Symlinks:                   /dev/disk/by-partlabel/disk-a
                                /dev/disk/by-partuuid/627dcadb-bb30-4b29-b6e0-23f8fc1e5409
                                /dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:1:0-part1
  org.freedesktop.UDisks2.Partition:
    Flags:              0
    IsContained:        false
    IsContainer:        false
    Name:               disk-a
    Number:             1
    Offset:             1048576
    Size:               1072676352
    Table:              '/org/freedesktop/UDisks2/block_devices/sdb'
    Type:               516e7cba-6ecf-11d6-8ff8-00022d09712b
    UUID:               627dcadb-bb30-4b29-b6e0-23f8fc1e5409

```

**Comment by mvollmer** [comment]
> Would it be possible to make Cockpit check for partition labels in /dev/disk/by-partlabel/ ?

Yes, we should improve this.

For example, if a block device has a filesystem with a label on it, we use that label when showing the block device (in some places) instead of the raw /dev/sda2.  We could extend this with partition labels, and allow the user to change the partition label.  It might get confusing though since then we have two labels for a block device...

Could you describe very concretely what you would like to see changed?  Just one or two examples would help us understand.

**Comment by mvollmer** [comment]
Also, how can I modify the label of a partition?  I am a bit naive here...

**Comment by FireDrunk** [comment]
GPT supports labels on partitions by default.

I'm using them, because i don't want to rely on ID's like sda or sdb. I'm a regular user of BTRFS and ZFS, and because of that, i often change harddrives. In my case, i always format the drives with gdisk, it can easily partition disks with labels and ZFS partition types.

From my home NAS:
```bash
root@storage:~# zpool status
  pool: datapool
 state: ONLINE
  scan: resilvered 9.63G in 0h5m with 0 errors on Tue Dec  9 10:09:46 2014
config:

        NAME            STATE     READ WRITE CKSUM
        datapool        ONLINE       0     0     0
          raidz1-0      ONLINE       0     0     0
            datapool-A  ONLINE       0     0     0
            datapool-B  ONLINE       0     0     0
            datapool-C  ONLINE       0     0     0
            datapool-D  ONLINE       0     0     0

errors: No known data errors
```
This is my main "point-of-view" regarding my harddrive setup. I look at the GPT labels as my "disks".
These are all labels to a single partition on a drive.

The perspective of Cockpit regarding physically detected drives on the right is fine, but it would be nice if it shows the drives not as detected by the OS (/dev/sda1 etc) but with their GPT labels.

To me, the GPT label is more important then the OS ID that was given by the kernel.

I don't know whether other GPT users agree, they might have a different opinion regarding the 'sorting' or importance of the GPT labels. But at this moment, GPT labels aren't even shown.

It might be a good start, to get the GPT labels shown the same way regular MBR partition labels are shown.

It's always possible change the UI afterwards to better accomodate the needs of many.

**Comment by cmurf** [comment]
Looks like:
parted -s /dev/sdX name Y Z
X is the drive letter
Y is the partition number
Z is the desired name
I haven't tested it yet.

Also note that MBR does not support partition labels. I'm not sure what "It might be a good start, to get the GPT labels shown the same way regular MBR partition labels are shown." means.

**Comment by FireDrunk** [comment]
MBR Member disk:
![mbr_member](https://cloud.githubusercontent.com/assets/6359704/5661280/4c9bc64a-972a-11e4-83dd-2ce0a9e6856e.PNG)

ZFS Member disk:
![zfs_member](https://cloud.githubusercontent.com/assets/6359704/5661284/513ba86e-972a-11e4-94e7-2b2b3969f919.PNG)

```bash
[root@fed21 ~]# gdisk /dev/sdb
GPT fdisk (gdisk) version 0.8.10

Partition table scan:
  MBR: protective
  BSD: not present
  APM: not present
  GPT: present

Found valid GPT with protective MBR; using GPT.

Command (? for help): p
Disk /dev/sdb: 2097152 sectors, 1024.0 MiB
Logical sector size: 512 bytes
Disk identifier (GUID): 5AC1226F-1E59-4C8C-A0C2-011EDD150DC7
Partition table holds up to 128 entries
First usable sector is 34, last usable sector is 2097118
Partitions will be aligned on 2048-sector boundaries
Total free space is 2014 sectors (1007.0 KiB)

Number  Start (sector)    End (sector)  Size       Code  Name
   1            2048         2097118   1023.0 MiB  A504  disk-a

```

It shows the disk as /dev/sdb1 but i would rather see data-a.
Maybe it's an idea to introduce more colums to the view:

GPT Label (device id) / Content / Size / Mountpoint / Options

For example:

disk-a (/dev/sdb1) / GPT Partition (ZFS Member) / 1.0GB / dropdown-menu

Or:

/dev/sda1 / Primairy Partition (EXT4 Filesystem) / 2.0GB / dropdown-menu

Does this make more sense?

**Comment by cmurf** [comment]
The MBR example is probably showing volume labels. Again, MBR doesn't support partition labels. The ZFS example is probably showing the pool name, matching up with zpool list, rather than filesystem or volume name which would be found with zfs list. So at the moment it's actually consistent behavior. What do you get for the command blkid?

**Comment by FireDrunk** [comment]
```bash
/dev/sda1: UUID="b4c374e6-0495-4f2e-9fc8-4bcd06ccf145" TYPE="ext4" PARTUUID="5b91976a-01"
/dev/sda2: UUID="5c6ee14d-b625-485a-ad11-e2b8c02ef94a" TYPE="swap" PARTUUID="5b91976a-02"
/dev/sda3: LABEL="fedora-server_fed21" UUID="e7c76b62-6ffd-4a85-8cc5-a203b9dd6f83" UUID_SUB="50506f68-c956-4559-823c-2fc6f9fd0ff4" TYPE="btrfs" PARTUUID="5b91976a-03"
/dev/sdb1: LABEL="testpool" UUID="6698647556592896889" UUID_SUB="643085828347197485" TYPE="zfs_member" PARTLABEL="disk-a" PARTUUID="627dcadb-bb30-4b29-b6e0-23f8fc1e5409"
/dev/sdc1: LABEL="testpool" UUID="6698647556592896889" UUID_SUB="9584204983327509401" TYPE="zfs_member" PARTLABEL="disk-b" PARTUUID="fd73e63b-b22a-4d92-bd46-7c1e9c4c812f"
```

Indeed, the disk label is different from the partition label when it comes to blkid.

**Comment by cmurf** [comment]
Yeah everyone keeps reinventing the terminology for every new fs and project it seems.

"disk label" is used to refer to a partition scheme, i.e. MBR and GPT are disk labels. This may have started as a parted convention, but it's common now. Neither MBR nor GPT have a literal disk label, which to me means a user defined name for a physical block device. There's no place to store such a thing.

UEFI spec defines PartitionName which is what gdisk c command, and parted name command, and blkid (and fstab) refer to as PARTLABEL. Just plain LABEL is a filesystem volume name (label) and is contained in the fs volume metadata, typically set at mkfs time.

I think most users are interested in volume name (i.e. LABEL). I think the partitioname is less useful generically because, well, MBR doesn't have such a thing at all. And also because in multiple device configurations, only one partition is shown to be mounted by the kernel anyway. For example an sdb1 sdc1 in a btrfs raid1, when mounted only one of those devices will show up in /proc/self/mountinfo or with the mount command, and it may not be the device you specified with the mount command. The volume label is more reliable.

This isn't to say support partition labels is bad or wrong, I just think it requires caution because of the above inconsistencies, whereas volume label (name) is consistently available up to the moment the volume is destroyed (which doesn't destroy the partition).

Where I'd find partition labels useful would be to track LVM PVs. The only thing that's really useful for finding a dead drive in a RAID or something though is disk/by-id.

So my two cents is that only "volume labels" should appear in the non-detail view rather than the block device(s) underlying it.

**Comment by FireDrunk** [comment]
I fully agree, and your analsysis on when it would be useful is flawless. So to move forward with this, what would be the best way to get the information in the detail overview of the partition? Because it's even missing there?

**Comment by cmurf** [comment]
It's a question for udisks2 / storaged folks if it is expected to support GPT partitionname/PARTNAME. I'm not sure if python-blivet does, but it supports a bunch of stuff udisks2 doesn't yet including LVM thin pools and virtual sized LVs, btrfs multiple device and subvolumes. In the short term even the thinp stuff is useful. Medium/longer term the btrfs stuff also.

**Comment by mvollmer** [comment]
Sorry for letting his sit for so long.  Is there anything concrete that needs changing?  Otherwise I am inclined to close this issue, to keep the books clean.
