### ISSUE TITLE
logs: Services appear as "systemd"; the actual service name link is too far away and not obvious

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#16495]
When viewing the logs page, services are attributed to systemd. Discovering the actual service and getting to the service page are both difficult.

Here's a screenshot from one of the tests (it's in 1280x720 resolution):

![Screenshot from 2021-10-19 14-18-38](https://user-images.githubusercontent.com/10246/137907969-8fd57c2d-202c-4ca3-9283-3918aaaa849f.png)

(Found in the Metrics UX study.)

This is actually worse in higher resolution, at 2560x1440 (cropped):

![image](https://user-images.githubusercontent.com/10246/137908423-cdd4ab4c-361d-4e37-adba-81e2b2e9e285.png)

We should probably:

1. Handle systemd activated services differently in the details (prioritizing the service name)
2. Move the link from the far right to the immedate right, near the title (to the right or below)
3. (Optionally) Make the link more inviting, perhaps by saying "View XXX service" instead of "Go to"'?
4. Section off all the debug information. The presentation is distracting and it takes away from the service name and the message.

**Comment by KKoukiou** [comment]
The 'systemd' title is because systemd is the SYSLOG_IDENTIFIER here. So this issue is not specific to systemd, but all services which have SYSLOG_IDENTIFIER other than the service name. 

Maybe we can do:
systemd (chatty.service) or maybe but the UNIT name in the first line above CODE_FILE, now it's a bit later, see UNIT.
