### ISSUE TITLE
bridge PATH for ssh logins

### ISSUE THREAD

**Issue by petervo** [cockpit-project/cockpit#1673]
When you login with ssh, PATH is determined by the user you are using that machine with. We need to decide if we want to hard code PATH in the bridge to ensure it's always consistent with non ssh logins or we want to allow machine specific PATHs.

**Comment by stefwalter** [comment]
Yes :)

**Comment by martinpitt** [comment]
I'm not at all convinced that this is a good idea. Our [second ideal](https://cockpit-project.org/ideals.html) says that Cockpit should work with existing APIs and configuration, not impose its own idea. If the remote machine e. g. adds /opt to the path to use a third-party Python or clevis or what not, we should respect that.

In other words, Cockpit ssh logins should be "more" consistent to CLI ssh logins to the same machine than in between machines.

@stefwalter, WDYT?

**Comment by marusak** [comment]
This issue is closed due to inactivity.

If this issue is a bug report and you are still able to reproduce it, please
comment here and provide us with an updated reproducer.

If this issue is a request for a new feature, we are sorry, but we won't be able
to address this in any time soon. If you are interested in helping us with
the implementation, please comment here.
