### ISSUE TITLE
Feature Request - Allow setting a default host & port to connect to

### ISSUE THREAD

**Issue by jpf91** [cockpit-project/cockpit#16757]
It would be great to make it somehow possible to define a default SSH host and port to connect to. I'm currently running Fedora CoreOS and cockpit in a container as recommended. However, my CoreOS host provides a container based SSH fileserver on port 22 so the management SSH port for the host is 2222. Right now I have to specify the target host on every login, so it would be great if I could confdigure a default instead.

Originally filed [here](https://github.com/cockpit-project/cockpit-container/issues/29), but I think this needs to be addressed directly in cockpit.

**Comment by marusak** [comment]
We have introduced something similar for cockpit-client. You can now click on item and it would connect you in. Maybe the same approach would work? It would require one more click, but you would not have to fill in the value.

We even talked about this when I was implementing this feature to always show it, but we decided not to, since when you click item now, it direcly logs you in, but in your use case you need to type in username and password. But I think we could make it work like this:
- If username and password is filled and you click on recent host, it logs you in
- If username or password is not filled and you click on recent host, it only prefills "connect to" field
- On cockpit-client it always logs you in

![Screenshot from 2021-12-10 08-09-06](https://user-images.githubusercontent.com/12330670/145532618-9e8f6d82-41cc-4185-b8f0-0fc00cdc1951.png)

@jpf91 would that work for you?
@garrett do you think it would make sense from UX perspective?

**Comment by garrett** [comment]
> We even talked about this when I was implementing this feature to always show it, but we decided not to...

Yep.

It would've required more effort to make it work properly on the browser log in page, but it was the end of the year and we wanted to add the feature to the desktop client. (The desktop client use local authentication, whereas your browser obviously can not. Therefore, the browser log in process must use a more traditional log in / password method. Getting that to work is more effort.)

For the in-browser log in page, we could _also_ remember the user. (Obviously, we shouldn't remember the password. :wink:)

Also, for the desktop client, we do ask for a password if that's not already handled via your ssh login method. (That is: When you ssh to a machine but don't have the auth set up for anything other than password.) But we don't ask for your user, as that's in the connect to string, in the `user@host` form. (`user@` is implied as your local user if it's left out, of course.) 

Back to the browser-based log in page, in addition to what you wrote above (in the list):
1. We would want to show the user field separately so the password field can be used as expected.
2. Browser-based pre-filling would need to work as expected, regardless of a saved `user@` in the quick log in part.

**Comment by jpf91** [comment]
@marusak That should work for me, one more click is perfectly fine.

I also just realized that the remote host can be given using the URL, e.g. `https://container.lan:9090/=container.lan:2222`. As I usually access the interface via a link anyway, I just adjusted that link for now :-)

**Comment by marusak** [comment]
Author figured out a different solution. Likely we won't need this as normal password managers plus the link as author suggested should cover majority of usecases .
