### ISSUE TITLE
Cockpit UI is unresponsive and cockpit-bridge consumes high CPU

### ISSUE THREAD

**Issue by stacymaughan** [cockpit-project/cockpit#16847]
I can't get Cockpit version 260 to work on Unbuntu Server 21.10. The web UI is unresponsive: most actions do nothing; switching to another tab shows a blank window or a spinning wheel. On the console, I can see that cockpit-bridge is consuming high CPU:
```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
  17993 stacy     20   0  628308 285128   7708 R  84.1   3.5   0:33.87 cockpit-bridge
    654 root      20   0  396232  13428  10596 S  18.9   0.2   0:17.86 udisksd
    395 root      20   0   24964   6428   3612 R  15.9   0.1   0:19.93 systemd-udevd
    637 message+  20   0    9432   5744   4272 S  11.6   0.1   0:09.53 dbus-daemon
      1 root      20   0   98976  10964   7812 S   2.7   0.1   0:06.90 systemd
```
If I logout of the web UI (one of the few things that seems to work), and log back in, I can see multiple version of cockpit-bridge spinning:
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
  53008 stacy     20   0  582196 335300   7636 R  32.1   4.2   0:23.02 cockpit-bridge
  17993 stacy     20   0 1736296   1.3g   7708 R  30.1  16.4   2:16.33 cockpit-bridge
    637 message+  20   0   11280   7784   4272 R  29.8   0.1   0:33.98 dbus-daemon
  60857 stacy     20   0  333724  91716   7584 R  27.5   1.1   0:03.58 cockpit-bridge
    654 root      20   0  396328  13448  10596 R  17.2   0.2   0:43.72 udisksd
    395 root      20   0   24964   6428   3612 S  15.2   0.1   0:45.82 systemd-udevd
    653 root      20   0   46452   7200   6352 S   3.0   0.1   0:06.31 systemd-logind
      1 root      20   0   98976  10968   7812 S   2.6   0.1   0:11.49 systemd
```
I started out with a fresh install of Ubuntu 20.04, and Cockpit installed from the default repo. As that didn't work, over time, I installed the backport versions, and upgraded to Unbuntu Server 21.10.

Besides that I've tried uninstall/reinstall multiple times/ways, e.g.:
```
sudo apt purge --auto-remove cockpit*

. /etc/os-release
sudo apt install -t ${VERSION_CODENAME}-backports cockpit
```
I've also tried removing a few individual cockpit related packages, adding some, and switching from networkd to NetworkManager.

**Comment by stacymaughan** [comment]
To make a very long story short, cockpit includes cockpit-storaged which includes udisksd which has a bug that causes it to spin when you have a ext4 file system with MMP enabled.  I solved my problem my disabling MMP on my filesystem.

Same thing happened on Fedora, by the way.

**Comment by garrett** [comment]
It appears this bug (MMP + ext4 in udisks causing high CPU) was reported upstream with udisks @ https://github.com/storaged-project/udisks/issues/946 and was fixed in https://github.com/storaged-project/udisks/pull/949.

It seems it's a regression in udisks version 2.7.6 and higher. The next version (currently unreleased) looks like it will have the fix. The current release (as of writing) is 2.9.4, released in October of 2021. Hopefully 2.9.5 (or whatever version they decide upon) will be released soon and built for all the various distros shortly afterward.

Meanwhile, your workaround of disabling MMP for ext4 (and being really careful to not mount it more than once) seems like the correct workaround.
