### ISSUE TITLE
Is there any way to let cockpit accept XFF header?

### ISSUE THREAD

**Issue by ZhiShengYuan** [cockpit-project/cockpit#16927]
It's possible that let cockpit accepts the X-FORWARDED-FROM header from localhost? this [document](https://cockpit-project.org/guide/latest/cockpit.conf.5.html) just says make it accept X-Forwarded-Proto, but if without XFF header the cockpit can log correct IP address,and without Nginx i can't use ssl_client_certificate

**Comment by allisonkarlitskaya** [comment]
We've wanted to implement this feature for some time now.

I just checked, and it seems that since 2014, IETF standardised the `Forwarded` header in RFC7239 as a replacement for `X-Forwarded-*`.  Ideally, we'd like to implement that, but on first glance, support for this header among reverse proxies seems a bit spotty.  I quick search for "Forwarded headers" for Apache, nginx and squid, in every case shows only results for X-Forwarded-For showing up...

I'm not sure if we'd be better off to implement the standards compliant version, or go with the one that's actually de-facto standard.

`X-Forwarded-For` would be easier to support, in any case, since it's (dramatically) easier to parse.

**Comment by jelly** [comment]
Going off from Arch's infrastructure most things seem to be standarized around `X-Forwarded-For`

```
[jelle@t14s][~/projects/infrastructure]%git grep X-Forwarded
roles/grafana/templates/nginx.d.conf.j2:        proxy_set_header X-Forwarded-For      $remote_addr;
roles/hedgedoc/templates/nginx.d.conf.j2:        proxy_set_header X-Forwarded-For $remote_addr;
roles/hedgedoc/templates/nginx.d.conf.j2:        proxy_set_header X-Forwarded-Proto $scheme;
roles/keycloak/templates/nginx.d.conf.j2:        proxy_set_header    X-Forwarded-For    $remote_addr;
roles/keycloak/templates/nginx.d.conf.j2:        proxy_set_header    X-Forwarded-Proto  $scheme;
roles/keycloak/templates/nginx.d.conf.j2:        proxy_set_header    X-Forwarded-For    $remote_addr;
roles/keycloak/templates/nginx.d.conf.j2:        proxy_set_header    X-Forwarded-Proto  $scheme;
roles/matrix/templates/homeserver.yaml.j2:#       X-Forwarded-For header as the client IP. Useful when Synapse is
roles/matrix/templates/nginx.d.conf.j2:        proxy_set_header X-Forwarded-For $remote_addr;
roles/matrix/templates/nginx.d.conf.j2:        proxy_set_header X-Forwarded-Proto $scheme;
```

**Comment by leomoty** [comment]
#13323 is also related

**Comment by MrSandyWilly** [comment]
Does this mean that once the change is implemented I'll be able to change `X-Forwarded-Proto` to `X-Forwarded-For` and I'll receive log messages with the correct IP?
