### ISSUE TITLE
Pixel tests: Unstable table label

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#16983]
Pixel tests are failing randomly with something that looks like shifted table columns. For example, TestMachinesStoragePools.testStoragePools:

![image](https://user-images.githubusercontent.com/3228183/153599286-fb7b5d06-9bdc-4b2b-b0ee-21f2b2009196.png)

We are ignoring the labels that this happens to for now, but it would be good to get at the bottom of this somehow and find a general approach.

**Comment by martinpitt** [comment]
@mvollmer: Did you file this against cockpit on purpose? That dialog is in c-machines.

**Comment by mvollmer** [comment]
> @mvollmer: Did you file this against cockpit on purpose? That dialog is in c-machines.

Yes, I think we should treat this as a problem of pixel tests in general, or the lib/cockpit-component-table.jsx in particular. We have also seen this in Cockpit, with the "ext2 filesystem" label.

**Comment by martinpitt** [comment]
It's very similar to [this common storage flake](https://logs.cockpit-project.org/logs/pull-16979-20220211-125657-dae63e2c-fedora-35/log.html), see https://logs.cockpit-project.org/logs/pull-16979-20220211-125657-dae63e2c-fedora-35/pixeldiff.html#TestStorageBasic-testBasic-partition

**Comment by garrett** [comment]
This could be a rounding error, where it's off by a pixel sometimes, as table cells are often computed based on the width of their content. It could also, in addition, be a timing issue where the table has a different width at different times (while it's figuring out how wide each cell could be).

The rounding being different could be due to floating point math.

While this page talks about divs with percentages, the same holds true for table cell math:
https://johnresig.com/blog/sub-pixel-problems-in-css/

Anyway, this would explain why the first cell (left aligned) and the last cell (right aligned) are consistent and the rest differ by a pixel.
