### ISSUE TITLE
Permssions UI

### ISSUE THREAD

**Issue by petervo** [cockpit-project/cockpit#1702]
We need to decide on a standardized UI for what the interface should look like when the user doesn't have permission to perform certain actions.

**Comment by stefwalter** [comment]
Current UI:

![screenshot from 2015-01-22 12 13 23](https://cloud.githubusercontent.com/assets/795070/5854676/abcb8072-a230-11e4-9e2e-2c77b6ab8a01.png)

Possible UI working with disabling buttons, links etc:

![screenshot from 2015-01-22 12 11 47](https://cloud.githubusercontent.com/assets/795070/5854661/7b04048c-a230-11e4-99a0-04a23c136923.png)

**Comment by andreasn** [comment]
UI looks good. The other option would be to hide the controls, but I think this is better.
Should it mention that you need to talk to another sysadmin to get permissions?

**Comment by stefwalter** [comment]
Lets put the user name in the message, instead of 'You', so that it's clear that it's a problem with that user account.

**Comment by andreasn** [comment]
So there are two different cases here:

1. Scruffy is the single sysadmin on the server, but logged in as 'scruffy' instead of 'root'. The solution for him/her would therefore be to log out as 'scruffy' and log in as 'root' and either perform the 'Add Bond' action, or go into Administrator Accounts and make sure that 'scruffy' are allowed to do things like that for now and in the future.

2. Scruffy is a junior admin in a team of 5 people led by a senior sysadmin, lets call him Alfred. Alfred have for perhaps good reasons decided to restrict Scruffy's network admin rights. So Scruffy needs to get in contact with Alfred in order to sort this out.

If we change the help text to "The user 'Scruffy' is not allowed to modify network settings" it would help usecase 1, and to some extent 2, even if it makes 2 feel a bit less natural.

**Comment by andreasn** [comment]
I really like the disabled UI over the dialog in general. The dialog is very surprising with no indication that the action is impossible to do and cuts you off from the rest of the UI until you close it. I would in general advice against dialogs when there is only one action to perform (to close it in this case). This is also what is recommended by the GNOME HIG and by the book Designing Interfaces (by Jenifer Tidwell)
https://developer.gnome.org/hig-book/2.32/hig-book.html#windows-alert
http://designinginterfaces.com/
