### ISSUE TITLE
cockpit-storaged  not installing all dependencies on Ubuntu 2x.xx

### ISSUE THREAD

**Issue by JohnnyElvis** [cockpit-project/cockpit#17041]
### Explain what happens

Unfortunately the package "udisks2-lvm2" is not installed during cockpit setup. If missing, LVM management does not seem to be possible. It would be a good idea to name required packages and why they are needed in the documentation

### Version of Cockpit

cockpit-storaged 252-1

### Where is the problem in Cockpit?

Storage

### Server operating system

Ubuntu

### Server operating system version

20.04, 21.10

### What browsers are you using?

Chrome

**Comment by martinpitt** [comment]
We don't actually want to add a "strong" dependency like "Recommends:" or even "Depends:". We don't want to pull LVM packages onto a system just because the admin installs cockpit. They are more than just dead bits on disk, they also come with systemd units, affect the boot path, etc., and unnecessary services are generally frowned upon by admins.

However, adding a "suggests:" and explaining this in the package description sounds like a good first step indeed!

**Comment by martinpitt** [comment]
Sent #17046
