### ISSUE TITLE
remote host tries sudo three times

### ISSUE THREAD

**Issue by AsocPro** [cockpit-project/cockpit#17169]
### Explain what happens

I am having an issue where due to the policies that we have on our machines cockpit is causing users accounts to be locked due to 3 failed password attempts with sudo. 

I have reproduced this bug with stock CentOS Stream virtual machines fully up to date as of March 22, 2022. On both machines (CentOSStream1 and CentOSStream2) all I have done is install the ISO and enable cockpit, and set the hostname through cockpit. Then from cockpit on  CentOSStream1 I added CentOSStream2 under the hosts menu. Then I logged out. 

This appears to be a caching issue since under normal usage we do not consistently see the locking. However it can be consistently reproduced with the following steps:

1. Restart web browser
2. Open private tab
3. Navigate to cockpit
4. Login
5. Navigate to a different host through the cockpit menu
6. Watch /var/log/secure to see that sudo had 3 failed login attempts

(EDIT - Video recording is a little choppy my machine seems to be having some slowness that is hampering the ability to record smoothly but this still should show the issue being reproduced. If a new less choppy video would help I can get a better one.)

https://user-images.githubusercontent.com/3435186/159513851-f5b8daef-8b96-4ee3-b296-b90be440a31f.mov

### Version of Cockpit

264.1

### Where is the problem in Cockpit?

Navigation & Shell

### Server operating system

CentOS

### Server operating system version

CentOS Stream Up to date as of March 22 2022

### What browsers are you using?

Firefox, Chrome, Edge

### System log

```shell
/var/log/secure:
Mar 22 08:56:09 centosstream2 sshd[3555]: Accepted publickey for admin from 172.16.255.130 port 45142 ssh2: RSA SHA256:f84j2jRjR76q8GBdFYmGPYcxpPKNPHjxipCbfbhvIQk
Mar 22 08:56:09 centosstream2 sshd[3555]: pam_unix(sshd:session): session opened for user admin by (uid=0)
Mar 22 08:56:09 centosstream2 polkitd[969]: Registered Authentication Agent for unix-session:4 (system bus name :1.114 [cockpit-bridge], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Mar 22 08:56:09 centosstream2 sudo[3583]: pam_unix(sudo:auth): authentication failure; logname= uid=1000 euid=0 tty= ruser=admin rhost=  user=admin
Mar 22 08:56:16 centosstream2 sudo[3583]:   admin : 3 incorrect password attempts ; TTY=unknown ; PWD=/run/user/1000 ; USER=root ; COMMAND=/bin/cockpit-bridge --privileged
Mar 22 08:56:16 centosstream2 polkitd[969]: Operator of unix-session:4 FAILED to authenticate to gain authorization for action org.freedesktop.packagekit.system-sources-refresh for system-bus-name::1.121 [cockpit-bridge] (owned by unix-user:admin)
Mar 22 08:56:40 centosstream2 polkitd[969]: Operator of unix-session:4 FAILED to authenticate to gain authorization for action org.freedesktop.packagekit.system-sources-refresh for system-bus-name::1.205 [cockpit-bridge] (owned by unix-user:admin)
```

**Comment by martinpitt** [comment]
That's the reason why maybe half a year ago, Cockpit stopped trying to authenticate through sudo by default, and one has to explicitly do this via the "Limited access" button. However, we let the browser remember that decision, so that the *next* time it will try sudo automatically (if it worked before).

Can you please try this in a private browser instance? So that there are no existing cookies/localstorage? If it works there, then you either succeeded getting root at the remote instance at some point, or there is something wrong with storing that information. @mvollmer , any additional ideas how to debug this?

**Comment by martinpitt** [comment]
Thanks -- so that indeed sounds like the shell would try sudo the first time. @mvollmer, does that ring a bell?

**Comment by mvollmer** [comment]
> Thanks -- so that indeed sounds like the shell would try sudo the first time. @mvollmer, does that ring a bell?

Yes, this is "by design", but the design wasn't very well motivated... we kind of never really nailed down what the defaults should be I am afraid.

So login.js (the main log page) defaults to "none" when logging into Cockpit inititally, while cockpit-bridge defaults to "any" when logging into remote hosts.  We should change the default for remote hosts also to "none" I'd say, because of situations like reported here.  We don't want to run sudo without explicit user request just to see what happens.

Also, what about this situation: Let's say a user can get "sudo", but not with their normal login password (maybe via 2FA or a different password). Cockpit will nevertheless remember that the user can get "sudo" and will try it automatically on the next connection.  This will fail and might have bad consequences like getting locked out.  Should we put a checkbox into the "Get Administrative access" dialog so that people need to opt into Cockpit trying sudo on the next connection?  (I'd say yes.)

(Connections to old versions of Cockpit should not be affected by all this, they will still try to run sudo and are not influenced by any defaults in the originating Cockpit.)

**Comment by AsocPro** [comment]
Thanks for the quick work on this. I was able to test the change on a manual build of cockpit-bridge and it is working fantastic! To make sure we can get support for our servers that are currently locked to RHEL 8.4 on the EUS repos is that as simple as getting that change backed into that branch or do I need to contact Red Hat specifically to make sure they make that happen?

**Comment by martinpitt** [comment]
@AsocPro : If using a COPR build suffices for your case (company policy etc.), that's easy. Our team regularly updates RHEL 8 (so 8.7 and of course CentOS 8 Stream will get it), but not the rather old 8.4. This is also a change which changes existing behaviour, so it's not unambiguously appropriate for a mature stable EUS release. So if you need the fix in the official package, please contact Red Hat.

**Comment by mvollmer** [comment]
> I was able to test the change on a manual build of cockpit-bridge and it is working fantastic!

Thanks, this is good to hear! Could you quickly say which change exactly you have tested?  Was it #17196, or the bigger #17177? Or something else?

**Comment by martinpitt** [comment]
@AsocPro: You can get cockpit-bridge with the fix from [this COPR repository](https://download.copr.fedorainfracloud.org/results/packit/cockpit-project-cockpit-17196/centos-stream-8-x86_64/03918095-cockpit/) (from [this COPR build](https://copr.fedorainfracloud.org/coprs/packit/cockpit-project-cockpit-17196/build/3918095/)). It's not going to stay around forever, but if something like that works for you, you can use the EPEL 8 builds from the official [Cockpit preview COPR](https://copr.fedorainfracloud.org/coprs/g/cockpit/cockpit-preview/) in two weeks (when we release 267)
