### ISSUE TITLE
Language addition - Georgian

### ISSUE THREAD

**Issue by NorwayFun** [cockpit-project/cockpit#17233]
Hello,
I've translated cockpit into Georgian, I see it shipped within latest version of Fedora rpm, but still cannot choose it from options of cockpit itself. 
Is this something to be done by me?
Thanks.

**Comment by martinpitt** [comment]
The last time a language was added, in commit 5e5322191413e47533765b2ecdd42e3d412a3efc, our PO refresh bot automatically added `nb-no` to `pkg/shell/manifest.json`. But that did not happen in commit 28f258b89d180 for adding `ka`. It's missing from https://github.com/cockpit-project/cockpit/blob/main/pkg/shell/manifest.json ; possibly because our bot does not get along with language names without a country? @marusak ?

**Comment by NorwayFun** [comment]
Ahm? There definitely is a country named Georgia and it's there for last 8000 years :)

**Comment by martinpitt** [comment]
@NorwayFun : Heh, sorry, that was not meant politically/geographically :grin:  I meant a locale name like `ka`; the manifest expects it as `ka-ge`, and I figure npm-update does not get along with that.

**Comment by NorwayFun** [comment]
Oh, Sorry. yep. By some reason it's sometimes "ka", may be "ka-GE" or even "ka_GE".
Seems like a bug.

**Comment by marusak** [comment]
Yeah, same as https://github.com/cockpit-project/cockpit/pull/15541#pullrequestreview-613637672 we need to tweak our [langmap](https://github.com/cockpit-project/cockpit/blob/main/po/language_map.txt). I'll send fix

**Comment by marusak** [comment]
Hmm, no, the file is named `ka.po` and we have entry for `ka` in the langmap. There is some different issue. I'll investigate later.

**Comment by marusak** [comment]
Ok, so the cause is fixed in https://github.com/cockpit-project/bots/pull/3226
I will manually check if our current manifest and LINGUAS are up to date.

**Comment by marusak** [comment]
Fixed in https://github.com/cockpit-project/cockpit/pull/17235

**Comment by NorwayFun** [comment]
Just recompiled git, it's there. 
Thanks.
