### ISSUE TITLE
267 regression: Shows Oops without error message when switching between pages with back button

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#17288]
### Explain what happens

1. `bots/vm-run -s cockpit.socket fedora-35`
2. Login as admin/foobar, land on Overview page
3. Click on "Logs"
4. Click the browser back button.

This does go back to the Overview, but the panel shows an Oops:

![image](https://user-images.githubusercontent.com/200109/165492266-7deeeaaa-b2eb-4101-9f37-3456d588bbe1.png)

I am testing this in German, as in English the "no valid html" errors for the nonexisting po.js are just too annoying. But it happens in English as well:

![image](https://user-images.githubusercontent.com/200109/165492431-083b0852-7498-4daa-b45f-d7805075414e.png)

However, in the browser console there are *zero* log messages when this  happens.

This is a prepared image from current main, but I can also reproduce it with [cockpit 267](https://bodhi.fedoraproject.org/updates/FEDORA-2022-70c1d3d182) on our stock bots fedora-35 image (you need to do the `--enablerepo=updates-testing` thing as 267 did not go into -updates).

If I run the current stock `./vm-run -s cockpit.socket fedora-35` from bots, and do the `firewall-cmd --add-service cockpit` dance, this is cockpit 266. With that version I can *not* reproduce it. But after updating to 267:

    dnf upgrade -y --enablerepo=updates-testing --advisory=FEDORA-2022-70c1d3d182
    firewall-cmd --add-service cockpit --permanent
    reboot

I can -- so this is not just an artifact of my local build / `NODE_ENV=development` etc.

### Version of Cockpit

267

### Where is the problem in Cockpit?

Navigation & Shell

### Server operating system

Fedora

### Server operating system version

35

### What browsers are you using?

Firefox

**Comment by martinpitt** [comment]
Related to that: Let's add a global thing to our tests to ensure `b.wait_not_visible("#navbar-oops")`. We have one test which triggers an oops, that obviously needs to be allowed (by reloading the page, for example). This ought to catch this issue and possibly others.

**Comment by mvollmer** [comment]
This is caused by a `ResizeObserver loop completed with undelivered notifications` error. Some PF components are using a ResizeObserver, which is a Browser builtin thing: https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver

I don't know why there is no entry in the console for this error.  Maybe because the error is not a JS exception?

I also don't know what this error happens. It originates in the Overview page.

I think it is pointless to activate the "Oops" for things that are not logged to the console. In this case here, the handler is called is called with url == "" and line == 0. Regular JS exceptions seem to have a non-empty url.
