### ISSUE TITLE
Removing a host is not logical

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit#17478]
### Explain what happens

1. Add a new host
2. Try to remove the host

![image](https://user-images.githubusercontent.com/67428/174876194-4c8d6e4f-5256-4b3e-ab9d-1790b076eb9b.png)

To remove the host I have to **edit** the host and then remove it, this seems not intuitive to me. Maybe we can add a remove button which makes this more obvious? @garrett 

My second issue is that the error when adding a local host I have in my ssh config is not clear enough:

![image](https://user-images.githubusercontent.com/67428/174876790-cfab80cc-b993-409f-99c8-039d9b336e7e.png)

We don't explain what a "untrusted host" is.

### Version of Cockpit

272

### Where is the problem in Cockpit?

Navigation & Shell

**Comment by garrett** [comment]
The reason why it is the way it is... is due to the space constraints (as it needs to be the same width as the sidebar) and making it too easy to remove a host otherwise.

This would be better handled by redesigning and reimplmenting the host switcher, which already has an issue filed @ https://github.com/cockpit-project/cockpit/issues/16693.

Perhaps something like this widget as a starting point:
https://www.patternfly.org/v4/components/masthead/react-demos/#basic
(This doesn't handle adding, editing, removing, etc. — so it's not a solution in and of itself. Just saying that it's possibly a _start_.)

**Comment by garrett** [comment]
> Sounds good to fix this in a re-design.

Let's address this in https://github.com/cockpit-project/cockpit/issues/16693.
