### ISSUE TITLE
[dnf-automatic] add option to reboot only when suggested by dnf

### ISSUE THREAD

**Issue by Klaas-** [cockpit-project/cockpit#17696]
Page: autoupdates

Hi,
currently there is only the option to do an unconditional reboot when dnf made changes:
https://github.com/cockpit-project/cockpit/blob/0b1a4d5b484badf5686b10512da48656f71d84bd/pkg/packagekit/autoupdates.jsx#L180-L188

I would like there to be two options: unconditional reboot on changes like now, or a reboot depending on the output of
`/usr/bin/dnf needs-restarting -r`
when that commands exits with a nonzero exit code a reboot is required

so you could do something like this:
`if ! /usr/bin/dnf needs-restarting -r ; then shutdown -r +5 rebooting after applying package updates; fi`
in the ExecStartPost section of the override file for a "reboot only when suggested" option.

I am not too sure about the frontend changes needed, otherwise I'd create a PR myself :)

Greetings
Klaas

**Comment by Klaas-** [comment]
the needs-restarting plugin is provided by python3-dnf-plugins-core, I think that's always installed with dnf

**Comment by martinpitt** [comment]
The main software updates page uses [tracer](https://github.com/FrostyX/tracer) to decide whether to reboot, restart some services, or do nothing. I believe we shouldn't introduce yet another technology here. @skobyda looked at apt's needrestart, dnf's needs-restarting, and tracer a while ago, and picked tracer as the best option -- but I don't know what the reasons against needs-restarting were. But the dnf developers themselves have fairly big reservations about doing this by default, see https://bugzilla.redhat.com/show_bug.cgi?id=1491190 .

But either way, this really should not be an UI option. If dnf/dnf-automatic/"the OS" can detect this and decide that a reboot isn't necessary, this should Just Happen™. The purpose of this hack is to ensure that the updates take effect, not strictly to actually reboot the machine -- how exactly it achieves that effect should be an implementation detail.

Honestly this whole code should go and dnf-automatic should be fixed to DTRT (as in its current form, it's dangerous and thus useless). Unfortunately there hasn't been any movement on that bug for years.

So honestly this is a wontfix currently.

**Comment by skobyda** [comment]
Just an input:
The main arguments to choose tracer over needs-restarting were:
- needs-restarting won't tell us if a reboot may be needed **BEFORE** the update happens. This functionality is provided by tracer and utilized in our UI.

But the request that @Klaas- is describing can be achieved by tracer as well, and should be achieved by tracer as well:
> I would like there to be two options: unconditional reboot on changes like now, or a reboot depending on the output of **TRACER**

 There is actually an open issue for that: https://github.com/cockpit-project/cockpit/issues/15267 , which has been on my backlog for quite while. Now that I see more demand for that feature, I can move it up my backlog list :) .

@Klaas- do you mind to take a look at https://github.com/cockpit-project/cockpit/issues/15267 it what's described in there looks like what might fit your need?
If so, then this issue is probably a duplicate.

**Comment by Klaas-** [comment]
Yes, I think this is a duplicate :) Thanks for that hint, I'll close this one
