### ISSUE TITLE
Ubuntu LTS: Modern browser needed; :is():where() selector check failed

### ISSUE THREAD

**Issue by aplatypus** [cockpit-project/cockpit#17773]
### Explain what happens

1.  I visited my cockpit page using my LAN IP address: `https://192.168.182.xx6:9090/`
2.  Firefox gave me a security warning I clicked on "advanced" to proceed
3. Firefox shows an error screen 
     ![image](https://user-images.githubusercontent.com/67028/192451813-deb88b9a-efb9-4748-baf8-d48d1df36052.png)
4.  As you see I then used `localhost` and stil see the warning.  
    * This is the latest build for firefox so the error message is misleading
5. I then changed the url to use HTTP://192.168.182.xx6:9090/` firefox blocks this too -- however Edge permits me to sign-on:
    ![image](https://user-images.githubusercontent.com/67028/192452750-01435ecb-3168-4b34-a4cd-fd1f6530aae9.png)
    * And using the IP address
    * Firefox only lets me through to a HTTP url when I use `loacalhost` -- `http://localhost:9090`
6. There are some other variations.
7. I didn't find a config to say HTTPS only (yet)

**Expectations**

* I would expect Cockpit to implement HTTPS
  * particularly over a network
* I am concerned that Cockpit permits HTTP for a semingly incoming network adderss and doesn't reject or reroute to use https
   *  less scrupulous browsers can get you in so it appears
* Cockpit settings should be configurable via cockpit
  *  this way I could find any settings to protect my loginfrom HTTP acces, if that were available
  *  if we can't do configuration, perhaps a HOWTO page or something is possible
* I expect anything not  `localhost` to  using HTTPS or ssh

### Version of Cockpit

264-1 Ubuntu 22.04.1

### Where is the problem in Cockpit?

Networking

### Server operating system

Ubuntu

### Server operating system version

Ubuntu 22.04.1 LTS

### What browsers are you using?

Firefox, Chrome, Edge

**Comment by garrett** [comment]
Huge apologies. This bug actually doesn't have to do with HTTPS. 

This bug is actually my fault (oops!), as we needed to have a check for `:is()` and `:where()` as PatternFly added both earlier this year, and browsers would fail to render widgets without support. When I wrote the check, it worked in all browsers. But all browsers have upgraded their version of `:is()` and `:where()` in recent development versions (which are starting to be released as stable, starting with Firefox) which happened to break the check. But we have a in the latest version of Cockpit and have hotfixes for older versions in browsers.

Explained in depth @ https://cockpit-project.org/blog/cockpit-277.html "Login: Fix “This web browser is too old” error with upcoming browsers"

At the time of writing the release notes last week, Ubuntu 22.04 LTS (and RHEL 8.6 & 9.0) packages were built but weren't deployed to the repos. I'm not sure if Ubuntu 22.04 LTS has the package available yet. If so, please upgrade. 

Otherwise, I'm sad to suggest to use a browser than Firefox for Cockpit if Ubuntu LTS repos don't have the fixed version of Cockpit yet. (I'm a Firefox fan too, and we actively develop to make sure Firefox works with Cockpit. Firefox is my main, default browser, and it is for others on the team as well.)

The difference between Firefox and Edge is that Firefox's version just got updated with the improved selector support (which broke our check) and Edge hasn't been updated on stable yet. This isn't a Firefox-specific issue; all browsers will have this problem as they update to new versions.

After upgrading Cockpit, everything should work across all browsers. (If it doesn't for whatever reason due to caching, force reload by holding down shift and pressing the refresh button in your browser's toolbar, or use the shortcut `shift-control-r` or `shift-F5`).

Again, I'm sorry this bug got into Cockpit, but it is resolved in the latest versions.

Since you're using Ubuntu 22.04 LTS, I'll keep this open until we have confirmation that the new version of Cockpit is available for it and works.

**Comment by garrett** [comment]
I renamed the issue in case others are looking for this.

Hopefully the fixed package is already available, but if not: then hopefully ASAP.

**Comment by martinpitt** [comment]
For the record, this is being tracked here: https://launchpad.net/bugs/1990623 . It's waiting for an Ubuntu SRU team member to review/accept the patched package.

**Comment by martinpitt** [comment]
In the meantime, you can test the fix from my PPA: https://launchpad.net/~pitti/+archive/ubuntu/fixes/

**Comment by Eduardolicious** [comment]
wasnt sure if this was the best place to add vs making a new issue, but just got the newest firefox update (106.0 x64) on my windows 11 install, and am getting this error now when accessing cockpit running on a rocky8.6 setup as well. cockpit is the newest 264.1-1.el8 that i show available there
![image](https://user-images.githubusercontent.com/67165184/196832353-817f3d89-1ec5-4a90-83a4-9d2d1155b2a3.png)

**Comment by garrett** [comment]
@Eduardolicious: It _should_ be fixed in 264.1-1.el8.

- Have you restarted Cockpit or rebooted your server since installing the update? 
- If you visited the page with that browser before, can you try shift-reloading (ctrl+shift+r or shift+F5)?

**Comment by martinpitt** [comment]
No, the fix is in cockpit 264.2-1.el8_6.

**Comment by garrett** [comment]
@martinpitt: Oh. Whoops; I was looking at 276.1-1 @ https://rpmfind.net/linux/RPM/centos/8-stream/baseos/x86_64/Packages/cockpit-276.1-1.el8.x86_64.html:

```
* Thu Sep 15 2022 Martin Pitt <mpitt@redhat.com> - 276.1-1
  - login: Use valid selectors when testing for :is() / :where() support (rhbz#2126044)
```

276... versus 264. I was looking at the latest release instead of the hotfix. Sorry.

**Comment by garrett** [comment]
Again, sorry about this the problem!

We've written a blog post about the issue, complete with an explanation and workarounds: https://cockpit-project.org/blog/login-issues.html

It's mainly a summary of what was written here (and elsewhere in other issues and discussions), but everything is in one place.

**Comment by garrett** [comment]
**Update**: The fixed version of Cockpit has officially landed in the Ubuntu repos.
