### ISSUE TITLE
cockpit.pam is missing from release tarball

### ISSUE THREAD

**Issue by kkaempf** [cockpit-project/cockpit#1780]
`cockpit.pam` is referenced by the .spec file but not included in the release tarball not is it available in the git checkout.

**Comment by mvollmer** [comment]
It is in `.../test/` and `make-srpm` magically copies it from there.

Yeah, this is a bit of a mess.  We only have the Fedora spec and pam files in our sources because we use them to build an rpm for the integration tests, which are also in our sources.

The release tarball does neither contain the spec nor the pam because it doesn't contain anything relating to the integration tests (but it does contain the unit tests).

The integration test machinery could be separate from the Cockpit sources, and #1658 is going in that direction.

So I believe there is no bug here as such.
