### ISSUE TITLE
Auto close menu

### ISSUE THREAD

**Issue by alanmilinovic** [cockpit-project/cockpit#17944]
Can you make menu automatically close/hide when clicked or tapped anywhere on the screen. I am talking about Session, Help, Host and System menu. It is more user friendly and shouldn't be much coding. Specially on mobile device it is a bit annoying.

**Comment by garrett** [comment]
Yeah, you're right. This _should_ happen. It doesn't work properly for some reason.

Opening a menu in the shell should probably have some kind of even at the root that checks bubbling so it makes sure it's a click that's outside of the active menu.

**Comment by KKoukiou** [comment]
The issue is that the different cockpit pages are nested in iframes. 'click' events are fired inside the iframe when you click inside the page to close the menu but these don't get propogated outside the iframe (which is where the shell (navigation) resides. This explains why no click events are cought on the shell when the user clicks inside the page.
I am not sure how this is solvable.
