### ISSUE TITLE
Pass thru auth support for cockpit-ws and cockpit-session

### ISSUE THREAD

**Issue by clemenko** [cockpit-project/cockpit#1796]
I would like to use x509 to authenticate end users instead of passwords.

**Comment by stefwalter** [comment]
Do you have a plan for how you think this would work?

My first reaction is that that this is out of scope. People can use certificates to get their kerberos ticket, and then use kerberos tickets with the GSSAPI support in Cockpit. That's the best mechanism to support all sorts of login methods, such as OTP etc.

**Comment by clemenko** [comment]
With x509 we require a user certificate. We validate the user's cert against a CA. Once validated we then pull the Username out of the DN. Once it is validated we consider that a successful auth process. And then give them access to the app/system as the Username. This eliminates the use of passwords enterprise wide.

**Comment by stefwalter** [comment]
Interesting. Are you interested in contributing the work here? It'd probably require more effort than it first appears. In addition, obviously the certificates could not be used to connect out to other machines via the dashboard. Those connections are made from cockpit-ws server side, and not the browser itself.

**Comment by clemenko** [comment]
I would love to help. What language is cockpit written in? I have a bit of experience with x509 and apache. At work we tend to front end a lot of things with apache/x509.

**Comment by stefwalter** [comment]
Cockpit is mainly written in javascript. But the small part that runs on the server is written in C using GLib.

Another idea that's been thrown around, is to figure out what it would take so that deployments like yours could use apache proxy infront of cockpit. We wouldn't use that as a general purpose solution, but if you want to do a more esoteric deployments, with specific authentication, then that might do the trick. There would need to be a way to configure cockpit-ws and cockpit-session to trust the proxy to send it user login information. That doesn't exist right now.

**Comment by clemenko** [comment]
Apache can pass variables into the http header, such as USERNAME. Then all cockpit would need is to accept the header as "authenticated" and move on. I guess setting an internal flag for the cockpit-ws to allow this. BUT THEN you would want to bind cockpit-ws to localhost so it can't be exploited.

**Comment by martinpitt** [comment]
> Apache can pass variables into the http header, such as USERNAME. Then all cockpit would need is to accept the header as "authenticated" and move on.

The password is also necessary to do sudo authentication, isn't it? Otherwise you couldn't really do much in the Cockpit UI?

**Comment by marusak** [comment]
This issue is closed due to inactivity.

If this issue is a bug report and you are still able to reproduce it, please
comment here and provide us with an updated reproducer.

If this issue is a request for a new feature, we are sorry, but we won't be able
to address this in any time soon. If you are interested in helping us with
the implementation, please comment here.
