### ISSUE TITLE
Can't add a machine with reinstalled OS

### ISSUE THREAD

**Issue by lukas-remis** [cockpit-project/cockpit#18061]
### Explain what happens

Cockpit won't allow to add again a machine which had OS reinstalled and has new keys.
Removing known_hosts from ~/.ssh doesn't help

### Version of Cockpit

215

### Where is the problem in Cockpit?

Unknown or not applicable

### Server operating system

Ubuntu

### Server operating system version

20.04

### What browsers are you using?

Chrome

**Comment by marusak** [comment]
I believe this was fixed in version 235 where we allow you to accept the new key. See https://github.com/cockpit-project/cockpit/pull/14688 (@mvollmer can correct me if I am wrong).

A quick workaround should be able to remove "known_hosts" item in localStorage in your browser. (Right click, `Inspect`, `Storage` card, `Local Storage`)
