### ISSUE TITLE
Can't start cockpit service after system update

### ISSUE THREAD

**Issue by akamuraaa** [cockpit-project/cockpit#18195]
### Explain what happens

1. i added a selfmade certificate to cockpit
2. cockpit shows "certificate is unsafe", but i can continue to use cockpit like always
3. i made system update from fedora 36 to 37
4. cockpit fails to start after update
5. i removed the certificate and added a converted .crt from certbot/let's encrypt
6. service still fails to start
![image](https://user-images.githubusercontent.com/104314814/213001982-5d69cf23-1a6c-4320-996d-07eb39d219f1.png)

i can't use "cockpit-tls" and "cockpit-ws" because it is not registered/command is not found.
how do i deactive https or how do i add a certbot/let's encrypt certifcate to cockpit?

### Version of Cockpit

250.1.1-1.el8

### Where is the problem in Cockpit?

None

### Server operating system

Fedora

### Server operating system version

37

### What browsers are you using?

Chrome

### System log

```shell
Jan 17 21:17:24 lars-server systemd[1]: Starting cockpit-wsinstance-http-redirect.socket - Socket for Cockpit Web Service http-redirect instance...
Jan 17 21:17:24 lars-server audit: BPF prog-id=187 op=LOAD
Jan 17 21:17:24 lars-server systemd[1]: Starting cockpit-wsinstance-http.socket - Socket for Cockpit Web Service http instance...
Jan 17 21:17:24 lars-server systemd[1]: Starting cockpit-wsinstance-https-factory.socket - Socket for Cockpit Web Service https instance factory...
Jan 17 21:17:24 lars-server systemd[1]: Listening on cockpit-wsinstance-http-redirect.socket - Socket for Cockpit Web Service http-redirect instance.
Jan 17 21:17:24 lars-server systemd[1]: Listening on cockpit-wsinstance-http.socket - Socket for Cockpit Web Service http instance.
Jan 17 21:17:24 lars-server systemd[1]: Listening on cockpit-wsinstance-https-factory.socket - Socket for Cockpit Web Service https instance factory.
Jan 17 21:17:24 lars-server systemd[1]: Starting cockpit.service - Cockpit Web Service...
Jan 17 21:17:24 lars-server systemd[1]: Started cockpit.service - Cockpit Web Service.
Jan 17 21:17:24 lars-server audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=cockpit comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=>
Jan 17 21:17:24 lars-server cockpit-tls[14753]: cockpit-tls: Invalid server certificate+key file /etc/cockpit/ws-certs.d/fullchain.crt: Required key not available
Jan 17 21:17:24 lars-server systemd[1]: cockpit.service: Main process exited, code=exited, status=1/FAILURE
Jan 17 21:17:24 lars-server systemd[1]: cockpit.service: Failed with result 'exit-code'.
Jan 17 21:17:24 lars-server audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=cockpit comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=?>
Jan 17 21:17:24 lars-server systemd[1]: cockpit-wsinstance-http-redirect.socket: Deactivated successfully.
Jan 17 21:17:24 lars-server audit: BPF prog-id=0 op=UNLOAD
Jan 17 21:17:24 lars-server systemd[1]: Closed cockpit-wsinstance-http-redirect.socket - Socket for Cockpit Web Service http-redirect instance.
Jan 17 21:17:24 lars-server systemd[1]: cockpit-wsinstance-http.socket: Deactivated successfully.
Jan 17 21:17:24 lars-server systemd[1]: Closed cockpit-wsinstance-http.socket - Socket for Cockpit Web Service http instance.
Jan 17 21:17:24 lars-server systemd[1]: cockpit-wsinstance-https-factory.socket: Deactivated successfully.
Jan 17 21:17:24 lars-server systemd[1]: Closed cockpit-wsinstance-https-factory.socket - Socket for Cockpit Web Service https instance factory.
```

**Comment by garrett** [comment]
I don't know if it's related to your issue, but you say you're using Fedora 37 yet your package states `250.1.1-1.el8`, which is [a year and a half old](https://cockpit-project.org/blog/cockpit-250.html) (current Cockpit is [version 283 from last week](https://cockpit-project.org/blog/cockpit-283.html)) and EL8 means it's for "Enterprise Linux 8" (which means Red Hat Enterprise Linux 8, CentOS Stream 8, or one of the derivatives, which are all slower moving — but even CentOS Stream 8 has a more recent version @ `282.1-1.el8` and AlmaLinux 8, based on RHEL8.x, is @ `276.1-1.el8`).

Please first try using a more recent version of Cockpit, and (more importantly), one built for your OS instead of a package built for a different distribution.

It might not have anything to do with your issue, but it's a good starting point to fix basic problems first. It might just happen to fix your issue too.

**Comment by garrett** [comment]
To switch to the correct version of Cockpit for Fedora 37, I think what you can do is:

```sh
sudo dnf distro-sync 'cockpit*'
```

This should switch all the Cockpit packages you have installed to the most up-to-date version of Cockpit available for your system.

If that doesn't work (for whatever reason), then you'll have to remove Cockpit and re-install `cockpit` and the Cockpit related packages. You can get a list of the various Cockpit packages with `rpm -qa | grep cockpit`

Additionally, since your version of Cockpit is from the wrong repo, your system may also have other packages from the wrong repo as well. You might want to just run `sudo dnf distro-sync` to switch all the packages over... perhaps with `sudo dnf distro-sync --repo fedora --repo updates --skip-broken` to switch your installed packages over to Fedora and Fedora Updates repos, skipping any packages that aren't available in Fedora. But this is a pretty big step and could theoretically be dangerous (although it probably is fine), so don't do this if you aren't sure. If you do run it, you can see a preview of what would happen and can select 'n' to not proceed if it's too much, so getting a preview with that command would definitely be harmless if you don't proceed. And it's probably fine to proceed, but, again: there's a very small chance that it won't be.

**Comment by akamuraaa** [comment]
Thank you very much. The "el8" package came from a 45drives repo, which installed for some modules of cockpit. After removing the repo and doing an dnf distro-sync, It worked.

**Comment by matdave** [comment]
I was having the same issue and solved it by changing the 45drives repo to `priority = 100` so that it didn't override base updates.
