### ISSUE TITLE
How much RAM do I have?

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#1838]
So one thing that I've been asking myself while looking at the memory performance graph on my home server is "Sure, 1.5 GB of Memory used, but 1.5 out of what now again?"

If we had this number somewhere in the UI, it would help an admin tremendously in deciding if it's time to buy more RAM for the server or not.

**Comment by stuartmaxwell** [comment]
I'd like to add a suggestion that may help... How about displaying the memory usage graphs as a percentage in the same way as the CPU chart? So instead of seeing "1.5GB" usage, you'd see "37.5%" instead. Typically that's more useful anyway, and would also help when viewing the memory charts with several servers listed. As an example, here's a snippet of a memory graph with four servers:
![image](https://user-images.githubusercontent.com/1298583/41887750-2790ba24-7956-11e8-9d47-399add5278f9.png)
With this display, you have no way of knowing which lines you need to worry about. The top blue line looks bad, but could be on a server with 24GB memory. The green line at the bottom looks okay but could belong to a server with only 2GB memory. If these were all switched to percentages instead, you'd get a better view of potential issues.

**Comment by garrett** [comment]
@andreasn: I think #10101 should have fixed memory reporting, at least on a per-machine basis. Please confirm and close if you think so.

**Comment by andreasn** [comment]
Yup, that seems to fix it. Thanks!
Closing.
