### ISSUE TITLE
[n] bytes of binary data displayed instead of the log

### ISSUE THREAD

**Issue by rekaburmeister** [cockpit-project/cockpit#18578]
We're using logback for SpringBoot logging. Originally, everything was working fine with Cockpit, but then I added some colours to the log output and suddenly, instead of log lines, we can only see [[n] bytes of binary data]

![image](https://user-images.githubusercontent.com/8222553/228475282-d93d1d56-23bf-42b1-93c3-0b5c98181ff9.png)

I reverted the changes but I still can't see the logback logs. Other service logs are fine. Everything looks OK when using `journalctl` from the command line.

Is there a config I can tweak? Do I need to reboot cockpit or something?

**Comment by martinpitt** [comment]
This isn't configurable, we can just try to interpret binary data more opportunistically as text. That page essentially calls `journalctl`.

Reproducible with

    echo -e "Hello \033[31;1;4mRed\033[0m world" | logger

This works on a Terminal.

**Comment by baamaboi** [comment]
@martinpitt Perhaps we can patch the following line to better support such undefined types

https://github.com/cockpit-project/cockpit/blob/99ae6a943b7d7a78f05c6fbce95e994a09de5a83/pkg/lib/journal.js#L214

A possible workaround can be to use  

```js
String.fromCharCode(value[i])
```
Views?

**Comment by jelly** [comment]
> This isn't configurable, we can just try to interpret binary data more opportunistically as text. That page essentially calls `journalctl`.
> 
> Reproducible with
> 
> ```
> echo -e "Hello \033[31;1;4mRed\033[0m world" | logger
> ```
> 
> This works on a Terminal.

We can tell journalctl to not output color though! `SYSTEMD_COLORS=false` which I think would be a fine solution.

**Comment by baamaboi** [comment]
> > hmm, would that help? I'm not concerned about journalctl's own output, but the data that is in the journal.
> 
> I was thinking journalctl would then not return binary data but instead just the text.

wouldn't it also prevent the user from having colored output in terminal ??

**Comment by martinpitt** [comment]
@baamaboi I looked at your [commit](https://github.com/baamaboi/cockpit/commit/ca2489868abfc04d19e7941424c8f52331901f5d), and this is too much magic and effort. First of all, don't convert the array to a string, then split it again -- loop over the original array. Second, trying to interpret escape sequences is both brittle and also too much effort. Please rather just do

    new TextDecoder().decode(new Uint8Array(value))

which will come out as:

    "Hello \u001b[31;1;4mRed\u001b[0m world"

this is fine -- it's a case of GIGO (programs are *really* not supposed to put ANSI escapes to non-tty stdout/err, so this deserves a bug report), but at least that's a precise representation of what's in the journal. Also, that string can even be `echo -e`'ed on a terminal and be properly visible again.

**Comment by arizonatribe** [comment]
[osbuild-worker-journal.log](https://github.com/user-attachments/files/17550198/osbuild-worker-journal.log)

I'm curious whether this issue was fully fixed. It still appears that binary data is being written to the journal and I wasn't able to deserialize it.

I caused a bug in one of my builds earlier and during troubleshooting noticed one of the `level=error` messages may have had more useful details that I couldn't deserialize:
 
```sh
journalctl -u osbuild-worker*
```

```
Oct 28 18:17:12 gigabox osbuild-worker[16060]: time="2024-10-28T18:17:12-06:00" level=error msg="failure details : [osbuild error: [123 34 116 121 112 101 34 58 32 34 111 114 103 46 111 115 98 117 105 108 100 46 101 114 114 111 114 46 115 116 97 103 101 34 44 32 34 100 101 116 97 105 108 115 34 58 32 123 34 115 116 97 103 101 34 58 32 123 34 105 100 34 58 32 34 101 51 51 56 56 48 100 53 98 98 54 51 101 51 55 50 102 53 49 100 54 99 98 49 52 99 57 100 55 52 50 49 56 52 54 51 97 50 49 99 98 56 97 97 100 97 57 100 54 52 51 99 55 49 101 102 98 100 99 48 101 56 55 55 34 44 32 34 116 121 112 101 34 58 32 34 111 114 103 46 111 115 98 117 105 108 100 46 102 105 114 101 119 97 108 108 34 44 32 34 111 117 116 112 117 116 34 58 32 34 70 97 105 108 101 100 32 116 111 32 111 112 101 110 32 102 105 108 101 32 92 34 47 115 121 115 47 102 115 47 115 101 108 105 110 117 120 47 99 104 101 99 107 114 101 113 112 114 111 116 92 34 58 32 82 101 97 100 45 111 110 108 121 32 102 105 108 101 32 115 121 115 116 101 109 92 110 65 100 100 105 110 103 32 115 101 114 118 105 99 101 32 39 115 115 104 39 32 116 111 32 100 101 102 97 117 108 116 32 122 111 110 101 46 92 110 65 76 82 69 65 68 89 95 69 78 65 66 76 69 68 58 32 115 115 104 92 110 65 100 100 105 110 103 32 115 101 114 118 105 99 101 32 39 99 111 99 107 112 105 116 39 32 116 111 32 100 101 102 97 117 108 116 32 122 111 110 101 46 92 110 65 76 82 69 65 68 89 95 69 78 65 66 76 69 68 58 32 99 111 99 107 112 105 116 92 110 65 100 100 105 110 103 32 115 101 114 118 105 99 101 32 39 100 104 99 112 118 54 45 99 108 105 101 110 116 39 32 116 111 32 100 101 102 97 117 108 116 32 122 111 110 101 46 92 110 65 76 82 69 65 68 89 95 69 78 65 66 76 69 68 58 32 100 104 99 112 118 54 45 99 108 105 101 110 116 92 110 65 100 100 105 110 103 32 115 101 114 118 105 99 101 32 39 105 109 97 103 101 45 98 117 105 108 100 101 114 39 32 116 111 32 100 101 102 97 117 108 116 32 122 111 110 101 46 92 110 73 78 86 65 76 73 68 95 83 69 82 86 73 67 69 58 32 90 111 110 101 32 39 112 117 98 108 105 99 39 58 32 39 105 109 97 103 101 45 98 117 105 108 100 101 114 39 32 110 111 116 32 97 109 111 110 103 32 101 120 105 115 116 105 110 103 32 115 101 114 118 105 99 101 115 92 110 84 114 97 99 101 98 97 99 107 32 40 109 111 115 116 32 114 101 99 101 110 116 32 99 97 108 108 32 108 97 115 116 41 58 92 110 32 32 70 105 108 101 32 92 34 47 114 117 110 47 111 115 98 117 105 108 100 47 98 105 110 47 111 114 103 46 111 115 98 117 105 108 100 46 102 105 114 101 119 97 108 108 92 34 44 32 108 105 110 101 32 49 53 54 44 32 105 110 32 60 109 111 100 117 108 101 62 92 110 32 32 32 32 114 32 61 32 109 97 105 110 40 97 114 103 115 91 92 34 116 114 101 101 92 34 93 44 32 97 114 103 115 91 92 34 111 112 116 105 111 110 115 92 34 93 41 92 110 32 32 70 105 108 101 32 92 34 47 114 117 110 47 111 115 98 117 105 108 100 47 98 105 110 47 111 114 103 46 111 115 98 117 105 108 100 46 102 105 114 101 119 97 108 108 92 34 44 32 108 105 110 101 32 49 49 53 44 32 105 110 32 109 97 105 110 92 110 32 32 32 32 115 117 98 112 114 111 99 101 115 115 46 114 117 110 40 91 92 34 99 104 114 111 111 116 92 34 44 92 110 32 32 70 105 108 101 32 92 34 47 117 115 114 47 108 105 98 54 52 47 112 121 116 104 111 110 51 46 57 47 115 117 98 112 114 111 99 101 115 115 46 112 121 92 34 44 32 108 105 110 101 32 53 50 56 44 32 105 110 32 114 117 110 92 110 32 32 32 32 114 97 105 115 101 32 67 97 108 108 101 100 80 114 111 99 101 115 115 69 114 114 111 114 40 114 101 116 99 111 100 101 44 32 112 114 111 99 101 115 115 46 97 114 103 115 44 92 110 115 117 98 112 114 111 99 101 115 115 46 67 97 108 108 101 100 80 114 111 99 101 115 115 69 114 114 111 114 58 32 67 111 109 109 97 110 100 32 39 91 39 99 104 114 111 111 116 39 44 32 39 47 114 117 110 47 111 115 98 117 105 108 100 47 116 114 101 101 39 44 32 39 102 105 114 101 119 97 108 108 45 111 102 102 108 105 110 101 45 99 109 100 39 44 32 39 45 45 115 101 114 118 105 99 101 61 115 115 104 39 44 32 39 45 45 115 101 114 118 105 99 101 61 99 111 99 107 112 105 116 39 44 32 39 45 45 115 101 114 118 105 99 101 61 100 104 99 112 118 54 45 99 108 105 101 110 116 39 44 32 39 45 45 115 101 114 118 105 99 101 61 105 109 97 103 101 45 98 117 105 108 100 101 114 39 93 39 32 114 101 116 117 114 110 101 100 32 110 111 110 45 122 101 114 111 32 101 120 105 116 32 115 116 97 116 117 115 32 49 48 49 46 92 110 34 44 32 34 101 114 114 111 114 34 58 32 110 117 108 108 125 125 125]]" jobId=29a00203-141a-4674-9282-c7673264cca7
```

**Comment by martinpitt** [comment]
@arizonatribe This has nothing to do with cockpit or systemd. This is an actual text message that consists of a bunch of ASCII characters which happen to all represent digits. Trying to interpret them as ASCII  just turns out gibberish. Perhaps osbuild was dumping a secret key into the log or something?

**Comment by arizonatribe** [comment]
> @arizonatribe This has nothing to do with cockpit or systemd. This is an actual text message that consists of a bunch of ASCII characters which happen to all represent digits. Trying to interpret them as ASCII just turns out gibberish. Perhaps osbuild was dumping a secret key into the log or something?

It's not ASCII, and if it were, it could be interpreted. It's some kind of binary data, and even reminds me a little of the way buffer data looks in JavaScript. Not saying I know what the encoding is specifically, just that it's somewhere in that ballpark.

Also, I would disagree with you that it has nothing to do with SystemD: it's being written to the systemd journal by one of the OSBuild workers (which are SystemD units).

And sure I _guess_ you could say an OSBuild issue has "nothing to do with cockpit", but I think you know there's very much a strong connection between OSBuild and Cockpit. Separate projects, sure, but I think we know Cockpit wouldn't exist without OSBuild.

It seems spurious to say that OSBuild is dumping a secret key into the journal. I mentioned that I know what I did that caused the bug (the log file I attached shows that it was just I named a firewall service in the `customizations.firewall.services` section of the blueprint that didn't exist yet). So it's not at a step in the process of building an OS image where one would need to be wondering about keys. That line specifically is one stating "failure details", and although this wasn't a case where finding the problem hinged on deserializing the error detail, I could imagine a future scenario where I really need to see that error detail.

Maybe this issue is more appropriate to be filed on OSBuild's project page though? I don't know. I don't think your assessment is accurate or that you're even thoughtfully factoring in the details I provided, but there's 400 open issues and 60 open PRs on this project, so I can understand there's probably a lot on the plate and that it's important to scrutinize issues beforehand. But from my perspective I don't care enough about this particular issue to push it forward here or on their project. It's more trouble than it's worth.

**Comment by martinpitt** [comment]
> I think you know there's very much a strong connection between OSBuild and Cockpit.

Is there? how so? Anyway, this isn't relevant. Your journal attachment shows that it's a cleartext message:

> time="2024-10-28T18:17:12-06:00" level=error msg="failure details : [osbuild error: [123 34 116 121 112 101... ]]

which very much looks like a JSON array dumped in text form with some prefixing.

> Maybe this issue is more appropriate to be filed on OSBuild's project page though?

Yes, it is. I have no idea what it is or what it does, I'm afraid.

It's also not related to the original issue here, which was fixed 1.5 years ago.

Sorry if that's dissatisfying.

**Comment by arizonatribe** [comment]
I have no need for the issue to be fixed and truly thought I was helping. As mentioned, there is no issue I need assistance with, just a clear case of kind of binary, buffer or blob data being dumped into journal logs that resembles this thread more so than anything else I found. I didn't express confidence this was the exact same issue, but thought someone may have thoughtful insight or a suggestion on how I could help out.

You have once again reminded me of the kind of annoyance, nitpicking, and borderline arrogance that has become common across open source project issue threads. You suck dude.

**Comment by martinpitt** [comment]
:thinking: There is clearly some kind of impedance mismatch here -- language barrier, or expectations how a bug tracker works, etc., not sure. But from my perspective you crossed a line now, so I have no interest in this any more. It's probably best if we put this to rest...
