### ISSUE TITLE
rtl: We should not flip the direction of all icons

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit#18895]
### Explain what happens

1. For RTL we have a patternfly override CSS rule which flips in the y axis all icons.  There are some icons like ? icon which does not make sense to flip

See https://github.com/cockpit-project/cockpit/pull/18822

**Comment by jelly** [comment]
In RTL not all icons should be flipped it turns out, only arrows and such but for example not the EditIcon. I can't find @garrett's explanation right now. I think we should close this for now and fix cases which apply when we have someone who can test RTL for us.

For icons where we need to flip the direction PatternFly now offers `shouldMirrorRTL`: `<Icon shouldMirrorRTL><AngleRightIcon /></Icon>`

**Comment by garrett** [comment]
No icons should be flipped except left/right directional icons. (This means arrows, carets, and similar.) The rest should not be flipped.

So no icons should be flipped by default, and PatternFly should be automatically flipping anything that points to the left or right.

Things like edit icons, spinners, and other icons that have a sense of direction but do not actually indicate direction should _not_ be flipped. (Spinners are abstract clocks and should always move clockwise. Handwriting is going the incorrect way in every culture; that is right-handers are more dominant so the icons all indicate writing with the wrong hand :wink: (right handedness). There's no culture I'm aware of that has more of us left-handed people.)
