### ISSUE TITLE
Enhance metrics page to also show warnings

### ISSUE THREAD

**Issue by briansmith0** [cockpit-project/cockpit#19000]
Page: Overview / "View metrics and history"

Currently all of the graphs at the top of the page only have two color states:  blue (normal), and red (problem).  It would be helpful if there was a warning color between normal and red.  

For example, show warning for filesystems over 80%, and the normal red/problem for filesystems over 90%:

![Screenshot from 2023-06-22 15-43-10](https://github.com/cockpit-project/cockpit/assets/60192516/a0cc5b5e-2b87-4606-887f-e1680176170a)

**Comment by marusak** [comment]
@garrett WDYT?

**Comment by garrett** [comment]
This is actually in the mockups, and it must've been an oversight. I approve! Thanks!

For example, here's one of the earlier mockups for metrics:

![metrics-current](https://github.com/cockpit-project/cockpit/assets/10246/912b12fb-58d3-4d62-86ad-a5d9e9162f18)

(We made some changes since, as I think the labels are on top, for example, and the spacing is a little different... plus, we didn't do the process table like this, but include processes via cgroups v2 under each relevant area. And there are other differences as well. But the intention was always to show a warning @ 80%, so thanks for bringing this up!)
