### ISSUE TITLE
"Invalid date format" when setting clock to "manual" using french language.

### ISSUE THREAD

**Issue by jciesla** [cockpit-project/cockpit#19091]
### Explain what happens

1. Set french language 
![image](https://github.com/cockpit-project/cockpit/assets/11711472/3c6855b3-1fb0-4fd2-a6f4-72cb27caa6a3)

2. Go to the overview page and set system time without NTP (manual mode). 
![image](https://github.com/cockpit-project/cockpit/assets/11711472/fade6079-c6f0-4324-98c4-dff6ac02f903)

3. setting date/time with manual mode throw an error "Invalid date format".

### Version of Cockpit

295

### Where is the problem in Cockpit?

Overview

### Server operating system

other

### What browsers are you using?

Firefox, Chrome

**Comment by jelly** [comment]
Thanks for the report, I can reproduce the issue fine. Debugging this:

In `pkg/lib/serverTime.js` we pass 
```
const new_date = new Date("21 juil. 2023");
```

Which obviously won't work.

**Comment by jelly** [comment]
Ok, I was in the debugging, what we try is:

```
date 14/07/2023
serverTime.js:705 14/07/2023 Invalid Date
new Date("14/07/2023")
Invalid Date
```

That is valid as a US date, but not for a French locale.

**Comment by jelly** [comment]
Ok, writing this all up:

It turns out we have multiple issues here:

### Dialog UX issue with displaying dates

Shown when opening:

![image](https://github.com/cockpit-project/cockpit/assets/67428/b83fa400-1e13-4186-9c2f-e0cbee109602)

Shown when changing

![image](https://github.com/cockpit-project/cockpit/assets/67428/26537c7c-3490-4c5a-b7ca-c30ba248ef65)


### US date is always saved

So the whole invalid format issue is because we set `manual_date` to `DD/MM/YYYY` always which is wrong because `Date` is locale dependent in JavaScript so that throws an invalid date error.

However, the `onChange` method of the `DatePicker` does return a valid JS `Date` object, in it's [third parameter](https://www.patternfly.org/v4/components/date-picker/#datepicker)

```
date
Wed Jul 12 2023 00:00:00 GMT+0200 (Central European Summer Time)
d
'12/07/2023'
```

So we should use that, however the code `change_time` code takes a datestr/timestr and passes it over to `date`. So the question is if my server's locale is French does `date --date=14/07/2023` even work?
```

**Comment by jciesla** [comment]
Hello @jelly, on my side I confirm it seams to work

![image](https://github.com/cockpit-project/cockpit/assets/11711472/9c5a9cef-0d58-4d72-9102-4a92958c67ee)

**Comment by Bernd-Wissler-KBR** [comment]
I have the same problem in the German UI.
If I type a date in the format "yyyy-mm-dd" the time works

![image](https://github.com/cockpit-project/cockpit/assets/124667642/15d3cf95-5a31-44b1-a9c3-4dd8c2e2733b)
