### ISSUE TITLE
fslist1 payload from python bridge does not match documentation 

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit#19195]
### Explain what happens

The fslist1 payload from python bridge includes just path, type and event attributes.
The documentation states more attributes, like modified: https://github.com/cockpit-project/cockpit/blob/main/doc/protocol.md#payload-fslist1

**Comment by leomoty** [comment]
I was playing with your cockpit-navigator and it broke when my machine swapped to the python bridge.

This was introduced in #14255 when I was testing something else on my own.

**Comment by leomoty** [comment]
Another remark, the pybridge doesn't seem to support watch over `fslist1` and the documentation was never amended to say that.

**Comment by jelly** [comment]
I think not supporting watching was an intentional change, but I might be wrong.

What is missing is `"owner", "group", "size" and "modified" (timestamp)`, as we use `os.scandir` everything seems to be available as `DirEntry.stat`? We should really add some `qunit` tests for this so we test this with the C and Python bridge.

**Comment by jelly** [comment]
@allisonkarlitskaya just assigned you so you are aware of the report, I'm happy to work on implementing this however :)

**Comment by leomoty** [comment]
@jelly not supporting watch is okay, I just meant to amend the documentation: https://github.com/cockpit-project/cockpit/blob/main/doc/protocol.md?plain=1#L873C3-L873C3

**Comment by jelly** [comment]
> @jelly not supporting watch is okay, I just meant to amend the documentation: https://github.com/cockpit-project/cockpit/blob/main/doc/protocol.md?plain=1#L873C3-L873C3

Yes, we should definitively do that if that was intentional to not support watching. Thanks for the further details!

**Comment by allisonkarlitskaya** [comment]
I have some vague ideas to increase the amount of information we send from stat requests.  I'd like for it to be opt-in, though, which will probably be an incompatible break with the C bridge.

**Comment by allisonkarlitskaya** [comment]
So I think my first instinct would be to handle this with an extra attribute on the `open` message, using POSIX field names, with as thin of an implementation as possibe.  Something like:

```json
{"attributes": "st_size"}
```

This has two potential problems:

 - incompatibility with the C bridge, which names things like "path", "type", "size", "group", etc. according to how GIO named them.  We could fix that by adding compatibility to the C bridge, which we would enable if we observed the `attributes` field in the open message.
 - expansion of symbolic information like uids, gids, mode bitfields, etc.  We probably don't want to need to know the value of various mode bits in JS world...

So maybe it would indeed be better just to replicate the C names and semantics anyway.  I'd still prefer opt-in, though.

One thing we ought to do is to look at if the existing implementation is calling `stat()` or not...

**Comment by leomoty** [comment]
Isn't deprecating the `watch` a breaking change in first place anyways?

For the current state of affairs:
@KKoukiou 's cockpit-navigator won't work with pybridge (due to watch throwing an error)
And the one by 45Drives doesn't rely on it

Not sure if there is any real world use case for the fields I added in past.

So throwing my 2 cents, the attributes bit in the message sounds nice.

**Comment by KKoukiou** [comment]
@leomoty For you interest I fixed the cockpit-navigator to work with python bridge. https://github.com/KKoukiou/cockpit-navigator/pull/75

It's less efficient than with the c bridge though.

**Comment by leomoty** [comment]
oh I didnt notice, been a few days since I last updated it, nice progress anyways!

**Comment by jelly** [comment]
> So I think my first instinct would be to handle this with an extra attribute on the `open` message, using POSIX field names, with as thin of an implementation as possibe. Something like:
> 
> ```json
> {"attributes": ["st_size"]}
> ```
> 
> This has two potential problems:
> 
>     * incompatibility with the C bridge, which names things like "path", "type", "size", "group", etc. according to how GIO named them.  We could fix that by adding compatibility to the C bridge, which we would enable if we observed the `attributes` field in the open message.
> 
>     * expansion of symbolic information like uids, gids, mode bitfields, etc.  We probably don't want to need to know the value of various mode bits in JS world...
> 
> 
> So maybe it would indeed be better just to replicate the C names and semantics anyway. I'd still prefer opt-in, though.

I would be in favor of that, opt-in seems fine to me. I think the file navigator plugin wants to use this. Maybe we should first learn more about how it's used there, as if by dropping `watch` mode, do they now basically do a `fslist1` for every `fswatch1` change. That sounds very inefficient. (I am also not sure why we don't support watch mode anymore in `fslist1`, @allisonkarlitskaya was there a good reason for that?)

> One thing we ought to do is to look at if the existing implementation is calling `stat()` or not...

@leomoty I saw you added `group`, `owner` etc. do you use it in an existing product? If so we should just support it. 

One thing we really lack there is some tests.

**Comment by allisonkarlitskaya** [comment]
So the Python bridge is a creature of decisions about how we would proceed with implementing things to get it working as quickly as possible.  In some cases we made decisions not to support a certain feature because we thought the feature was bad.  In other cases it's because we just thought that nobody used it and it wouldn't be worth supporting.

All decisions are definitely open to reevaluation.

Personally, without looking at the code or the things involved, it conceptually makes sense to me that fslist1 should support sending updates, but there are definitely some overlaps with fswatch1 there:

 - fsread1: obviously should just read files.  It's not even clear how we'd support sending updates on changed file contents on the protocol level, although perhaps we could do it by holding the channel open after the read (and "done" message) and closing the channel on changes (and expect the caller to reopen to fetch the new contents).

 - fswatch1: unless we figure out some clever way to get fsread1 to support change notification (and I don't like it when things are too clever) then we need this for watching at least files.  But if it exists, then it also makes sense for watching directories, no?

 - fslist1: we want this for listing directories, although maybe that functionality could be merged into fswatch1 as well, even though it wouldn't really be an accurate name for it anymore?

In any case, I definitely support a single channel type which does all of:

 - opens a directory
 - adds an inotify watch on it
 - sends the initial contents of the directory
 - includes metadata about files on an opt-in basis
 - sends updates when the content of the directory changes (files added/removed)
 - sends updates (to the extent possible, and subject to opt-in) when the metadata of contained files changed

Let's design this well.

**Comment by allisonkarlitskaya** [comment]
I'm thinking/working on this now.  ETA something like two or three weeks, I'd say.  Is that OK for everyone involved?

**Comment by KKoukiou** [comment]
@allisonkarlitskaya thanks, there is no blockage from cockpit-navigator side, it's working already with some code refactoring. Just a bit inefficient.

**Comment by jelly** [comment]
Related: https://github.com/allisonkarlitskaya/systemd_ctypes/issues/56

This is something we can discuss during our meetup :)

**Comment by leomoty** [comment]
> @leomoty I saw you added group, owner etc. do you use it in an existing product? If so we should just support it.

Don't feel pressured, I only ever made a prototype and I can easily update it if necessary.
