### ISSUE TITLE
Logging into remote machine with cockpit ≈ 286 fails with `protocol-error`

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#19317]
### Explain what happens

When trying to add a remote host with Cockpit 286 (as on RHEL 8.8) or 287 (as on Debian stable), i.e. with classic cockpit-ssh/C bridge, logging in fails:

![image](https://github.com/cockpit-project/cockpit/assets/200109/a697c9e1-b4c9-41ff-9e19-e91220e49034)

The same is visible in the journal:
```
cockpit-ws[234177]: /system/po.js: external channel failed: protocol-error
cockpit-ws[234177]: /manifests.js: external channel failed: protocol-error
cockpit-ws[234177]: /system/overview.js: external channel failed: protocol-error
[... some more ...]
```

Christian Labisch reported this, and I confirmed it locally.

Our tests cover connecting to very old versions in RHEL 7, but not not "little bit old" versions like rhel-8-8 and debian-stable. We need to start doing that.

### Version of Cockpit

300.1

### Server operating system version

8.8

### What browsers are you using?

Firefox

Also tracked in RHEL in https://issues.redhat.com/browse/RHEL-3537

**Comment by martinpitt** [comment]
@allisonkarlitskaya I think that's something for you?

**Comment by allisonkarlitskaya** [comment]
Two theories:
 - the Python bridge is modifying the request to the packages webserver in a way that the C packages webserver doesn't like and that's giving us protocol-error.  That happens because the current bridge effectively rewrites all control messages.  We've already observed this with kill messages, and maybe there are other examples.
 - the Python bridge is receiving a control message that it doesn't like from the C bridge.  First guess here would be `authorize`, but it could be anything.

**Comment by allisonkarlitskaya** [comment]
When I think about it, I lean slightly towards the second point I think.  I'm currently working on a branch that would solve the first one, so I'll keep going on that and we can see if it fixes it.  Otherwise, we might seriously consider adjusting the bridge to be less brutal about unexpected transport control messages from peers.

**Comment by allisonkarlitskaya** [comment]
The issue is that we've transitioned to an implementation of `cockpit-bridge` written in Python instead of C.  We have test scenarios that verify that it works with very old versions of the bridge (ie: RHEL 7) but we don't have tests that verify that it works with medium-old versions (ie: modern C bridge, what would be found on a RHEL 8 system).

**Comment by martinpitt** [comment]
I created an integration test in https://github.com/martinpitt/cockpit/tree/r88-bridge which reproduces that. There's a commented out "passwordless sudo" hack which makes the test pass. Without that, you first get a "login failed" screen, and when trying to log in again, the protocol-error.

This points towards a problem with authorize messages.
