### ISSUE TITLE
Add meaningful error message in logs if unallowed user is trying to log in

### ISSUE THREAD

**Issue by LiFiCode** [cockpit-project/cockpit#19558]
After a whole afternoon of wasted time and two reinstalls...

Please - pretty please- add a meaningful error message to the logs if an unallowed user (for example root) is trying to log in.
I'm not suggesting to give feedback in the browser - that would open up a can of worms and would allow to fish for valid usernames...

But please - `TLS fatal alert ` is probably NOT the error message in the logs which help in a case like that.

see [this issue i opened after trying a lot of things](https://github.com/cockpit-project/cockpit/issues/19557).

**Comment by LiFiCode** [comment]
Update Docs to tell people that root access is not allowed by default.

i Quote:
"...By default this is configured to allow you to login with the username and password of **any local account** on the system..."

As is written at [cockpit-project.org/guide/latest/authentication](https://cockpit-project.org/guide/latest/authentication.html#initial-auth)

**Comment by martinpitt** [comment]
Sorry for the hassle! But this is intentional, same as SSH. Exposing the root user directly on web-facing services is too dangerous, and such services must not expose any information about the given user+password pair (such as whether a user exists).

The way to check for this is the journal:
```
cockpit-session[1041]: pam_listfile(cockpit:auth): Refused user root for service cockpit
```
I.e. this may lead to some initial confusion, but we really can't/want to change the behaviour of this. `pam_listfile` could arguably be more verbose, e.g. point to the given `file=`. I reported this to https://github.com/linux-pam/linux-pam/issues/615 , please feel free to subscribe and discuss there.

The "TLS fatal alert" is unrelated -- that happens because you didn't install a "proper" certificate, and thus cockpit generated a default self-signed one which the browser rejects (and then you said "proceed anyway...")

Please also consider *not* setting a root password, and use sudo.

**Comment by LiFiCode** [comment]
Thanks for your reply, Martin.
And you're right of course.

I do normally - after everything is set up and the server goes into production - remove the root-ssh-login.
And the next step would have been to setup certbot and make a valid cert etc.

Like i said in my answer to your comment @ [the issue i initially opened](https://github.com/cockpit-project/cockpit/issues/19557
), it was a combination of things.

Thanks for raising this with the pam_listfile people. Maybe a better error in the logs will help someone in the future.
Greetings and thanks for making great software!
