### ISSUE TITLE
e.responseData.topFrame crash with Safari

### ISSUE THREAD

**Issue by dannyuk1982** [cockpit-project/cockpit#19596]
### Explain what happens

Whenever I use cockpit it always has an `ooops!` in red at the top. 

The console says:

```
[Error] TypeError: null is not an object (evaluating 'e.responseData.topFrame')
	(anonymous function)
[Error] Tracer failed: "{"problem":null,"exit_status":1,"exit_signal":null,"message":"Traceback (most recent call last):\n  File \"<string>\", line 2, in <module>\nModuleNotFoundError: No module named 'tracer'"}", data: """"
	(anonymous function) (updates.js:2:1101803)
	(anonymous function) (cockpit.js:1:12732)
	(anonymous function) (cockpit.js:1:12838)
	L (cockpit.js:1:12244)
[Error] TypeError: null is not an object (evaluating 'e.responseData.topFrame')
	(anonymous function)
```

Unfortunately I have no idea what the issue, is there any way I can try and debug this or does anyone know what might be the issue from that console dump?

Thanks,

### Version of Cockpit

264-1ubuntu0.22.04.1

### Where is the problem in Cockpit?

Unknown or not applicable

### Server operating system

Ubuntu

### What browsers are you using?

Safari macOS

**Comment by martinpitt** [comment]
You can ignore the "tracer" log message, that's fixed in recent versions and unrelated here. But I don't know what to do about the `topFrame` crash. There is no `topFrame` in cockpit's source code anywhere, neither in 264.1 nor in current versions.

We don't (and can't) test Safari in our CI, but we do have a number of users which use Cockpit with Safari, so I don't believe it's generally broken. A good first step would be to test with a different browser (Firefox or Chromium), possibly on a different device (like your phone or another laptop). If the crash happens there as well, it's something on the server side, otherwise specific to your browser/client.

It's also worth updating to a recent version from backports, see https://cockpit-project.org/running.html#ubuntu

If it still happens with that, please let us know some details of your installation -- this crash was not reported by anyone else, nor does it happen in our CI, so there must be something "special". Do you use a proxy, or a custom `cockpit.conf`, or do you have a particular browser extension, etc.?

**Comment by dannyuk1982** [comment]
Thanks for the detailed response. Just gone to work through these and, after several weeks of "Ooops" it's not no longer there. No changes in Cockpit, can only assume it was a Safari bug. Cheers again!
