### ISSUE TITLE
TestSystemInfo.testBasic pixel flake due to high CPU usage

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#19614]
Tests failed on 9da922928c1b1ea8489e12ba5ba6ecfdbe0f5bf3, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20231116-012752-9da92292-fedora-39-updates-testing/log.html)
[bodhi updates](https://bodhi.fedoraproject.org/updates/?search=&status=testing&status=stable&releases=F39)

**Comment by martinpitt** [comment]
This [pixel failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20231116-012752-9da92292-fedora-39-updates-testing/pixeldiff.html#TestSystemInfo-testBasic-overview) happens because the CPU usage label gets very wide, and thus the start of the progress moves a little to the left. We could either wait until CPU usage goes down, or ignore the whole table row.

**Comment by martinpitt** [comment]
Haven't seen this in a while, closing.

**Comment by martinpitt** [comment]
Actually, no reason for this to not happen again.
