### ISSUE TITLE
Nightly tests did not succeed on fedora-39/updates-testing: TestStorageMdRaid.testRaid pixel failure

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#19700]
Tests failed on 9720dae822c82231e0d4cebcddf78716480209d6, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20231206-012759-9720dae8-fedora-39-updates-testing/log.html)
[bodhi updates](https://bodhi.fedoraproject.org/updates/?search=&status=testing&status=stable&releases=F39)

**Comment by martinpitt** [comment]
The kdump NFS failure is a [known top flake](https://ci-weather-cockpit.apps.ocp.cloud.ci.centos.org/tests.html?days=7&test=test%2Fverify%2Fcheck-kdump+TestKdumpNFS.testBasic), but the [mdraid pixel diff](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20231206-012759-9720dae8-fedora-39-updates-testing/pixeldiff.html#TestStorageMdRaid-testRaid-page) is curious -- why would it be "DISK4" instead of "DISK3" all of a sudden?

**Comment by mvollmer** [comment]
> why would it be "DISK4" instead of "DISK3" all of a sudden?

Unexplainable... did this happen more than once?

**Comment by martinpitt** [comment]
Not so far. If it's a rare "WTF?", then let's not waste time on it. If it happens again, we can duplicate and reopen, but the weather report has much bigger tasks.
