### ISSUE TITLE
Support for iSCSI initiators

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#1973]

**Comment by andreasn** [comment]
![Mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/storage/iscsi.png)

**Comment by fabiand** [comment]
Pretty nice mockup!

Notes:
* Box: _iSCSI Targets_
  * I'd actually consider _iSCSI Portals_ which might be clearer because it is less overloaded (target vs portal)
  * Should the _iSCSI Targets_ box always be visible? I'd consider to only show it if one or more targets were added - but I'm sure that is the plan
  * The initial portal addition could be triggered from some hidden menu

* Box: _Add SCSI Storage Target_ (should be iSCSI here)
  * Maybe consider to call it _Add iSCSI Portal_ (reasoning above).
  * _Optional settings_
    * It can be called _Optional Initiator settings_ then it is also clear what the IQN is for - it will specify the IQN of the initiator.
    * OTOH the IQN of the initiator is global and not per portal. So we might need to find a different place for it.
    * We also might want to consider using _Discover targets_ instead of Next.

* Second Box: _Add SCSI Storage Target_ 
  * First we need somehow a throbber (probably a spinner in the next button of the previous box), because the discovery can take a while.
  * Maybe consider to call it _Discovered/Available targets_
  * Add a small text somewhere which repeats the portal name, to give the user a chance to see he selected the correct portal
  * A refresh button?

* Box _Add iSCSI Disk from target <target>_
  * Maybe using _Attach_ instead of _Add_
  * Possibly show a little text naming the target somewhere, i.e.: _Attach iSCSI Disk from target <target>_

**Comment by andreasn** [comment]
![Mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/storage/iscsi.png)

**Comment by mvollmer** [comment]
Done.
