### ISSUE TITLE
Nightly tests did not succeed on fedora-39/updates-testing: testRaidRepair() kernel regression

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#19937]
Tests failed on ce58d96f97eaab7ea095ed6b19df0285669bb320, [logs](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-20240204-012711-ce58d96f-fedora-39-updates-testing/log.html)
[bodhi updates](https://bodhi.fedoraproject.org/updates/?search=&status=testing&status=stable&releases=F39)

**Comment by martinpitt** [comment]
Oh no -- we've been neglecting this regression in https://github.com/cockpit-project/bots/pull/5804 and now https://github.com/cockpit-project/bots/pull/5861 for a while, and now it has landed in Fedora. @mvollmer could you please have a look, so that we at least have a chance of stopping it in bodhi? But I suppose at this point it's gonna be a naughty.

**Comment by martinpitt** [comment]
Naughtied today.
