### ISSUE TITLE
Cleanup of user sessions is flaky on Arch Linux

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit#19972]
### Explain what happens

This happens quite often in navigator/podman where cleaning up a `@nd` test times out waiting on sessions to get cleaned up.

https://cockpit-logs.us-east-1.linodeobjects.com/pull-1555-20240208-080819-df71695b-arch/log.html#18

**Comment by jelly** [comment]
loginctl kill-session seems to support sending a stronger signal using `--signal`.

**Comment by jelly** [comment]
Bumping the timeout does nothing, a grep to see running processes gives me nothing?!

```
+ loginctl kill-session 6 || true; loginctl terminate-session 6 || true
Could not kill session: No such file or directory
+ loginctl --no-legend list-sessions | awk '/web console/ { print $1 }'
+ while loginctl show-session 6; do sleep 0.2; done
killing ssh master process 557436
+ date >&2
Thu Feb  8 13:48:10 UTC 2024
+ loginctl session-status 6 >&2
6 - admin (1000)
  Since: Thu 2024-02-08 13:47:14 UTC; 55s ago
  State: closing
 Leader: 673
    TTY: web console
 Remote: ::ffff:172.27.0.2
Service: cockpit
   Type: web
  Class: user
   Idle: no
   Unit: session-6.scope

Feb 08 13:47:14 archlinux systemd[1]: Started Session 6 of User admin.
Feb 08 13:47:15 archlinux sudo[681]:    admin : PWD=/ ; USER=root ; COMMAND=/usr/bin/cockpit-bridge --privileged
Feb 08 13:47:15 archlinux sudo[681]: pam_unix(sudo:session): session opened for user root(uid=0) by admin(uid=1000)
Feb 08 13:47:30 archlinux systemd[1]: Stopping Session 6 of User admin...
Feb 08 13:47:30 archlinux sudo[681]: pam_unix(sudo:session): session closed for user root
Feb 08 13:47:30 archlinux cockpit-session[673]: pam_unix(cockpit:session): session closed for user admin
Feb 08 13:47:30 archlinux systemd[1]: session-6.scope: Deactivated successfully.
Feb 08 13:47:30 archlinux systemd[1]: Stopped Session 6 of User admin.
Feb 08 13:47:30 archlinux systemd[1]: session-6.scope: Consumed 1.102s CPU time.
+ ps aux | grep 1000 >&2
root        1292  0.0  0.2   4380  3072 ?        Ss   13:48   0:00 bash -c set -e; ps aux | grep 1000 >&2
root        1294  0.0  0.1   3272  1536 ?        S    13:48   0:00 grep 1000
Press RET to continue...
```

**Comment by jelly** [comment]
What is interesting is:
```
Could not kill session: No such file or directory
```

While if I try it normally it gives me:
```
[root@archlinux ~]# loginctl kill-session 6
Could not kill session: No session '6' known
```

How do we debug this!

**Comment by jelly** [comment]
Seems like a4d8ab85312d06b91d834db8dcb4c5ce5b444e29 handled this previously.

**Comment by mvollmer** [comment]
> Bumping the timeout does nothing, a grep to see running processes gives me nothing?!

I think logind used to have trouble with getting notified by the kernel when a cgroup went empty. So a "stuck" session doesn't have any processes in it anymore (they have all terminated as expected), but logind hasn't noticed that, and never will.

I don't know the history of this problem and how it was fixed. Maybe it still exists on arch?

**Comment by mvollmer** [comment]
This is the old issue: https://bugs.freedesktop.org/show_bug.cgi?id=89024

Nothing much to see there, unfortunately. "Something" was fixed somewhere and the issue just went away, apparently.

**Comment by mvollmer** [comment]
When this happened originally, "loginctl terminate-session N" would get the session unstuck and closed immediately (after it got stuck in "closing" without any processes in it). Does this work here as well?

**Comment by jelly** [comment]
Our code does:

```
1583   │             self.machine.execute("""for u in $(loginctl --no-legend list-users  | awk '{ if ($2 != "root") print $1 }'); do
1584   │                                         loginctl terminate-user $u 2>/dev/null || true
1585   │                                         loginctl kill-user $u 2>/dev/null || true
1586   │                                         pkill -9 -u $u || true
1587   │                                         while pgrep -u $u; do sleep 0.2; done
1588   │                                         while mountpoint -q /run/user/$u && ! umount /run/user/$u; do sleep 0.2; done
1589   │                                         rm -rf /run/user/$u
1590   │                                     done""")
1591   │
1592   │             # Terminate all other Cockpit sessions
1593   │             sessions = self.machine.execute("loginctl --no-legend list-sessions | awk '/web console/ { print $1 }'").strip().split()
1594   │             for s in sessions:
1595   │                 # Don't insist that terminating works, the session might be gone by now.
1596   │                 self.machine.execute(f"loginctl kill-session {s} || true; loginctl terminate-session {s} || true")
1597   │
1598   │             # Wait for sessions to be gone
1599   │             sessions = self.machine.execute("loginctl --no-legend list-sessions | awk '/web console/ { print $1 }'").strip().split()
1600   │             for s in sessions:
1601   │                 try:
1602   │                     m.execute(f"while loginctl show-session {s}; do sleep 0.2; done", timeout=30)
```

Frommy memory after the terminate-session it would be stuck in closing. So you are suggestion terminating it again helps?

**Comment by jelly** [comment]
A different option is to restart logind when we detect a hanging closing that also works.

**Comment by martinpitt** [comment]
@jelly That already happens, but maybe not often enough/at the wrong time for this:
```py
            # Restart logind to mop up empty "closing" sessions, and clean user id cache for non-system users
            self.machine.execute("systemctl stop systemd-logind; cd /run/systemd/users/; "
                                 "for f in $(ls); do [ $f -le 500 ] || rm $f; done")
```

**Comment by martinpitt** [comment]
It's [really hard](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1580-20240226-223312-cb98806f-arch/log.html) to get a c-podman PR to green due to this. I have some trouble to catch this locally, but at first I'd question the assumption that the session is really empty. In both my linked log and your paste from above it looks like the session may still have a process running?

```
  State: closing
 Leader: 673
cockpit-session[673]: pam_unix(cockpit:session): session closed for user admin
```

I take it this is actually the bridge (which c-session execve()s). We've seen such bridge leaks in the past, although this shouldn't even depend on a clean bridge shutdown after logging out of the UI -- we hardly ever do that in tests, we just kill everything.

But in all logged cases, it feels like logind got confused -- it simultaneously thinks that there is a (closing) session, but also failed with "Could not kill session: No such file or directory" as Jelle already observed. Perhaps logind got restarted with stale data in `/run`, and the Leader process doesn't actually exist any more?

@jelly FYI, your [grep above](https://github.com/cockpit-project/cockpit/issues/19972#issuecomment-1934166805) was wong -- `ps aux | grep 1000` won't work, you need `| grep admin` or `pgrep -au admin`. Indeed that would be highly interesting -- if the Leader: (or even the whole cgroup) doesn't actually exist, it is stale /run state, otherwise a broken logind runtime state or a kernel bug.

I'll let my two parallel test loops run until I catch this, and then have a closer look.

**Comment by martinpitt** [comment]
> Could not kill session: No such file or directory

This is actually expected, kind of. It's an inherent TOCTOU:
```
            # Terminate all other Cockpit sessions
            sessions = self.machine.execute("loginctl --no-legend list-sessions | awk '/web console/ { print $1 }'").strip().split()
            for s in sessions:
                # Don't insist that terminating works, the session might be gone by now.
                self.machine.execute(f"loginctl kill-session {s} || true; loginctl terminate-session {s} || true")
```
This is one of the (rare) cases where the `|| true` seems fairly unavoidable :cry: But it does seem to suggest that logind's schizophrenic left brain half thinks that the session is actually gone, while the right half still has it in "closing" state.

Wrt. the leaked process -- Actually, it does seem to be clear that there can't actually be a process left any more. At that point in the code, `while pgrep -u $u; do sleep 0.2; done` already passed, which should include `admin`. But still, it'd be good to actually show `systemd-cgls` output if this fails.

So both of which are very strong indications of obsolete /run state. By now I actuallly did catch it once, but unhelpfully `--sit` does not *actually* sit for cleanup failures, so you have to watch this like a hawkeye. Plus, at the time when I logged in the evidence was gone (no trace of the session in question any more). I'll try to run a single test in a loop instead of the whole suite (don't want to get distracted). That also caught it once, but once again after the test actually finished, the logind session was gone. Or perhaps my `ssh c` somehow cleaned it up? Next round I'll run with existing ssh sessions.

I created a https://github.com/cockpit-project/cockpit/tree/session-cleanup branch, and sent https://github.com/cockpit-project/cockpit-podman/pull/1582 to exercise it. I have an idea what to do here, but I first want to collect the evidence.

**Comment by martinpitt** [comment]
I caught it in [this run](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1582-20240227-065515-a5a1c2f8-arch/log.html#8-1) (first attempt, no effort), as well as locally. In both cases I confirm that there is no corresponding user cgroup nor leader process.

Next round, testing with an additional logind restart.
