### ISSUE TITLE
Never read with cockpit.file('/boot/bigfile').watch(callback, {'read': false })

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit#19983]
```
cockpit.file('/boot/bigfile').watch(callback, {'read': false })
```

This would initially when setting up read the `/boot/bigfile` which is undesired behaviour caused by [this](https://github.com/cockpit-project/cockpit/blob/main/pkg/lib/cockpit.js#L3676). Not calling `read()` when options.read == false seems to hang `watch()` so more work is required to get this fixed.

Unit test for verification: https://github.com/cockpit-project/cockpit/commit/a6838ab688268469e7df8a01da626b74144aff3c

**Comment by martinpitt** [comment]
[The docs](https://cockpit-project.org/guide/latest/cockpit-file.html#cockpit-file-notify) does mention the initial read(), but indeed we need to fix that to not happen with `read: false`. Also, the bit of  "This might happen because of external changes, but also as part of calls to read(), [...]" sounds utterly wrong: reading a file should not trigger the watch handler. If it does, then I suppose it's established API and a weird quirk, but then we should create an unit test and make it definite ("might" doesn't make this predictable at all).

However, it *does* make sense to always call the watch handler initially, so that consumers don't need to call it explicitly once - you almost always want this for initialization. But we should describe it as such.

That test does not modify the file after setting up the watch, so why would your handler ever be called? This may be related to .read() forcing a watch handler callback, or just badly worded. So indeed this needs to be fixed -- we need to replace that .read() with calling the watch handler on init with `read: false`, fix up that utterly confusing documentation, and pin down the behaviour in unit tests.

**Comment by VivekJaiswal18** [comment]
@jelly @martinpitt Is Cockpit-Project taking part in GSoC 2024?

**Comment by jelly** [comment]
@VivekJaiswal18 so far we have no GSoC 2024 plans, please don't use issues to ask about GSoC and use Github's discussions feature.
