### ISSUE TITLE
Indicating of Password Strength

### ISSUE THREAD

**Issue by fridex** [cockpit-project/cockpit#2031]
Based on https://github.com/cockpit-project/cockpit/issues/644

It would worth it to add password strength indication. There can be seen confusing behavior in some cases when a password is not strong enough (e.g. https://github.com/cockpit-project/cockpit/pull/1877#issuecomment-83519840) - there is shown only an error code without any additional info. Thus, it would be nice to indicate the password strength when adding a new user or changing a password of an existing one and let a user proceed only if the password is strong enough.

**Comment by fridex** [comment]
Rather than reinventing the wheel this looks suitable for me:

https://github.com/ablanco/jquery.pwstrength.bootstrap

Demos:
https://cdn.rawgit.com/ablanco/jquery.pwstrength.bootstrap/master/examples/index.html

**Comment by stefwalter** [comment]
As far as the timplementation, we need to respect the server's password strength configuration, rather than inventing something in Cockpit.

The PAM stack uses pwquality to do this. There's a pwscore command which can be used to determine the password's score. It prints out a strength, or it fails when the system is configured to reject the password.

**Comment by stefwalter** [comment]
As far as the timplementation, we need to respect the server's password strength configuration, rather than inventing something in Cockpit.

The PAM stack uses pwquality to do this. There's a pwscore command which can be used to determine the password's score. It prints out a strength, or it fails when the system is configured to reject the password.

**Comment by stefwalter** [comment]
By the way, depending on the design, the UI is trivial to implement using a patternfly progress bar without pulling in yet another dependency.

**Comment by andreasn** [comment]
Designs are in #2061 so removing the needsdesign tag from this issue.
