### ISSUE TITLE
TestHistoryMetrics.testEvents mobile pixel view flake

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#20338]
The job `fedora-39/daily` failed on commit 61e5addb28d7d9ad8cc4d5c4ec4a5e2bac248b64.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-61e5addb-20240421-012835-fedora-39-daily/log.html

[example failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-20421-366e23b1-20240503-024735-fedora-40-other/pixeldiff.html#TestHistoryMetrics-testEvents-metrics-history-expanded-hour-mobile)

**Comment by martinpitt** [comment]
This is becoming too annoying -- the [weather report](https://ci-weather-cockpit.apps.ocp.cloud.ci.centos.org/tests.html?days=7&repo=cockpit-project%2Fcockpit&test=test%2Fverify%2Fcheck-metrics+TestHistoryMetrics.testEvents) confirms this as second-highest flake with a 34 to 50% failure rate. Pilot board yellow.

**Comment by jelly** [comment]
This happens daily now, yesterday and today

**Comment by allisonkarlitskaya** [comment]
I just hit this in https://github.com/cockpit-project/cockpit/pull/20411

**Comment by martinpitt** [comment]
Promoting to urgent. This breaks pretty much every PR now. I retried #20421 four times in vain.

**Comment by martinpitt** [comment]
I ran `TZ=Etc/UTC test/verify/check-metrics TestHistoryMetrics.testEvents` in three parallel loops locally, and that doesn't reproduce it. So this is highly timing dependant, and presumably coincides with our loss of e2e machines (i.e. prone to happen on rhos machines). Note that the "UTC" is important, otherwise the test immediately fails due to a different local time zone (two hours off for me in CEST).

I tested this interactively both in Firefox mobile mode (Ctrl+Shift+M), and in Chromium with `TEST_SHOW_BROWSER=pixels`. This works just fine, so this brokenness is really just a test artifact, not an actual bug on the page. The `.scrollIntoViewIfNeeded()` call somehow messes up the rendering of the menu bar. The function does wait for animations, plus an extra 0.5 seconds.

This has been ignored by pilots for two weeks, we are too busy, and is a very deep rabbit hole with a very low benefit/effort ratio. @mvollmer already attempted this in commits e700960997d1e2773756c64d15ae512b7e742e6a and 790b377702af2457af430f86e0c55b430742be3e. So the pragmatic solution is to just stop the mobile test for this.
