### ISSUE TITLE
No one expects the dependency on

### ISSUE THREAD

**Issue by cgwalters** [cockpit-project/cockpit#2048]
Downstream: https://bugzilla.redhat.com/show_bug.cgi?id=1206683

Instead of https://github.com/cockpit-project/cockpit/blob/master/pkg/shell/cockpit-accounts.js#L144 it would seem a lot saner to me to call out to:  https://fedorahosted.org/libuser/ 

It looks like accountsservice doesn't use libuser, but also calls out to binaries.  Ugh, it provides the password via argv.

So, libuser via dbus or so?

**Comment by stefwalter** [comment]
Hmmm, yeah I missed the fact that it's TCL. 

We have no way for a user to set their own password without using either accountsservice or passwd. Since RHEL atomic has boycotted the former, we've tried to use the latter.

Besides the fact that usermod expects the password on the command line, it expects to be run as root, and doesn't run with user permissions.

**Comment by stefwalter** [comment]
We can open a process with a pty, so maybe we can script passwd direct from javascript. Lets see.
