### ISSUE TITLE
Cant view the groups section on accounts tab for a user

### ISSUE THREAD

**Issue by LastStopITSolutions** [cockpit-project/cockpit#20564]
### Explain what happens

1.  I  create a user within the cockpit dashboard
2.  Account is created successfully
3.  When i visit the account page for the new user, It doesn't show the groups section so i cant add or remove a user from a group nor see what groups the user is currently in.

### Version of Cockpit

264-lubuntu0.22.04.1

### Where is the problem in Cockpit?

Accounts

### Server operating system

Ubuntu

### Server operating system version

22.04

### What browsers are you using?

Chrome

**Comment by tomasmatus** [comment]
You are using quite an old version of cockpit. Normally on Ubuntu we recommend installing cockpit from the backport repository which has more recent version as listed here [https://cockpit-project.org/running.html#ubuntu](https://cockpit-project.org/running.html#ubuntu).

Since you are on Ubuntu 22.04 the repository name should be `jammy-backports`
