### ISSUE TITLE
wrong translation in .po file for pt-br

### ISSUE THREAD

**Issue by jfaltenbacher** [cockpit-project/cockpit#20708]
### Explain what happens

in line 2264 and 2265 of the pt-br po file (https://github.com/cockpit-project/cockpit/blob/main/po/pt_BR.po#L2263C2-L2265C32) 
 '_Create new group_' should be translated to "_Criar novo grupo_" instead of "Criar Grupo de Volumes" 

### Version of Cockpit

current main branch

### Where is the problem in Cockpit?

Documentation

### Server operating system

openSUSE

### What browsers are you using?

Firefox

**Comment by martinpitt** [comment]
Right, the translation is out of date, that's why it's marked "fuzzy". It's not actually active, it's just a hint for translators.

I updated it in weblate: https://translate.fedoraproject.org/translate/cockpit/main/pt_BR/?checksum=f96a4b43f5c74592

It will be picked up by the next translation import. Thank you!
