### ISSUE TITLE
cockpit-ws-user.service gets into a dependancy loop due to basic.target

### ISSUE THREAD

**Issue by SludgeGirl** [cockpit-project/cockpit#20914]
### Explain what happens

1. Start cockpit.socket
2. Login
3. Reboot the system

This will cause a dependency loop that can be seen in journal:
```
Aug 19 14:53:12 fedora systemd[1]: basic.target: Job cockpit-ws-user.service/stop deleted to break ordering cycle starting with basic.target/stop
Aug 19 14:53:12 fedora systemd[1]: basic.target: Found dependency on basic.target/stop
Aug 19 14:53:12 fedora systemd[1]: basic.target: Found dependency on sockets.target/stop
Aug 19 14:53:12 fedora systemd[1]: basic.target: Found dependency on cockpit-wsinstance-https-factory.socket/stop
Aug 19 14:53:12 fedora systemd[1]: basic.target: Found ordering cycle on cockpit-ws-user.service/stop
```

From what I can gather, this is because cockpit-ws-user.service, is set to load after basic.target which sets it up to start looping:

```
root@fedora:~# systemctl show -p Before,After cockpit-ws-user.service
Before=cockpit.service shutdown.target cockpit-wsinstance-http.socket cockpit-wsinstance-https-factory.socket
After=tmp.mount systemd-journald.socket sysinit.target system.slice systemd-tmpfiles-setup.service basic.target -.mount
```

Removing it with `DefaultDependencies=no` I've confirmed does fix the issue, however I don't feel I have the knowledge to suggest a change like this, so I've opened this issue instead of a pr

I've checked this in both Fedora and Tumbleweed

```
root@fedora:~# cat /etc/os-release
NAME="Fedora Linux"
VERSION="40 (Server Edition)"
```
```
cockpitvm:~ # cat /etc/os-release
NAME="openSUSE Tumbleweed"
# VERSION="20240704"
```

### Version of Cockpit

318

### Where is the problem in Cockpit?

Services

### Server operating system

Fedora

### Server operating system version

40

### What browsers are you using?

Firefox

**Comment by SludgeGirl** [comment]
Awesome! Thanks @martinpitt! I assumed that was the case and from everything I new it /sounded/ fine just wanted to air on the side of caution

**Comment by Brainfrazzle** [comment]
Verified on Arch Linux cockpit 360-1 with a confirmed fix
Still reproducible on 360-1. The root cause is that four socket units lack DefaultDependencies=no, causing systemd to implicitly add After=sockets.target to each, which creates a circular ordering during shutdown.
Affected units:

```
cockpit-session.socket
cockpit-wsinstance-https-factory.socket
cockpit-wsinstance-http.socket
cockpit-wsinstance-https@.socket (template — also affects live session instances e.g. cockpit-wsinstance-https@<hash>.socket)
```

```
The cycle chain looks like:
cockpit-*-socket-user.service/stop
  → cockpit-*.socket/stop  (via BindsTo/PartOf)
    → sockets.target/stop  (implicit from DefaultDependencies)
      → basic.target/stop
        → cockpit-*-socket-user.service/stop  (implicit from DefaultDependencies)
```
The cockpit-wsinstance-https@.socket cycle only appears when a Cockpit session is active at reboot time, since the template is instantiated per-session.
Fix: add DefaultDependencies=no under [Unit] to all four socket units. These sockets are tightly bound to cockpit.service via PartOf/BindsTo and do not need the default target ordering. Verified clean shutdown across multiple reboots including with an active Cockpit session.
