### ISSUE TITLE
[RFE] Libvirt monitoring

### ISSUE THREAD

**Issue by sgallagher** [cockpit-project/cockpit#2099]
It would be really handy if Cockpit could provide monitoring for virtual machines similar to the way that it does for docker containers.

Bonus points for implementing full virt-manager functionality.

**Comment by andreasn** [comment]
Isn't that oVirt?
http://www.ovirt.org

**Comment by sgallagher** [comment]
oVirt is a much more comprehensive solution than I was talking about, but I suppose one option would be to develop an oVirt Role for Fedora Server that Cockpit could set up and deploy.

**Comment by mwardRH** [comment]
I would love to see virt-manager become a part of cockpit. This way I could manage host OS, Containers and Virtual Machines from one interface.

**Comment by mvollmer** [comment]
Could this happen via the systemd-machined API?

**Comment by sgallagher** [comment]
I think machined only works if the container or virtual machine was registered with it, which I don't believe that libvirt does now. Besides, the libvirt API is far more comprehensive and can deal with everything from virtual network setup to storage management in addition to creating and monitoring the VMs.

I think it might be worthwhile to have a conversation with the team maintaining virt-manager and consider trying to move that project into a plugin for Cockpit.

**Comment by sgallagher** [comment]
Another project to look at integrating with: http://kimchi-project.github.io/kimchi/

**Comment by stefwalter** [comment]
@sgallagh I'm assuming this isn't something you're interested in working on yourself, right? I've placed it on our ideas page, and will close this issue. But I can reopen it if I've misunderstood.

https://github.com/cockpit-project/cockpit/wiki/Ideas

**Comment by sgallagher** [comment]
What's the advantage to closing this ticket? Obviously it's not actually resolved. Also, no. I do not have time to implement this myself these days.

**Comment by stefwalter** [comment]
These are "issues", not "tickets". The issues should have an obvious conclusion, and a reasonably solid expectation of someone contributing towards that conclusion.

While this issue describes a good idea, it's not clear that anyone will stand up and actually contribute this feature. In addition it's not something that makes sense to just close with 'wontfix' or similar. This issue is also not an incomplete part of another feature that has been implemented. 

As it stands if this is "inspiration" or an "idea", in which case it should go on the Ideas page.

**Comment by sgallagher** [comment]
To me, that seems like the sort of thing best handled by a milestone of "FutureFeature" and a tag of "Seeking Help" or something like it. One of the advantages to having it as a ticket is that the tickets are indexed by major search engines and others who come up with the same idea are likely to find this entry rather than a wiki page somewhere.

**Comment by mvollmer** [comment]
However we would mark idea tickets, the idea is that we would still close them because they are not part of the "what do we need to do" set.  Search engines will hopefully find closed tickets.  You can regard the wiki page as a kind of additional summary of valuable ideas.

**Comment by stefwalter** [comment]
Right. I don't think that we need to be overeager about closing enhancements right away. But if they sit around for nearly a year and nobody has signed up to work on them, or contributed toward them, and they're not "missing functionality" where an already implement feature is incomplete ... then we should treat them as an idea. Not that it's a bad idea, likely a good idea. But these things haven't grown past being an idea, and it's not clear when it will.

**Comment by xsgordon** [comment]
To answer the "how is this different from oVirt" question, if you look at the oVirt plugin for cockpit it depends on the VDSM agent which is oVirt/RHEV specific. This means it can't currently be used for other virtualization use cases including standalone single machine virtualization using CentOS/RHEL/Fedora nor for non-oVirt managed virtualization use cases (e.g. OpenStack).

I suspect the ideal solution would be to modify the oVirt plugin so that it gets the basic read only information directly from Libvirt rather than VDSM, thus meaning this part will work for any solution leveraging Libvirt, and then provide the additional managed functionality via connection to ovirt-engine or nova for oVirt or OpenStack environments.

**Comment by xsgordon** [comment]
For future time travellers, you are going to want to look at https://github.com/cockpit-project/cockpit/pull/4434
