### ISSUE TITLE
shell: Login's close button is not styled like a button

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#21160]
![image](https://github.com/user-attachments/assets/779cfe09-b7f9-4f59-8086-1ee6f1a99618)

_Spotted in https://github.com/cockpit-project/cockpit/issues/20826#issuecomment-2434802896_
           
The bug is that all action buttons need to look like a button. The exception is "Cancel", which is a link styled button. But this is a "Close" action, which should be styled like a secondary button, not a link.

**Comment by Bestbynature** [comment]
Hello @jelly and @garrett 

I am new to open source contribution. Please how do I proceed to fix this issue?

**Comment by aditya-vardhan-singh** [comment]
Hello @garrett and @jelly sir!

I have carefully🚨 changed the "Close" button style from "link" -> "secondary". 
This will give the appearance of an action rather than a link.
Thank you @garrett sir for providing the [patternfly.org](https://www.patternfly.org/components/button) docs.

Also keeping in mind that I shouldn't ❌ change the style of "Cancel" and other such options like "edit", "Troubleshoot", etc.

I'm raising a PR for the same. 
Pls let me know if there is any thing else to be done related to this or if I misunderstood any thing.
Thank you! 🙏
