### ISSUE TITLE
Multi-VM networking tests are flaky in nightly runs

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#21165]
The job `fedora-40/updates-testing` failed on commit c36f4413e07e666d20d9daf57a44d163de577831.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-c36f4413-20241027-013122-fedora-40-updates-testing/log.html

**Comment by martinpitt** [comment]
Flaky networking tests with unreachable VMs started a few days ago, and since then we got similar issues every night:

 - https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-c36f4413-20241027-013124-fedora-40-daily/log.html (#21164)
 - https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-2aec8925-20241028-013145-fedora-40-updates-testing/log.html#90-2 (#21172)
 - https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-d455f3ef-20241029-013134-fedora-40-updates-testing/log.html (#21181)

My suspicion is that all these multi-provision tests try to run in parallel, and then require too much RAM (crash), or possibly too much CPU (too slow). The nightly runs run all tests in a single go, as opposed to splitting them out into four scenarios. That is fine, and easier for reporting, and nobody is waiting for them. But we need to slightly lower the parallelism for them, or make them use less RAM.

**Comment by martinpitt** [comment]
Last night's [daily](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-e6db1ad8-20241030-013154-fedora-40-daily/log.html) and [updates-testing](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-e6db1ad8-20241030-013156-fedora-40-updates-testing/log.html) runs were a bit more lucky via retries, but still a bunch of flakes. Same pattern.

I sent https://github.com/cockpit-project/bots/pull/7049 to make this more debuggable.
