### ISSUE TITLE
Using cockpit with `strictNullCheck = true` results in not assignable errors

### ISSUE THREAD

**Issue by kingsleyzissou** [cockpit-project/cockpit#21352]
### Explain what happens

I am importing the `pkg/lib` directory into an existing react/ts project (https://github.com/osbuild/image-builder-frontend).

We have `strictNullCheck` set to true in our `tsconfig`. This results in a number of errors in the `pkg/lib/cockpit/channel.ts` file, I'll just copy the first error for the sake of brevity.

```
pkg/lib/cockpit/channel.ts:31:3 - error TS2411: Property 'command' of type 'undefined' is not assignable to 'string' index type 'JsonValue'.

31   command?: never;
     ~~~~~~~

Found 7 errors in the same file, starting at: pkg/lib/cockpit/channel.ts:31
```

When I check the type for `JSONValue` I see:
```
export type JsonValue = | null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };
```

Which is an issue when `strictNullCheck`is set to true since `undefined !== null`.

### Version of Cockpit

main

### Where is the problem in Cockpit?

None

### Server operating system

Red Hat Enterprise Linux

### What browsers are you using?

Chrome

**Comment by kingsleyzissou** [comment]
Build errors:
https://github.com/osbuild/image-builder-frontend/actions/runs/12069594511/job/33657192559?pr=2603

**Comment by allisonkarlitskaya** [comment]
Please try also enabling

`"exactOptionalPropertyTypes": true`

in your `tsconfig.json` and let me know if it helps.

The issue here is that semantically `command?` should mean "command may or may not exist" but without `exactOptionalPropertyTypes` that's treated as equivalent to "the value of command may be `undefined`", which clearly runs headlong into our JSON type not permitted `undefined`.

See https://www.typescriptlang.org/tsconfig/#exactOptionalPropertyTypes

**Comment by allisonkarlitskaya** [comment]
One thing we could address with this issue: documenting what tsconfig options we expect our consumers to use.  It might also be worth asking the tsc folks why this option isn't the default by now...
