### ISSUE TITLE
TestHistoryMetrics.testEvents pixel flake

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/cockpit#21422]
The job `fedora-41/updates-testing` failed on commit 2d6af150d3a8a900a643e71b7bb03b2e495463d1.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-2d6af150-20241211-013210-fedora-41-updates-testing/log.html

**Comment by martinpitt** [comment]
This isn't related to updates-testing FTR, it [happens on current image as well](https://cockpit-logs.us-east-1.linodeobjects.com/pull-21419-c7bdffce-20241211-103030-fedora-41-other/log.html#33).

**Comment by martinpitt** [comment]
Compare the [screenshot](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-2d6af150-20241211-013210-fedora-41-updates-testing/TestHistoryMetrics-testEvents-metrics-history-compressed-hour-medium-pixels.png) with the [reference](https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-2d6af150-20241211-013210-fedora-41-updates-testing/TestHistoryMetrics-testEvents-metrics-history-compressed-hour-medium-reference.png), it's really just the extra background line.

Hint for running locally:
```
TZ=Etc/UTC TEST_ALLOW_JOURNAL_MESSAGES=".*" test/verify/check-metrics TestHistoryMetrics.testEvents
```

(otherwise time differs, and tracer crashes get in the way).

I've run this umpteen times locally and cannot reproduce it, though :cry:
