### ISSUE TITLE
Unable to Add \ Edit hosts

### ISSUE THREAD

**Issue by waldoinc** [cockpit-project/cockpit#21466]
### Explain what happens

1.  Fresh or upgraded Ubuntu server 24.10 - unable to access the hosts section
2.  Upgraded VM had fully functioning Cockpit instance with 7 hosts added.
![24 04 server](https://github.com/user-attachments/assets/704ebfb8-8f45-43bb-800c-cbf447387ecf)
![24 10 server](https://github.com/user-attachments/assets/4fc5bc55-151f-4957-aeda-25c8660c9bbe)

### Version of Cockpit

329-1~bpo24.04.1 (waldolab-pit)  -  329-1~bpo24.10.1 (waldolab-omni)

### Where is the problem in Cockpit?

None

### Server operating system

Ubuntu

### Server operating system version

24.04 and 24.10

### What browsers are you using?

Brave

**Comment by martinpitt** [comment]
This was intentional. Please see https://cockpit-project.org/blog/cockpit-322.html for details.

**Comment by waldoinc** [comment]
Thanks for that! Tried to search around for any information regarding the change, but kept coming up empty. 
Appreciate all the work that you and the team do!

**Comment by Magicrafter13** [comment]
Well that sucks. I should have stayed on Fedora 40. Shame I had to search GitHub to learn about this too, but oh well - I never was one to subscribe to newsletters.

I don't understand how there would be bidirectional control over an SSH connection though...

**Comment by martinpitt** [comment]
@Magicrafter13 Because all cockpit pages are loaded from the corresponding remote hosts. They can do  iframe traversal to run arbitrary commands on *all* other simultaneously connected machines. So this is only safe to enable if you don't connect to untrusted hosts. That's basically what the config option does -- you have to understand the problem and opt in.
