### ISSUE TITLE
Yum updates

### ISSUE THREAD

**Issue by jwundrak** [cockpit-project/cockpit#2386]
This is btw a feauture request.

It will be very nice, if i can see possible updates and commit them. In larger deploments there can be a notification: Server x requires updates and I commit them. The next step is somthing like a RSS, that System X needs an critical update.
Also great: Ubuntu gives you a list, what Fixes are solved. This output should also included.

Just an idea, but this is a cool feature...

**Comment by andreasn** [comment]
There is some ongoing work on atomic ostree updates.
Mockups: https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/software-updates/software-updates-ostree-v2.png
And the pull request: https://github.com/cockpit-project/cockpit/pull/2281

I would imagine that for a first stab at doing updates using rpm/yum/dnf it would follow a somewhat similar workflow (except the rollback, since rpm can't do that).

**Comment by andreasn** [comment]
And here is the Trello card for it: https://trello.com/c/lnGL2htr

**Comment by andreasn** [comment]
I think this is solved by https://github.com/cockpit-project/cockpit/pull/6724
@martinpitt is that correct?

**Comment by martinpitt** [comment]
Yes, I agree. We do show pending updates with changelogs, bug lists, CVE links now. We don't have a "notification" as that's difficult to do from Cockpit itself - but there are distro specific mechanisms for that like Debian's apt-listchanges cron job/email.
