### ISSUE TITLE
docker: tail & truncate logs for containers

### ISSUE THREAD

**Issue by jwundrak** [cockpit-project/cockpit#2442]
Currently, if you open a docker container, which has got a lot of output (maybe only, because it runs a lot of days) the whole output will be transmitted. 

So two enhancements will be great:
1. a setting, to  get only the last x rows of the logs
2. a button, to flush the logs. An option will be http://serverfault.com/a/638039

**Comment by dperpeet** [comment]
The API supports a "tail" option to return the last X number of lines, so that is definitely doable.

@jwundrak what do you mean by flush? Cockpit follows the output anyway, so anything new should be added automatically. If you mean truncating the files, is there a docker-supported way of doing this? Assumptions about where docker places things on the filesystems might not be valid on different distributions or in future versions.

**Comment by jwundrak** [comment]
@dperpeet Yes, I mean truncating the log file of a container. The linked option was the solution I used. Maybe this is the better one: https://github.com/docker/docker/pull/9222

**Comment by dperpeet** [comment]
the proposed approach was abandoned in favor of log drivers, which is a feature that seems to have gotten merged for docker 1.6 https://github.com/docker/docker/pull/10568
We might need to split this issue into two parts: tail and truncate.
While "tail" appears easy, we need to take care regarding switching pages in Cockpit, which can mess up interaction with docker (e.g. missing lines in the log).

**Comment by dperpeet** [comment]
We'll need to do some research on what docker can deliver for the versions running on the platforms/configurations we currently use, and if those features can allow us to deliver the requested behavior.

**Comment by KKoukiou** [comment]
Closing this issue because the Docker plugin is not being actively developed any longer.
Replacement should be https://github.com/cockpit-project/cockpit-podman/ so any RFEs should be opened on that repository.
