### ISSUE TITLE
Provide some contextual documentation for service types and statuses

### ISSUE THREAD

**Issue by nekohayo** [cockpit-project/cockpit#2748]
In the services page, you have Targets/System Services/Sockets/Timers/Paths. It might not hurt to have 2-3 lines of introductory text at the top of each of those subpages to explain/remind what those are and a "Learn more" link to full-fledged docs (wherever they are)?

Likewise, could be nice to have a little [?] near "Static" to explain what that is.

**Comment by dperpeet** [comment]
While the idea is appealing, I have some concern that going down this road leads to a cluttering of the ui at the expense of experienced users.

For in-depth explanations I would judge the best solution to be for the user to copy a word and paste it into a search engine.
One option I can see for cockpit is to have hover-explanations for certain areas, which are somehow marked out via their style. It is conceivable that the user could switch the css between showing and hiding those styles.

Since this is a general decision, I feel this would be a good topic to cover in [Patternfly](https://www.patternfly.org/). What do you think, @andreasn?

**Comment by dperpeet** [comment]
@nekohayo Do you have a concrete idea how this could look? Maybe a mockup?

**Comment by stefwalter** [comment]
These designs look really good: https://www.patternfly.org/patterns/field-level-help/

**Comment by andreasn** [comment]
I think that could work really well! Esp for labels next to fields.

**Comment by nekohayo** [comment]
Yeah, that's what I meant with the "[?]" in my original description above. It's a pattern we see often. Even just a plain html 'title="lorem ipsum" ' tooltip might do the trick if you want to keep the implementation simple.

**Comment by martinpitt** [comment]
Still current. IMHO these should just be tooltips, which is what we use everywhere else in Cockpit. We could take the descriptions from the systemd manpages:

 * Targets: Group units and as well-known synchronization points during start-up
 * Services: One ore more related processes controlled and supervised by systemd
 * Sockets: IPC or network socket controlled and supervised by systemd, for socket-based activation
 * Timers: (should speak for itself, but..) Timer controlled and supervised by systemd, for timer-based activation.
 * Paths: A file system path monitored by systemd, for path-based activation

@andreasn, WDYT?

**Comment by andreasn** [comment]
I like the tooltip idea. Let's go with that!

**Comment by marusak** [comment]
I am actually inclining to asking documentation team to extend official documentation about the meaning of these units.
We already link to this documentation and we would not pollute UI unnecessary.
Also if it is going to be in the documentation, then there is more space for it to be explained properly then trying to find very short description that would fit into tooltip.

**Comment by marusak** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1930275
