### ISSUE TITLE
Failure at  b.wait_in_text("tr:contains('IPv4')", "Automatic (DHCP)")

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#2890]
We're getting this failure on RHEL7 a lot on hubbot:

```
Wrote check-networking-testBasic-FAIL.png
Journal database copied to check-networking-testBasic-10.111.112.102-FAIL.journal
EWarning: Permanently added '10.111.112.102' (ECDSA) to the list of known hosts.

======================================================================
ERROR: testBasic (__main__.TestNetworking)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./check-networking", line 134, in testBasic
    b.wait_in_text("tr:contains('IPv4')", "Automatic (DHCP)")
  File "/home/hubbot/hubbot/ceb44d0523be4ee089b49583064c6811a84c7e87_r7_x86-64/test/testlib.py", line 238, in wait_in_text
    return self.wait_js_func('ph_in_text', selector, text)
  File "/home/hubbot/hubbot/ceb44d0523be4ee089b49583064c6811a84c7e87_r7_x86-64/test/testlib.py", line 208, in wait_js_func
    return self.phantom.wait("%s(%s)" % (func, ','.join(map(jsquote, args))), timeout=self.phantom_wait_timeout)
  File "/home/hubbot/hubbot/ceb44d0523be4ee089b49583064c6811a84c7e87_r7_x86-64/test/testlib.py", line 658, in wait
    return self.run({'cmd': 'wait', 'cond': cond, 'timeout': timeout*1000})
  File "/home/hubbot/hubbot/ceb44d0523be4ee089b49583064c6811a84c7e87_r7_x86-64/test/testlib.py", line 621, in run
    raise Error("timeout")
Error: timeout
```

**Comment by mvollmer** [comment]
It's a race, of course.

it takes some time after a new interface has been hotplugged until NM returns the correct AvailableConnections property for it.  We often start changing the settings before this point because we now already press ahead when the state of the interface is still "Inactive".

Pressing ahead while AvailableConnections is empty will lead to the creation of a new, second connection object.  This is mostly fine in theory (if undesired) because we should be able to handle multiple connection objects, except that "nmcli" will then work on the other connection object while the UI shows the other.

Also, there don't seem to be any timestamps in the settings, so we can't reliably find the most recent one, which is the one we want to use for the UI.

I'll check what happens on f22 and then try to come up with a fix.

**Comment by mvollmer** [comment]
On f22, a device doesn't go through the "Inactive" state.  It goes "Not Available" -> "Configuring IP", at which point AvailableConnections is correct.

On rhel-7, it starts out as "Inactive", at which point AvailableConnections is still empty.

**Comment by mvollmer** [comment]
> Also, there don't seem to be any timestamps in the settings, so we can't reliably find the most recent one, which is the one we want to use for the UI.

There are, just not always.  We need to treat a missing timestamp as 0.
