### ISSUE TITLE
Continuous / historical systems ressources (CPU, memory, I/O) monitoring

### ISSUE THREAD

**Issue by nekohayo** [cockpit-project/cockpit#3254]
Heya, wondering (hoping) this is something that Cockpit could do... I would love being able to have graphs of the past whenever I log into cockpit, not just graphs that start "when I log into cockpit". In particular, I'm interested in CPU, RAM and I/O over the previous days and weeks (maybe even months if that can somehow be stored).

That way you can figure out easily if that pesky MySQL is slowly leaking or filling your memory, or if you have been under a DDoS, etc.

**Comment by stefwalter** [comment]
You can install ```cockpit-pcp``` and turn on archiving of performance data (on the System page). Once data has started to be collected you can zoom and scroll the graphs. 

We do need have a better way to install Cockpit sub-packages from within Cockpit, so that this is discoverable:

https://trello.com/c/r05Yyvu5/241-lazy-installation-of-cockpit-modules
