### ISSUE TITLE
[Suggest] Permit add arguments when launch container

### ISSUE THREAD

**Issue by shannara** [cockpit-project/cockpit#3271]
Hi,

I suggest to add field for add optional argument for docker run window (example VIRTUAL_HOST=xxxx or anything)
Indeed, if i need run docker with argument, i should switch to terminal, not difficult, just easy UX :)

**Comment by dperpeet** [comment]
I'm not sure what kind of optional arguments you are referring to.

If you mean to add parameters to the command that's run in the container, then you can already do this in cockpit by changing the command in the dialog to create a container.

Under the hood, cockpit uses the [docker remote api](https://docs.docker.com/engine/reference/api/docker_remote_api/) to interface with docker, not the [command line tool run](https://docs.docker.com/engine/reference/commandline/run/). This is also briefly explained in our [Cockpit guide - Docker](http://cockpit-project.org/guide/latest/feature-docker.html). The command line `run` performs `create` and `start` operations in one go, while this is split in the remote API and in Cockpit.

If you wish to influence the environment variables in the container at creation time, then that is something that could be exposed. Is this something that can't be solved via command line arguments to the program executing within the container?

Otherwise, what are the arguments you wish to add and to what purpose?

**Comment by shannara** [comment]
It's not parameters but env variable, 
$ docker run -e VIRTUAL_HOST=site.com  ...

Indeed, i have docker nginx-proxy in front (https://github.com/jwilder/nginx-proxy), and create other container app.
I check Docker documentation and note that usage of env var are no longer the recommended method for connecting to linked services.
I continue read various documentation of usage of link fonction.

**Comment by dperpeet** [comment]
I suggest you try linking containers. As far as I know, and docker [docs on linking](https://docs.docker.com/v1.8/userguide/dockerlinks/) indicate this too, environment variables are automatically propagated when linking containers. Cockpit supports these links in the ui as well.

I will close this issue for now, feel free to reopen it if you believe that Cockpit needs to be changed regarding the environment variables.
