### ISSUE TITLE
Building on Debian uses a expliclit list of build dependencies

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#3298]
instead of getting them from `debian/control`.

Pbuilder does not have a straightforward way to install builddeps.

One idea would be to do a proper build (maybe abridged), but there is no `--save-after-build` option.

Another idea is to replicate what puilder-satisfydepends does, or use it directly.

Another idea is to just grep the build-depends out of debian/control (maybe with the help of /usr/lib/pbuilder/pbuilder-satisfydepends-funcs) and discard the version requirements.

**Comment by mvollmer** [comment]
@mbiebl, any ideas?

**Comment by fsateler** [comment]
There is `mk-build-deps` from the devscripts package, that generates a package with the correct build-dependences. Then doing `dpkg -i cockpit-build-deps*.deb ; apt-get install -f` should install everything.

**Comment by stefwalter** [comment]
It should be fine to use an explicit list of build dependencies. Our list of build dependencies should change rarely, and hopefully we can even drop a couple over time.

**Comment by martinpitt** [comment]
I just stumbled over this when doing some fixes to the Debian packaging. This needs a new `dh-systemd` build dependency, and due to this static hardcoding in three places test VM preparation now fails.

> pbuilder does not have a straightforward way to install builddeps

It of course has (building source packages and creating chroots for them is it's whole raison d'être), but this was disabled with

    test/images/scripts/debian-unstable.setup:echo PBUILDERSATISFYDEPENDSCMD=true >~/.pbuilderrc

So there are three options here:

  - we need to build new images after adding `dh-systemd` to the three Debian-ish files, and continue to duplicate the build deps four times, or

 - reopen this issue, let pbuilder install the build deps from the .dsc, and drop the duplication (we might still want to pre-cache the build deps into the generated images for faster building), or

 - as we already build a test VM, drop pbuilder entirely (right now it doesn't really give us anything over just building the package right in the test VM), and just use `dpkg-checkbuilddeps` or `pbuilder-satisfydepends` on image construction.

**Comment by stefwalter** [comment]
> as we already build a test VM, drop pbuilder entirely (right now it doesn't really give us anything over just building the package right in the test VM), and just use dpkg-checkbuilddeps or pbuilder-satisfydepends on image construction.

Well we want to test cockpit on a VM that more closely matches what the user would have installed. Having all the development dependencies installed does move away from that somewhat.

**Comment by martinpitt** [comment]
OK. Is it a goal that the package build does not hit the network for anything? I. e. is that the reason for pre-installing the build deps into pbuilder and disabling build dep resolution, or is it just for more efficient builds? I. e. if we would pre-cache build deps in pbuilder but let it do dep resolution on its own, would that be okay?

**Comment by martinpitt** [comment]
But I suppose the minimum that we can do here is to replace the hardcoded lists with parsing them from `tools/debian/control`. I'll look into that at some point, feel free to reassign to me (I can't do that yet myself).

**Comment by stefwalter** [comment]
> OK. Is it a goal that the package build does not hit the network for anything? 

Yes. During testing, we get more speed and reliability by not hitting the network. Especially because our verify machines are distributed all over the place.

**Comment by mvollmer** [comment]
>> pbuilder does not have a straightforward way to install builddeps
>
> It of course has (building source packages and creating chroots for them is it's whole raison d'être), but this was disabled [...]

I should have said "pbuilder does not have a straightforward way to _only_ install builddeps without actually building but with saving of the modified build environment".
