### ISSUE TITLE
Support loading Cockpit at an alternate root URL path

### ISSUE THREAD

**Issue by hrumph** [cockpit-project/cockpit#3323]
Hi, I followed the instructions on the wiki and they work but there's
no good way (that I know of) to set a location other than "/", because the links served by cockpit don't change. For instance cockpit returns a link somewhere called "/login", and there are no configuration settings to get cockpit to return the link "/mylocation/login" instead (in the html+javascript it returns).

**Comment by hrumph** [comment]
some sort of configuration setting like URLRoot or something like that would be the solution to this.

**Comment by stefwalter** [comment]
The current versions of Cockpit expect to be hosted at a /cockpit path. See https://github.com/cockpit-project/cockpit/blob/master/doc/urls.md

So this should be fixed in a recent version, provided ```/cockpit``` works for you. You can also use paths like ```/cockpit+myapplication/``` as the root path.

Cockpit has not been designed to have completely relocatable URLs. You are welcome to come up with a plan and implement such support, or perhaps someone else will contribute this at some point.

**Comment by hrumph** [comment]
Well I tried to use the rawhide version (v. 0.87) of cockpit without much luck.   It may prefix a lot of the internally used paths with "/cockpit" but it doesn't prefix everything. For instance the path assigned to the "system" link is just "/system".  I don't know how to work with this current arrangment but I'm certainly very inexperienced with nginx.

**Comment by hrumph** [comment]
I may not have been clear about what I meant in my last post. I meant that, AFAICS, there isn't consistent accross-the-board prefixing. It may be that it's only the menu links that aren't prefixed but all the nginx experts i spoke to said that substituting would be the only way and it's a bad practice.

**Comment by stefwalter** [comment]
Right, it seems like the clean URL support is getting in the way of prefixing. The actual URLs you see as you navigate in the browser in Cockpit aren't the real URLs used in HTTP requests (with the exception of the first one). This is because we use the HTML5 history.pushState() function.

If you're interested in working towards fixing this, I'd be happy to provide advice and review patches. 

Cockpit has not yet claimed or completed support for reverse proxies (some users have figured out ways to make it sorta work). So this is something that would need to be worked on before Cockpit can be considered to work with reverse proxies.

**Comment by dcrdev** [comment]
Just to weigh in here, I run cockpit solely behind an Apache reverse proxy and it works flawlessly - earlier versions had trouble with sessions, but as of 0.8 it's fine.

Here is my configuration if it's of any use to anyone:
```
<If "%{HTTP_HOST} = 'cockpit.domain.com'">
  RewriteEngine On
  RewriteCond %{HTTPS} off
  RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI}
</If>

<VirtualHost *:443>
    ServerName cockpit.domain.com
    ErrorLog /path/to/error.log
    CustomLog /path/to/requests.log combined

    SSLProxyEngine On
    RequestHeader set Front-End-Https "On"
    ProxyPreserveHost On

    ProxyPass / http://127.0.0.1:9095/
    ProxyPassReverse / http://127.0.0.1:9095/

    <Location "/cockpit/socket">
        ProxyPass "wss://127.0.0.1:9095/cockpit/socket"
    </Location>

    SSLEngine on
    SSLCertificateFile      /etc/httpd/ssl/server.pem
    SSLCertificateChainFile /etc/pki/CA/cacert.pem
    SSLCertificateKeyFile   /etc/httpd/ssl/server.key

    SSLProtocol             all -SSLv2 -SSLv3 -TLSv1
    SSLCipherSuite          ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA3$
    SSLHonorCipherOrder     on

    # HSTS (mod_headers is required) (15768000 seconds = 6 months)
    Header always set Strict-Transport-Security "max-age=15768000"
</VirtualHost>
```

You obviously need mod_proxy_wstunnel enabled.

**Comment by hrumph** [comment]
@dcrdev, thanks for the ideas. The nginx configuration suggested on the Wiki works, and I think I could use a bunch of rewrite directives in the configuration to achieve the same effect but that's too messy for me, and even the nginx pros consider that kind of thing to be messy even if all the needed functionality is available. I want to be able to force cockpit to dish out whatever URL root's i want it too through cockpit configuation settings. Anyway I realise that this is not a priority for the cockpit devs. Maybe I'll look into this in the future to see if I can contribute somehow when I have some free time.

**Comment by stefwalter** [comment]
By the way, in the meantime, Cockpit *does* have an embedding mode that uses URLs that are slightly customizable. Log into Cockpit like this:

```
http://mytargetserver.example.com:9090/cockpit+myapplication/@localhost/shell/index.html
```

You can substitute whatever you want for ```myapplication``` above.

**Comment by hrumph** [comment]
Thanks for this @stefwalter. I going to try this out tommorrow.
