### ISSUE TITLE
Add armhf package in lauchpad

### ISSUE THREAD

**Issue by DienoX** [cockpit-project/cockpit#3404]
"Add armhf package in lauchpad" - i think it is good idea because I last time try to install this awesome app and Ubuntu say this repository haven't armhf package :c
Could you add armhf package, thank you!

**Comment by stefwalter** [comment]
Cockpit is not yet officially packaged for Ubuntu as far as I know. Have you found a repository that you're using on non-armhf?

**Comment by DienoX** [comment]
From http://cockpit-project.org/running.html I picked Ubuntu and I added this repository to arm server.

**Comment by stefwalter** [comment]
@DienoX Interesting. Are you interested in packaging Cockpit for arm in launchpad?

**Comment by DienoX** [comment]
No.

**Comment by stefwalter** [comment]
Could you file a bug with Ubuntu then? I think @jpsutton is the Cockpit PPA maintainer there.

**Comment by jpsutton** [comment]
Yes, that's my ppa.  The version there is extremely old, but I'll try to get the new packages up there soon and I'll try to get arm added to the architecture list.

**Comment by jpsutton** [comment]
My last comment on this issue since it is closed:

I uploaded cockpit 0.92 to the PPA and made a request to launchpad to enable ARM builds for that PPA also.  Launchpad Question: https://answers.launchpad.net/launchpad/+question/281259

**Comment by NightDawn** [comment]
is small problem
http://i.imgur.com/I59OfCz.png

**Comment by jpsutton** [comment]
Yes, it is not building correctly on Launchpad for some reason.  The build
log is quite confusing, and I currently don't know how to duplicate the
build environment they're using for ARM so that I can troubleshoot
locally.  If you have the capability to build for ARM already, I suggest
downloading the source packages from the PPA and attempting to build
yourself.  If you have to make any changes to make it work, feel free to
send them over to me and I'll include them so that hopefully the LP builds
start working.

**Comment by NightDawn** [comment]
So No chance for Ubuntu ARM port?

**Comment by jpsutton** [comment]
Unfortunately the build is erroring and I just don't have time to troubleshoot at the moment.  I believe the build logs on the PPA are public so feel free to troubleshoot and submit patches.
