### ISSUE TITLE
Preserve state and location when switching frames

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#3450]
When I'm on a kubernetes or image registry sub-page (e.g. cluster-containers or registry-images), navigate to some other cockpit page - e.g. the dashboard - and then back to kubernetes / the image registry, I see the Overview and not the previously active page.

**Comment by petervo** [comment]
Is that any different from the rest of cockpit? Go from a container page, then to logs then back to containers, same behavior. Or am i misunderstanding the issue?

**Comment by stefwalter** [comment]
Yup, it's a bug. Not your fault ... but a bug none the less. And since you're involved in this section, I assigned it to you. But feel free to assign it to me if you'd rather not take this on.

From the beginning of talking with about the new navigation with @andreasn and @allanday and planning it out ... the plan was that switching sections in Cockpit is like switching  tasks ... when reactivating a section we should keep its navigation and state and open dialogs etc.

**Comment by petervo** [comment]
Fixed by #3789
