### ISSUE TITLE
sosreport: Enable tests on debian

### ISSUE THREAD

**Issue by dperpeet** [cockpit-project/cockpit#3500]
The package sosreport is in debian, so this should be possible.

Follow-up to #3486

**Comment by martinpitt** [comment]
For new contributors, these are the steps:

 1. Add the sosreport package to bots/images/scripts/debian.setup (`$TEST_PACKAGES`), and create a PR that rebuilds all Debian/Ubuntu images, so that the package is available.
 2. Land that PR, ensuring that this does not break anything (or hauls in an unrelated regression due to the image refresh).
 3. Drop the relevant skips in test/verify/check-sosreport in a new PR.

**Comment by martinpitt** [comment]
And of course cockpit-sosreport needs to be packaged in the first place.
