### ISSUE TITLE
iPhone "Server has closed the connection"

### ISSUE THREAD

**Issue by joedborg** [cockpit-project/cockpit#3560]
If I try to login to Cockpit using an iPhone, I get the error:

`Disconnected: Server has closed the connection. <Try to reconnect> <Log in again>`

...which keeps reappearing, no matter which option I select.

**Comment by dperpeet** [comment]
Sorry for the late reply. Which browser (and version) were you using and what's the version of Cockpit you wanted to connect to?

**Comment by andreasn** [comment]
I think on the iPhone, all browsers use the same system webkit rendering engine, since it's the only one allowed (Chrome and Firefox on iOS both use that).
I think this is the same as issue #3640

http://arstechnica.com/information-technology/2015/11/firefox-finally-comes-to-ios/
https://developer.chrome.com/multidevice/ios/overview
http://www.howtogeek.com/184283/why-third-party-browsers-will-always-be-inferior-to-safari-on-iphone-and-ipad/

**Comment by petervo** [comment]
As @andreasn said same issue as #3640
