### ISSUE TITLE
storage: suggest name for a new raid

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#3722]
If you don't fill out the name, it will default to the name "127" and the next raid you create will default to the name "126", so we might as well fill those out in the name field to indicate that.

**Comment by mulkieran** [comment]
Any chance of instead having a generic idea of "accept default", when the backend supplies a default?

**Comment by andreasn** [comment]
How do you mean? Could you explain more in detail?

**Comment by mulkieran** [comment]
It would be nice to be able to say, in the GUI, "just accept whatever name this app wants to give the array, I don't care."

AFAICT, the drawbacks to that approach are:
1. Inconsistency, because some apps will supply a default and some won't. But I don't think that's such a big deal, because the different parts of the storage stack are different in lots of ways.
2. A technical challenge, because I don't know how you would express this idea to the user of accepting the unknown and unspecified name in the GUI.

The good things are:
1. Cockpit doesn't have to imitate some underspecified code in mdadm. This is good, because it wlll probably not be able to imitate it exactly anyway, and because it may change. Maybe mdadm will decide that 256 is an even more exciting number than 128.
2. For apps that supply their own default, Cockpit _never_ has to specify a default. This is nice, because eventually Cockpit would specify a bad default that conflicts with something that the app has a handle on but it doesn't know about, causing the app either to fail or to dynamically make up a new, different name, anyway.
