### ISSUE TITLE
User with /sbin/nologin should not be able to login 

### ISSUE THREAD

**Issue by nenonano** [cockpit-project/cockpit#3798]
as per sbj, an user with nologin shell is still able to login in cockpit.. he can't do anything but, IMO, it should be avoided

**Comment by nenonano** [comment]
sorry, forgot to tell: cockpit 0.93 on C7

**Comment by stefwalter** [comment]
Maybe we should put ```pam_shells.so``` in our default PAM files. What do you think @mvollmer @dperpeet @petervo?

**Comment by petervo** [comment]
I'm good with that.

**Comment by martinpitt** [comment]
`pam_shells` doesn't work for Fedora, as `/sbin/nologin` is in `/etc/shells` and thus a valid shell. This is a bit unfortunate (e. g. Debian/Ubuntu don't have it as a valid shell so that this PAM module would work there), and superfluous as `pam_shells` is not actually being used by the standard PAM files so that the "friendly" message of `nologin` would still be displayed by e. g. `login` or `ssh`.

FTR: `pam_nologin` only checks the `/{etc,run}/nologin` stamps and don't look at the shell either. There is no PAM module for rejecting nologin as a shell.

**Comment by martinpitt** [comment]
Adding `pam_shells` works fine for a `/bin/false` shell at least, and it would work if/when Fedora drops nologin as a valid shell, so adding that to the PAM configs would still make sense IMHO.

**Comment by stefwalter** [comment]
I would then suggest we document how to lock out users properly in

http://cockpit-project.org/guide/latest/authentication.html

That's in the ```doc/guide/authentication.xml``` file. We could describe the best way to both lock and prevent login for a user (eg: ```passwd -l``` or similar).

**Comment by martinpitt** [comment]
Looks like Fedora will drop it soon: https://bugzilla.redhat.com/show_bug.cgi?id=1378893
