### ISSUE TITLE
[RFE] shibboleth/saml auth

### ISSUE THREAD

**Issue by jcpunk** [cockpit-project/cockpit#3938]
My site has a very stable shibboleth service that I'd prefer to use, is adding shibboleth authentication something the project would be open to?

**Comment by stefwalter** [comment]
Cockpit has pluggable authentication handlers, which can handle things like site-specific SAML authentication requirements:

https://github.com/cockpit-project/cockpit/blob/master/doc/authentication.md

But is this something you're interested in working further on? If so, what would it look like generalized for the upstream case, rather than a specific configuration?

**Comment by jcpunk** [comment]
My C is a bit rusty and probably not trustworthy for authentication code, but generically a behavior flow of something like:
- my IdP is idp.example.com
- login there it hands the username off to Cockpit
- authentication happens.

Without mod_auth_mellon or mod_shib to do the SAML, this may be more of a pipe dream....

**Comment by stefwalter** [comment]
The authentication components can be written in python, nodejs, go, or whatevér you would like. If you run into problems writing such an authentication component, feel free to chat about the issue on #cockpit (IRC on freenode) or via specific issues here.
