### ISSUE TITLE
storage: scale and ticks are volatile for read/write graphs

### ISSUE THREAD

**Issue by mulkieran** [cockpit-project/cockpit#3964]
![screenshot from 2016-03-09 15-11-59](https://cloud.githubusercontent.com/assets/1218366/13649940/35fd1ce8-e60e-11e5-8042-409a0999d789.png)

This graph kept changing from two intermediate ticks to four.

**Comment by mulkieran** [comment]
It would be nice for me if the top increment actually went to a multiple of the ticks, although it should not be marked. In this example, the top of the graph would be at 384 (3 * 128). Currently, it seems to be just a margin above the highest point graphed.

This might help with the jitteriness of the tick marks, although I can not say for sure.

**Comment by marusak** [comment]
This issue is closed due to inactivity.

If this issue is a bug report and you are still able to reproduce it, please
comment here and provide us with an updated reproducer.

If this issue is a request for a new feature, we are sorry, but we won't be able
to address this in any time soon. If you are interested in helping us with
the implementation, please comment here.
