### ISSUE TITLE
Authentication List of SSH keys doesn't refresh on key deletion.

### ISSUE THREAD

**Issue by bexelbie** [cockpit-project/cockpit#4069]
I had a key that I deleted in an unrelated shell.  I got this:

![cockpit-auth](https://cloud.githubusercontent.com/assets/7413661/13959495/a88e0bbe-f054-11e5-935f-ab702412c3ab.png)

**Comment by stefwalter** [comment]
This represents a key that's loaded into the agent and usable, but has been removed from the file system. In #4088 I've put some code to display a title for the key. However the on/off button will remain disabled because the SSH tools (```ssh-add``` in this case) provide no way to specifically unload such a key.

The user should log out to have it unloaded.
