### ISSUE TITLE
Images don't always disappear from the list.

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#412]
For example, when commiting an image with the same name as an existing one, Docker implicitly removes the name from the old image.  Cockpit shows both images with identical names until reloaded.

**Comment by petervo** [comment]
So the bug as described here doesn't exist anymore. The behavor now is that on commit the old one is removed and the new one is added to list. The reason is we no longer show images that don't have tags. https://github.com/cockpit-project/cockpit/commit/30de4249b6f9180b1c2d1447841a08f686761c78.

So if everyone is fine with this behavior then i think this is fine to close.

**Comment by mvollmer** [comment]
Sounds good.
