### ISSUE TITLE
select display language with no effect 

### ISSUE THREAD

**Issue by vanloswang** [cockpit-project/cockpit#4319]
I just select display language to chinese or some one else, the language display on the UI is not changed.
The version of cockpit is 0.104, OS is fedora 23 x86_64.

**Comment by dperpeet** [comment]
I believe it only seems that way, since the text defaults to English if there is no translation available. If you select Catalan, for example, there has been quite a bit of translation work done for that language and you'll see the difference right away.
The translation effort is tracked here: https://trello.com/c/Eut2LIkk/111-translations
Actual translations are here: https://fedora.zanata.org/project/view/cockpit (this is where anyone can contribute)

You are right in the sense that it is nowhere near completion!

In the medium term we want to highlight parts of cockpit that are stable enough and require translations, but currently there is no such mechanism in place.

Feel free to open another issue if you really can't see other languages in the Cockpit ui (e.g. for Catalan).

**Comment by vanloswang** [comment]
@dperpeet Could you add my account to https://fedora.zanata.org/project/view/cockpit contributors.I will do some contribution to the Chinese tanslation.
