### ISSUE TITLE
Cockpit should deal with storage changes that need updates in the bootloader

### ISSUE THREAD

**Issue by mvollmer** [cockpit-project/cockpit#4325]
Such as renaming the volume group that has the rootfs or swap.

Cockpit could refuse to make the change, merely warn about it, or silently update the grub config.

**Comment by marusak** [comment]
This issue is closed due to inactivity.

If this issue is a bug report and you are still able to reproduce it, please
comment here and provide us with an updated reproducer.

If this issue is a request for a new feature, we are sorry, but we won't be able
to address this in any time soon. If you are interested in helping us with
the implementation, please comment here.
