### ISSUE TITLE
Alerts not dismissable

### ISSUE THREAD

**Issue by aweiteka** [cockpit-project/cockpit#4401]
Kubernetes module alerts are not dismissable in Version 0.105.

Docs: https://www.patternfly.org/widgets/#alerts

**Comment by petervo** [comment]
Dismissable alerts should really only be used if next time you come back to that page/item it will stay dismissed. Everywhere we use alerts in the kubernetes package right now comes from api statues since we can't change that status we use use dismissable. I'd recommend not using it in #4340 either since again kubernetes will change the api status when the error is no long applicable.
