### ISSUE TITLE
Debian Jessie libgssapi-krb5-2

### ISSUE THREAD

**Issue by michaelschefczyk** [cockpit-project/cockpit#4556]
Dear All, dear Stef,

Since a couple of weeks ago, Cockpit on Debian seems to depend on libgssapi-krb5-2 1.14.2+dfsg-1 as cockpit-ws does depend on it. That version is included in Debian Stretch but not in Jessie. If I am not mistaken, there is also no backports version of this for Jessie.

Please consider to state this on the website so that plain Debian Jessie users do not need to try as they will fail. Of course, you may also want to make your software available to Debian Jessie users again.

Regards,

Michael

**Comment by dperpeet** [comment]
This may be a packaging issue, since that part of the actual code hasn't changed in a while, if I'm not mistaken.
@larsu Do you know why this dependency might have changed?

**Comment by larsu** [comment]
The symbols file of libgssapi-krb5-2 in 1.14 bumped the versions of some functions that cockpit is using, but doesn't provide the older versions. This means that cockpit-ws gets marked as depending on the new version. I've reported this upstream in bug [#827208](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=827208), but Sam already replied saying that this is standard policy: these functions have changed, and there's no way for debian to find out in an automated way whether cockpit uses the new functionality.

The repository targets `unstable` because that has newer versions of a lot of cockpit's dependencies. Maybe `testing` is a better idea, but I don't think `stable` is what we want for these releases.

I've opened a [pull request](https://github.com/cockpit-project/cockpit-project.github.io/pull/47) for the web site to clarify that we're targeting unstable.
