### ISSUE TITLE
Possibility to hide existed menu entries 

### ISSUE THREAD

**Issue by igorSmirnovPlexi** [cockpit-project/cockpit#4558]
Hi, we are working with cockpit project and developing new packages for our needs. In some cases new packages might override functionality of base packages, for example we've created system package which present the system monitoring like a base system package, but with additional functionality - e.g. monitoring history! We'd like to have possibility to replace original menu entry with our new packages, actually without remove it, just to hide in the menu. The navigation URI for the base packages will stay without changes.

**Comment by dperpeet** [comment]
This is an interesting idea.
At first glance I would say you could add an optional manifest.json entry with a priority and thus the ability to override existing entries. Good starting points for this would be the [sidebar menu generation](https://github.com/cockpit-project/cockpit/blob/a044625778065c2cfa1e83773c2b6343bfb911db/pkg/shell/indexes.js#L285) or where the [manifests are interpreted](https://github.com/cockpit-project/cockpit/blob/9c75bc2b3853713696980b3dceaab8d24d4724ec/pkg/shell/base_index.js#L768).
Something like `hidden` wouldn't be as good, since that would require changes in the package to be overridden.

@igorSmirnovPlexi Would you like to help make this happen? If you open a pull request, I'd be happy to review and help out if necessary.

**Comment by stefwalter** [comment]
Hmmm @dperpeet how would someone override one of the standard components, lets say "network" or "storage" with their own implementation? Overriding the component at the same URL is very useful to indicate that the topic (such as "storage") is handled differently on this system.

In theory one would just install that component to the same location in the file system, and not install the component being replaced, but that's rather fragile. Hence the question, should we have a consistent approach for this?

**Comment by dperpeet** [comment]
@stefwalter Like I said, the cleanest way I see right now would be to extend the manifest.json. As it stands, the directory name of the package isn't tied to the display name in the menu anyway. With a priority system, be it numerical or binary (default / override) we could solve this without impacting the default case.

**Comment by igorSmirnovPlexi** [comment]
I'll create pull request

**Comment by smirnovigor** [comment]
I've created pull request from my private account #4580

**Comment by smirnovigor** [comment]
The manifest.json has new property "override" which hide original menu entry from menu list.

The new manifest.json looks so:
```    
"menu": {
        "home": {
            "label": "Home",
            "order": 0
        },
        "system": {
            "label": "System",
            "order": 1,
            "override": "system"
        },
        "sdm": {
            "label": "Storage",
            "order": 2,
            "override": "storage"
        }
    },
```

**Comment by stefwalter** [comment]
What happens when someone navigates to http://localhost:9090/storage on a system where "storage" has been overridden? Shouldn't we make it so "sdm" can show up at http://localhost:90980/storage? In this case the "sdm" package really does represent how storage is configured/runs/managed on the system.

If so, we would need to handle this in cockpitpackages.c in the bridge, and at the package level, rather than the menu item level. In addition we could have a way of hiding a menu item using override.json.

**Comment by igorSmirnovPlexi** [comment]
I agree, the right way is to override URL navigation too. How can I help you to make it?

**Comment by igorSmirnovPlexi** [comment]
@stefwalter I suggest to accept my patch until we'll have a proper way to override the menu entries

**Comment by igorSmirnovPlexi** [comment]
@stefwalter could you accept my patch?

**Comment by stefwalter** [comment]
This should be replaced by the more general purpose #5979

**Comment by dbarrell** [comment]
> The manifest.json has new property "override" which hide original menu entry from menu list.

Hi @smirnovigor where does this manifest go? In the systemd directory or in the package that is going to override sysytemd?

**Comment by smirnovigor** [comment]
It should go to the cockpit's packages directory (don't remember where exactly, cause I moved to another project)

**Comment by dbarrell** [comment]
That'll be `/usr/share/cockpit` then - Thanks!
