### ISSUE TITLE
Cockpit builds fail under mock

### ISSUE THREAD

**Issue by sgallagher** [cockpit-project/cockpit#4987]
The following steps worked on Sept. 6th, 2016 at 1200 EDT and failed on Sept. 7th at 0600 EDT. I have a script that automatically pulls the latest git HEAD every six hours (if anything has changed) and runs some tests on it, which includes a build under mock for Fedora Rawhide on x86_64.

```
rm -rf cockpit
git clone https://github.com/cockpit-project/cockpit.git
pushd cockpit
./autogen.sh
./tools/make-srpm
mock -r fedora-rawhide-x86_64 cockpit-wip-1.src.rpm
```

Some commit that landed between those two times above caused the following error to appear in the build:

```
+ make -j -j8 'CFLAGS=-O2 -Wall -Werror -fPIC -g -DWITH_DEBUG' all
NODE_ENV=production SRCDIR=. BUILDDIR=. ./tools/missing ./tools/webpack-make -d Makefile-webpack.deps webpack.config.js
/usr/bin/env: 'node': No such file or directory
WARNING: './tools/webpack-make' is missing on your system.
         You might have modified some files without having the proper
         tools for further handling them.  Check the 'README' file, it
         often tells you about the needed prerequisites for installing
         this package.  You may also peek at any GNU archive site, in
         case some other package contains this missing './tools/webpack-make' program.
```

(Note: Node.js and the npm modules should not be required to build /from/ the SRPM. They should only be required when building the SRPM itself, and this has been the case up to now.)

**Comment by larsu** [comment]
This happens because `Makefile-webpack.deps` depends on `pkg/storaged/override.json`, which is only generated during configure and thus triggers webpack to be run again.

    Prerequisite 'pkg/storaged/override.json' is newer than target 'Makefile-webpack.deps'.

For some reason, I'm getting the generated `override.json` included in the tarball made by `tools/make-srpm` in some cases, which is why it was pretty hard to reproduce this problem. The released tarball doesn't have it, though.

@stefwalter, do you have an idea on how we could fix this? Seems a bit much to require webpack to be run from the released tarball as well just for that one case?

**Comment by sgallagher** [comment]
Thanks folks, that fixed my automated scans.
