### ISSUE TITLE
containerized cockpit kubernetes on atomic

### ISSUE THREAD

**Issue by andrewklau** [cockpit-project/cockpit#5026]
There doesn't seem to be anyway to enable `cockpit-kubernetes` from within an atomic container environment (other than using cockpit/kubernetes, however this loses host level administration). 

I'd like to run cockpit/ws and connect to a remote kuberentes cluster. 

I've managed to do this by including `cockpit-kubernetes` in the underlying atomic host (`rpm-ostree pck-add cockpit-kubernetes`) and also by hacking the cockpit/ws image (adding the cockpit-kubernetes package, removing nsenter and adding an openssh-server for auth) but both methods seem wrong in the overall concept of being able to drop in cockpit anywhere.

**Comment by petervo** [comment]
You shouldn't have to hack the cockpit/ws image, rpm-ostree pkg-add cockpit-kubernetes should have been enough.  What was the behavior or error you got with just that change?

**Comment by andrewklau** [comment]
Yep `rpm-ostree pkg-add cockpit-kubernetes` was enough.

But I was curious to to see if there was an alternative method of having the package installed in the container instead. That way it won't be dependent on having the package available on the atomic host.

**Comment by stefwalter** [comment]
Atomic Host cannot be used to manage the kubernetes master itself. Apparently its currently by design that Atomic Host does not have the client tools necessary to configure kubernetes. The https://lists.projectatomic.io/projectatomic-archives/atomic-devel/ mailing list would be a good place to raise this issue.

CC @cgwalters
