### ISSUE TITLE
Extend branding to built-in modules

### ISSUE THREAD

**Issue by deryni** [cockpit-project/cockpit#5058]
Currently the `branding.css` file is loaded by the login page and the cockpit shell.

A recently approved PR (#5050) re-ordered the inclusion of `branding.css` in the shell to make branding more usable (to avoid CSS cascade priority issues, etc.).

The branding doesn't currently extend to the module iframe however as the modules don't load `branding.css`.

In a brief discussion with @petervo in the IRC channel yesterday he mentioned that doing this would potentially have issues because modules may be loaded from remote machines and so may not be using the same `branding.css` file (so the branding may not be complete/consistent).

He also commented that he would be hesitant to "bleed" the shell branding into the modules but that perhaps a mirrored module branding file might be appropriate for this case.

The usage here would be mainly (at least in our proposed usage) would be to apply consistent link coloring, etc. with the shell and existing product styles.

Is this something that people think would be useful enough to warrant doing?

**Comment by stefwalter** [comment]
The branding would be the wrong place to adjust CSS across all the modules. Branding is not part of the packages, and only the shell package should be aware of branding. 

I would suggest patching cockpit.css in the base package if you want to customize all of Cockpit to this extent.

**Comment by deryni** [comment]
I didn't have that branding distinction in my head when we were looking at this here. But I can see the argument/logic there. Using some other "branding" file instead is completely reasonable.

The idea of having another file (call it `module-branding.css` or whatever) loaded, by default, in the modules would be to allow for branding to be overlayed on pre-existing cockpit packages, etc. the way the shell branding pieces work (and without patching core cockpit files).

This isn't a large issue, and if it were added it would likely want to be documented with suggestions for what should and shouldn't be changed here, but it would help keep minor style things consistent (the remote machine problem would be "solved" by mirroring the file to the various servers and would be a local configuration issue).

The issue with patching a base package file is that you can't do that with pre-packaged cockpit (like in CentOS 7) as the file is not marked as a configuration file and, as such, will be replaced on each cockpit upgrade. (Not that that's an insurmountable problem obviously but it is an added annoyance.)

**Comment by ecarlisle** [comment]
@stefwalter : I was wondering the same, if a `package-additions.css` could be included as the last stylesheet in the package markup.  By default this could point to a blank.css file unless detected otherwise.  Such CSS might instead be bundled into cockpit.css as the last set of selectors, but that might be less obvious and harder to debug.

**Comment by dperpeet** [comment]
In the case of embedding cockpit, it would be great not to have to repackage cockpit. Is there a safe way to "inherit" styles?

**Comment by bochecha** [comment]
I was pointed to this issue by @dperpeet in #cockpit.

Over at the ideascube project, we're trying to embed cockpit components (our own ones, not the default ones) into our web application.

I got it working, but the components look very out of place in the middle of our pages, because they use their own CSS. We'd like them to use our CSS.

Could it be possible to somehow have our app CSS be the branding for the components we embed?

**Comment by stefwalter** [comment]
So lets think big picture for a moment.

 * As @larskarlitski has done, we've moving in the direction of removing entries in cockpit.css, and just bundling those in the component specific CSS files.
 * We want to serve the CSS resources compressed when possible, which makes them hard to insert lines into at run time or modify.

So maybe we should just go ahead and include branding.css as the last line in all the modules HTML files. This makes it clear what's going on ... easy to understand ... and we use browser caching across them all to preserve rapid load times.

That would mean that cockpit-ws (which includes branding) could and would override the CSS data shipped with the modules. But I think that makes sense. It's an external component overriding the base implementation. 

What do you think @petervo?

**Comment by ecarlisle** [comment]
Hi! I'd like to revisit this topic. I think the approach on @stefwalter 's post from 10/18/2016 would be fantastic.  Making branding.css the last-listed stylesheet in all packages could allow for consistent style-customizations across all packages. I'd appreciate any thoughts, feedback on considering this option. Thanks!

**Comment by larskarlitski** [comment]
> The usage here would be mainly (at least in our proposed usage) would be to apply consistent link coloring, etc. with the shell and existing product styles.

I can still see us doing this, but have a hard time justifying spending time on it without a more concrete use-case. Which branding css would like to override things like link color when we make this change?

**Comment by marusak** [comment]
This issue is closed due to inactivity.

If this issue is a bug report and you are still able to reproduce it, please
comment here and provide us with an updated reproducer.

If this issue is a request for a new feature, we are sorry, but we won't be able
to address this in any time soon. If you are interested in helping us with
the implementation, please comment here.
