### ISSUE TITLE
timeseries graphs incorrect

### ISSUE THREAD

**Issue by mbghsource** [cockpit-project/cockpit#5395]
I'm trying cockpit+pcp to monitor all the nodes of a minimal hyperconverged ovirt+glusterfs experimental cluster running centos 7. These systems have been running for at least 2 days continuously and the load on these systems are also not changing much.

Here is a screen recording showing gaps in timeseries when in reality there should be no such gaps.
https://drive.google.com/open?id=0B9LV8Sb_qIEUUllvaE5rQlV0eUk

As soon as I login to cockpit, I see the graphs with a 5 minute window just starting to show values.
When, I increase the time window to 6 hours, the graphs are all zero. When I go back in time, I am able to see some data in the history. When I come back to the current time, the graph doesn't show any values, unless I switch back the time window to 5 minutes. Even then, the graph only starts showing data from that instant going forward.

The following behaviors are confusing. 
- There is no way of differentiating between real zero values in the graph and gaps in timeseries.
- Also, every time I go back to the 5 minute time window, the data that was shown a few minutes ago, is gone, and only fresh data is shown.

I did not do any specific configuration changes to cockpit. I just installed cockpit and pcp rpms and started using it with whatever defaults it was configured with.

**Comment by marusak** [comment]
This issue is closed due to inactivity.

If this issue is a bug report and you are still able to reproduce it, please
comment here and provide us with an updated reproducer.

If this issue is a request for a new feature, we are sorry, but we won't be able
to address this in any time soon. If you are interested in helping us with
the implementation, please comment here.
