### ISSUE TITLE
test-authssh fails in ssh_option_set

### ISSUE THREAD

**Issue by stefwalter** [cockpit-project/cockpit#5527]
I noticed that ```test-authssh``` has started warning on git master with the following message:

```
** (cockpit-ssh:26393): WARNING **: (../src/ws/ssh.c:1155):cockpit_ssh_connect: runtime check failed: (ssh_options_set (data->session, SSH_OPTIONS_USER, data->username) == 0)
```

@petervo Is this a result of the refactoring that happened recently?

**Comment by petervo** [comment]
Yes, and it's expected from one of the basic auth tests to test the basic auth parsing code. But because it's a separate process we don't really have a way to expect it so it doesn't show up like we do other warnings in the tests. We could downgrade to a message, or explicitly test for the empty username name case and abort early if having it like this is bad.

**Comment by stefwalter** [comment]
I guess it's fine. It's worth working towards getting the tests to be quiet ... but I guess this is pretty far away from that.
