### ISSUE TITLE
Show project display name instead of namespace when it is avialable?

### ISSUE THREAD

**Issue by vanloswang** [cockpit-project/cockpit#5729]
On Origin web console, it will show project display name instead of namespace when it is avialable. But on Cockpit Cluster UI, it does not have this feature. We can use display name to distinguish the projects better, and the namespace is more or less  an internal identity. for my case, I prefer this feature on Origin web console, Shall we add this feature on Cockpit?

**Comment by stefwalter** [comment]
Sure. Will you add a pull request?

However, we always want to display the namespace name, since that's teh name that can be copied and pasted into the console. If they are different I would suggest something like:

"Display name (real-name)"

If both display name and real name are identical then just:

"real-name"
