### ISSUE TITLE
cockpit doesn't fire session timeout

### ISSUE THREAD

**Issue by igorSmirnovPlexi** [cockpit-project/cockpit#5936]
I'm running my own plugin on cockpit, wich subscribes to the server webSocket chanel via cockpit-bridge. I expect that after 15 minutes, session timeout will be fired, but cockpit continues to run.

**Comment by petervo** [comment]
Is your websocket still connected? The timeout only applies when nothing is connected.

**Comment by igorSmirnovPlexi** [comment]
Even when my websocket is closed, cockpit runs his own connection incessantly.
<img width="1264" alt="screen shot 2017-02-23 at 5 19 21 pm" src="https://cloud.githubusercontent.com/assets/19838682/23265486/6c5661de-f9ed-11e6-90da-0a72634f6830.png">

**Comment by petervo** [comment]
The connection opened by cockpit.js can be closed by calling ```close``` on the transport object. 

Are you opening your own websocket separate from cockpit.js? I'd be interested in hearing your reasons for doing that and still using cockpit.js. I wouldn't expect them to play well together.

**Comment by igorSmirnovPlexi** [comment]
Mmm, did I miss something? 
I'm opening my connection via cockpit channel (cockpit bridge). 
In the same time the cockpit is opening his own websocket connection for his own propose (as I think).
In the end I have two separate connection to the server. Is it right?
<img width="1264" alt="screen shot 2017-02-23 at 5 19 21 pm" src="https://cloud.githubusercontent.com/assets/19838682/23267096/5fcd08aa-f9f2-11e6-946f-0054ec48e789.png">

**Comment by petervo** [comment]
I think i'd have to see some code to figure out what you are doing. If you are only using cockpit.js there should only be one websocket connection. You have a snippet i can try out?

**Comment by igorSmirnovPlexi** [comment]
This how I create my ws conection. 

```
function openConnection() {

    return new Promise((resolve, reject) => {

        var socketUrl = getSocketUrl(getCurrentPort());

        // wait for cockpit connection
        cockpit.transport.wait(() => {

            socketUrl += "/cockpit/channel/" + cockpit.transport.csrf_token + "?" + window.btoa(JSON.stringify({
                    payload: "websocket-stream1",
                    address: getGuestMachine(),
                    port: SETTINGS.serverPort,
                    path: "/"
                }));

            var socket = new WebSocket(socketUrl);

            socket.onopen = () => resolve(socket);
        });
    });
};
```

**Comment by petervo** [comment]
You are explicitly opening a 2nd websocket, so as expected you now have two. One opened by cockpit.js and the other by this code.

Depending on what you are trying to achieve this may not be necessary. See https://github.com/cockpit-project/cockpit/blob/master/pkg/kubernetes/scripts/kube-client-cockpit.js#L560 https://github.com/cockpit-project/cockpit/blob/master/pkg/kubernetes/scripts/kube-client-cockpit.js#L623 for an example of how we create a websocket javascript object that uses a cockpit channel to communicate rather than make another websocket connection. 

If you determine that we really need both then you can't expect the main websocket connection established by cockpit.js to disconnect when your custom socket is disconnected. You'll need to close that one manually if that is what you need to happen.

**Comment by igorSmirnovPlexi** [comment]
Thank you very much, I'll try this aproach and will inform you once it will done. 
Thank you again, man!

**Comment by igorSmirnovPlexi** [comment]
I have connected through cockpit.channel, one websocket connection to the server. 
When my server close his websocket connection, created channel fire close event and I call to transport.close to close the connection.

**Comment by stefwalter** [comment]
When Cockpit loads up the default index.html preloads iframes for the system and dashboard pages in order to speed up the load time. Do you think this may be related? Are you trying to avoid having any of the default user interface? If so, overriding index.html with your own copy (see cockpit.conf) may be a solution.

**Comment by igorSmirnovPlexi** [comment]
I'm not trying to change default pages. I just have my own plugin, which loads as home page and in this case preloads are unuseful. Is there a way to prevent this?

**Comment by igorSmirnovPlexi** [comment]
Sorry but I have to reopen this issue.
Even after my server closes websocket connection, no session timeout was fired, cause socket still has active connection, probably for system page.
Calling to ```cockpit.transport.close``` doesn't help though, because cockpit is called from iframe instance and it doesn't affect on parent cockpit instance.
Calling to ```cockpit.transport.close``` from console (parent instance) does close the session.

**Comment by petervo** [comment]
No there isn't a way to prevent cockpit.js from opening a websocket connection. If you did that that would cause all other plugins to not work. If all you want to do is close the session you can use ```cockpit.logout()```(http://cockpit-project.org/guide/latest/cockpit-login.html.)  or ```cockpit.kill``` depending on what exact behavior you would like.

If you don't care about other plugs replacing the shell package might be a good option. Otherwise you might want to recondiser using the cockpit channel based websocket approach i suggested earlier.

**Comment by igorSmirnovPlexi** [comment]
@petervo if ```cockpit.logout``` is called from iframe, it doesn't affect parent window! 
Does plain cockpit without any external plugins have session timeout?

**Comment by petervo** [comment]
> @petervo <https://github.com/petervo> if |cockpit.logout| is called from
> iframe, it doesn't affect parent window!

You are correct it doesn't currently work the way I thought it did. Sorry for misleading you there. We will either make it work or document why it does not.

> Does plain cockpit without any external plugins have session timeout?

I don't really know what you mean by this. I think you are possibly misunderstanding what session timeout is meant for. A session times out when it has no open channels for a period of time. When a user is logged into cockpit in a browser, even when they are not actively doing anything, there is always a stream of messages going back and forth on the websocket. Things like health checks, metrics etc... In addition cockpit opens up a lot of long lived channels, ei dbus connections, file watches etc... where the channel is kept open and reacts to event from the underlying apis. It is only when the user logs out or closes the tab and the websocket is disconnected that the cockpit timeout kicks in. If they don't reconnect within a certain amount of time, the session is considered abandoned and closed and the next time they try to connect they will need to log in again.

It sounds like that is not the behavior that you are looking for. If not you are probably better off providing your own shell that does not do health checks. You would also need to track and limit the duration of long lived channels.

**Comment by igorSmirnovPlexi** [comment]
No problem, I close this issue. 
In my specific case I do need to close connection to my server, if there is no user activity, even if monitoring subscriptions are still active. I managed this by timing out my websocket channel and throwing notification to the user.
