### ISSUE TITLE
Locking session causes connection closing

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#6135]
With 135's new Lock/Unlock feature:
 * Log in as some admin user (not root, not having sudo NOPASSWD) and enable "Reuse my password for  privileged tasks"
 * Go to "Services" and select some harmless service which you can safely restart, like `/system/services#/crond.service`.
 * Click on "Unlocked" in the  top bar. That label will just disappear (!).
 * Click on "Stop" button for the service
 * Get an error dialog "Server has closed the connection".

After a page reload in the browser, the "Locked" label appears, and the trying to stop the service now correctly produces a "Permission denied" error dialog box.

So this is not really a functional breakage, but mostly polish.

**Comment by stefwalter** [comment]
> Click on "Unlocked" in the top bar. That label will just disappear (!).

It disappears when we don't really know if we can display "Locked". May need some fine tuning here. But the disappearing is by design in certain cases. The canonical case here is logging in as root. We can never display "Locked". A second case is if the user has sudo NOPASSWD set ... we can never display "Locked". If your case doesn't fall under those, then lets debug it, and patch that.

> Get an error dialog "Server has closed the connection".

Indeed the lock stuff needs lots of polish. The actual failure here is that we close connections through the privileged bridge. That's why I couldn't finish the feature. The pages need to be made aware of the fact that they have to reconnect to certain things, 

I pragmatic first step may be to close those sorts of connections with "access-denied" instead. I think I know a way to implement that.

But even then, I don't think this fixes the issue.

**Comment by martinpitt** [comment]
> If your case doesn't fall under those,

Right, I should have mentioned that: This is the official cockpit 135 F25 package  from koji on my laptop. I logged in as normal human user (martin) and I don't have NOPASSWD. I updated the description accordingly.

**Comment by larskarlitski** [comment]
We removed the locking feature a while ago.
