### ISSUE TITLE
trying to remove a disk from a RAID that is not running results in an error

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#6143]
![screenshot from 2017-03-17 12-48-34](https://cloud.githubusercontent.com/assets/209895/24041967/216fbfd8-0b10-11e7-8796-d1fa0c04170d.png)

I tried to remove the last disk from a RAID. I made sure to stop it first. Then I pressed the remove button.
It gave me the error above.

If it's not possible to remove a disk from a RAID that is not running, maybe it's better to make the remove button insensible.

**Comment by andreasn** [comment]
@mvollmer

**Comment by mvollmer** [comment]
Same for adding.

**Comment by mvollmer** [comment]
Okay, let's make it so that people can't remove a disks if that would destroy data.  (Only remove spares, or failed disks, or if there is a spare to take over immediately.)  This needs a running array.

Note that adding/removing disks in Cockpit is only for managing failed disks, not for growing/shrinking the size of the array (rehsaping).  We can't do reshaping.  Maybe we should, or maybe we should put all our money on lvm2.
