### ISSUE TITLE
storaged: iscsi becomes very unhappy when connecting to two targets at the same time

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#6300]
I have two iscsi target servers.
One on 192.168.1.21 (target name iqn.2017-04.io.rh-storage:server1) and the other on 192.168.1.54 (target name iqn.2017-04.io.rh-storage:server)

When I connect the first one, everything is fine.
But as soon as I connect another one, I get an Oops in Cockpit.
And then I can't do anything until I do
` sudo iscsiadm --mode node --logoutall=all` from the CLI

**Comment by andreasn** [comment]
@mvollmer probably knows what's going on here.

**Comment by andreasn** [comment]
Just tested this on a fresh Fedora 25 system, and it happens there as well.

**Comment by marusak** [comment]
This issue is closed due to inactivity.

If this issue is a bug report and you are still able to reproduce it, please
comment here and provide us with an updated reproducer.

If this issue is a request for a new feature, we are sorry, but we won't be able
to address this in any time soon. If you are interested in helping us with
the implementation, please comment here.
