### ISSUE TITLE
storaged: iscsi initiator name change doesn't bite until reboot

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#6313]
To reproduce:
* Set the name for the initiator on a system called A
* Create a new connection to a iscsi target
* Get the list with LUNs on the Target
* Get asked for credentials, even if there are no credentials needed
* Go to the server that runs the Target, System B, and check the journal
* It will say that it refused the connection
* Realize that you spelled the name wrong when you set the name for the initiator on System A
* Go back to the initiator configuration on System A, this time set the correct name so it matches what's in the ACL section on the Target.
* Try to connect to the Target again. Fails this time too.
* Reboot System A.
* Try again to connect to the Target. This time it works.

**Comment by marusak** [comment]
This issue is closed due to inactivity.

If this issue is a bug report and you are still able to reproduce it, please
comment here and provide us with an updated reproducer.

If this issue is a request for a new feature, we are sorry, but we won't be able
to address this in any time soon. If you are interested in helping us with
the implementation, please comment here.
