### ISSUE TITLE
Ubuntu 17.04 cockpit-docker does not install if mainline docker is installed

### ISSUE THREAD

**Issue by opless** [cockpit-project/cockpit#6515]
Story:
I wish to install docker-cockpit.

- I am using the docker-ce package from dockers repo (yes, the yakkity version.)
- Docker installs now appear to be called docker-ce / docker-ee 
- However cockpit-docker depends on docker.io or docker-engine

Result:
It is impossible to install cockpit-docker.

This issue probably exists in debian too.

If there's a workaround that'd be great!

-S

**Comment by stefwalter** [comment]
Which version of docker are you using? @martinpitt Is there a way to accomplish this on Debian if an alternate Docker is installed?

**Comment by martinpitt** [comment]
The cockpit-docker Debian package already has

    Recommends: docker.io (>= 1.3.0) | docker-engine (>= 1.3.0) | docker-ce (>= 1.3.0),

so it should be possible to install docker-ce. Even if you install something else, it's just a recommends so you can still keep cockpit-docker installed.

However, this was only changed in commit 162ecb0ae on May 8, so presumably you didn't have a version with that fix installed. Hence this should be fixed with current versions.

**Comment by martinpitt** [comment]
Forgot: To get a version with that fix, install cockpit from backports:

    sudo apt install -t zesty-backports cockpit-docker

**Comment by opless** [comment]
Cheers, I'll check it out.
