### ISSUE TITLE
Provide ARM package for Debian 8 (jessie)

### ISSUE THREAD

**Issue by matthewkeogh50** [cockpit-project/cockpit#6560]
Hi,

Just wanted to say cockpit is amazing. Thanks for all the hard work :) are there any plans to add support for raspbian (running on a raspberrypi) 

following the install guide for debian:

sudo apt-get install cockpit = E: Unable to locate package cockpit

deb http://repo-cockpitproject.rhcloud.com/debian/ jessie main = -bash: deb: command not found

Thanks

Plan:
 - [X] Wait for Debian 9 (Stretch) release
 - [X] Wait for Cockpit to enter testing, so that it becomes backportable
 - [X] Wait for Cockpit 143 to clear binary NEW
 - [x] Upload Cockpit to stretch-backports, needed backports NEW
 - [x] Upload Cockpit to jessie-backports-sloppy

**Comment by da2x** [comment]
The repository you mention seems to be gone.It could also conflict with Raspbian.

Debian moves very slowly with new packages, and Raspbian slower still. Debian recently added [Cockpit in sid](https://packages.debian.org/sid/cockpit) (unstable), and at the pace of Debian it will be yeas before it reaches you on Raspbian. If you want cutting edge technology, you could consider [installing Fedora on your Raspberry Pi](https://fedoraproject.org/wiki/Raspberry_Pi). Fedora comes with Cockpit by default!

**Comment by stefwalter** [comment]
@martinpitt Is there something that can be done here?

**Comment by anantmishra** [comment]
:+1:

**Comment by martinpitt** [comment]
The repository does exist, but it doesn't have directory indexes (so you can't look at it easily in a browser - but try e. g. http://repo-cockpitproject.rhcloud.com/debian/dists/jessie/main/binary-amd64/Release). And foremost it only has amd64 packages, and the RasPi is armhf.

My plan so far was this:

 - Wait for Debian 9 (Stretch) release (happened last weekend)
 - Wait for Cockpit to enter testing, so that it becomes backportable (happened yesterday)
 - Wait for Cockpit 143 to clear binary NEW (should happen in a few days hopefully)
 - Upload Cockpit to stretch-backports and jessie-backports-sloppy

Then there will be "official" Cockpit Debian armhf packages for Debian 8 and 9 which ought to work on Raspian.

**Comment by martinpitt** [comment]
There will soon be an ARM package for Debian 9, in the official [Debian backports repository](https://backports.debian.org/). This is still stuck in [the NEW queue](https://ftp-master.debian.org/backports-new.html), but I hope it will be processed in the next days/few weeks.

There is not currently an ARM package for Debian 8. If there is much demand, I can also upload it to jessie-backports-sloppy, so that there is again an official backport. But this should wait for the Debian 9 backport.

Until then you are of course welcome to just backport/build it yourself, with something like 
```
# install build dependencies
sudo apt-get install -y debhelper dh-systemd dh-autoreconf autoconf automake git intltool libssh-dev zlib1g-dev libkrb5-dev libxslt1-dev libglib2.0-dev libsystemd-dev libpolkit-agent-1-dev libjson-glib-dev libpam0g-dev xsltproc xmlto docbook-xsl glib-networking openssh-client python

dget http://httpredir.debian.org/debian/pool/main/c/cockpit/cockpit_146-1.dsc
dpkg-source -x cockpit_*.dsc
cd cockpit-*
dpkg-buildpackage -us -uc -b
```

**Comment by anantmishra** [comment]
Thanks @martinpitt for the update. I will appreciate it if you could upload it to jessie-backports-sloppy so that we have the package for Debian 8 as well. I would like to install it on [raspbian](http://raspbian.org/) that still runs jessie.
Due thanks for providing the build steps. I will try build it on [raspbian](http://raspbian.org/) in the meantime.

**Comment by martinpitt** [comment]
Cockpit is now in stretch-backports for Debian 9. http://cockpit-project.org/running.html is updated accordingly.

**Comment by martinpitt** [comment]
The package got accepted into jessie-backports-sloppy, so it is now [available on ARM](https://buildd.debian.org/status/package.php?p=cockpit&suite=jessie-backports-sloppy) as well.
I sent a [PR to update the install instructions](https://github.com/cockpit-project/cockpit-project.github.io/pull/81) accordingly.
