### ISSUE TITLE
Automatic logout

### ISSUE THREAD

**Issue by Sebak17** [cockpit-project/cockpit#6677]
Hello,
when I logout and login to panel, the connections to another server have a error "Login failed" and I must to login to another server again.

**Comment by petervo** [comment]
Are you talking about secondary servers on the dashboard? If so did you need to log into those servers with a different password? That would be expected behavior as cockpit doesn't store the password anywhere. If they have the same password as the primary server the password should be reused as long as you checked the "Reuse my password for privileged tasks" check box on the login page.

**Comment by stefwalter** [comment]
No reply from original issue reporter. Closing this issue.
