### ISSUE TITLE
kubernetes: Better explain what "Cluster" is and improve default state

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#7066]
This came up during usability testing (of an unrelated feature):

Many participants were exploring, and found the "Cluster" page (cockpit-kubernetes). By default it looks like this:

![kube](https://user-images.githubusercontent.com/200109/27381043-98180d0e-5681-11e7-986e-8c59e52d7195.png)

Nowhere does this say "Kubernetes" or "OpenShift" or any other hint that the "server" mentioned there is not *that* server you are currently working on.

Also, we should maybe show something different if there is no ~/.kube/config at all - perhaps some links to Kubernetes/OpenShift docs?

CC @andreasn, @garrett

**Comment by garrett** [comment]
Here's a mockup of a wording change:

[![cluster-not-found](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/kubernetes/cluster-not-found.png)](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/kubernetes/cluster-not-found.png)

I agree it should also have an empty state, instead of being greeted with an error.

The empty state should probably look similar to what happens when you click the "Troubleshoot" button, but slightly customized.

[![cluster-empty-state](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/kubernetes/cluster-empty-state.png)](https://raw.githubusercontent.com/cockpit-project/cockpit-design/master/kubernetes/cluster-empty-state.png)

_This is basically the same as the "Troubleshoot" dialog minus the errors, plus the Kuberenetes set up string as the header._

I was considering a modification of the not-found state as an empty state, but it wound up feeling like "Cluster needs setup / You should really set up the Kubernetes cluster / [Set Up Cluster]" and then a dialog that restates setting up cluster again.

As other parts of Cockpit that require configuration immediately drop you into set up dialog (possibly for the same reason), it felt like skipping the empty state screen and going directly to an empty state dialog made sense here.

Do you agree, @andreasn?

**Comment by garrett** [comment]
By-the-way, the **Image Registry** has this exact same problem (except it is lacking "Troubleshoot" and only has "Reconnect").

![screen shot 2018-01-25 at 17 07 54](https://user-images.githubusercontent.com/10246/35398495-4f5bdb1e-01f2-11e8-9939-677222bf72e8.png)

**Comment by martinpitt** [comment]
Our kubernetes UI is on maintenance mode, so this won't happen any more. See https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/message/SBDE64DAIVTLIYRGVMESUPR5STRRFCGW/
