### ISSUE TITLE
External channel usage

### ISSUE THREAD

**Issue by petervo** [cockpit-project/cockpit#7720]
Our current external channels usage in machines/vnc and sosreport do not properly set the host if those packages are used from a secondary machine. Additionally they hard code the application instead of using relative urls. That breaks usecases when the application is not 'cockpit'

**Comment by marusak** [comment]
This issue is closed due to inactivity.

If this issue is a bug report and you are still able to reproduce it, please
comment here and provide us with an updated reproducer.

If this issue is a request for a new feature, we are sorry, but we won't be able
to address this in any time soon. If you are interested in helping us with
the implementation, please comment here.
