### ISSUE TITLE
In the windows system to visit cockpit modify the ip is not successful

### ISSUE THREAD

**Issue by RoyinRolland** [cockpit-project/cockpit#7859]
In the windows system to visit cockpit modify the card ip is not successful.

No pop-up box:
"Changing the settings will break the connection to the server, and will make the administration UI unavailable."

**Comment by petervo** [comment]
I don't really understand this, could you explain a little more what you are trying to do? Maybe step by step instructions or screen shots that detail what you are getting vs what you expect.

**Comment by machadotiago** [comment]
@petervo we have the same problem here and it is reproducible in many Windows version (we tried from 7 to 10)
I recorded a video for that, please check it here: [changeip.zip](https://github.com/cockpit-project/cockpit/files/2435370/changeip.zip)
Basically the problem is: it is not possible to set an static IP of a server that is running Cockpit if the client is using Chrome running on a Windows.
If we try the same step by step of what I did in the video but from a client on a Linux machine it works perfectly.

**Comment by DiegoRampim** [comment]
We have the same problem.
I changed the value of `rollback_time` for `10.0` and works on `Windows 7` and `Windows 10`. But I think this solution is not the better.  Any suggestion? 

https://github.com/cockpit-project/cockpit/blob/04116d29f4d8f1aa83eea03db49a4afffd4d191a/pkg/networkmanager/interfaces.js#L2098

**Comment by mvollmer** [comment]
Thanks a lot for the video.  Let me try to summarize the expected behavior:

- Cockpit is connected to the machine via IP address 192.168.15.13.
- Change the IP address on the machine from 192.168.15.13 to 192.168.15.51
- "This breaks the connection" dialog comes up after a while
- Click "Do it anyway"
- Cockpit gets disconnected (because it still tries to talk to the old IP address)
- Change the address in the URL bar
- Cockpit loads again and can be used.

Is that what you see 'everywhere' except with Chrome on Windows?

What versions of Chrome are you using?

Can you show the journal messages of the Linux machine?

**Comment by mvollmer** [comment]
> Can you show the journal messages of the Linux machine?

Also, is there anything in the Browser JavaScript console?

**Comment by machadotiago** [comment]
> Is that what you see 'everywhere' except with Chrome on Windows?

Exactly!


> What versions of Chrome are you using?

We have tried many versions of Chrome, including the latest one (Version 69.0.3497.100 (Official Build) (64-bit))


> Can you show the journal messages of the Linux machine?

I have attached the logs to this message. It starts at 11:45:32 where you can see me changing the IP to 192.168.15.55
[output.txt](https://github.com/cockpit-project/cockpit/files/2450811/output.txt)


> Also, is there anything in the Browser JavaScript console?
This is what the console has printed out:

![image](https://user-images.githubusercontent.com/3775353/46542228-4d284580-c894-11e8-8b26-0b0d9e3a9a24.png)

**Comment by machadotiago** [comment]
Hi @mvollmer ,
do you have any idea where the problem is?

**Comment by mvollmer** [comment]
(Thanks for the reminder!) 

> do you have any idea where the problem is?

No, unfortunately not, but I think we can narrow things down.  According to the logs, everything goes as planned on the Linux box.  (There are some polkit rejections that I need to have a close look at, but right now I think they are not relevant.)

The whole mechanism relies on the fact that the connection from the browser to the target machine survives when the target disappears temporarily.  It is very well possible that Windows and Linux behave differently enough.  Reducing `rollback_time` will make the traffic interruption shorter, and that might allow the connection to survive also with WIndows. If that is all true, then this is a proper fix. (Tbh, I don't know much about TCP/IP in this regard...)

In any case, a page reload should reconnect the browser to the target.  However, you will indeed not be able to actually change the IP address because it will always be rolled back.

I will try to find a Windows machine and learn more about TCP/IP timeouts.

@machadotiago, are you able to test with `rollback_time = 10`?

**Comment by machadotiago** [comment]
> @machadotiago, are you able to test with `rollback_time = 10`?

we will test it today and I'll let you know the result.

**Comment by machadotiago** [comment]
I tried it today with different rollback_time values (from 2 seconds to 15) and the problem persist.
It actually worked one single time (when using 10 seconds) but I could not reproduce it again.

**Comment by machadotiago** [comment]
Forget what I said in the comment above about my tests. I did some wrong settings in my environment. 
After changing the timer in the correct place it is now **working fine**. First, I tried changing the rollback_timer from **15s** to **10s**. It worked but I could still simulate the problem after trying a few times. I changed then to 7s (half of the original value) and now it works 100%.

**Comment by mvollmer** [comment]
> I changed then to 7s (half of the original value) and now it works 100%.

Let's go with 7 seconds, then!  Thanks!

**Comment by samanvay123** [comment]
Hi,
I am very new to linux and networking.I am not able to get the file interface.js so that i can modify the rollback_time.i am using rhel 8.Thanks for the help !
