### ISSUE TITLE
OpenWRT/LEDE packages.

### ISSUE THREAD

**Issue by rct** [cockpit-project/cockpit#7882]
For SOHO networks, cockpit client support to provide visibility into network devices running OpenWRT/LEDE would be very useful. 

Apologies if this isn't the right place to open this issue.   I'd imagine a number of useful hooks are already available to support OpenWRT/LEDE's web interface - LuCI (Lua Configuration Interface). 

As a user,
I would like to see statistics from my OpenWRT/LEDE devices in the Cockpit dashboard along with my other systems.

**Comment by stefwalter** [comment]
Machines in the Cockpit dashboard are running a Cockpit session, with the cockpit-bridge and cockpit-system packages installed. Is that the case for OpenWRT?

**Comment by rct** [comment]
No, but I think that would be the desired outcome.  AFAICT, no cockpit packages exist for OpenWRT or LEDE.  I'm assuming whatever porting is needed to support a new linux distro would be required.  OpenWRT or LEDE is a very minimal OS with no systemd.  There is a configuration interface called uci.

**Comment by stefwalter** [comment]
At the current time Cockpit doesn't show a useful UI on systems without systemd. That could change given sufficient effort. 

That is listed on the ideas page: https://github.com/cockpit-project/cockpit/wiki/Ideas

In order to find people willing interested in  working on Cockpit without systemd, or OpenWRT packages, you could post on the mailing list:

https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/

Closing this issue. But please let me know if you're willing to work on it, and we can reopen it.

**Comment by sean9999** [comment]
this would be awesome, but given the constraints openwrt typically runs under, probably not feasable

**Comment by Xenador77** [comment]
Please delete this if it is not "polite" to comment on an old closed issue but is anyone else interested in figuring this out with me? Maybe an extremely limited cockpit, "sidecar?"
