### ISSUE TITLE
os update: prioritize packagekit pkg updates over ostree updates pkg?

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#7912]
I always get the "Unable to communicate with OSTree" page on my system when I build the code. 
I feel package based systems are still more common that ostree based ones.
Should we prioritize the packagekit updates pkg over ostree pkg?

**Comment by martinpitt** [comment]
Back when I wrote this, my reasoning was that *if* somone uses rpm-ostree, then installing cockpit-packagekit should not scribble over that by attempting to (essentially) run `dnf upgrade` on an rpm-ostree system, as that would just fail (or worse, destroy the ostree). Unfortunately manifests are not powerful enough to say "only show this if this `command` is true" - having that capability would be really useful for this case; same for ovirt or "Applications".

But until then, IMHO this should err on the safe side and show ostree if you have both that and packagekit installed. It's not a strong opinion though, so I'm happy to be convinced otherwise.

(And believe me, I feel the pain all the time as I hack on packagekit very often ☺)

**Comment by martinpitt** [comment]
I don't see a better way right now, I'm afraid, so I'm closing this. Please reopen if you have some idea.
