### ISSUE TITLE
machines: amount of RAM and how it's used is separate

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#8052]
So I can see that I have 1000 MiB RAM on my VM, but the only way to see how it's utilized is if I jump over to the performance tab.
So I wonder if it makes sense to put the stats directly in the Overview tab.

**Comment by andreasn** [comment]
Usage is pretty empty by itself anyway.

**Comment by mareklibra** [comment]
@andreasn , good idea.
Formerly, the `Usage` subtab was meant not only for memory/cpu but for networks and disks as well.
But this is recently not yet implemented.
Such a statistic might fit the "Overview" subtab well.

I can imagine some small graphics representation of how much memory/cpu is consumed/available on the Overview subtab. We would get rid of the donut charts completely.

Anyway, this might be tricky from performance perspective.
Collecting of such "usage" data is quite expensive operation since polling is required.

Recently, the polling is started/ended when corresponding subtab is opened/left.
We can do the same thing on the Overview subtab, but load will be increased.

We might make use of 3rd party collecting tool (like PCP) but this would bring another dependency to get cockpit-machines working.

@martinpitt , what do you think?

**Comment by martinpitt** [comment]
@andreasn: What do you mean by "performance tab"? "Usage" maybe? We already start polling per machine once you activate the "Usage" tab, and as this is (deliberately) not the default tab we can limit the performance hit and avoid immediately polling *all* VMs (which can be numerous!). Once we do poll, then I figure showing more details from the poll should be fine.

If the target machine has PCP installed and enabled we could use it of course, but (1) we can't generally peek into the VM too much as a we don't know how to log in, and (2) PCP isn't commonly found in VMs so we need a good fallback.

**Comment by KKoukiou** [comment]
TBH I like the separation of VM configuration details in the overview tab, which we just fetch from the libvirt xml and utilization data in other tab. @andreasn unless you have strong opinion here would you mind if I closed this?

**Comment by KKoukiou** [comment]
@andreasn I am closing this since it's horribly outdated - if you think it still makes still sense I will be glad to refactor the whole VM row according to some mockup.
