### ISSUE TITLE
Apps: installed apps don't display

### ISSUE THREAD

**Issue by jeepingben** [cockpit-project/cockpit#8066]
Installed applications with icons defined in their metainfo aren't displayed as installed.

https://github.com/cockpit-project/cockpit/blob/master/pkg/apps/watch-appstream.py#L229
This is wrong - dir isn't declared in this scope and the builtin function dir is being passed instead.
The fix is simple, I'm not sure how to test it, but I think just adding an icon to the installed component used in the test would trigger it.

**Comment by mvollmer** [comment]
> Installed applications with icons defined in their metainfo aren't displayed as installed.

This does generally work, and I am afraid we need more information to reproduce this.
I am adding a test with icons: https://github.com/cockpit-project/cockpit/pull/11632
Please reopen if this is still broken for you.

> https://github.com/cockpit-project/cockpit/blob/master/pkg/apps/watch-appstream.py#L229

The code has changed since, I guess.  There is a mention of 'dir' in `convert_cached_icon` but that should be fine.  Also, installed meta data shouldn't have cached icons, only local and static, afaik.
