### ISSUE TITLE
machines: consoles management

### ISSUE THREAD

**Issue by suomiy** [cockpit-project/cockpit#8140]
Features
 - implementation by a dialog
 - should manage multiple consoles
 - allow remote connections

should be secured by implementing some of the following
- set interfaces IP
- set password
- set time limited token

**Comment by mareklibra** [comment]
@garrett , @andreasn , may I ask you for design of this?

The user will be able to configure `Spice`, `VNC` and `Serial` console for a VM.
None or multiple console types are valid for a single VM.

For `Spice` and `VNC`, the details include:
- IP
- port (an integer of `auto`)
- optional fields:
    - password

For Serial console, the details:
- `pty` device

**Comment by mareklibra** [comment]
For now, I would skip TLS. Will be needed, but let's go step-by-step.

**Comment by suomiy** [comment]
> For now, I would skip TLS. Will be needed, but let's go step-by-step.

I guess it will take some effort (tests likely), but at least we could include it in the design.

**Comment by suomiy** [comment]
I think there should be a possibility to switch between `Spice`, `VNC` and `Serial` modes (views)?.

reasons:

- there is no TLS for `Serial` and `VNC`
-  `Serial` is different ( port could also be there)


#### Allowing IPs
Also there should be a way to allow all IPs to connect with to `Spice` and `VNC`  .

1. a checkbox/ button
2. a hint that you have to type 0.0.0.0 to the IP field to allow all IPs
3. a button that will fill in 0.0.0.0 to the IP field

**Comment by mareklibra** [comment]
As mentioned above, I would skip TLS for now. Dealing with certificates is sufficiently complex topic for a separate PR/issue.

I have not strong opinion on "switching between modes", it's a matter of design, IMO. The important thing is, that none or multiple can be enabled/configured for a single VM.

Good point with the binding to IP 0.0.0.0. It should be there, makes sense from libvirt perspective.
Anyway, having that, we will still face the issue with remote connection (domain xml will contain 0.0.0.0).

One of the ways how to proceed here is to let the user to provide yet another IP which will be used instead of 0.0.0.0 . To do it automatically, we can deal with guest-agent. Or any better way?

**Comment by KKoukiou** [comment]
This is duplicated by https://github.com/cockpit-project/cockpit/issues/8140
