### ISSUE TITLE
machines: add image detection to create vm dialog

### ISSUE THREAD

**Issue by suomiy** [cockpit-project/cockpit#8141]
image detection and populating the dialog with values (OS, maybe memory?). Quite bothersome to implement

see also #7820 for original discussion

**Comment by andreasn** [comment]
Would you mind breaking this issue up even further into two issues?
I feel they are two very different problems.
Image Detection is about making the setup smoother, picking better default based on what the OS needs, while Description Field is about making it possible to identify the VM easier.
Maybe we can make this issue about the image detection, and then we can open up a separate issue about the description field.

**Comment by andreasn** [comment]
The main problem this would solve would be to give better defaults based on what a particular OS needs, instead of forcing the administrator to look it up the minimum system requirements online ([RHEL7 example](https://access.redhat.com/articles/rhel-limits)) and lessen the risk of setting up a VM that doesn't work, because of a misconfigured parameter.
This is also needed to get on level with current virt-manager behaviour, so it's not a user experience regression to move from handling your VMs in Cockpit instead of virt-manager.

The behaviour I imagine is that when you put a ISO in the dialog, it will automatically fill out the other fields based on the information in the [libosinfo database](https://libosinfo.org/), still keeping them editable of course, for when you need more than the recommended disk space etc.
For ISOs that doesn't match any entries in the database, it would keep the same behaviour as now.

**Comment by KKoukiou** [comment]
This was implemented by:

commit 5ed43aaf251ba0a7b7a0a182a811fa5cb7a74865
Author: Katerina Koukiou <kkoukiou@redhat.com>
Date:   Thu Apr 11 10:57:35 2019 +0200

    machines: Implement OS auto-detection in the VM creation dialog when possible
