### ISSUE TITLE
Local (Host) VNC sessions

### ISSUE THREAD

**Issue by jcpunk** [cockpit-project/cockpit#8192]
Cockpit can currently show VNC sessions for VMs.

It would be nice if I could also show VNC sessions for the local system.  Ideally, I'd like something similar to the Terminal, Machines, or Container page but focused on VNC sessions for the Host.

At one point the VNC plugin had the ability to specify a server to connect.  That seems to be gone now.

**Comment by ebdavison** [comment]
I would love to see this as well.

**Comment by jcpunk** [comment]
With the VNC POC gone, I've got a link here to when it was removed

> https://github.com/cockpit-project/cockpit/commit/c8a328072df87035080c7a468707035f40845ef6

**Comment by mareklibra** [comment]
Can be built on top of https://github.com/cockpit-project/cockpit/pull/8894

**Comment by marusak** [comment]
This issue is closed due to inactivity.

If this issue is a bug report and you are still able to reproduce it, please
comment here and provide us with an updated reproducer.

If this issue is a request for a new feature, we are sorry, but we won't be able
to address this in any time soon. If you are interested in helping us with
the implementation, please comment here.

**Comment by martinpitt** [comment]
Reopening, this feature was requested from Steve Barcomb.

**Comment by martinpitt** [comment]
Reopening, this feature was requested from Steve Barcomb.

**Comment by martinpitt** [comment]
Honestly, this proposal feels a bit besides the point -- cockpit already *is* a graphical UI to work with your servers, and a VNC server really has no place on a server machine. It might be interesting for a desktop machine of course, but then the overhead of going through a web server and browser, instead of using a VNC client directly, also seems kind of dubious. 

Also, VNC clients are super-simple to install and use, the difficulty is to set up the VNC service on it -- and I would never recommend to do that on any public internet server at least. You normally interact with a server through SSH (and Satellite/Ansible on 1 top of that) or Cockpit.

Diagnosing boot problems is certainly a common use case, but that can't happen through a software VNC service on the machine itself anyway (but usually happens through the CMC, or a similar service from the data center).

Hence, we are not planning to do that from our team, but of course I'm happy to discuss/provide guidance for someone who would want to work on this. I'd first like to hear about some credible use cases, though.

As this is not a core use case for cockpit, this would also fit very well as a stanalone project, so that people can install it if/when they need it.

**Comment by ahussey-redhat** [comment]
I can definitely see the use case for implementing this specifically for workstations.

IE;  you have a fleet of Fedora workstations and need to perform a task that requires a GUI, and you already use cockpit to manage various other components of the workstations, having the ability to use VNC via cockpit would be beneficial.

Just my 2 cents

I also agree with the fact that VNC clients are easy to install and configure. With regards to the security aspect, I agree that you shouldn't expose VNC over the public internet. I think having the VNC client behind cockpit would at least add a layer of security, assuming that the VNC server is only listening on localhost.

**Comment by hrfried** [comment]
Adding onto this—I would love to use cockpit as a backup option for rustdesk and as a general "all-in-one shop" for colleagues, and it would be running solely in our internal wireguard (netbird) network. There are plenty of scenarios where having a graphical session for the host makes sense, and it's wrong in my opinion to underestimate the utility of having this all in one place.

The lack of this feature along with the dropping of cockpit-docker support solely in favor of podman makes it hard to justify deploying and using cockpit...which sucks, because cockpit is a really nice project and I really enjoy it.

Just my 2 cents.
