### ISSUE TITLE
machines: CPU is incompatible with host CPU on some architectures

### ISSUE THREAD

**Issue by suomiy** [cockpit-project/cockpit#8385]
followup of #7820

 happens on fedora i386 when creating+starting vms:
- `CPU is incompatible with host CPU: unknown host CPU`

###### Unsuccessful try by using host CPU configuration:
`--cpu host` to virt-install

we get error:
- `warning: ERROR    unsupported configuration: CPU mode 'host-model' for i686 kvm domain on i686 host is not supported by hypervisor`

and in other images we get warnings:
- `warning: ERROR    internal error: process exited while connecting to monitor: CPU feature arat not found`
- `CPU feature tsc_adjust not found`

**Comment by suomiy** [comment]
https://github.com/suomiy/cockpit/commit/3acb9037e590490be4891e091aa274f3e64d7b7e
adds vm start to tests when this issue is fixed

**Comment by suomiy** [comment]
new error on debian stable:
-  unsupported configuration: CPU mode 'custom' for x86_64 kvm domain on x86_64 host is not supported by hypervisor

**Comment by martinpitt** [comment]
@KKoukiou , do you know if this is still an issue?

**Comment by KKoukiou** [comment]
I know that we are skipping these errors here https://github.com/cockpit-project/cockpit/blob/master/test/verify/machineslib.py#L1337

I can try to remove and try to reproduce.

**Comment by marusak** [comment]
This issue is closed due to inactivity.

If this issue is a bug report and you are still able to reproduce it, please
comment here and provide us with an updated reproducer.

If this issue is a request for a new feature, we are sorry, but we won't be able
to address this in any time soon. If you are interested in helping us with
the implementation, please comment here.
