### ISSUE TITLE
machines: VNC Vertical Sizing is Off

### ISSUE THREAD

**Issue by dcrdev** [cockpit-project/cockpit#8392]
The vnc viewer in the latest release doesn't appear to be handling vertical resizing - part of the screen gets cut off and unlike the x axis, the y axis doesn't offer scrollbars.

![screenshot_2018-01-10_17-13-04](https://user-images.githubusercontent.com/8715048/34786190-4c44924a-f62b-11e7-8c2b-2e3edea0d0a4.png)

CentOS 7.4 Host
Fedora 26 Client with Chrome 63.0.3239.132

Might I also make a suggestion at the same time... Could a button be implemented to allow full screen viewing of the running vnc session?

**Comment by mareklibra** [comment]
Real full screen can be achieved just via external viewer, like `remote-viewer`.

@andreasn , what do you think?

We might i.e. open a new tab with just the single no-vnc session. Or use just the whole plugin-space. It would be up to the browser if it can resize to full screen (like F11 key in FF).

**Comment by dcrdev** [comment]
@mareklibra true but this has value for those who do not want to open up vnc externally in the firewall. It's only a suggestion really.

My main point though is around the vertical sizing - as it makes the functionality unusable.

**Comment by dcrdev** [comment]
@mareklibra any update on the scrollbar issue?

The vnc console is still unusable for me because of this.

**Comment by mareklibra** [comment]
@dcrdev , this needs to be fixed. Unfortunately, I did not have time to get to it so far.

**Comment by mareklibra** [comment]
Related: https://github.com/cockpit-project/cockpit/pull/8894

**Comment by KKoukiou** [comment]
This issue is not present anymore. See screenshot bellow:
![installation-fedora-vnc-](https://user-images.githubusercontent.com/14921356/55225636-5d9df500-5213-11e9-804c-1a1b5a2cc36e.png)

**Comment by torpinouche** [comment]
I know this is closed but adding some information that might help someone else. Feel free to delete.

It happens sometime when resolution changes (ex.: login screen has a different resolution than the session). The workaround is to modify the size of your browser (restore down then maximize or modify manually).

I am also loosing the keyboard when navigating in other menus of Cockpit. If you experience it, you can change the console type to Desktop Viewer and back to VNC or, faster, just click in the black area of VNC (left or right side on the capture above) and then your keys will be captured again by VNC instead of the browser.

Since we are in the workarounds, in the Terminal you can Copy and Paste if you do CTRL-A before CTRL-C and CTRL-V.

My vote for full screen or a way to hide the left menu to have more space. Having 2FA authentication with Cockpit is great and this is on the the reasons why I do not access VNC directly by opening another port in the FW.

**Comment by mzamot** [comment]
Having a full screen button or the option of opening the VNC in a different tab would be really nice

**Comment by KKoukiou** [comment]
> Having a full screen button or the option of opening the VNC in a different tab would be really nice

Please create a new issue for that - it makes sense but noone will keep track of it in a closed issue.

**Comment by brekke-roq** [comment]
I have the same issue on ubuntu 22 host while installing ubuntu 20 guest. It seem that it has something to do with Virtio video driver as switching to QXL fixed the issue.

**Comment by syncmasterN** [comment]
> I have the same issue on ubuntu 22 host while installing ubuntu 20 guest. It seem that it has something to do with Virtio video driver as switching to QXL fixed the issue.

Please provide more details on what exactly you have changed, I am having the same problems on some versions of Centos7, ubuntu and rhel8 & 9.

**Comment by souhaiebtar** [comment]
> The vnc viewer in the latest release doesn't appear to be handling vertical resizing - part of the screen gets cut off and unlike the x axis, the y axis doesn't offer scrollbars.
> 
> ![screenshot_2018-01-10_17-13-04](https://user-images.githubusercontent.com/8715048/34786190-4c44924a-f62b-11e7-8c2b-2e3edea0d0a4.png)
> 
> CentOS 7.4 Host Fedora 26 Client with Chrome 63.0.3239.132
> 
> Might I also make a suggestion at the same time... Could a button be implemented to allow full screen viewing of the running vnc session?

i had to install using text mode by adding `inst.text` (because i can't see the buttons that i have to click on),

![](https://linuxconfig.org/wp-content/uploads/2018/11/02-force-text-mode-installation-rhel-8.png)

, at the end thanks goes to `linuxconfig.org` site

**Comment by garrett** [comment]
We have a PR @ https://github.com/cockpit-project/cockpit-machines/pull/900 that should further improve the situation. Hopefully it'll land ASAP, so it should ideally be in the next release of Cockpit. 

Meanwhile, I'd suggest clicking on "Expand" to make the VM take up more of the browser view, which should help mitigate the issue. It's at the top-right of the "Console" card on the VM's overview:

![image](https://user-images.githubusercontent.com/10246/221828437-b2b2dc27-3eac-4bb9-8adf-e5d51900b59a.png)

**Comment by souhaiebtar** [comment]
even with the "expand" button, it didn't work, i had to install using cli

**Comment by garrett** [comment]
@souhaiebtar: Could you provide details?

1. Which version of Cockpit?
2. Which distribution and version was Cockpit running on?
3. What browser are you using?
4. What were you installing as a VM?

We could then try to recreate that and hopefully make sure it's fixed in https://github.com/cockpit-project/cockpit-machines/pull/900 (if it isn't already).

Thanks!

**Comment by souhaiebtar** [comment]
@garrett 
1. Cockpit Version: cockpit 286 ( and cockpit-machine 283)
2. Host Os: fedora server 37
3. Browser: Chromium ( and i also tested on firefox)
4. VM: Rocky linux 9

**Comment by garrett** [comment]
I've tried Rocky 9 on what's in main and with that PR, to see what would happen. This is also Fedora 37 (but Silverblue instead of Server, but it should be similar enough). This is on Firefox, but as you note, it should be similar in Chrome too.

It looks like it's a lot better with the change. But it's not perfect; there are still some issues. But we're aware of that and plan on merging in the fixes as-is and doing a follow-up to try to get it behaving better in different situations too.

So, hopefully, the next version of Cockpit will help fix the problem for you. (And then we'll have to try to figure out how to improve it in the corner case scenarios and for mobile too. Although it's probably a little weird to manipulate a VM via VNC from a phone, even if it worked fully correct, however.)

## Testing the pending branch with Rocky 9 VM

Here's Rocky 9 in the VM page:

![image](https://user-images.githubusercontent.com/10246/221883551-4fb0562c-1a6c-4552-b7bc-dee458966ab5.png)

Here it is after I click expand and move the mouse over it (it had a momentary glitch, but I think that's due to the resize request):

![image](https://user-images.githubusercontent.com/10246/221883739-5c2953a5-5838-4919-8579-e92a5c0b953b.png)

## Still some issues

Some smaller sizes still have issues (these are all resizing the browser, where responsive mode starts kicking in):

![image](https://user-images.githubusercontent.com/10246/221884674-2d9089d1-ff31-463e-992d-25c7b0bc966b.png)

![image](https://user-images.githubusercontent.com/10246/221884768-bfa82ffe-0ad6-4cfe-af90-dbd89053971f.png)

![image](https://user-images.githubusercontent.com/10246/221884825-512fd56a-9de0-4c76-a771-5c641f3f8624.png)

![image](https://user-images.githubusercontent.com/10246/221885683-388c8ed3-5fd9-42c4-a9c7-5becdfc07f17.png)

(This last one is an iPhone size, after the page was reloaded.)

## But it's better, especially expanded

Even when it's narrow, the expand works:

![image](https://user-images.githubusercontent.com/10246/221886079-c18cee1b-ec43-47fe-9f0f-f4c8624bfee5.png)

![image](https://user-images.githubusercontent.com/10246/221886378-dd493f26-3a3c-4983-befc-b00c1b946619.png)

**Comment by souhaiebtar** [comment]
i have a gtx 1060, do you think  it can be the problem ?

**Comment by souhaiebtar** [comment]
@garrett  is nested vm enabled by default or not in cockpit, sorry for not being related to the problem above ?

**Comment by garrett** [comment]
@souhaiebtar: I'm pretty sure this isn't Cockpit-related. Nested VMs are a system-level thing. I think you should be able to use nested VMs with Cockpit-Machines. File a bug at https://github.com/cockpit-project/cockpit-machines/issues/new if there's some problem specifically with nested machines and Cockpit-Machines.

(I think we're even using nested VMs for testing Cockpit-Machines... we have test VMs that test running a VM.)

**Comment by jelly** [comment]
Nested VMs are something the OS has to enable and not really something cockpit-machines controls over. For more information see https://www.linux-kvm.org/page/Nested_Guests

But note that nested VMs won't be the most fast thing to use.

**Comment by thiagolinhares** [comment]
I'm having same issue, but on Rocky Linux 9.1

> [root@localhost ~]# rpm -qa | grep cockpit
> cockpit-bridge-276.1-1.el9.x86_64
> cockpit-ws-276.1-1.el9.x86_64
> cockpit-packagekit-276.1-1.el9.noarch
> cockpit-system-276.1-1.el9.noarch
> cockpit-storaged-276.1-1.el9.noarch
> cockpit-276.1-1.el9.x86_64
> cockpit-navigator-0.5.9-2.el9.noarch
> cockpit-machines-274-1.el9.noarch

> [root@localhost  ~]# cat /etc/os-release
> NAME="Rocky Linux"
> VERSION="9.1 (Blue Onyx)"
> ID="rocky"
> ID_LIKE="rhel centos fedora"
> VERSION_ID="9.1"
> PLATFORM_ID="platform:el9"
> PRETTY_NAME="Rocky Linux 9.1 (Blue Onyx)"
> ANSI_COLOR="0;32"
> LOGO="fedora-logo-icon"
> CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
> HOME_URL="https://rockylinux.org/"
> BUG_REPORT_URL="https://bugs.rockylinux.org/"
> ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
> ROCKY_SUPPORT_PRODUCT_VERSION="9.1"
> REDHAT_SUPPORT_PRODUCT="Rocky Linux"
> REDHAT_SUPPORT_PRODUCT_VERSION="9.1"

**Comment by deajan** [comment]
Same issues here, trying to install Almalinux 9.1 on a Almaliinux 9.1 host

**Comment by garrett** [comment]
@thiagolinhares @deajan: VNC sizing was fixed in this PR: https://github.com/cockpit-project/cockpit-machines/pull/900, which landed in Cockpit-Machines 286 on March 22.

**Comment by deajan** [comment]
@garrett Thanks for the follow up. Hopefully Redhat will backport this at some time.

**Comment by deajan** [comment]
Just for the notes, Redhat did backport Cockpit Machines 284 to RHEL 9.2, but didn't include the necessary fix yet.
Guess we'll have to wait until RHEL 9.3, since they usually only backport security fixes.
