### ISSUE TITLE
network bonds: Network jargony names in mode

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#842]
The current dropdown requires you to be a bit of a domain expert in networking, since it uses very non-descriptive names for the modes. XOR, Round Robin and 802.3ad sticks out here.
Both RR and XOR provice load balancing and fault tolerance. This needs to be indicated.
http://en.wikipedia.org/wiki/Link_aggregation#Driver_modes

**Comment by andreasn** [comment]
Screenshot of the current UI:
![screenshot from 2016-10-07 18-49-41](https://cloud.githubusercontent.com/assets/209895/19198337/e70221a8-8cbe-11e6-9c56-c5ad8b206b83.png)
![screenshot from 2016-10-07 18-46-47](https://cloud.githubusercontent.com/assets/209895/19198341/eca761f4-8cbe-11e6-9804-5e09b4eb1b60.png)

**Comment by bhaktibhikne** [comment]
@andreasn Hi! This is Bhakti from the IRC.  As we discussed,I drew up two suggestions for the inclusion of a small description of the modes. 

In Figure 1,the mode descriptions can be displayed right below the modes and as the description changes along with the mode. So,for a newbie,it will provide an idea of how the mode works. Since the user is not given the option to choose via the mode description,the seasoned sysadmins will not have to worry about the extra information provided. 

In the second figure,the mode description can be provided when the user is choosing a mode. The description can be visible in a hover text box. 

As you suggested,the popup will be irritating for the sysadmin who knows the mode. Same for an inline warning that will be displayed before confirming the modes.

![network-bond-settings](https://cloud.githubusercontent.com/assets/18215820/19221763/1297e34e-8e67-11e6-9b31-f816b637ff3e.jpeg)

![network-bond-settings1](https://cloud.githubusercontent.com/assets/18215820/19221766/1d724700-8e67-11e6-9a88-753ca13f56a3.jpeg)

**Comment by andreasn** [comment]
Thanks for the mockups!
Figure 2 looks very close to the Patternfly pattern for Field Level Help. What do you think about that pattern? (Cockpit uses Patternfly as a UI toolkit and design guidelines, see http://www.patternfly.org)

How long would these description sentences be? Could you write some of them out, so we can get a feel for how much space they need, and how they would be worded?

**Comment by bhaktibhikne** [comment]
The pattern for the Field Level Help can work. But,if we use this,the popover will contain information about all the modes at all times. The popover will then occupy more space even if we limit ourselves to maximum of two sentences per mode. 

We can limit the description to two sentences per mode.  I will write a few of them and post them here.

**Comment by bhaktibhikne** [comment]
I referred to [bonding documentation ](https://www.kernel.org/doc/Documentation/networking/bonding.txt)on kernel.org for the description of the modes. Since the documentation explains the working in a short way,it seems a good idea to use them for the description:

**Round robin:**
Transmit packets in sequential order from the first available slave through the last.  This mode provides load balancing and fault tolerance.

 **Active-backup ** 
 Only one slave in the bond is active  This mode provides fault tolerance. 

**XOR**
Transmit based on the selected transmit  hash policy. This mode provides load balancing and fault tolerance.

 **Broadcast** 
Transmits everything on all slave interfaces.  This mode provides fault tolerance.

**802.3ad** 
 Creates aggregation groups that share the same speed and duplex settings. 

 **Adaptive transmit load balancing**
Channel bonding that does not require any special switch support.
  
**Adaptive load balancing**
 Includes balance-tlb plus receive load balancing (rlb) for IPV4 traffic, and does not require any special switch support. 

Using Field Level Help for the description will occupy a lot of space,especially since our column width will have to be taken into consideration too.

**Comment by dperpeet** [comment]
> I referred to bonding documentation on kernel.org for the description of the modes. Since the documentation explains the working in a short way,it seems a good idea to use them for the description:

Looks good. Do you have a mockup of how this could look in the current ui? It doesn't have to be as high-fidelity as https://trello-attachments.s3.amazonaws.com/57062c8306d061518bf282ff/2069x4864/31b2cd9788d9b6a261f92ebb674d6739/navigation.png, but maybe something to show how the ui would look if we added the text?

**Comment by bhaktibhikne** [comment]
Not yet. But I will create the mockup for the ui and add it here.

**Comment by bhaktibhikne** [comment]
@andreasn @dperpeet I am adding the mockups for the UI. It is not completely perfect. I wasn't sure of the exact font and font size used but this is a probable UI if we have the particular Font,Font size and spacing. What are do you think?

![bond-mockup1](https://cloud.githubusercontent.com/assets/18215820/19449449/4779bf94-94c3-11e6-82a1-69c7e5f45b74.png)
![bond-mockup2](https://cloud.githubusercontent.com/assets/18215820/19449450/47827422-94c3-11e6-973e-a31544bb2e35.png)

**Comment by andreasn** [comment]
What do you feel are the advantages and disadvantages of each of the two versions?

**Comment by bhaktibhikne** [comment]
In the first version,the description will be available only as long as the user is hovering over the modes. As soon as he moves towards the other details,the description won't be visible. On the positive side,the window looks cleaner because of the absence of the description. In some cases,the description of the modes can cover the "modes" option itself because of lack of space. 

For the second version,the description of the modes will be present even after the user moves on to other details.This can look cluttered to the seasoned users. But,this will provide more space for complete description of the modes. 

A third version could  include the description in the same line as that of the modes.
For example:
Active Backup(Only one slave in the bond is active This mode provides fault tolerance) 

But this will force the users to read what is in the brackets even if they already know what the mode does and also will look extremely cluttered with so much of text in a small area.

**Comment by dperpeet** [comment]
I think the information shouldn't clutter the UI, if possible. @bhaktibhikne: Which option do you think is best? And what about using [field level help](https://www.patternfly.org/pattern-library/forms-and-controls/field-level-help/#_) like we do on the system information page?

**Comment by bhaktibhikne** [comment]
@dperpeet I have installed Cockpit on my local machine following instructions from [here.](https://github.com/cockpit-project/cockpit/blob/master/HACKING.md)

I read the code of Performance Profiles in System. I just wanted to confirm if this is the correct link : https://github.com/cockpit-project/cockpit/blob/master/pkg/tuned/dialog.js 
In this code,we can change the functions according to our modes and add the information respectively for the modes.

**Comment by dperpeet** [comment]
> I read the code of Performance Profiles in System. I just wanted to confirm if this is the correct link : https://github.com/cockpit-project/cockpit/blob/master/pkg/tuned/dialog.js
> In this code,we can change the functions according to our modes and add the information respectively for the modes.

Right, the info gets changed in the [`update_button` function](https://github.com/cockpit-project/cockpit/blob/master/pkg/tuned/dialog.js#L77)

**Comment by bhaktibhikne** [comment]
Correct. I can start by adding the Field Level Help to the existing UI and displaying a sample information text. Once that works properly,I will work on the code and paste it here.

**Comment by andreasn** [comment]
Would you be able to post a mockup of how it would look and function with the field level help?

**Comment by bhaktibhikne** [comment]
@andreasn yep.  
For the Field level help we can have two versions. One having the "i" on the left next to "Mode" and one on the extreme right next to dropdown for mode selection. 
If we go for the first one,although the popover will be within the frame,the user might be confused if the informations is regarding the modes or for each mode. 
For the second one,the popover will go outside the "Bond Settings" frame. If the size of the popover is decided,then this option will be more favourable as compared to the first one.
I couldn't get the correct font and font size for the popover so that is an issue. 

![bond-mockup3](https://cloud.githubusercontent.com/assets/18215820/19814839/a1daafaa-9d5d-11e6-9f41-1921d8beb1dd.jpg)

![bm3](https://cloud.githubusercontent.com/assets/18215820/19814717/1e77e9de-9d5d-11e6-9bdf-1e60204cd877.png)

![bond-mockup4](https://cloud.githubusercontent.com/assets/18215820/19814844/a814fd26-9d5d-11e6-97b8-7b9f6885cfee.jpg)

![bm4](https://cloud.githubusercontent.com/assets/18215820/19814725/276f53ba-9d5d-11e6-8c77-009d7520ede9.png)

**Comment by andreasn** [comment]
I like the latest variant, with the info popup on the right.
Lets go for that!

**Comment by bhaktibhikne** [comment]
Awesome!! 
I will start working on the code and create a pull request soon.

**Comment by andreasn** [comment]
New design:
![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/27f1161aa57545a38da9ca8ff0f05e619d47b78f/network/network-bond.png)

**Comment by andreasn** [comment]
I did a design review with some UX people from other teams and we figured this solution had some drawbacks in the sense that it's not very accessible and it's a little bit flimsy with popups inside of dropdowns, so I revisited the design.

![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/0744a62b37b46b8f3474ad835770dabc1a9eafd9/network/network-bond.png)

This would have the type as a group in the dropdown and the explanation text below the dropdown. Will talk to Vendula from docs and see if she can help me with good help text snippets.

**Comment by andreasn** [comment]
Put 802.3ad in the Load balancing & Fault tolerance group, since at least the documentation on the Linux foundation wikisays it works similar to XOR (so I think that means it does both?)
https://wiki.linuxfoundation.org/networking/bonding

Also moved the info about certain external requirements for the mode into a warning popup.
![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/d0b2118ef6de66f6fc5a42a9a1dc92980aa8739c/network/network-bond.png)

**Comment by marusak** [comment]
@andreasn there is [this](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_systems_using_the_rhel_8_web_console/managing-networking-in-the-web-console_system-management-using-the-rhel-8-web-console#bond-modes_configuring-network-bonds-using-the-web-console) documentation, which explains every type nicely. Wouldn't it be better to just point to this documentation?
If not, there has been a few designs, which is the current one?

**Comment by marusak** [comment]
I talked with @andreasn that inline doc would be enough. But we need to figure out how we should show this remote URL.

**Comment by andreasn** [comment]
So let's solve this with a docs pointer!
Will make a design for this.

**Comment by andreasn** [comment]
![mockup](https://raw.githubusercontent.com/cockpit-project/cockpit-design/b5bf4809f74eb58613cf8dcd54e43bd75ec5ad03/network/network-bond-inlinehelp.png)

**Comment by andreasn** [comment]
https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/embedded-assistance
