### ISSUE TITLE
machines: VM START action failed message still exists after VM runnning successfully

### ISSUE THREAD

**Issue by AlertBear** [cockpit-project/cockpit#8448]
The VM failed to start since error in the defined xml file, I got the warnining message under overview.
But after fixing the error in xml, I start the vm successfully. But the warning still exists.

![virtual machines - localhost localdomain - mozilla firefox_001](https://user-images.githubusercontent.com/9636916/35087289-58d7843e-fbf5-11e7-9dfd-79963f625c5c.png)

**Comment by mareklibra** [comment]
It shows last error message related to the particular VM.

To avoid unwilling lost of information, the error message is not removed automatically but the user has the `close` button available (the cross on the right side).

Behavior might be improved by rendering timestamp.
@andreasn , what do you think?

**Comment by andreasn** [comment]
Will the error still show up in the Logs?
If so, I think it would make sense to remove the error, since it no longer applies, and misinforms you about the state.

**Comment by mareklibra** [comment]
@andreasn , it will be in browser's console log, so nothing where users usually look into.
The error will appear in server log, but it's a remote system.
So there is no reliable component listing such issues.

**Comment by mareklibra** [comment]
What is probably no big harm:
- include timestamp in the message
- remove the message of same kind - means if the user hits `Run` then corresponding `VM_START` error message is removed, if present. Any other type of an message would remain.

Or we can rely on the libvirt log.

**Comment by andreasn** [comment]
Makes sense to me!

**Comment by martinpitt** [comment]
I discussed this the other day with @KKoukiou : My initial idea would be to add the related action to every message (e. g. `VM_START`), and whenever that action gets run again, clear all existing notifications of the same type.

**Comment by KKoukiou** [comment]
I gave it some extra though (and discussed it with @marusak) and the decision is that this should not be implemented.
When a VM fails on an action and then it fails again on the same action there is not any guarantee that the failure is the same. So I think keeping both notifications alive still make sense.

In addition, since this issue was reported, we use different component for the notifications in machines page. The toast notification list that we currently are using allows us to stack multiple notifications thus keeping a history of the failures.
