### ISSUE TITLE
Kubernetes container is "throbbing" on topology view

### ISSUE THREAD

**Issue by huang-jy** [cockpit-project/cockpit#8471]
After deploying the kubernetes yaml, everything works as expected; but when viewing the topology screen, the diagram "throbs" like a heart beat, which is quite annoying. Can this be disabled or turned off?

**Comment by martinpitt** [comment]
I agree that the [d3](https://d3js.org/) charts are a bit toy-ish. The slight wobbling might still have some utility (although making that slower would be appreciated, too), but the throbbing is outright annoying. I'll look whether it has some options to disable these.

@andreasn, @garrett, do you know whether that throbbing is useful for anything?

**Comment by martinpitt** [comment]
Sorry, it's not d3 directly, it's [kubernetes-topology-graph](https://www.npmjs.com/package/kubernetes-topology-graph). That uses d3, but I think the animation comes from kubernetes-topology-graph itself. @stefwalter, I think you wrote most of it, do you have an opinion here?

**Comment by mvollmer** [comment]
FWIW, I have always assumed that the throbbing is an undesired side effect of some polling activity.

**Comment by huang-jy** [comment]
I thought it was too, hence my "heartbeat" analogy.

**Comment by garrett** [comment]
## Style changes

I've edited the style a little and tried to squash most of the bouncy animation (which is _not_ straightforward with d3 < 4.x):

http://garrettlesage.com/cockpit-mockweb/topology/

I don't have a way to test this properly, however.

Style changes:
- Removed circles by default (they're noisy and get in the way of shape recognition)
- Pinned icons now have a dotted circle
- Dashed lines are now more dashed
- Thickened lines to be 1.5 pixels instead of just 1 pixel wide
  - 1.5 to make them a little thicker, but not twice as thick
  - Using fractional pixels for lines in this context is fine as they're always on diagonals.
- Added a hover state to icons (thin & solid outline)

Ideally, I'd like the icon size to be bumped up a little bit more too, but I couldn't figure that out.

Changes are available @ https://github.com/garrett/cockpit-mockweb/commit/cff9ee88847ff0189577652509b24efca3495332 (I also have a local branch of kubernetes-topology-graph ­— I'm happy to send a PR once it's confirmed that the changes are decent enough).

## Back to the "throbbing"

None of this is necessarily fixing the "throbbing". My guess is that the "throbs" are related to the servers data changing. In d3, when you make & refresh a force-directed graph and don't assign locations for all the items, they start from random locations. 

We should try to _not_ update the view unless necessary — and might want to fix locations to where they currently are when new information arrives (although this might have issues too, if).

The JS changes above should help reduce the gratuitous animations a little, but they're still there. It would probably take a bit more effort to fix it properly.

**Comment by martinpitt** [comment]
Our kubernetes UI is on maintenance mode, so this most likely won't be fixed any more. See https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/message/SBDE64DAIVTLIYRGVMESUPR5STRRFCGW/

**Comment by martinpitt** [comment]
cockpit-kubernetes got removed from Fedora ≥ 30 and master a while ago.
