### ISSUE TITLE
Provide Ansible Playbooks examples on feature pages

### ISSUE THREAD

**Issue by myllynen** [cockpit-project/cockpit#8480]
It would be nice if Cockpit could provide standalone Ansible playbooks for the tasks a user completes with Cockpit UI. This would allow, for example, configuring and tuning one system with Cockpit and then replicating the setup automatically to any number of other systems.

This would probably require Cockpit components to use Ansible internally to make sure the playbooks provided matches the operations completed, so perhaps this would not be feasible with such components which do not use (now nor in the future) Ansible.

**Comment by martinpitt** [comment]
While I sympathize with the broad idea, I see way too many problems with that to be realistic, to be honest. Some examples:

 * Cockpit talks to a lot of APIs like D-Bus, REST, Unix sockets, etc. Ansible doesn't have a provision to talk to a e. g. D-Bus API or even a concept like "listen to a D-Bus signal" or "`select()` on an Unix socket". These would need to be replaced with calling command line utiltities instead (which is their purpose). Thus Ansible is not an universal backend which Cockpit could be based on.

* If you want to record what the user did and transcribe that into an Ansible playbook, how would the machine know which operations are taken in reaction to which information that the user saw? In some cases the user herself might not even truly know and make "gut feeling" decisions. Likewise, some actions might be experimental or unnecessary.

Ansible and Cockpit fulfill two fundamentally different and mostly opposite use cases: The former *puts* a system into a previously defined state, while Cockpit *shows* and *reacts* to the current system state, and allows you to interactively change it. You can kind of do the latter with `ansible run`, but first this is not really Ansible's main use case, and second it would be way too slow to do everything through an interface like this.

So what you ask for would go against Cockpit's design principles, make everything way too slow, limit what Cockpit could do, be a multi-man-year effort, and in the end not make  anyone happy. 

I think the best way to approach this problem ("I did something interactively and now want to provide a playbook for it") are the [feature documentation pages](http://cockpit-project.org/guide/latest/features.html), which show what's going on under the hood, and what the CLI/config file equivalents are for what Cockpit does. Of course these don't always translate 1:1, but that's due to the fundamental difference pointed above. E. g. there would be nothing wrong with showing some example Ansible scripts on these feature pages. If you have suggestions how to improve the feature pages, or file reports about what are you missing from them for being able to write Ansible scripts, please let us know - concrete improvements are always much more actionable than such generic requests. Thanks!

**Comment by myllynen** [comment]
Thanks for sharing your insights. I admit that before filing this RFE I was merely thinking about some basic use cases (like adjusting partition size, creating a file system, creating a user, etc) but not about Cockpit internals. It sounds like that implementing this would be so infeasible that perhaps it's best to close this ticket, at least now we have archived the reasoning why this seems to be out of scope for Cockpit. Thanks.

**Comment by martinpitt** [comment]
Agreed.
