### ISSUE TITLE
time & date formats are different across Cockpit

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#8583]
This will potentially open a can of worms, since we're a bit inconsistent in general with regards to time formats in Cockpit. It would be good to harmonize those.

My system time on the Server page is displayed like this:
`2018-02-08 12:56`

But on the services page it's displayed like this:
`1/19/2018, 1:57:36 PM`

The first feels more normal to me, since I'm used to the Swedish system, while the second seems to be the US format.

**Comment by andreasn** [comment]
To throw more things into the mix, this is how SELinux displays it:
`Occurred between 11/23/2017 and 11/23/2017`

And this is how it's on the Account page:
`11/2/2017, 12:56:43 PM`

**Comment by andreasn** [comment]
Note that if I run "systemctl status cockpit", I will get the timestamp in this format:
`Active: active (running) since Thu 2018-02-08 12:16:49 CET; 45min ago`

**Comment by garrett** [comment]
We have a switcher for language, but not locale.

Americans expect MM/DD/YYYY and 12-hour with AM/PM, while most of the rest of the world expects DD/MM/YYYY and 24-hour time. 

- https://en.wikipedia.org/wiki/Date_and_time_representation_by_country#Local_conventions
- https://en.wikipedia.org/wiki/Date_format_by_country

Cockpit would probably either need to switch locale (probably similar to how it can switch language) and/or detect the browser's reported locale. For the sake of minimizing confusion, I would suggest standardizing on the unambiguous YYYY-MM-DD 24-hour time for now (and possibly as a fallback for later too), as displayed in the previous comment until Cockpit is aware of locale (one way or another).

Perhaps we can expose the HTTP "Accept-Language" header to the JavaScript somewhere (as JS doesn't actually have this value, apparently):
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language

Then could see about relying on browser-based localization of DateTime:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat

…But that wouldn't handle the case where the browser locale is not set to the preferred locale. This is similar to language settings for the browser and within Cockpit.

**Comment by andreasn** [comment]
Went over all the pages, and this is what I have so far:


String | URL | Format
-- | -- | --
System time | /system | 2018-04-05 12:53
BIOS date | /system/hwinfo | 04/01/2014
(log header) | /system/logs | April 5, 2018 (12:51)
Created | /docker#/image/sha256% | 5 months ago
Last Login | /users#/ACCOUNT | 3/22/2018, 6:12:12 PM
Lock account on | /users#/ACCOUNT | 2018-04-03
Since | system/services#/SERVICE | 4/3/2018, 1:57:20 PM
Occured between | /selinux/setroubleshoot | 11/23/2017 and 11/23/2017

**Comment by andreasn** [comment]
> …But that wouldn't handle the case where the browser locale is not set to the preferred locale. This is similar to language settings for the browser and within Cockpit.

Is this in the case where my browser UI is in English, but I prefer the European time setting? Or something else? Just want to make sure it's not a super-edge-case.

**Comment by garrett** [comment]
### Summary

Locale support in browsers is a mess.

While it often works, it doesn't always, either due to OS and/or browser issues. Therefore, we need to handle it something like the following:

1. Sniff for locale & try to use what's reported
2. If locale cannot be determined, default to [insert choice here — en_US? en_US international? other?] 
3. Provide a means of switching locale if sniff or fallback is not appropriate. This would probably live in the same dialog as the language selector.

---

### Example issues

Feel free to skip the rest of this comment; the above is probably enough. :wink:

Various scenarios where locale is incorrect:
1. Company-provided builds of desktop installations may differ from a user's preferred language & locale
5. Windows has locale add-on support, but it doesn't really work right
   - Personal experience: Windows 10 German edition may have English installed as an add-on pack, but then there's a random mix of German and English; this results in one locale getting reported in some places but the other with other APIs, and affects browsers differently
2. Firefox has issues with locale in some cases
   - [downloaded build is stuck on locale](https://stackoverflow.com/questions/1206042/how-to-get-firefox-language-setting-really)
     - > Both navigator.language and the HTTP User-Agent header use the value of the preference "general.useragent.locale", which is hard-coded in intl.properties to the locale of the Firefox build you downloaded
     - If browser request sniffing is wrong on Firefox's website's side (for any of the reasons on this list or other), the wrong build may be downloaded
   - [Firefox flatpak doesn't have proper locale support](https://github.com/xhorak/firefox-devedition-flatpak/issues/65)
3. Chrome has similar issues with locale https://stackoverflow.com/questions/37221494/how-to-change-the-locale-in-chrome-browser
4. Variances in (usually imperial) systems: **en_US** (US spelling, US datetime & imperial measurements) vs **en_US international** (US spelling, international datetime & metric system) vs **en_UK** (UK spelling, international datetime & metric/imperial mixed system) vs **en_IN** (similar to en_US international, but with Indian rupees)
   - there are other language locale differences, but the US is usually the odd one out in every way (with the exception of decimal place marker and currency)
5. Safari doesn't have locale support; it uses the OS setting
6. Many bilingual people prefer using English as their computing UI, as translations are often poor, lacking, or simplay do not exist in a native language

Items # 1 (company build) & 2 (flaky OS support) are probably the ones people would hit the most in Cockpit.

**Comment by garrett** [comment]
A very good first step is to sync up the datetime values where we can and provide a decent default. Then we can proceed on implementing the sniffing and switching afterward.

**Comment by garrett** [comment]
I'd propose these international-friendly defaults:

- Unambiguous datetime: `YYYY-MM-DD HH:MM`
  - Drop seconds in most cases, except in logs
  - 24-hour time
  - mm/dd vs dd/mm isn't an issue in this date format
  - fragmentable: date, time, or datetime can be used, depending on context
- Relative "ago" in some cases (which cases?)
  - should have absolute time in HTML attribute (which should also show in tooltip)
  - used when time isn't critical, but a general sense of when something happened is still valuable
- Celsius for temperatures (CPU temp, disk temp, etc.)
- Period for fractional numbers
- No separator for thousands

This doesn't cover:
- currency (probably outside the scope of Cockpit anyway)

If we implement the above, it would be least-confusing to most people, and we can be consistent. Once locale sniffing & switching is in place, people can have more comfortable regional variants.

**Comment by andreasn** [comment]
Last checked on the Software Updates page might be another place, but I'm not 100% sure that the situation can happen that the last check was done say, 3 days ago, or if it's always a couple of minutes ago.

**Comment by andigi89** [comment]
Hi everybody, 
I'm Andi and I am a "newbie" in contributing for Fedora, Does anybody work on it to solve this problem?

Regards
Andi

**Comment by martinpitt** [comment]
Hey @andigi89 . Not right now, do you want to give it a shot? @Gundersanne did some work on it some months ago, but I think there are some remaining places.

**Comment by andigi89** [comment]
Hey@martinpitt - I would like to give it a shot ;) 

@Gundersanne should I consider #9459 and #9417? So, I can go forward on finding places in cockpit which are not switched yet?
