### ISSUE TITLE
Option to skip tests that need additional images

### ISSUE THREAD

**Issue by jscotka** [cockpit-project/cockpit#8669]
connected with
 https://github.com/cockpit-project/cockpit/issues/8668

It reminds me some older discussion. would be nice to have some tags in tests, to be able to filter them dynamically, instead of some black/white-listing of files
like I can imagine something like:
 * check-session: cockpit-bridge, nonetwork, basic, sanity, fedora, ubuntu, rhel, atomic
 * check-apps : cockit-app, nonetwork, optional, fedora, ubuntu, atomic
 * check-kubernettes: cockpit-kubernettes, network, sanity, fedora, rhel

and then filter these tests for each system based on tags, instead of pass tests in case not suitable for this env.
There can be used some generic solution like metadata format 
   https://github.com/psss/fmf
Or in case avocado scheduler they have possible to write tags to each class, test method 
   http://avocado-framework.readthedocs.io/en/52.0/WritingTests.html#categorizing-tests

User stories: 
 * run fast sanity tests first to check package sanity, quick qualification
 * divide testst to more levels depends on priority
 * avoid tests what needs additional images
 * avoid tests what needs network access (eg. download extra images)
 * run tests suitable for system (ubuntu)
 * filter test with not fulfilled requirements

**Comment by martinpitt** [comment]
To be honest, adding such a general and involved tagging system is too hard to maintain for us: we wouldn't use it in the cockpit team itself, as in CI we always want to run all tests anyway.  So if you set it up once, it would constantly break over time when developers mis-tag their tests. The tests are already split up by component, so it's much easier to just actually run  the test(s) you want than adding an indirection on top of that.

However, let's go through your user stories:

>  run fast sanity tests first to check package sanity, quick qualification

This can already be achieved with the test/avocado check, even with checklogin-raw.py (which doesn't need a webbrowser, or any other heavy requirements). It runs on the actual target machine and thus also doesn't requrire cockpit's docker/test VM infrastructure.

>  divide testst to more levels depends on priority

Tests and components don't really have an absolute/objective priority IMHO, so adding this to the tests would be quite arbitrary. For validating a package update, all tests need to pass, it would seem a bit weird to e. g. say that the network page is less important than the container one. We don't want either of them to break :-)

>  avoid tests what needs additional images

This is a really good use case, and I think we can accomodate this relatively easily. test/common/testlib.py `MachineCase.setup()` can check a flag and check if  `provision`  contains any `image` values (see `git grep -A3 -w provision test/verify/` for which tests would be affected).

We even already have such a flag: `--nonet` (works both on test/verify/run-tests and on the individual tests like test/verify/check-multi-os). However, it currently just skips the  download and then lets the test fail on machine provisioning due to the missing image. I think it would make sense to fix this to just skip the test instead. This would give you the behaviour you need?

>  avoid tests what needs network access (eg. download extra images)

Our tests themselves don't require network access -- the VMs even have outside network access disabled. The only thing is the image download, which is covered in the previous point.

>  run tests suitable for system (ubuntu)

I don't understand this, can you please expand on this? We already have test images for lots of OSes, including Ubuntu. Not every functionality is available everywhere, this is where the `@skipImage` annotations come into play.

>  filter test with not fulfilled requirements

They should already skip themselves automatically and not fail. What do you mean by this?

**Comment by jscotka** [comment]
I understand that you want to run all tests. These filtering and running just smaller part is possible via these tests/avocado, but this is more less generic, not connected with any specific testsuite. each of them can have marked some subset as sanity tests for components. 

it is question if skip these tests with --nonet option is better, for me bigger sense makes filter these cases on higher level, for example via this decorarot like ``@skipGeneric``, and add to these cases some tag like: ``additionalImages``, then I will be able to skip them, and use --nonet to avoid dowloading images and let test fail, because it make sense too.

last issue with skipping tests not suited for some system, as you suggested it is possible  to use this ``skipImage``, yes, this feature implements it. Maybe this is more less about my feeling, thata you use ``names`` of images for filter systems, means that image is called for example rhel-7.5-atomic what means system filter like: 
* system: Redhat enterprise linux 
* is it atomic: yes
* version: 7.5
so image names contains these filters, and could be used. but it is more less about metadata (test tagging) and filtering and similar tags assigned to images, each image contains data what this image fulfill. 
But I understand that this  more generic way may lead to complexity od test&image description, so I understand that there is no reason to add this.

**Comment by martinpitt** [comment]
> add to these cases some tag like: additionalImages, then I will be able to skip them

I don't like this part because it means to manually add tags for something which the testsuite already knows (via the `provision` variable). This really should just use that information via an environment variable, a new CLI option, or `--nonet`.

For other cases, such as skipping tests for packages that you don't install, the tagging system makes sense IMHO. This is handled in PR #8680.

So I would re-devote this issue to figuring out how to skip tests that need additional images.

**Comment by KKoukiou** [comment]
This issue is quite old - obsolete this closing.

In general I think we should avoid opening issue for code refactoring - we can discuss these things over IRC/emails since it only interests the developers of cockpit and not the users.

If you want to discuss this issue let's keep in on #cockpit channel on freenode IRC server.
