### ISSUE TITLE
machines: User has to click 'Run' to start VM when checked "Immediately Start VM" checkbox

### ISSUE THREAD

**Issue by qiyuann** [cockpit-project/cockpit#8677]
**Description of problem:**
With checking the "Immediately Start VM" checkbox when creating VM, the VM cannot start automatically after the guest OS is installed, user has to click the 'Run' button to bring it up.

**Version-Release number of selected component (if applicable):**
cockpit-machines-162-1.fc26.noarch
cockpit-bridge-151-2.fc26.x86_64
cockpit-system-151-2.fc26.noarch
libvirt-3.2.1-7.fc26.x86_64
Firefox 57.0.1

**How reproducible:**
100%

**Steps to Reproduce:**
1. Click "Create New Virtual Machine" button, and enter/select each field in the popped up window as:
![screenshot from 2018-02-22 15-36-04](https://user-images.githubusercontent.com/23047456/36525871-cf535b94-17e6-11e8-8e65-9756aae4968a.png)

2. Install guest OS via vnc console, and click Reboot at the last step.
![screenshot from 2018-02-22 15-40-15](https://user-images.githubusercontent.com/23047456/36525887-e9776646-17e6-11e8-9ab5-c3497f6e0fe8.png)

**Actual results:**
1. The VM was shut off when the Reboot button was clicked.
![screenshot from 2018-02-22 15-50-48](https://user-images.githubusercontent.com/23047456/36526187-3051fa9e-17e8-11e8-9132-721cc7c5ec79.png)

2. Need to click 'Run' button to start the VM.

**Expected results:**
1. If checked the "Immediately Start VM" checkbox, the VM should start automatically after the guest OS is installed.

**Comment by stefwalter** [comment]
CC @suomiy Can you reproduce this?

**Comment by suomiy** [comment]
This was put there intentionally (`--norebooot` option), because of how virt-install behaves.

options:

#### 1. use `--norebooot` (Current)
- vm shutdowns on reboot or shutdown


#### 2. without `--norebooot`
- vm starts on reboot or shutdown 
- chance virt-install will hang until vm is turned off again after reboot 
  - this has implications on writing metadata to the vm (that it could happen much later)
  - basically virt-install is waiting 1 sec in infinite loop and checking if vm is active and then does after install handling 
    - could happen if you reboot under 1 sec. Nevertheless I have never observed this. 
    - it is not such a big deal, you are just having virt-install process running next to the installed vm and this process finishes once you turn it off. But it is not atomic and things could go wrong.


#### 3. disable wait
All of this is caused because we are waiting for the install to finish. This has the advantage of cleaning up (done by virt-install) if the installation fails and possibility to try again (done by our script)

#### Conclussion
I don't think the option `2.` is a good idea and I am not sure about the option `3.` 

We could also add some note that reboot is disabled for installing vms..
