### ISSUE TITLE
Is it possible to create menus and submenus?

### ISSUE THREAD

**Issue by dhilst** [cockpit-project/cockpit#8714]
I want to create a new menu entry, with submenus, how can I achieve that!? I want something like systemd package with have submenu and another plugins can plug to it. Is this possible?

Also, need to restart cockpit-ws everytime that I change the manifest.json, and when I restart I need to login again. The manifest is at `.local/share/cockpit/helloworld/`.

**Comment by martinpitt** [comment]
In the manifest you can have only the one top menu entry for your page. But of course you have full control on your own page, so you can put another menu there.

You don't need to restart cockpit-ws after changing manifest.json - it's enough to log out and back in. There's also some [package reload API](https://github.com/cockpit-project/cockpit/blob/master/pkg/playground/pkgs.js), so if you have the cockpit playground in your packages (e. g. running cockpit from git or otherwise link playground into ~/.share/cockpit/) you even have a button to reload the manifest without logging out and in.

**Comment by dhilst** [comment]
Thank you so much!

**Comment by mvollmer** [comment]
> There's also some package reload API

We should definitely make more use of this, I dropped the ball on that.  (The API was introduced for the "Applications" tool so that people don't need to logout/login when installing new packages.)

We should at least make it so that a reload of the browser is enough to reread the manifests.  I made a note for that: #8716.
