### ISSUE TITLE
storage: it seems possible to remove a Physical Volume twice(?)

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#8882]
I wanted to change some disks around for a VM to give it more space.
I added a new Physical Volume (200GB) to a Volume Group, and then I tried to delete another (100GB).
So I pressed the "-" button. It didn't seem to bite, so I tried to press it again.
Now it seems I have two "Emptying" jobs happening, and it seems like it's possible to trigger a third job.
Cockpit should probably disable the remove button once the remove PV job has been triggered.

![screenshot from 2018-03-23 18-37-08](https://user-images.githubusercontent.com/209895/37844828-37d6c87e-2ec9-11e8-9bfb-b2b446ac0c82.png)

**Comment by andreasn** [comment]
Tried to press it again, and now a third Emptying job started.

This is on the RHEL 7.5 beta, using Cockpit 154.

**Comment by andreasn** [comment]
Tried to press Cancel on one of the jobs, and then Cancel on another one, in an attempt to bring the jobs down to one. When I do that I get this dialog:

![screenshot from 2018-03-23 18-43-27](https://user-images.githubusercontent.com/209895/37845180-32551be8-2eca-11e8-8aed-f5205dd6ab5b.png)

**Comment by marusak** [comment]
This issue is closed due to inactivity.

If this issue is a bug report and you are still able to reproduce it, please
comment here and provide us with an updated reproducer.

If this issue is a request for a new feature, we are sorry, but we won't be able
to address this in any time soon. If you are interested in helping us with
the implementation, please comment here.
