### ISSUE TITLE
kubernetes: virtual Machines, offline vms

### ISSUE THREAD

**Issue by suomiy** [cockpit-project/cockpit#8895]
a new feature will be added to virtual machines:  [offline vms](https://github.com/kubevirt/user-guide/blob/master/offline-virtual-machine.md) 
- it behaves like a definition of vms
- vms can be started and destroyed by manipulating offline vms
- vms and offline vms can be manipulated and thus different at the same time

So we have two entities which can be different but are still linked together through some actions and attributes.

How should we display them in the ui?
currently dislaying only vms:
![screenshot from 2018-03-26 14-40-19](https://user-images.githubusercontent.com/3648838/37907021-3113ccd4-3104-11e8-97a2-093707f6aab7.png)

Offline vm will look similar, but the behaviour of actions (i.e. delete) will depend on each other.

Two propositions:
1. Show offline vm bellow the vm in the list
2. Have a switch in the vm  to toggle between offline and online view.

Any ideas? @andreasn @garrett

**Comment by garrett** [comment]
I've read your text here and the document you linked, but I'm still trying to understand the concept. (Perhaps this headache of mine is in the way right now, or perhaps it's just way over my head anyway.)

What does someone want to ultimately do when they would use offline VMs?

Is it like making a clone and modifying the clone, and then pushing the changes back (kind of like a test copy)? Or is it like checking a book out of a library when they only have one copy (and then you return it later)? Or something else entirely?

**Comment by mareklibra** [comment]
I hope, this helps, the concept is new:

The `OfflineVirtualMachine` comes from Kubevirt's terminology. Not everybody is happy with this naming, might be misleading for newcomers but it is already used.

A `OfflineVirtualMachine` represents entity close to common understanding of a virtual machine from standard virtualization world like we (Cockpit) were dealing so far.
Means - an entity which is defined, stored, can be repeatedly started/stopped, has long life-time.

The `VirtualMachine` entity used in Kubevirt is ephemeral - the object exists in k8s only if the VM is running, deleted otherwise.
A `VirtualMachine` is associated with a `pod` holding the `qemu` process and Libvirt (via `shim`).

Internally, a `VirtualMachine` is created from `OfflineVirtualMachine` when the `OfflineVirtualMachine` is about to `start`.

The concept of `OfflineVirtualMachine` is a way to reuse k8s API to store something what usually goes to dedicated database (please do not start a flame here).

So from UI perspective, the user defines `OfflineVirtualMachines` and fires actions on them. The cluster (k8s) manages lifecycle of `VirtualMachine` and other relaed objects accordingly.
The UI shall provide information about `OfflineVirtualMachine`, `VirtualMachine`, `pod` and others to get sufficient cluster insight.

**Comment by martinpitt** [comment]
Our kubernetes UI is on maintenance mode, so this won't happen any more. See https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/message/SBDE64DAIVTLIYRGVMESUPR5STRRFCGW/
