### ISSUE TITLE
software updates: Ugly resizing when expanding rows

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#8964]
On RHEL 7.5, will test on master tomorrow.
It seems that rows does not take up the full width initially, but they do when expanding rows. And this makes everything jump around. I think it should take the full width from the beginning

**Comment by andreasn** [comment]
https://andreasn.portknox.net/s/wfT3iPX5PezGywj

**Comment by martinpitt** [comment]
The reason is that the table lines are capped with max-width to not allow arbitrarily wide changelog entries. But once the expander opens, the full changelog gets rendered (markdown, with pre-wrapping as otherwise it may look really broken), which forces the table to get wider.

Not sure what to do about that. We could make wide changelogs get a (horizontal) scrollbar? Or fix this case with dropping pre-wapping at the expense of other changelogs relying on pre-wrap layout, particularly for the case where we don't actually get Markdown format.

**Comment by garrett** [comment]
Table should be 100% wide for this reason. I believe we have addressed this in recent pull requests, where the shifting should not happen under most circumstances.

(I have seen a few pixel shift, however, so it still kind of applies a little bit in some corner cases.)

**Comment by andreasn** [comment]
Do you have the PR numbers for that?
If so, we can close this.

**Comment by garrett** [comment]
Related PRs:

- #9292 (merged)
- ~#9272~ → #9370 (still pending)

#9292 was the fix; #9370 is an optimization

**Comment by martinpitt** [comment]
Both PRs got merged, so I suppose this can be closed now?
