### ISSUE TITLE
[Feature request] Dashboard - add "Show all" tab to view all graphs

### ISSUE THREAD

**Issue by wUFr** [cockpit-project/cockpit#8994]
Would be nice if dashboard had option to show all graphs at once. Now i have to "display:block;" each tab manually in browser dev tools

Preview:
![dashboard_show_all](https://user-images.githubusercontent.com/10975377/38770225-c66df97a-400f-11e8-819e-027efded4330.PNG)

**Comment by larskarlitski** [comment]
Do you mean in the dashboard? You already get this kind of overview on the System page for each individual host. I think we don't show them beneath each other in the dashboard, because that would make the server list move down quite far.

However, I agree that this might be useful on the dashboard as well. Maybe it makes sense to move that to the side on larger screens?

**Comment by wUFr** [comment]
could work

![dashboard](https://user-images.githubusercontent.com/10975377/38804952-704aa622-4174-11e8-8d5a-95f62fd49f87.png)

**Comment by wUFr** [comment]
i would edit it myself, since im front-end dev, but idk how to setup any dev evironment to do that :D
