### ISSUE TITLE
Run cockpit in a docker to monitor/manage host ? 

### ISSUE THREAD

**Issue by rgarrigue** [cockpit-project/cockpit#9029]
Hi

It's just a question, I'ld like to run cockpit in a container to monitor and maybe manage the (ubuntu server) host. Is there an official image for that, or maybe it's a bad idea and I should go for cadvisor instead ? 

Best regards,

**Comment by martinpitt** [comment]
We indeed release an officially supported [Cockpit web service container](https://hub.docker.com/r/cockpit/ws/). We only really test it on Fedora and RHEL Atomic, but in principle it also ought to work on other operating systems. The main missing thing when you run this directly through docker is that you lack the "atomic install cockpit/ws" command, so you need to run the [atomic-install](https://github.com/cockpit-project/cockpit/blob/master/containers/ws/atomic-install) script manually (or at least the relevant parts). Note that you still have to install cockpit-bridge, cockpit-system, and possibly other cockpit extensions (like cockpit-docker) on the host - this container provides only the web service. Due to how Cockpit works, these can't be run from a container right now.
