### ISSUE TITLE
firewall: not clear that firewall is open to outgoing traffic

### ISSUE THREAD

**Issue by andreasn** [cockpit-project/cockpit#9047]
This came up during the [usability testing](https://github.com/cockpit-project/cockpit/wiki/Usability-test-Firewall).
It's not clear that the firewall allows all outgoing traffic, and that the ports listed in the table are only for incoming traffic. This was voiced as an issue by 50% of the participants (3 out of 6)

**Comment by garrett** [comment]
Original design had a message about incoming requests being blocked by default. We could bring that back and expand upon it.

![original firewall design](https://user-images.githubusercontent.com/10246/151836287-35d8078f-2540-4735-85bf-cb5b9e21ece0.png)

It would look like this (quick mockup where only the title is changed from what's in the cockpit-design repo):

![recent firewall design, modified for the text at the top](https://user-images.githubusercontent.com/10246/151837240-10abaabc-d56b-4938-b288-7b7a03263757.png)

That would be a "quick fix" (relative to now, not how long this bug has been open).

We could, eventually, add support for outgoing. Since it'd be tied to zones, I think the only* way where it'd make sense would be to display it like this (revised to dump the trash icons and move dangerous and secondary functionality to kebab menus)]:

![recent firewall design adjusted a bit further, for the future, to include incoming/outgoing per zone](https://user-images.githubusercontent.com/10246/151839044-f22bc1b8-0436-4a8c-a59a-cf9ba1be9408.png)

\* (I've considered other methods, but they all require mode switching or grouping incoming and outgoing. Especially when zones are concerned, it's important to be able to get an overview of the firewall, so the above mockup is probably the only way to show the concepts that make sense.)

**Comment by garrett** [comment]
If we did decide to handle outgoing traffic, we might want to build upon the concept above (last of the mockups) we might want to:

1. Change the text at the top.
2. Make outgoing not blocked by default actually, unless that's a setting in the zone dialog. (I guess it should be a block by default setting.)
3. Change messaging to be in the incoming/outgoing perhaps? It'd be text to the right of the sub-sub-headings.
4. Start with non-editable, already-included services and just message what's included in the zone.

I had a mockup that illustrated this, but Inkscape crashed and it's already getting late here today. So we'll have to discuss it... and if it's a good idea, I'm happy to mock it up again.

Meanwhile, we probably want to consider mockup # 2 above, with the addition of the text at the top.

**Comment by jelly** [comment]
> If we did decide to handle outgoing traffic, we might want to build upon the concept above (last of the mockups) we might want to:
> 
> 1. Change the text at the top.

I like the explainer for "incoming requests are blocked by default". However for outgoing traffic I don't think this is the case with firewalld? Needs verification.

> 2. Make outgoing not blocked by default actually, unless that's a setting in the zone dialog. (I guess it should be a block by default setting.)

Needs checking

> 3. Change messaging to be in the incoming/outgoing perhaps? It'd be text to the right of the sub-sub-headings.

Sounds good and clear to me.

> 4. Start with non-editable, already-included services and just message what's included in the zone.

Sounds good

**Comment by jelly** [comment]
After researching controlling/configuring outbound firewall rules is hard in firewalld, the best effort we can make is to figure out how we can show outbound rules if they exists.

**Comment by garrett** [comment]
> After researching controlling/configuring outbound firewall rules is hard in firewalld, the best effort we can make is to figure out how we can show outbound rules if they exists.

Yep. There are good reasons why we haven't tried tackling output firewall rules for now. (Complicated, not often used, not so well documented, etc.) Blocking some outgoing makes a lot more sense on desktops/laptops compared to servers (but then the UI would be even trickier for desktops/laptops for that versus servers). 

Desktops/laptops are often running a hodgepodge of software making who-knows-what connections out to the Internet. 

Servers usually have a task or two, especially in these days of VMs and containers (where I'm assuming the server is inside the VM or container in this definition, not the host). And VMs and containers often use port mapping anyway too. 

If it's in a larger environment, most servers will likely have a dedicated (external) firewall too.

Of course, there are many network admins doing their own things at the command line and I agree we should at least show that.

But, back to this issue: We definitely could and should at least better message what's going on for now and then consider what makes sense when following up.

**Comment by garrett** [comment]
This was designed from early on, but still isn't implemented. It's just adding a string that was in the old mockups.
