### ISSUE TITLE
[Feature Idea] Audit logging of Cockpit-actions

### ISSUE THREAD

**Issue by danielperna84** [cockpit-project/cockpit#9066]
I apologize in advance if this isn't the right place start this topic. Feel free to redirect me at the proper audience. I have looked at the [Roadmap](https://github.com/cockpit-project/cockpit/wiki/Roadmap), [Ideas](https://github.com/cockpit-project/cockpit/wiki/Ideas) and [Ideals of Cockpit](http://cockpit-project.org/ideals.html).

A feature I consider important for a software that is capable of altering critical parts of a server is proper logging of WHAT has been done WHEN by WHOM. I have watched the journal while using Cockpit, and things like setting different DNS servers of a network interface aren't clearly logged. The NetworkManager does output a bit, but in much less detail than I believe is necessary for corporate environments. Imagine a whole bunch of Docker containers going down because of a misconfiguration and there's no way to figure out who is accountable for the resulting problems.

Having looked at the ideals of Cockpit I do realize, that this logging should actually rather be part of the tools for which Cockpit is _just a GUI_. But maybe centralizing the logging process within Cockpit could be a better solution as it then would follow certain standards.

The basic concept I have in mind is, that Cockpit should provide some centralize Logging-hook that's accessible from every component. Then in the NetworkManager component the part that is responsible for changing settings on the system would call something like `log("%s %s %s %s", component, user, settingname, value)`. Or possibly even without defining the user and component since these should be automatically know anyway.
Digging deeper it would be nice if the generated logs would actually be easy to use with [Splunk](www.splunk.com) or [Graylog](www.graylog.org).

I am aware, that switching to the terminal and making changes manually would bypass the enforced logging. Hence it's valid to say this type of logging within Cockpit can be considered useless. Then again I have stumbled upon [session recording](https://fosdem.org/2018/schedule/event/session_recording/attachments/slides/2349/export/events/attachments/session_recording/slides/2349/Session_Recording_in_Cockpit___FOSDEM_2018.pdf) in the Cockpit terminal.

So, what is the general opinion on this topic? Any pros or cons? Maybe alternative solutions that allow auditing what happens on the system via Cockpit?

**Comment by martinpitt** [comment]
To be honest, I'm rather sceptical about doing this on the Cockpit level, for the reason you already mentioned. It's all too easy to work around this, by e. g. using the Terminal and CLI commands, or even the Cockpit API without the UI (and skip the logging calls). For a reliable audit trail, one really wants to put these logs into the actual system services like NetworkManager, so that things get logged regardless of what calls the API.

Note that the session recording efforts are  for implementing a viewer/player for recorded sessions in cockpit, *not* to record what happens in cockpit. A user subjected to session recording (i. e. using the `tlog` shell) isn't even allowed to use Cockpit, as that would completely break the idea of session recording.

**Comment by danielperna84** [comment]
Thanks for your reply. I agree, that in practice this won't be as secure as I would wish. Closing this issue to make room for others.
