### ISSUE TITLE
cockpit-machines: Launch Remote Viewer .vv port=null when only SICE TLS

### ISSUE THREAD

**Issue by xenithorb** [cockpit-project/cockpit#9244]
When using the "Launch Remote Viewer" button, the downloaded `.vv` file looks as follows:

```
[virt-viewer]
type=spice
host=10.0.0.3
port=null
delete-this-file=1
fullscreen=0

[...............................GraphicsConsole]
```

If `defaultMode='secure'` is set in the domain's configuration:

```
    <graphics type='spice' autoport='yes' defaultMode='secure'>
```

Shouldn't it default to TLS anyway? It seems that it doesn't currently use it at all.

**Comment by marusak** [comment]
This issue is closed due to inactivity.

If this issue is a bug report and you are still able to reproduce it, please
comment here and provide us with an updated reproducer.

If this issue is a request for a new feature, we are sorry, but we won't be able
to address this in any time soon. If you are interested in helping us with
the implementation, please comment here.
