### ISSUE TITLE
Permission object doesn't change on lock.

### ISSUE THREAD

**Issue by Gundersanne** [cockpit-project/cockpit#9427]
The Permission object's "changed" signal only gets sent once at the start. And when locking via the UI `permission.allowed` doesn't change.

**Comment by larskarlitski** [comment]
@martinpitt recently changed the way we test for elevated permissions by creating a channel with `{ superuser: "require" }`. We could keep this channel open and send the `changed` signal when it closes. That wouldn't fix the notification for the other case, when you gain the permission.

The "lock" button in the UI is pretty broken because of it. Also, we don't listen to this signal in a lot of places. Also, there's no unlock. I think it might be best to remove the lock button until we get this feature in a better shape. What do you think, @garrett?

**Comment by garrett** [comment]
Yeah, the lock/unlock functionality is pretty broken as-is. The full design (from a while ago) is at https://github.com/cockpit-project/cockpit/wiki/Feature:-unlocking-privileged-operations — and lots of pieces are missing.

Related: We should make singing in as an administrator clearer. Perhaps it should be a switch instead of a checkbox? And/or it should be default? Perhaps it would be good to discuss at the Hackfest.

**Comment by martinpitt** [comment]
PR #9531 dropped the "Drop Privileges" functionality, for reasons like this.
