### ISSUE TITLE
ws: Login page's labels get cut off in certain languages 

### ISSUE THREAD

**Issue by Gundersanne** [cockpit-project/cockpit#9514]
![screenshot from 2018-06-26 14-02-25](https://user-images.githubusercontent.com/11140201/41910450-fac7e33e-7949-11e8-81ab-83198f2d7fc4.png)

**Comment by agamvrinos** [comment]
Hey @martinpitt . I reproduced this and saw that this is still an issue. Could you elaborate on how you'd like this to be handled?

**Comment by marusak** [comment]
This does not happen anymore since we have PF4 likealike homepage.
![loginscreenname](https://user-images.githubusercontent.com/12330670/67192217-7cecb180-f3f3-11e9-977e-d9a484be9dc5.png)

Currently languages we support and their translation of `User name`:
Nom d'usuari                                                                    
Uživatelské jméno                                                               
Benutzername                                                                    
Nombre de usuario                                                               
Käyttäjätunnus                                                                  
Nom d’utilisateur                                                               
Nome utente                                                                     
ユーザー名                                                                      
사용자 이름@                                                                    
Nazwa użytkownika                                                               
Nome de usuário                                                                 
Имя пользователя                                                                
Användarnamn                                                                    
Ім'я користувача                                                                
用户名                                                                          
使用者名稱   
One of the longest one is czech and it still fits:
![czechfits](https://user-images.githubusercontent.com/12330670/67192371-bfae8980-f3f3-11e9-8d33-8851ed33036e.png)

It may overflow (to the other side now) but currently does not happen and likely won't happend (at least in near future).
Also on small screens (like phones) this text is above the input, which may be solution if it starts to overflow once again.
