### ISSUE TITLE
Hide system information on login page

### ISSUE THREAD

**Issue by t3chn0m4g3** [cockpit-project/cockpit#9567]
On the `Cockpit` login page the following information are displayed / exposed:
- `Hostname` as webpage title and as server name
- `Installed OS` by logo and with release information (i.e. UBUNTU 18.04 LTS)

Usually you want to hide all system information where possible, especially if exposed to an untrusted network. Is there a way to turn off the mentioned information?

**Comment by martinpitt** [comment]
It is not currently configurable, so you would need to modify the login page yourself. Alternatively, if that is a public-facing machine with untrusted access, you can not run the cockpit web server there but connect to it from a remote cockpit-ws running machine.

TBH I would worry a lot more about exposing ports like ssh and cockpit on sensitive machines than exposing the installed OS (which you can already get with checking the response on the ssh, mail, or other open ports) or the host name (which you already know as you just connected to it). So I'd think "usually" is a rather strong assumption here.

**Comment by t3chn0m4g3** [comment]
Thanks, are there any plans to make this configurable?

**Comment by martinpitt** [comment]
There are no current plans for this, no.

**Comment by martinpitt** [comment]
I'm closing this, as I don't see us implementing this, sorry.

**Comment by zpangwin** [comment]
Since this is unsupported / won't be implemented, here is a workaround for anyone interested who is coming in from search engines like I did. Working as of writing for cockpit v246-1 on Fedora. Being unsupported, it is possible that this could break in the future.

I do agree that exposed information such as might be found via ssh / mail, etc should be a higher priority but considering that those *can* be configured to only display such information *after* authentication (or not at all), I still feel like this is a somewhat valid request as it is basically in keeping guidelines provided by the `lynis` auditing package for other packages such as `postfix`. Anyway, I was *only* concerned about information being displayed on the login page or in its page source; anything after authentication I did not mess with.

1. Hide visible OS Details and Branding on the login page. For this simply renaming some ids is enough to prevent them being filled in. This has no effect on the login form and that continues to work fine without this information.

    sudo cp -a /usr/share/cockpit/static/login.html /usr/share/cockpit/static/login.html.$(date +'%Y-%m-%d').bak;
    sudo sed -Ei 's/ id="brand"/ id="nobrand"/g' /usr/share/cockpit/static/login.html;
    sudo sed -Ei 's/ id="badge"/ id="nobadge"/g' /usr/share/cockpit/static/login.html;

2. Remove OS details from dynamically embedded JSON in page source. This is slightly trickier in that you can't just remove the section / rename it without breaking the login form - at least that was what happened when I tried it. What I did o work around this was to bring up the login page once and view the page source. Then I copied the generated JSON string and pasted it into my vim session where I was editing the same html file as in the previous step. Finally, I replaced individual strings in the JSON with the value of "MASKED". After reloading the page with Ctrl + Shift + R (skip cache), I was no longer able to see any host info displayed in the page source and I was still able to log in ok.

    # I used vim but use whatever you like
    sudo vi /usr/share/cockpit/static/login.html

Replace the line: `<meta insert_dynamic_content_here>`

With the following (formatted for readability but I left mine as one line):

    <script>
      var environment = {
        "page":{
            "connect":true,"require_host":false
        },
      "hostname":"localhost",
      "os-release":{
        "NAME":"MASKED",
        "ID":"masked",
        "PRETTY_NAME":"MASKED",
        "VARIANT":"MASKED",
        "VARIANT_ID":"masked",
        "CPE_NAME":"MASKED",
        "DOCUMENTATION_URL":"MASKED"
      },
      "CACertUrl":"/ca.cer"
    };
    </script>

I have not extensively tested this for problems but I saw some host info after authenticating so I think it might be just inserting the info on each page rather than passing between pages... Will try to post back with any updates if I find anything broken due to this setup (I assume restoring my backup of the file would be a good enough test to confirm if my changes broke anything or not).
