### ISSUE TITLE
Terminal - Some keys not working on MacOS

### ISSUE THREAD

**Issue by t3chn0m4g3** [cockpit-project/cockpit#9581]
On MacOS some keys are not working as expected, i.e. `ALT+L` is not interpreted into `@` or `ALT+7` not into `|`. It seems the involvement of the `ALT / OPTION` key is the culprit.

macOS Version: `10.13.5 (High Sierra)`
Chrome Version: `67.0.3396.99 (Official Build) (64-bit)`
Safari Version: `Version 11.1.1 (13605.2.8)`
Firefox Version: `61.0 (64-Bit)`

**Comment by t3chn0m4g3** [comment]
Can anyone confirm?

**Comment by martinpitt** [comment]
Do you have a chance to test the "Serial Console" terminal on the Machines page? That uses XTerm.js, which should be a lot more modern than our ancient termjs-cockpit. If that works, then this will fix itself once we migrate the main Terminal page over to XTerm.js. Otherwise I'm afraid we'll need some external help from a developer with a Mac.

**Comment by t3chn0m4g3** [comment]
@martinpitt Works perfectly fine on v188.

Thanks to everyone for their effort in making this possible :bowtie:

**Comment by t3chn0m4g3** [comment]
@martinpitt @marusak I just noticed, copy / paste works now, too 😃 This is great! Thanks again, guys!

**Comment by PeterFalken** [comment]
Copy and Paste are working correctly now, I can confirm as well. But now the output of the terminal console seems to lag and feels slow. I opened issue #11369 to track this problem.
