### ISSUE TITLE
Machines: Create/Attach disk design update

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#9681]
In https://github.com/cockpit-project/cockpit/pull/9166 @garrett had some design feedback for the new dialog. In order to unblock some followup PRs this was landed, but there is one thing to fix: Right now the dialogs look like this:

![01](https://user-images.githubusercontent.com/17194943/41976507-995c0c86-7a1d-11e8-9a35-9b313f5dfa7e.png)

![02](https://user-images.githubusercontent.com/17194943/41976508-997c1602-7a1d-11e8-90aa-1820ab95da1b.png)

But the tabs should be replaced with radio buttons:

![vm-add-disk](https://user-images.githubusercontent.com/10246/42803071-1c4353de-89a5-11e8-8d44-132a91153231.png)

**Comment by garrett** [comment]
Details of little issues mentioned in #9166:

1. Remove colons (`:`). Seen in the screenshot.
2. Vertical alignment in the implementation seems off for some reason. It should be aligned to baseline. I thought the CSS classes are supposed to take care of that though... I'm not sure if it's just rendering oddly on the screenshots in #9166 or an actual issue.
3. The buttons are supposed to be "Add" instead of "Add Disk".

These are all covered in the mockups, but perhaps they're not obvious enough, so they're called out explicitly.

**Comment by mareklibra** [comment]
#9738 fixes colons and primary button description

Remains:
>2. Vertical alignment in the implementation seems off for some reason. It should be aligned to baseline. I thought the CSS classes are supposed to take care of that though... I'm not sure if it's just rendering oddly on the screenshots in #9166 or an actual issue.

**Comment by KKoukiou** [comment]
Everything here will be addressed from https://github.com/cockpit-project/cockpit/issues/10703
