### ISSUE TITLE
machines-ovirt: Lost CPU Type information 

### ISSUE THREAD

**Issue by kenzhaoyihui** [cockpit-project/cockpit#9712]
Description of problem:
Lost CPU Type information 

Version-Release number of selected component (if applicable):
RHEL-7.5-20180322.0
cockpit-machines-ovirt-172-2.el7.noarch

How reproducible:
100%

Steps to Reproduce:
The same as the description.
![cockpit-0723](https://user-images.githubusercontent.com/18360375/43069767-912ecae8-8ea0-11e8-9acc-2acd27afc96e.png)

Expected results:
CPU Type information can be shown from cockpit.

Additional info:

**Comment by KKoukiou** [comment]
@kenzhaoyihui, I fixed the same issue cockpit-machines with https://github.com/cockpit-project/cockpit/commit/228c6601d2891a220012dda1a4bfebd730947b59
Since that component is shared between the two packages I guess it's fixed for ovirt package as well.

Could you please verify that master fix/doesn't fix have this issue?

**Comment by kenzhaoyihui** [comment]
Tested with cockpit-machines-ovirt-173-3.el7.noarch, it works well, So, close it
