### ISSUE TITLE
tests: WebKit automation

### ISSUE THREAD

**Issue by garrett** [cockpit-project/cockpit#9713]
Proper mobile support includes Safari on iOS.

Our automated tests cannot include Safari on iOS, and it would be a challenge to even include Safari on macOS. Therefore, I suggest we do automated testing on WebKit, which is used by:

- Safari / iOS
- Safari / macOS
- Epiphany (GNOME Web)
- Qt-based browsers

It is possible to use a Selenium WebDriver for Safari on macOS — but this requires hardware that can run macOS and is still limited to desktop-only:
- https://developer.apple.com/documentation/webkit/testing_with_webdriver_in_safari
- https://webkit.org/blog/6900/webdriver-support-in-safari-10/

WebKitGTK+ _also_ has WebDriver support: https://blogs.igalia.com/carlosgc/2017/09/09/webdriver-support-in-webkitgtk-2-18/ — and this works inside of Linux just fine, and therefore would be better for our needs.

And there are several solutions using Qt's version of WebKit. (However, Qt's WebKit usually lags behind what's in Safari and WebKitGTK+.)

Using WebKit on Linux should get us most of the way there for Safari, and should help to ensure our Linux desktop support is even better too as a bonus. :wink:

**Comment by garrett** [comment]
Epiphany now has automation mode: https://blogs.igalia.com/carlosgc/2019/01/08/epiphany-automation-mode/

The blog post has example code and also links to the WebKitGTK driver.

Running WebKitGTK headless might be better for us, but the blog post above may have some interesting details.

**Comment by marusak** [comment]
The problem is not with support for headless browsers, but for browsers having proper protocol through which we can interact with the page (we use chrome debug protocol).
You linked to selenium which we are depreciating for a while now. We are not even fully testing firefox, so I would say we should focus on that first and once we test fully chrome and firefox, then we can try to test some other browsers. But this is run for a loong distance, so I don't think we need to really actively tracking this.
