### ISSUE TITLE
realmd: Better label when realmd is not installed, but machine is in a domain

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/cockpit#9772]
Fallout from PR #9759: If realmd is not installed but the machine is actually joined to a domain, we transition from the "installing realmd" dialog to the "are you sure you want to leave domain" dialog.

We just can't detect that it's in a domain before installing realmd. Perhaps the label should be something more neutral then, and not imply that the machine isn't joined?

**Comment by garrett** [comment]
My concerns:

1. It's very visible as it's on the overview
2. Not everyone will want to have machines in a domain
3. A long string could work wrap oddly

Otherwise, "Install domain support…" should be fine.

Or we could have:

> Domain [Install support](#fakelink)

(But we would then need to do some accessibility stuff here, to make sure the link is associated with the domain label. However, we still need to change the `<td>`s to `<th>`s. I thought I did a PR for that, but I don't see it. Perhaps it's just in a local branch...)

**Comment by garrett** [comment]
I'm happy with "Install domain support..."

**Comment by martinpitt** [comment]
Thanks @garret. We use "Install NFS Support" and "Install VDO support" already, so at least there's some consistency.

**Comment by Alcadeus0** [comment]
Hi, can I take up this issue :)
