### ISSUE TITLE
Question: differences between RedHat and Ubuntu (and other) versions?

### ISSUE THREAD

**Issue by raarts** [cockpit-project/cockpit#9779]
Hi,

I installed cockpit on an Ubuntu 16.04 ARM device, and it works (compliments), but when I looked 
at some youtube demos (all done on rhel), I seem to be missing a lot of menu entries. Some of them were due to software not being installed (firewalld for instance), and I could fix those easily, other were harder, for example tuned is not available on Ubuntu. Also the applications menu is empty. 

Is there an overview of the differences, and what is supported and what not?

**Comment by martinpitt** [comment]
There is no overview, as this set of differences changes a *lot*. For example tuned is indeed not available on 16.04, but it is on [18.04 LTS](https://launchpad.net/ubuntu/+source/tuned).

There are currently no Applications in Debian/Ubuntu, but technically there could be - and this is hard to track from our POV.

Some menu entries might also be missing because you don't have the corresponding docker-* package installed? Try "apt search cockpit" to find some potentially interesting extensions for you.

**Comment by bomberlord** [comment]
I'm sorry to dig this up but i have a question relative to the firewall management in Ubuntu. I've disabled iptables and installed firewalld, permited the cockpit service in firewalld and everything is working. Except for the firewall management in cockpit. How did you manage to get it working?

Best regards
