### ISSUE TITLE
http-stream2 channel can fail with EAGAIN on connect

### ISSUE THREAD

**Issue by larskarlitski** [cockpit-project/cockpit#9861]
I saw this in weldr-web, which opens a lot of connections to lorax-composer's unix domain socket. Due to a small bug, it sometimes starts with a listen backlog of 1, which made http-stream2 channel fail with EAGAIN.

It should probably poll for the socket to become writable and fail only when a timeout is reached.

**Comment by martinpitt** [comment]
This sounds like sockets are opened non-blocking by default? I wonder if switching to blocking and adding a timeout would really make client code easier and more robust? I. e. whether the Cockpit API can make enough predictions/assumptions about how the client wants to handle loaded/blocking services?

**Comment by larskarlitski** [comment]
Yes, all sockets in Cockpit are non-blocking. We can't make them blocking, because `cockpit-bridge` needs to handle all the other channels in the same thread. We could put the socket into the main loop and wait for it to become ready.

> I. e. whether the Cockpit API can make enough predictions/assumptions about how the client wants to handle loaded/blocking services?

Good point. We probably can't make too many assumptions for the general case, but I think having a reasonable timeout would go a long way in such cases. (Admittedly, this case I saw in lorax-composer probably doesn't happen that often.)

In general, failing with `EAGAIN` and reporting that to higher-level code seems wrong to me. If we keep it as is, we probably want something that reports "unable to connect, because the server is busy".

**Comment by martinpitt** [comment]
I tried to reproduce that with `rm -f /tmp/x.sock; nc -U -l /tmp/x.sock` and then trying to connect to that in the browser console:

    cockpit.http("/tmp/x.sock").get("/").then(console.log).catch(console.error)

this normally works fine, but even if I already launch a `nc -U /tmp/x.sock` to have one connection, connect() still works:

    connect(16, {sa_family=AF_UNIX, sun_path="/tmp/x.sock"}, 110) = 0

that's probably because netcat uses a large backlog, apparently even indefinitely large?

```
$ ss -l
Netid State  Recv-Q Send-Q                                       Local Address:Port                  Peer Address:Port Process 
u_str LISTEN 0      5                                              /tmp/x.sock 30105                          * 0      
```

I.e. Recv-Q is zero.

That said, I still believe that actually *failing* is better than an indefinite hang, so that the page can handle this better -- if it's worth retrying or not. Automagically retrying in the bridge feels too magic to me.

This probably never came up as there are only two cases where we actually connect to a unix socket: in cockpit-composer and podman.

So I think let's just continue to ignore this, until it becomes an actual problem.
