### ISSUE TITLE
Cockpit does not start after restart

### ISSUE THREAD

**Issue by sweise17** [cockpit-project/cockpit#9932]
Freshly installed version of Cockpit on Debian 9.5 just won't start. After restarting my servers the status of `service cockpit status` is only inactive. When I run `service cockpit start`, the output of `service cockpit status` is OK but my web interface is not available on both servers.
The error also occurs when I install Cockpit on Debian and do not make any changes.

**Comment by martinpitt** [comment]
`cockpit.service` is not *supposed* to auto-start on  boot. It is activated on demand with socket activation. The unit that should be running is `cockpit.socket`.

"Not available on both servers" needs more information. What exactly do you see? What's the output of `sudo systemctl status cockpit.service` after a connection attempt? Any journal messages, firewall, etc?

**Comment by sweise17** [comment]
`● cockpit.service - Cockpit Web Service
   Loaded: loaded (/lib/systemd/system/cockpit.service; static; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:cockpit-ws(8)`

firewalld is active. But I added `firewall-cmd --add-service cockpit`

**Comment by sweise17** [comment]
I have to add, that I configured Cockpit behind a Apache2 reverse Proxy.

_/etc/cockpit/cockpit.conf_
```
[WebService]
Origins = https://cp.sebastianweise.com http://127.0.0.1:9090
ProtocolHeader = X-Forwarded-Proto
AllowUnencrypted = true
```
and my Apache2 site-conf
```
<IfModule mod_ssl.c>
<VirtualHost *:443>
        ServerName cp.sebastianweise.com
        SSLCertificateFile /etc/letsencrypt/live/<domain>/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/<domain>/privkey.pem
        Include /etc/letsencrypt/options-ssl-apache.conf

        ProxyPreserveHost On
        ProxyRequests Off

        RewriteEngine On
        RewriteCond %{HTTP:Upgrade} =websocket [NC]
        RewriteRule /(.*)           ws://127.0.0.1:9090/$1 [P,L]
        RewriteCond %{HTTP:Upgrade} !=websocket [NC]
        RewriteRule /(.*)           http://127.0.0.1:9090/$1 [P,L]

        ProxyPass / http://127.0.0.1:9090/
        ProxyPassReverse / http://127.0.0.1:9090/
</VirtualHost>
</IfModule>
```

**Comment by sweise17** [comment]
**_Update:_**
When I disable firewalld and the reboot the vServer, everything is working fine. Also the second Server with still activated firewalld is controllable without problems.
I think that the firewall is blocking Apache2. When it is active, all my Websites are going down.
Any ideas?

**Comment by martinpitt** [comment]
`firewall-cmd --add-service` only applies to the current boot. If you want it to persist, you need to add `--permanent` as well. Confusing, I know, but not something which we can influence on the Cockpit side.

**Comment by sweise17** [comment]
Adding
`firewall-cmd --add-service cockpit --permanent`
and
`firewall-cmd --add-service http --permanent`
and
`firewall-cmd --add-service https --permanent`
didn´t work for me first, but after a reboot everything is working fine 😃 
Thank u.

**Comment by martinpitt** [comment]
Right, `--permanent` does *not* affect the currently running instance, that's the `--add-service` without the permanent option that you used before. So if you want to add the service both "now" and "after reboots", you need to run both variants.

Great to hear that it works now!

**Comment by DavidFW1960** [comment]
Just installed cockpit.
Added repo to /etc/apt/sources.list.d/backports.list and did a apt install cockpit cockpit-docker cockpit-machines. Debian Stretch 9.5

david@debian:~$ systemctl status cockpit
● cockpit.service - Cockpit Web Service
   Loaded: loaded (/lib/systemd/system/cockpit.service; static; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:cockpit-ws(8)

So same error. Dead.
I didn't reboot the server.. was I supposed to?
I have not installed or configured a firewall that I know of. Just did a Debian install.. no desktop.
cannot load localip:9090 in a browser.
This server runs headless.

**Comment by DavidFW1960** [comment]
I see this:
```
david@debian:~$ curl -k https://localhost:9090
curl: (35) Unknown SSL protocol error in connection to localhost:9090
david@debian:~$ systemctl status cockpit.socket
● cockpit.socket - Cockpit Web Service Socket
   Loaded: loaded (/lib/systemd/system/cockpit.socket; enabled; vendor preset: enabled)
   Active: failed (Result: resources) since Fri 2018-10-12 11:19:08 AEDT; 6h ago
     Docs: man:cockpit-ws(8)
   Listen: [::]:9090 (Stream)
      CPU: 1ms
david@debian:~$
```

**Comment by martinpitt** [comment]
> Active: failed (Result: resources)

That means that there's something wrong with socket units on your system. Can you please check

    sudo journalctl -u cockpit.socket

for any error messages?

Also, "Unknown SSL protocol error in connection to localhost:9090" sounds like there is already something else running on port 9090. What do you see in

    sudo ss -tulpen | grep 9090

**Comment by DavidFW1960** [comment]
Dammit! You're right! Sabnzdb is listening on that port. Can I change the cockpit port?

david@debian:~$ sudo journalctl -u cockpit.socket
-- Logs begin at Mon 2018-09-10 16:21:48 AEST, end at Fri 2018-10-12 17:58:46 AEDT. --
Oct 12 11:19:08 debian systemd[1]: cockpit.socket: Failed to listen on sockets: Address already in use
Oct 12 11:19:08 debian systemd[1]: Starting Cockpit Web Service Socket.
Oct 12 11:19:08 debian systemd[1]: Failed to listen on Cockpit Web Service Socket.
Oct 12 11:19:08 debian systemd[1]: cockpit.socket: Unit entered failed state.
david@debian:~$ sudo ss -tulpen | grep 9090
tcp    LISTEN     0      128      :::9090                 :::*                   users:(("docker-proxy",pid=5579,fd=4)) ino:28229875 sk:da v6only:0 <->

**Comment by martinpitt** [comment]
@DavidFW1960 : Yes, you can change it. See https://cockpit-project.org/guide/latest/listen.html

**Comment by dandelionred** [comment]
I had the same problem with cockpit not available on reboot, but I could start it manually. I used such override snippet to prevent it from listening on all interfaces
```
[Socket]
ListenStream=
ListenStream=192.168.1.1:9090
```

The IP was not established yet (a static ip set with networkmanager) when cockpit starts. As per https://cockpit-project.org/guide/latest/listen.html I fixed it with `FreeBind=yes` appended to the snippet.

**Comment by saadelkenawy** [comment]
How could I add auto restart in daemon of cockpit service

**Comment by marusak** [comment]
> How could I add auto restart in daemon of cockpit service

Sorry, what do you mean by `auto restart`? cockpit service is socket activated, so there is no need to `restart` it.

**Comment by saadelkenawy** [comment]
> > How could I add auto restart in daemon of cockpit service
> 
> Sorry, what do you mean by `auto restart`? cockpit service is socket activated, so there is no need to `restart` it.

please advise according to my search to add a parameter to service of cockpit to ON-Restart = on-failure 

Configures whether the service shall be restarted when the service process exits, is killed, or a timeout is reached. The service process may be the main service process, but it may also be one of the processes specified with ExecStartPre=, ExecStartPost=, ExecStop=, ExecStopPost=, or ExecReload=. When the death of the process is a result of systemd operation (e.g. service stop or restart), the service will not be restarted. Timeouts include missing the watchdog "keep-alive ping" deadline and a service start, reload, and stop operation timeouts.

Takes one of no, on-success, on-failure, on-abnormal, on-watchdog, on-abort, or always. If set to no (the default), the service will not be restarted. If set to on-success, it will be restarted only when the service process exits cleanly. In this context, a clean exit means an exit code of 0, or one of the signals SIGHUP, SIGINT, SIGTERM or SIGPIPE, and additionally, exit statuses and signals specified in SuccessExitStatus=. If set to on-failure, the service will be restarted when the process exits with a non-zero exit code, is terminated by a signal (including on core dump, but excluding the aforementioned four signals), when an operation (such as service reload) times out, and when the configured watchdog timeout is triggered. If set to on-abnormal, the service will be restarted when the process is terminated by a signal (including on core dump, excluding the aforementioned four signals), when an operation times out, or when the watchdog timeout is triggered. If set to on-abort, the service will be restarted only if the service process exits due to an uncaught signal not specified as a clean exit status. If set to on-watchdog, the service will be restarted only if the watchdog timeout for the service expires. If set to always, the service will be restarted regardless of whether it exited cleanly or not, got terminated abnormally by a signal, or hit a timeout.

**Comment by dandelionred** [comment]
@saadelkenawy I guess `systemctl edit cockpit.service` is what you're looking for.

**Comment by saadelkenawy** [comment]
> @saadelkenawy I guess `systemctl edit cockpit.service` is what you're looking for.

I will try to do it and. will feedback @dandelionred

**Comment by helamonster** [comment]
I'm trying to have cockpit listen on port 80 only (I've got haproxy handling my SSL), but can't seem to get it working.

Changes I've made:
```
root@cockpit ~ $ cat /etc/cockpit/cockpit.conf 
[Session]
IdleTimeout=0
[WebService]
AllowUnencrypted=true

root@cockpit ~ $ cat /etc/systemd/system/cockpit.socket.d/listen.conf 
[Socket]
ListenStream=80

root@cockpit ~ $ systemctl  daemon-reload
root@cockpit ~ $ systemctl  restart cockpit
A dependency job for cockpit.service failed. See 'journalctl -xe' for details.

root@cockpit ~ $ journalctl -xe
...
Jan 26 17:37:59 cockpit.dc1.domain.com systemd[1]: Starting Socket for Cockpit Web Service https instance factory.
-- Subject: A start job for unit cockpit-wsinstance-https-factory.socket has begun execution
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A start job for unit cockpit-wsinstance-https-factory.socket has begun execution.
-- 
-- The job identifier is 7509584.
Jan 26 17:37:59 cockpit.dc1.domain.com systemd[647212]: cockpit.socket: Failed to create listening socket ([::]:9090): Address already in use
Jan 26 17:37:59 cockpit.dc1.domain.com systemd[1]: cockpit.socket: Failed to receive listening socket ([::]:9090): Input/output error
Jan 26 17:37:59 cockpit.dc1.domain.com systemd[1]: cockpit.socket: Failed to listen on sockets: Input/output error
Jan 26 17:37:59 cockpit.dc1.domain.com systemd[1]: Starting Cockpit Web Service Socket.
...

```

I am able to start cockpit manually and everything works fine:
```
root@cockpit ~ $ /usr/lib/cockpit/cockpit-ws -p 80  --for-tls-proxy 

jeremy@latitude ~ $ curl -s http://cockpit.dc1.domain.com:80 | grep '<title>'
    <title>Loading...</title>

jeremy@latitude ~ $ curl -s https://cockpit.dc1.domain.com:443 | grep '<title>'
    <title>Loading...</title>

```
I also tried adding `FreeBind=yes` to the `/etc/systemd/system/cockpit.socket.d/listen.conf` file to no avail (same address already in use error).
Not sure what I'm missing here. Is there another setting for cockpit.conf equivilent to the ` --for-tls-proxy` argument?




Nevermind.... After changing `listen.conf` to:
```
[Socket]
ListenStream=
ListenStream=80
FreeBind=yes
```
Everything worked as intended :-) Leaving this here for anyone else trying to do the same thing.

**Comment by helamonster** [comment]
I changed `cockpit.conf` to include the `Origins` option:
```
[Session]
IdleTimeout=0
[WebService]
Origins=https://cockpit.dc1.domain.com
AllowUnencrypted=true
```

... and now I can log in. A bit tricky setting up, but seems all OK now.

**Comment by helamonster** [comment]
Actually, that does not seem to be doing what I want it to do. I want to only allow HTTPS traffic. When I block port 80 to external hosts, I can no longer access the https page. Strange:
```
jeremy@latitude ~ $ curl -s https://cockpit.dc1.domain.com:443 | grep '<title>' ; echo $?
1
```
Is the application attempting to connect to port 80 rather than 443? It seems to be. How can I force it to only use HTTPS?

**Comment by martinpitt** [comment]
@helamonster `--for-tls-proxy` is then *not* what you want, as that instructs cockpit to *only* serve HTTP, but with assuming https:// origins. That is meant for the case when you put cockpit-ws behind a TLS terminating proxy (nginx or something else). If you let haproxy do TLS termination, why do you want cockpit-ws to speak TLS as well?

**Comment by tobsowo** [comment]
> 

I have this same issue following this [guide ](https://www.linuxtechi.com/how-to-install-cockpit-on-ubuntu-20-04/). When I start cockpit and load the ip:9090 in browser it's not loading and checking the status after about a minute it's no more running.

**Comment by colorwebdesigner** [comment]
I have the same problem. After installing `cockpit` from the repository on a fresh `Debian 11` system, I was unable to login via the web interface and the system recommended me to watch the error log. I saw the same things there: 

- `cockpit-session: pam_ssh_add: Failed adding some keys`
- `cockpit-ws: received request from bad Origin: https://xx.xx.xx.xx`
- `cockpit-ws: Received invalid handshake request from the client`

So you can broke your mind trying to find out what is going wrong. BUT If you log in to your `FreedomBox`, go to `system` -> `cockpit` settings and look at the bootom of the page you will see message:

> Cockpit will only work when accessed using the following URLs:
> - `https://server_name.local`
> - `https://long_string_for_tor_domain.onion`
> - `https://vds.provider.net` <-- THIS IS WRONG

So сockpit will not work if you are trying to access using IP. Check the URL you are trying to acces to Cockpit. 
In my case the problem was with VDS static url. Cockpit identified and recorded my address everywhere in configs as: `vds.myprovider.net`, but the real address was `static.xx.xx.xx.xx.ip.provider.net`.

When I tried to enter the `cockpit` using the real address, everything worked.

**Comment by gboye0** [comment]
Hello guys. Can someone pls explain why when I check cockpit status on RHEL 7 it tells me the inactive and dead. However I can access the web console. It had me pulling my hair out thinking it was not running even have configuring permanent access on firewalld par @sebiweise. Each time I start it and restart the vm, it is not running when i check status but I can connect to the web console and administer it as normal.
 Thanks for your thoughts.

**Comment by jcasale** [comment]
Hello @gboye0, the service is a socket activation-based service.

Have a look at [Socket Activated Internet Services](https://0pointer.de/blog/projects/socket-activated-containers.html#:~:text=%2D%2D%20Basically%2C%20socket%20activation%20simply,the%20first%20connection%20comes%20in.):

> Basically, socket activation simply means that systemd sets up listening sockets (IP or otherwise) on behalf of your services (without these running yet), and then starts (activates) the services as soon as the first connection comes in.

>

**Comment by gboye0** [comment]
Thanks @jcasale.

**Comment by martinpitt** [comment]
@gboye0 For completeness, the thing you want to look at is `systemctl status cockpit.socket`; With just `cockpit` it shows `cockpit.service`, which stops when nothing uses it (to avoid using resources).
